function result = detectAndMask(acquisitionState, borderOptions)
%DETECTANDMASK Detect surfaces, thickness, and the video intensity mask.

    validate_resolved_options(borderOptions);
    detector = oce.borders.resolveMethod(borderOptions.method);
    validate_acquisition_state(acquisitionState);

    reconstruction = acquisitionState.reconstruction;
    [thickness, detectorIndices, anteriorSurface, posteriorSurface] = detector( ...
        reconstruction.axes.lateral.values, ...
        acquisitionState.geometry.bmode_lateral_axis_mm, ...
        reconstruction.amplitude.values, acquisitionState.geometry, ...
        reconstruction.axes.depth.values, ...
        borderOptions.parameters);

    [thickness, detectorIndices, anteriorSurface, posteriorSurface] = ...
        apply_lateral_edge_exclusion(thickness, detectorIndices, ...
            anteriorSurface, posteriorSurface, acquisitionState.geometry, ...
            borderOptions.lateral_edge_exclusion);

    result = struct( ...
        'surface_mode', string(borderOptions.surface_mode), ...
        'thickness', thickness, ...
        'indices', normalize_indices(detectorIndices), ...
        'anteriorSurface', anteriorSurface, ...
        'posteriorSurface', posteriorSurface, ...
        'intensityMask', oce.borders.buildIntensityMask( ...
            reconstruction, borderOptions.mask_threshold));
end

function validate_acquisition_state(state)
    if ~isstruct(state) || ~isscalar(state) || ...
            ~isfield(state, 'geometry') || ~isfield(state, 'reconstruction')
        error('OCE:Borders:InvalidAcquisitionState', ...
            ['detectAndMask requires a structured acquisition_state with ' ...
             'geometry and reconstruction products.']);
    end
end

function validate_resolved_options(options)
    if nargin < 1 || ~isstruct(options) || ~isscalar(options)
        error('OCE:Borders:InvalidResolvedOptions', ...
            'detectAndMask requires one resolved BorderOptions struct.');
    end

    required = ["method"; "surface_mode"; "mask_threshold"; ...
        "lateral_edge_exclusion"; "parameters"];
    missing = required(~isfield(options, required));
    if ~isempty(missing) || ...
            ~isstring(options.surface_mode) || ...
            ~isscalar(options.surface_mode) || ...
            ismissing(options.surface_mode) || ...
            ~isstruct(options.parameters) || ~isscalar(options.parameters) || ...
            ~isstruct(options.lateral_edge_exclusion) || ...
            ~isscalar(options.lateral_edge_exclusion) || ...
            ~all(isfield(options.lateral_edge_exclusion, ...
                ["enabled"; "fraction_per_side"]))
        error('OCE:Borders:InvalidResolvedOptions', ...
            ['detectAndMask requires resolved method, surface_mode, ' ...
             'mask_threshold, lateral_edge_exclusion, and parameters fields.']);
    end
end

function [thickness, indices, anterior, posterior] = ...
        apply_lateral_edge_exclusion(thickness, indices, anterior, ...
            posterior, geometry, options)
    if ~options.enabled || options.fraction_per_side == 0
        return;
    end

    samplesPerBmode = geometry.samples_per_bmode;
    bmodeCount = geometry.bmode_count;
    margin = max(1, round(options.fraction_per_side * samplesPerBmode));
    margin = min(margin, floor((samplesPerBmode - 1) / 2));
    if margin < 1
        return;
    end

    excluded = false(1, geometry.lateral_sample_count);
    for bmodeIndex = 1:bmodeCount
        range = (bmodeIndex - 1) * samplesPerBmode + ...
            (1:samplesPerBmode);
        excluded(range([1:margin, end - margin + 1:end])) = true;
    end

    indices.Idx_Up(excluded) = NaN;
    indices.Idx_Down(excluded) = NaN;
    anterior(excluded, 2) = NaN;
    posterior(excluded, 2) = NaN;
    thickness(excluded) = NaN;
end

function indices = normalize_indices(detectorIndices)
    indices = struct( ...
        'raw', detectorIndices.Idx, ...
        'anterior', detectorIndices.Idx_Up, ...
        'posterior', detectorIndices.Idx_Down);
    diagnostics = setdiff(fieldnames(detectorIndices), ...
        {'Idx', 'Idx_Up', 'Idx_Down'}, 'stable');
    for index = 1:numel(diagnostics)
        name = diagnostics{index};
        indices.(name) = detectorIndices.(name);
    end
end
