function [fitresult, gof] = FitTheoreticalPlot(xdata1, ydata1, sp, lb, ub)
%CREATEFIT1(XDATA1,YDATA1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xdata1
%      Y Output: ydata1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Mar-2018 16:18:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xdata1, ydata1 );

% Set up fittype and options.
ft = fittype( 'a*(sinc(k*x/pi) - 1*((sinc(k*x/pi)/(k*x))-(cos(k*x)/(k*x)))/(k*x) )', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% opts.Lower = [0 0];
% opts.StartPoint = [0.3772 3350];
% opts.Upper = [5000 5000];
opts.Lower = lb;
opts.StartPoint = sp;
opts.Upper = ub;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% 
% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'ydata1 vs. xdata1', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel xdata1
% ylabel ydata1
% grid on


