function options = getDefaultDispersionWindowOptions()
%GETDEFAULTDISPERSIONWINDOWOPTIONS Build editable dispersion-window defaults.

    options = struct();
    options.center = struct( ...
        'method', "max_mirrored_correlation", ...
        'manual_local_index', [], ...
        'search_range_fraction', [0.30 0.70], ...
        'max_rms_phase_increment', struct( ...
            'smoothing_span_fraction', 0.07), ...
        'max_mirrored_correlation', struct( ...
            'half_width_fraction', 0.25, ...
            'half_width_samples', [], ...
            'minimum_half_width_samples', 8, ...
            'score_smoothing_span_fraction', 0.03));
    options.spatial = struct( ...
        'method', "fraction_of_bmode", ...
        'interval_fraction', 0.30, ...
        'manual_interval_count', []);
    options.directional_offsets = struct( ...
        'left_samples', -3, ...
        'right_samples', 3);
    options.temporal = struct( ...
        'start_index_inclusive', 75, ...
        'method', "cycle_count", ...
        'manual_interval_count', [], ...
        'cycle_count', 3);
    options.boundary_policy = "shift_to_fit";
    options.show_progress = false;
end
