function options = getDefaultFilterOptions()
%GETDEFAULTFILTEROPTIONS Build editable temporal-filter defaults.

    options = struct();
    options.enabled = true;
    options.method = "fir_bandpass";
    options.frequency = struct( ...
        'selection_source', "acquisition_row", ...
        'column', "frequency_Hz", ...
        'center_hz', [], ...
        'bandwidth', struct( ...
            'mode', "fraction_of_center", ...
            'fraction', 0.65, ...
            'hz', []));
    options.order = 100;
    options.diagnostic = struct( ...
        'fft_length', 2^12, ...
        'line_index', []);
    options.surface_postprocessing = struct( ...
        'remove_temporal_mean', true, ...
        'median', struct( ...
            'enabled', true, ...
            'window_samples', [3 3]));
    options.invalid_row_policy = ...
        "zero_surface_and_matching_depth";
end
