function groups = repository_test_catalog()
%REPOSITORY_TEST_CATALOG Canonical categorized inventory for repository tests.

    groups = repmat(struct('name', "", 'tests', {{}}), 4, 1);

    groups(1).name = "Contracts and resolution";
    groups(1).tests = { ...
        @test_final_architecture_contract, ...
        @test_parameter_preparation_chain_contract, ...
        @test_maintained_terminology_contract, ...
        @test_fireice_dependency_contract, ...
        @test_canonical_helper_ownership_contract, ...
        @test_interactive_acquisition_architecture, ...
        @test_synthetic_golden_harness_contract, ...
        @test_path_and_function_resolution, ...
        @test_config_domain_resolution, ...
        @test_io_acquisition_resolution, ...
        @test_border_domain_resolution, ...
        @test_motion_domain_resolution, ...
        @test_filtering_domain_resolution, ...
        @test_dispersion_windows_resolution, ...
        @test_dispersion_analysis_resolution, ...
        @test_results_domain_resolution, ...
        @test_plotting_domain_resolution, ...
        @test_pipeline_domain_resolution};

    groups(2).name = "Unit behavior";
    groups(2).tests = { ...
        @test_interactive_acquisition_helpers, ...
        @test_find_surface, ...
        @test_loupas_phase_increment, ...
        @test_manual_preview_helpers};

    groups(3).name = "Integration and workflow";
    groups(3).tests = { ...
        @test_startup_contract, ...
        @test_prepare_acquisition_parameters_contract, ...
        @test_manual_single_file_workflow_contract, ...
        @test_phase_speed_persistence_contract, ...
        @test_results_summary_persistence_contract, ...
        @test_results_export_contract, ...
        @test_plotting_individual_contract, ...
        @test_plotting_summary_contract, ...
        @test_pipeline_single_contract, ...
        @test_pipeline_batch_contract, ...
        @test_pipeline_summary_contract, ...
        @test_pipeline_workflow_contract};

    groups(4).name = "Synthetic regression";
    groups(4).tests = { ...
        @test_phase_unwrap, ...
        @test_local_speed_estimators, ...
        @test_wave_motion_plane, ...
        @test_config_domain_contract, ...
        @test_io_acquisition_contract, ...
        @test_oct_system_reconstruction_contract, ...
        @test_spectral_domain_1310_contract, ...
        @test_border_domain_contract, ...
        @test_border_multibmode_contract, ...
        @test_phantom_border_robustness_contract, ...
        @test_motion_domain_contract, ...
        @test_filtering_domain_contract, ...
        @test_dispersion_windows_contract, ...
        @test_dispersion_analysis_contract, ...
        @test_results_domain_contract, ...
        @test_results_angular_ordering_contract, ...
        @test_experiment_scan_axis_summary_contract, ...
        @test_results_summary_contract, ...
        @test_synthetic_scientific_golden};
end
