function result = buildWindows(configForRun, filterResult, xAxisMm, ...
        resolvedFilter, geometry)
%BUILDWINDOWS Extract explicit directional windows from resolved run inputs.

    [options, values, samplesPerBmode, bmodeCount, cropStartIndex, ...
        cropEndIndex, filterDelaySamples] = validate_inputs( ...
            configForRun, filterResult, xAxisMm, resolvedFilter, geometry);
    frequencyHz = validate_frequency(resolvedFilter);
    sampleIntervalS = resolvedFilter.sample_interval_s;

    spatialMethod = oce.dispersion.resolveSpatialExtentMethod( ...
        options.spatial.method);
    spatial = spatialMethod(options.spatial, samplesPerBmode);
    validate_interval_count(spatial.interval_count, ...
        samplesPerBmode, "spatial");

    alignedTimeCount = size(values, 2) - filterDelaySamples;
    absoluteStartIndex = options.temporal.start_index_inclusive;
    alignedEndIndex = min( ...
        cropEndIndex, cropStartIndex + alignedTimeCount - 1);
    if absoluteStartIndex < cropStartIndex || ...
            absoluteStartIndex > alignedEndIndex
        error('OCE:DispersionWindows:TemporalStartOutsideDomain', ...
            ['temporal.start_index_inclusive (%d) must lie within the ' ...
             'retained acquisition sample range %d:%d.'], ...
            absoluteStartIndex, cropStartIndex, alignedEndIndex);
    end

    requestedIntervalCount = cropEndIndex - absoluteStartIndex;
    availableIntervalCount = alignedEndIndex - absoluteStartIndex;
    durationMethod = oce.dispersion.resolveWindowDurationMethod( ...
        options.temporal.method);
    temporal = durationMethod(options.temporal, frequencyHz, sampleIntervalS, ...
        requestedIntervalCount, availableIntervalCount);
    validate_interval_count(temporal.interval_count, alignedTimeCount, ...
        "temporal");

    requestedAlignedTime = absoluteStartIndex - cropStartIndex + 1 + ...
        (0:temporal.interval_count);
    [alignedTimeIndices, temporalBoundary] = shift_to_fit( ...
        requestedAlignedTime, alignedTimeCount, "temporal");
    temporalBoundary.requested_start_index_inclusive = ...
        temporalBoundary.requested_start_index_inclusive + cropStartIndex - 1;
    temporalBoundary.requested_end_index_inclusive = ...
        temporalBoundary.requested_end_index_inclusive + cropStartIndex - 1;
    temporalBoundary.effective_start_index_inclusive = ...
        temporalBoundary.effective_start_index_inclusive + cropStartIndex - 1;
    temporalBoundary.effective_end_index_inclusive = ...
        temporalBoundary.effective_end_index_inclusive + cropStartIndex - 1;
    if string(options.temporal.method) == "to_end"
        temporalBoundary.policy = "to_end";
        temporalBoundary.requested_start_index_inclusive = absoluteStartIndex;
        temporalBoundary.requested_end_index_inclusive = cropEndIndex;
        temporalBoundary.effective_start_index_inclusive = absoluteStartIndex;
        temporalBoundary.effective_end_index_inclusive = alignedEndIndex;
        temporalBoundary.applied = alignedEndIndex ~= cropEndIndex;
        temporalBoundary.shift_samples = 0;
    end
    sourceTimeIndices = alignedTimeIndices + filterDelaySamples;
    absoluteTimeIndices = cropStartIndex + alignedTimeIndices - 1;
    if string(filterResult.surface_postprocessed.quantity) == "wrapped_phase"
        windowTimeAxisS = (absoluteTimeIndices - 1) * sampleIntervalS;
    else
        windowTimeAxisS = (absoluteTimeIndices - 0.5) * sampleIntervalS;
    end

    centerMethod = oce.dispersion.resolveCenterMethod(options.center.method);
    centerResolution = centerMethod(values, options.center, ...
        samplesPerBmode, bmodeCount, sourceTimeIndices, ...
        options.show_progress);
    validate_centers(centerResolution, samplesPerBmode, bmodeCount);

    bmodes = repmat(empty_bmode(), 1, bmodeCount);
    for bmodeIndex = 1:bmodeCount
        globalRange = (bmodeIndex - 1) * samplesPerBmode + ...
            (1:samplesPerBmode);
        centerLocal = centerResolution.local_indices(bmodeIndex);
        center = center_metadata(centerResolution, bmodeIndex, ...
            centerLocal, globalRange(centerLocal), xAxisMm(centerLocal), ...
            options.center.method);
        leftRequested = centerLocal - spatial.interval_count + ...
            options.directional_offsets.left_samples + ...
            (0:spatial.interval_count);
        rightRequested = centerLocal + ...
            options.directional_offsets.right_samples + ...
            (0:spatial.interval_count);
        [leftLocal, leftBoundary] = shift_to_fit( ...
            leftRequested, samplesPerBmode, "left spatial");
        [rightLocal, rightBoundary] = shift_to_fit( ...
            rightRequested, samplesPerBmode, "right spatial");

        bmodes(bmodeIndex).index = bmodeIndex;
        bmodes(bmodeIndex).global_lateral_range = ...
            [globalRange(1) globalRange(end)];
        bmodes(bmodeIndex).center = center;
        bmodes(bmodeIndex).left = make_window("left", true, ...
            leftLocal, globalRange(leftLocal), sourceTimeIndices, ...
            absoluteTimeIndices, xAxisMm, windowTimeAxisS, values, ...
            leftBoundary, temporalBoundary);
        bmodes(bmodeIndex).right = make_window("right", false, ...
            rightLocal, globalRange(rightLocal), sourceTimeIndices, ...
            absoluteTimeIndices, xAxisMm, windowTimeAxisS, values, ...
            rightBoundary, temporalBoundary);
    end

    result = struct( ...
        'source', struct( ...
            'quantity', string(filterResult.surface_postprocessed.quantity), ...
            'units', string(filterResult.surface_postprocessed.units), ...
            'layout', string(filterResult.surface_postprocessed.layout), ...
            'filter_enabled', filterResult.enabled, ...
            'filter_applied', filterResult.applied, ...
            'signal_size', size(values)), ...
        'frequency', struct('center_hz', frequencyHz), ...
        'sample_interval_s', sampleIntervalS, ...
        'resolved_options', struct( ...
            'center', centerResolution, ...
            'spatial', spatial, ...
            'directional_offsets', options.directional_offsets, ...
            'temporal', temporal, ...
            'temporal_boundary', temporalBoundary, ...
            'boundary_policy', options.boundary_policy, ...
            'show_progress', options.show_progress), ...
        'bmodes', bmodes);
    result.resolved_options.center.method = options.center.method;
end

function [options, values, samplesPerBmode, bmodeCount, cropStartIndex, ...
        cropEndIndex, filterDelaySamples] = validate_inputs( ...
            config, filterResult, xAxisMm, resolvedFilter, geometry)
    if ~isstruct(config) || ~isfield(config, 'DispersionWindowOptions')
        error('OCE:DispersionWindows:MissingOptions', ...
            'config_for_run must contain resolved DispersionWindowOptions.');
    end
    options = config.DispersionWindowOptions;
    if ~isfield(config, 'resolved_crop') || ...
            ~isstruct(config.resolved_crop) || ...
            ~isfield(config.resolved_crop, 'time') || ...
            ~isstruct(config.resolved_crop.time) || ...
            ~isfield(config.resolved_crop.time, 'start_index_inclusive') || ...
            ~isfield(config.resolved_crop.time, 'end_index_inclusive')
        error('OCE:DispersionWindows:MissingCrop', ...
            'config_for_run.resolved_crop.time is required.');
    end
    cropStartIndex = positive_integer( ...
        config.resolved_crop.time.start_index_inclusive, ...
        'resolved_crop.time.start_index_inclusive');
    cropEndIndex = positive_integer( ...
        config.resolved_crop.time.end_index_inclusive, ...
        'resolved_crop.time.end_index_inclusive');
    if cropEndIndex <= cropStartIndex
        error('OCE:DispersionWindows:InvalidAcquisitionGeometry', ...
            'resolved_crop.time end must be greater than its start.');
    end

    requiredFilterFields = {'enabled', 'applied', ...
        'surface_postprocessed', 'time_axis_s', 'design'};
    require_fields(filterResult, requiredFilterFields, ...
        'OCE:DispersionWindows:InvalidFilterResult', 'filter_result');
    require_fields(filterResult.surface_postprocessed, ...
        {'values', 'quantity', 'units', 'layout'}, ...
        'OCE:DispersionWindows:InvalidFilterResult', ...
        'filter_result.surface_postprocessed');
    values = filterResult.surface_postprocessed.values;
    if ~isnumeric(values) || ~ismatrix(values) || isempty(values) || ...
            size(values, 1) < 2 || size(values, 2) < 2
        error('OCE:DispersionWindows:InvalidSurfacePhaseMap', ...
            'The postprocessed surface signal must be a nonempty numeric matrix.');
    end
    if string(filterResult.surface_postprocessed.layout) ~= "lateral_time"
        error('OCE:DispersionWindows:InvalidSignalLayout', ...
            'The postprocessed surface signal layout must be lateral_time.');
    end
    timeAxisS = filterResult.time_axis_s(:)';
    if ~isnumeric(timeAxisS) || numel(timeAxisS) ~= size(values, 2) || ...
            any(~isfinite(timeAxisS)) || any(diff(timeAxisS) <= 0)
        error('OCE:DispersionWindows:InvalidTimeAxis', ...
            'filter_result.time_axis_s must match the signal and increase.');
    end
    require_fields(filterResult.design, {'delay_samples'}, ...
        'OCE:DispersionWindows:InvalidFilterResult', 'filter_result.design');
    filterDelaySamples = double(filterResult.design.delay_samples) * ...
        double(filterResult.applied);
    if ~isscalar(filterDelaySamples) || ~isfinite(filterDelaySamples) || ...
            filterDelaySamples < 0 || ...
            filterDelaySamples ~= round(filterDelaySamples) || ...
            filterDelaySamples >= size(values, 2) - 1
        error('OCE:DispersionWindows:InvalidFilterResult', ...
            'Filter delay must leave at least two aligned time samples.');
    end
    require_fields(resolvedFilter, {'sample_interval_s', 'frequency'}, ...
        'OCE:DispersionWindows:InvalidResolvedFilter', 'resolved_filter');
    require_fields(resolvedFilter.frequency, {'center_hz'}, ...
        'OCE:DispersionWindows:InvalidResolvedFilter', ...
        'resolved_filter.frequency');
    if ~isscalar(resolvedFilter.sample_interval_s) || ...
            ~isfinite(resolvedFilter.sample_interval_s) || ...
            resolvedFilter.sample_interval_s <= 0
        error('OCE:DispersionWindows:InvalidResolvedFilter', ...
            'resolved_filter.sample_interval_s must be positive and finite.');
    end
    require_fields(geometry, {'samples_per_bmode', 'bmode_count'}, ...
        'OCE:DispersionWindows:InvalidAcquisitionGeometry', 'geometry');
    if isfield(geometry, 'raster')
        % Directional windows assume angular B-modes centered on the
        % excitation; raster lines do not share that left/right geometry.
        error('OCE:DispersionWindows:UnsupportedScanGeometry', ...
            'Dispersion windows support only angular_bmodes geometry.');
    end
    samplesPerBmode = positive_integer( ...
        geometry.samples_per_bmode, 'geometry.samples_per_bmode');
    bmodeCount = positive_integer( ...
        geometry.bmode_count, 'geometry.bmode_count');
    if size(values, 1) ~= samplesPerBmode * bmodeCount
        error('OCE:DispersionWindows:SpaceAngleMismatch', ...
            ['Signal rows must equal samples_per_bmode * bmode_count ' ...
             '(%d expected, %d received).'], ...
            samplesPerBmode * bmodeCount, size(values, 1));
    end
    if ~isnumeric(xAxisMm) || ~isvector(xAxisMm) || ...
            numel(xAxisMm) < samplesPerBmode || ...
            any(~isfinite(xAxisMm(1:samplesPerBmode))) || ...
            any(diff(xAxisMm(1:samplesPerBmode)) <= 0)
        error('OCE:DispersionWindows:InvalidSpaceAxis', ...
            'x_axis_mm must contain one finite increasing local B-mode axis.');
    end
    xAxisMm = xAxisMm(:)'; %#ok<NASGU>
end

function frequencyHz = validate_frequency(resolvedFilter)
    frequencyHz = resolvedFilter.frequency.center_hz;
    if ~isnumeric(frequencyHz) || ~isscalar(frequencyHz) || ...
            ~isfinite(frequencyHz) || frequencyHz <= 0
        error('OCE:DispersionWindows:InvalidFrequency', ...
            'The resolved filter center frequency must be positive.');
    end
end

function validate_interval_count(value, availableSamples, domain)
    if ~isscalar(value) || ~isfinite(value) || value < 1 || ...
            value ~= round(value) || value >= availableSamples
        error('OCE:DispersionWindows:InvalidIntervalCount', ...
            ['Resolved %s interval count must be a positive integer ' ...
             'smaller than the available sample count %d.'], ...
            domain, availableSamples);
    end
end

function validate_centers(resolution, samplesPerBmode, bmodeCount)
    if ~isstruct(resolution) || ~isfield(resolution, 'local_indices') || ...
            numel(resolution.local_indices) ~= bmodeCount
        error('OCE:DispersionWindows:CenterCountMismatch', ...
            'Center resolution must contain one local index per B-mode.');
    end
    indices = resolution.local_indices(:);
    if any(~isfinite(indices)) || any(indices ~= round(indices)) || ...
            any(indices < 1) || any(indices > samplesPerBmode)
        error('OCE:DispersionWindows:CenterOutsideBmode', ...
            'Every resolved center must remain within its local B-mode.');
    end
end

function [effective, metadata] = shift_to_fit(requested, domainSize, label)
    requested = round(requested(:)');
    if isempty(requested) || any(diff(requested) ~= 1) || ...
            numel(requested) > domainSize
        error('OCE:DispersionWindows:InvalidRequestedRange', ...
            'Requested %s range is not a valid contiguous interval.', label);
    end
    shift = 0;
    if requested(1) < 1
        shift = 1 - requested(1);
    elseif requested(end) > domainSize
        shift = domainSize - requested(end);
    end
    effective = requested + shift;
    if effective(1) < 1 || effective(end) > domainSize
        error('OCE:DispersionWindows:RangeOutsideDomain', ...
            'The %s range cannot fit in the available domain.', label);
    end
    metadata = struct( ...
        'policy', "shift_to_fit", ...
        'applied', shift ~= 0, ...
        'requested_start_index_inclusive', requested(1), ...
        'requested_end_index_inclusive', requested(end), ...
        'effective_start_index_inclusive', effective(1), ...
        'effective_end_index_inclusive', effective(end), ...
        'shift_samples', shift);
end

function metadata = center_metadata(resolution, index, localIndex, ...
        globalIndex, xCoordinateMm, method)
    metadata = struct( ...
        'method', method, ...
        'local_lateral_index', localIndex, ...
        'global_lateral_index', globalIndex, ...
        'x_coordinate_mm', xCoordinateMm);
    if isfield(resolution, 'search_ranges')
        metadata.search_range_local_indices = resolution.search_ranges(index, :);
    end
    if isfield(resolution, 'scores')
        metadata.score = resolution.scores(index);
    end
    if isfield(resolution, 'fallback_used')
        metadata.fallback_used = resolution.fallback_used(index);
    end
end

function window = make_window(direction, reverseSpatially, localIndices, ...
        globalIndices, sourceTimeIndices, absoluteTimeIndices, xAxisMm, ...
        timeAxisS, values, spatialBoundary, temporalBoundary)
    window = struct( ...
        'direction', direction, ...
        'spatial_reversal_required', reverseSpatially, ...
        'local_lateral_indices', localIndices, ...
        'global_lateral_indices', globalIndices, ...
        'time_indices', absoluteTimeIndices, ...
        'x_axis_mm', xAxisMm(localIndices), ...
        'time_axis_s', timeAxisS, ...
        'values', values(globalIndices, sourceTimeIndices), ...
        'spatial_interval_count', numel(localIndices) - 1, ...
        'spatial_sample_count', numel(localIndices), ...
        'temporal_interval_count', numel(absoluteTimeIndices) - 1, ...
        'temporal_sample_count', numel(absoluteTimeIndices), ...
        'spatial_boundary', spatialBoundary, ...
        'temporal_boundary', temporalBoundary);
end

function value = empty_bmode()
    value = struct('index', [], 'global_lateral_range', [], ...
        'center', [], 'left', [], 'right', []);
end

function require_fields(value, fields, identifier, label)
    if ~isstruct(value) || ~isscalar(value)
        error(identifier, '%s must be a scalar struct.', label);
    end
    missing = fields(~isfield(value, fields));
    if ~isempty(missing)
        error(identifier, '%s is missing fields: %s.', label, ...
            strjoin(missing, ', '));
    end
end

function value = positive_integer(value, label)
    if ~isscalar(value) || ~isfinite(value) || value < 1 || ...
            value ~= round(value)
        error('OCE:DispersionWindows:InvalidAcquisitionGeometry', ...
            '%s must be a positive integer.', label);
    end
end
