function directionResult = computeDirectionalPhaseSpeed(window, source, options)
%COMPUTEDIRECTIONALPHASESPEED Analyze one resolved directional window.

    [spectrum, ridge] = oce.dispersion.computeDispersionSpectrum( ...
        window.values, window.x_axis_mm, window.time_axis_s, options, ...
        source, window.direction);
    frequencyHz = spectrum.frequency_axis_hz;
    rawPhaseSpeed = frequencyHz ./ ridge.wavenumber_per_m;
    smoothing = options.phase_speed.smoothing;
    smoothedPhaseSpeed = smooth(rawPhaseSpeed, ...
        smoothing.span_fraction, char(smoothing.method));

    requestedHz = options.target_frequency.requested_hz;
    if isfinite(requestedHz)
        selectedIndex = knnsearch(frequencyHz', requestedHz, 'K', 1);
        targetSelection = struct( ...
            'requested_frequency_hz', requestedHz, ...
            'selected_bin_index', selectedIndex, ...
            'selected_frequency_hz', frequencyHz(selectedIndex), ...
            'frequency_error_hz', frequencyHz(selectedIndex) - requestedHz, ...
            'selected_wavenumber_per_m', ...
                ridge.wavenumber_per_m(selectedIndex), ...
            'selected_phase_speed_m_per_s', ...
                smoothedPhaseSpeed(selectedIndex));
    else
        targetSelection = struct( ...
            'requested_frequency_hz', NaN, ...
            'selected_bin_index', NaN, ...
            'selected_frequency_hz', NaN, ...
            'frequency_error_hz', NaN, ...
            'selected_wavenumber_per_m', NaN, ...
            'selected_phase_speed_m_per_s', NaN);
    end

    directionResult = struct( ...
        'direction', string(window.direction), ...
        'spectrum', spectrum, ...
        'ridge', ridge, ...
        'phase_speed_curve', struct( ...
            'frequency_hz', frequencyHz, ...
            'wavenumber_per_m', ridge.wavenumber_per_m, ...
            'phase_speed_m_per_s', rawPhaseSpeed, ...
            'smoothed_phase_speed_m_per_s', smoothedPhaseSpeed, ...
            'smoothing', smoothing), ...
        'target_selection', targetSelection);
end
