function oceResult = buildScientificResult(processingInputs, configForRun, ...
        windowResult, analysis)
%BUILDSCIENTIFICRESULT Assemble the versioned persisted scientific result.

    validate_inputs(processingInputs, configForRun, windowResult, analysis);
    directions = compact_directions(analysis.directions);
    frequencyAxisHz = shared_frequency_axis(analysis.directions);
    directionalThicknessMm = reshape( ...
        [analysis.directions.mean_thickness_mm], [], 1);
    directionalPhaseSpeed = reshape(arrayfun(@(item) ...
        item.target_selection.selected_phase_speed_m_per_s, ...
        analysis.directions), [], 1);
    scanAxisCount = analysis.scan_axis_count;
    bmodeDirectionsDeg = [];
    if isfield(analysis, 'bmode_direction_deg')
        bmodeDirectionsDeg = analysis.bmode_direction_deg;
    end
    [sourceIndices, anglesDeg] = oce.dispersion.orderBidirectionalAngles( ...
        scanAxisCount, bmodeDirectionsDeg);
    sourceIndices = sourceIndices(:);
    angularPhaseSpeed = directionalPhaseSpeed(sourceIndices);
    angularThicknessMm = directionalThicknessMm(sourceIndices);
    [phaseMean, phaseStd, phaseRange] = ...
        oce.results.computeScalarStatistics(angularPhaseSpeed);
    [thicknessMeanUm, thicknessStdUm, thicknessRangeUm] = ...
        oce.results.computeScalarStatistics(angularThicknessMm * 1e3);

    oceResult = struct( ...
        'schema', struct( ...
            'name', "oce_phase_speed_result", 'version', 3), ...
        'acquisition', compact_acquisition(processingInputs, configForRun), ...
        'processing', struct('config', compact_config(configForRun, analysis.options)), ...
        'borders', struct( ...
            'quantity', ...
                "mean_physical_thickness_per_directional_dispersion_window", ...
            'units', "mm", ...
            'layout', "direction", ...
            'ordering', "acquisition_direction_order", ...
            'directional_mean_thickness_mm', directionalThicknessMm), ...
        'windows', compact_windows(windowResult), ...
        'dispersion', struct( ...
            'target_frequency', analysis.target_frequency, ...
            'direction_ordering', "acquisition_direction_order", ...
            'scan_axis_angles_deg', analysis.scan_axis_angles_deg, ...
            'scan_axis_count', scanAxisCount, ...
            'directions', rmfield(analysis.directions, ...
                {'spectrum', 'ridge', 'phase_speed_curve', ...
                 'target_selection', 'mean_thickness_mm'}), ...
            'estimators', struct('kf_ridge', struct( ...
                'method', string(analysis.method), ...
                'frequency_axis_hz', frequencyAxisHz, ...
                'frequency_axis_quantity', "temporal_frequency", ...
                'frequency_axis_units', "Hz", ...
                'frequency_axis_layout', "frequency", ...
                'directions', directions), ...
                'phase_gradient', compact_phase_gradient(analysis, configForRun))), ...
        'angular', struct( ...
            'unit', "deg", ...
            'layout', "angle", ...
            'ordering', "counterclockwise_full_circle", ...
            'full_circle_angles_deg', anglesDeg, ...
            'source_direction_indices', sourceIndices, ...
            'phase_speed_m_per_s', angularPhaseSpeed, ...
            'mean_thickness_mm', angularThicknessMm), ...
        'statistics', struct( ...
            'phase_speed', struct( ...
                'quantity', "phase_speed", 'units', "m/s", ...
                'mean_m_per_s', phaseMean, ...
                'standard_deviation_m_per_s', phaseStd, ...
                'range_m_per_s', phaseRange), ...
            'thickness', struct( ...
                'quantity', "mean_physical_thickness", 'units', "um", ...
                'source_units', "mm", 'conversion_factor', 1e3, ...
                'mean_um', thicknessMeanUm, ...
                'standard_deviation_um', thicknessStdUm, ...
                'range_um', thicknessRangeUm)));
    oce.results.validateScientificResult(oceResult);
end

function validate_inputs(inputs, config, windows, analysis)
    if ~isstruct(inputs) || ~isscalar(inputs) || ...
            ~isfield(inputs, 'acquisition_row') || ...
            ~isfield(inputs, 'subExperiment')
        error('OCE:Result:InvalidBuildInputs', ...
            'Prepared acquisition metadata are required.');
    end
    if ~isstruct(config) || ~isscalar(config) || ...
            ~isfield(config, 'AcquisitionOptions')
        error('OCE:Result:InvalidBuildInputs', ...
            'Resolved processing configuration is required.');
    end
    if ~isstruct(windows) || ~isscalar(windows) || ...
            ~isfield(windows, 'bmodes')
        error('OCE:Result:InvalidBuildInputs', ...
            'Resolved dispersion windows are required.');
    end
    if ~isstruct(analysis) || ~isscalar(analysis) || ...
            ~isfield(analysis, 'directions') || ...
            isempty(analysis.directions) || ...
            ~isfield(analysis, 'scan_axis_count') || ...
            ~isfield(analysis, 'scan_axis_angles_deg')
        error('OCE:Result:InvalidBuildInputs', ...
            'Structured dispersion analysis is required.');
    end
end

function acquisition = compact_acquisition(inputs, config)
    row = inputs.acquisition_row;
    if istable(row)
        if height(row) ~= 1
            error('OCE:Result:InvalidBuildInputs', ...
                'acquisition_row must contain exactly one row.');
        end
        sourceRow = table2struct(row);
    elseif isstruct(row) && isscalar(row)
        sourceRow = row;
    else
        error('OCE:Result:InvalidBuildInputs', ...
            'acquisition_row must be a one-row table or scalar struct.');
    end
    acquisition = struct( ...
        'experiment_id', row_string(sourceRow, 'experiment_id'), ...
        'subexperiment_id', string(inputs.subExperiment), ...
        'run_id', row_string(sourceRow, 'run_id'), ...
        'sample_type', row_string(sourceRow, 'sample_type'), ...
        'protocol', string(config.AcquisitionOptions.scan_geometry), ...
        'source_row', sourceRow);
end

function value = row_string(row, name)
    if ~isfield(row, name)
        value = "";
        return;
    end
    value = row.(name);
    if iscell(value), value = value{1}; end
    value = string(value);
end

function config = compact_config(config, analysisOptions)
    redundant = intersect(fieldnames(config), ...
        {'processing_config_base', 'acquisition_row', 'metadata'});
    config = rmfield(config, redundant);
    % Both estimators refer to dispersion.target_frequency.
    config.DispersionAnalysisOptions = rmfield( ...
        analysisOptions, 'target_frequency');
end

function snapshot = compact_windows(windowResult)
    snapshot = windowResult;
    for index = 1:numel(snapshot.bmodes)
        snapshot.bmodes(index).left = rmfield( ...
            snapshot.bmodes(index).left, 'values');
        snapshot.bmodes(index).right = rmfield( ...
            snapshot.bmodes(index).right, 'values');
    end
    snapshot.provenance = struct( ...
        'source', "runtime_structured_result", ...
        'limitations', strings(0, 1));
end

function directions = compact_directions(source)
    directions = rmfield(source, {'scan_axis_index', 'direction', 'mean_thickness_mm'});
    for index = 1:numel(directions)
        spectrum = directions(index).spectrum;
        spectrum = rmfield(spectrum, ...
            {'magnitude', 'frequency_axis_hz', ...
             'temporal_magnitude_mean', 'fft', 'crop'});
        spectrum.input = rmfield(spectrum.input, 'direction');
        spectrum.quantity = ...
            "mean_temporal_fft_magnitude_across_lateral_samples";
        spectrum.units = "arbitrary_magnitude";
        spectrum.layout = "frequency";
        spectrum.temporal_diagnostic_magnitude = ...
            source(index).spectrum.temporal_magnitude_mean;
        directions(index).spectrum = spectrum;

        curve = directions(index).phase_speed_curve;
        curve = rmfield(curve, {'frequency_hz', 'wavenumber_per_m', ...
            'phase_speed_m_per_s', 'smoothed_phase_speed_m_per_s'});
        curve.quantity = "phase_speed";
        curve.units = "m/s";
        curve.layout = "frequency";
        curve.raw_phase_speed_m_per_s = ...
            source(index).phase_speed_curve.phase_speed_m_per_s;
        curve.smoothed_phase_speed_m_per_s = ...
            source(index).phase_speed_curve.smoothed_phase_speed_m_per_s;
        directions(index).phase_speed_curve = curve;
        directions(index).target_selection = rmfield( ...
            directions(index).target_selection, 'requested_frequency_hz');
    end
end

function result = compact_phase_gradient(analysis, configForRun)
    result = analysis.phase_gradient;
    if result.enabled && ~isequaln(result.target_frequency_hz, ...
            analysis.target_frequency.requested_hz)
        error('OCE:Result:InvalidBuildInputs', ...
            'Phase-gradient frequency must equal the common physical target.');
    end
    result = rmfield(result, 'target_frequency_hz');
    result.target_frequency_reference = "dispersion.target_frequency.requested_hz";
    if result.enabled
        % Keep the input contract honest before moving detailed provenance to config.
        metadata = rmfield(result.input, 'difference_axis');
        for name = string(fieldnames(metadata))'
            if ~isequaln(metadata.(name), configForRun.MotionOptions.surface.(name))
                error('OCE:Result:InvalidBuildInputs', ...
                    'Surface phase provenance disagrees with MotionOptions.%s.', name);
            end
        end
        result.directions = rmfield(result.directions, 'diagnostic');
        % This is the pre-filter phase.surface product, not raw acquisition.
        % Sampling, aggregation and LOWESS remain in processing.config.MotionOptions.
        fields = {'quantity', 'units', 'layout', 'estimator', 'difference_axis'};
        result.input = rmfield(result.input, setdiff(fieldnames(result.input), fields));
        result.input.source = "phase.surface";
    end
end

function axisHz = shared_frequency_axis(directions)
    axisHz = directions(1).phase_speed_curve.frequency_hz;
    for index = 2:numel(directions)
        candidate = directions(index).phase_speed_curve.frequency_hz;
        if ~isequaln(candidate, axisHz)
            error('OCE:Result:InconsistentFrequencyAxes', ...
                'All directional frequency axes must be identical.');
        end
    end
end
