function validateScientificResult(result)
%VALIDATESCIENTIFICRESULT Validate the version-3 persisted result contract.

    require_scalar_struct(result, 'oce_result');
    require_exact_fields(result, {'schema', 'acquisition', 'processing', ...
        'borders', 'windows', 'dispersion', 'angular', 'statistics'}, ...
        'oce_result');
    validate_schema(result.schema);
    validate_acquisition(result.acquisition);
    validate_processing(result.processing);
    validate_windows(result.windows);
    validate_dispersion_and_borders(result.dispersion, result.borders);
    validate_gradient_provenance(result);
    validate_angular(result.angular, result.dispersion, result.borders);
    validate_statistics(result.statistics, result.angular);
end

function validate_schema(schema)
    require_scalar_struct(schema, 'schema');
    require_exact_fields(schema, {'name', 'version'}, 'schema');
    if ~isstring(schema.name) || ~isscalar(schema.name) || ...
            schema.name ~= "oce_phase_speed_result" || ...
            ~isnumeric(schema.version) || ~isscalar(schema.version) || ...
            schema.version ~= 3
        error('OCE:Result:UnsupportedSchema', ...
            'Supported result schema is oce_phase_speed_result version 3.');
    end
end

function validate_acquisition(value)
    require_scalar_struct(value, 'acquisition');
    require_exact_fields(value, {'experiment_id', 'subexperiment_id', ...
        'run_id', 'sample_type', 'protocol', 'source_row'}, 'acquisition');
    names = {'experiment_id', 'subexperiment_id', 'run_id', ...
        'sample_type', 'protocol'};
    for index = 1:numel(names)
        item = value.(names{index});
        if ~isstring(item) || ~isscalar(item)
            invalid('acquisition.%s must be a string scalar.', names{index});
        end
    end
    if string(value.protocol) ~= "angular_bmodes"
        invalid('acquisition.protocol must use canonical scan geometry angular_bmodes.');
    end
    if ~isstruct(value.source_row) || ~isscalar(value.source_row)
        invalid('acquisition.source_row must be a scalar struct.');
    end
    if isfield(value.source_row, 'scan_geometry') && ...
            string(value.source_row.scan_geometry) ~= "angular_bmodes"
        invalid('acquisition.source_row.scan_geometry must be angular_bmodes.');
    end
end

function validate_processing(value)
    if ~isstruct(value) || ~isscalar(value) || ...
            ~isequal(fieldnames(value), {'config'}) || ...
            ~isstruct(value.config) || ~isscalar(value.config)
        invalid('processing.config must be a scalar resolved-config snapshot.');
    end
    config = value.config;
    if ~isfield(config, 'AcquisitionOptions') || ...
            ~isstruct(config.AcquisitionOptions) || ...
            ~isfield(config.AcquisitionOptions, 'scan_geometry') || ...
            string(config.AcquisitionOptions.scan_geometry) ~= "angular_bmodes"
        invalid('processing.config must use scan_geometry angular_bmodes.');
    end
    if ~isfield(config, 'DispersionWindowOptions') || ...
            ~isstruct(config.DispersionWindowOptions) || ...
            ~isfield(config.DispersionWindowOptions, 'spatial') || ...
            ~isstruct(config.DispersionWindowOptions.spatial) || ...
            ~isfield(config.DispersionWindowOptions.spatial, 'method')
        invalid('processing.config must use geometry-neutral dispersion-window naming.');
    end
    spatialMethod = lower(strtrim(string( ...
        config.DispersionWindowOptions.spatial.method)));
    if ~isscalar(spatialMethod) || ismissing(spatialMethod) || ...
            ~ismember(spatialMethod, ["fraction_of_bmode", "manual_interval_count"])
        invalid('processing.config must use geometry-neutral dispersion-window naming.');
    end
end

function validate_windows(value)
    required = {'source', 'frequency', 'sample_interval_s', ...
        'resolved_options', 'bmodes', 'provenance'};
    require_exact_fields(value, required, 'windows');
    if ~isstruct(value.bmodes) || isempty(value.bmodes)
        invalid('windows.bmodes must be a nonempty struct array.');
    end
end

function validate_dispersion_and_borders(dispersion, borders)
    require_scalar_struct(dispersion, 'dispersion');
    require_exact_fields(dispersion, {'target_frequency', 'direction_ordering', ...
        'scan_axis_angles_deg', 'scan_axis_count', 'directions', 'estimators'}, 'dispersion');
    require_exact_fields(dispersion.estimators, {'kf_ridge', 'phase_gradient'}, ...
        'dispersion.estimators');
    kf = dispersion.estimators.kf_ridge;
    require_exact_fields(kf, {'method', 'frequency_axis_hz', ...
        'frequency_axis_quantity', 'frequency_axis_units', 'frequency_axis_layout', ...
        'directions'}, 'dispersion.estimators.kf_ridge');
    if string(kf.method) ~= "windowed_fft_ridge" || ...
            string(kf.frequency_axis_quantity) ~= "temporal_frequency" || ...
            string(kf.frequency_axis_units) ~= "Hz" || ...
            string(kf.frequency_axis_layout) ~= "frequency" || ...
            string(dispersion.direction_ordering) ~= "acquisition_direction_order"
        invalid('Dispersion method, frequency metadata, or ordering is invalid.');
    end
    frequency = kf.frequency_axis_hz;
    if ~isnumeric(frequency) || ~isreal(frequency) || ~isvector(frequency) || ...
            isempty(frequency) || any(~isfinite(frequency)) || any(diff(frequency(:)) <= 0)
        invalid('k-f frequency_axis_hz must be finite and increasing.');
    end

    target = dispersion.target_frequency;
    require_scalar_struct(target, 'dispersion.target_frequency');
    require_exact_fields(target, {'source', 'requested_hz'}, ...
        'dispersion.target_frequency');
    if ~(ischar(target.source) || ...
            (isstring(target.source) && isscalar(target.source)))
        invalid('dispersion.target_frequency.source must be a text scalar.');
    end
    targetSource = string(target.source);
    if targetSource == "resolved_filter_center"
        if ~isnumeric(target.requested_hz) || ...
                ~isscalar(target.requested_hz) || ...
                ~isfinite(target.requested_hz) || target.requested_hz <= 0
            invalid('Resolved target frequency must be positive and finite.');
        end
    elseif targetSource == "not_available"
        if ~isnumeric(target.requested_hz) || ...
                ~isscalar(target.requested_hz) || ~isnan(target.requested_hz)
            invalid('Unavailable target frequency must use requested_hz=NaN.');
        end
    else
        invalid('Unsupported dispersion target-frequency source: %s.', targetSource);
    end

    scanAxisCount = dispersion.scan_axis_count;
    scanAxisAngles = dispersion.scan_axis_angles_deg;
    if ~isnumeric(scanAxisCount) || ~isscalar(scanAxisCount) || ...
            ~isfinite(scanAxisCount) || scanAxisCount < 1 || ...
            scanAxisCount ~= round(scanAxisCount) || ...
            ~isnumeric(scanAxisAngles) || ~isvector(scanAxisAngles) || ...
            numel(scanAxisAngles) ~= scanAxisCount || ...
            any(~isfinite(scanAxisAngles))
        invalid('dispersion scan-axis metadata is invalid.');
    end

    directions = dispersion.directions;
    if ~isstruct(directions) || isempty(directions) || ...
            numel(directions) ~= 2 * scanAxisCount
        invalid('dispersion.directions must contain one left/right pair per scan axis.');
    end
    if ~isstruct(kf.directions) || numel(kf.directions) ~= numel(directions)
        invalid('k-f directions must align with the common direction identities.');
    end
    for index = 1:numel(directions)
        identity = directions(index);
        require_exact_fields(identity, {'scan_axis_index', 'direction'}, 'direction identity');
        if ~isequal(identity.direction, conditional(mod(index, 2) == 1, "left", "right")) || ...
                ~isequal(identity.scan_axis_index, ceil(index / 2))
            invalid('Dispersion direction ordering is invalid at index %d.', index);
        end
        validate_direction(kf.directions(index), index, frequency(:), target);
    end
    validate_phase_gradient(dispersion.estimators.phase_gradient, target, numel(directions));

    require_scalar_struct(borders, 'borders');
    require_exact_fields(borders, {'quantity', 'units', 'layout', ...
        'ordering', 'directional_mean_thickness_mm'}, 'borders');
    thickness = borders.directional_mean_thickness_mm;
    if string(borders.quantity) ~= ...
            "mean_physical_thickness_per_directional_dispersion_window" || ...
            string(borders.units) ~= "mm" || ...
            string(borders.layout) ~= "direction" || ...
            string(borders.ordering) ~= "acquisition_direction_order" || ...
            ~isnumeric(thickness) || ~isvector(thickness) || ...
            numel(thickness) ~= numel(directions)
        invalid('Directional border-thickness contract is invalid.');
    end
end

function validate_direction(direction, index, frequency, target)
    require_exact_fields(direction, {'spectrum', 'ridge', ...
        'phase_speed_curve', 'target_selection'}, sprintf('kf_ridge.directions(%d)', index));
    spectrum = direction.spectrum;
    spectrumRequired = {'quantity', 'units', 'layout', ...
        'temporal_diagnostic_magnitude'};
    if any(~isfield(spectrum, spectrumRequired)) || ...
            string(spectrum.quantity) ~= ...
                "mean_temporal_fft_magnitude_across_lateral_samples" || ...
            string(spectrum.units) ~= "arbitrary_magnitude" || ...
            string(spectrum.layout) ~= "frequency" || ...
            ~isnumeric(spectrum.temporal_diagnostic_magnitude) || ...
            numel(spectrum.temporal_diagnostic_magnitude) ~= numel(frequency)
        invalid('Direction %d temporal diagnostic is invalid.', index);
    end
    curve = direction.phase_speed_curve;
    curveRequired = {'quantity', 'units', 'layout', ...
        'smoothed_phase_speed_m_per_s'};
    if any(~isfield(curve, curveRequired)) || ...
            string(curve.quantity) ~= "phase_speed" || ...
            string(curve.units) ~= "m/s" || ...
            string(curve.layout) ~= "frequency" || ...
            ~isnumeric(curve.smoothed_phase_speed_m_per_s) || ...
            numel(curve.smoothed_phase_speed_m_per_s) ~= numel(frequency)
        invalid('Direction %d phase-speed curve is invalid.', index);
    end
    if isfield(curve, 'raw_phase_speed_m_per_s') && ...
            numel(curve.raw_phase_speed_m_per_s) ~= numel(frequency)
        invalid('Direction %d raw phase-speed curve size is invalid.', index);
    end

    selection = direction.target_selection;
    selectionRequired = {'selected_wavenumber_per_m', 'selected_bin_index', ...
        'selected_frequency_hz', 'frequency_error_hz', ...
        'selected_phase_speed_m_per_s'};
    require_exact_fields(selection, selectionRequired, 'k-f target_selection');

    if string(target.source) == "not_available"
        if ~isfield(selection, 'selected_wavenumber_per_m')
            invalid('Direction %d unavailable target selection is incomplete.', index);
        end
        values = [selection.selected_bin_index, selection.selected_frequency_hz, ...
            selection.frequency_error_hz, ...
            selection.selected_wavenumber_per_m, ...
            selection.selected_phase_speed_m_per_s];
        if ~isnumeric(values) || numel(values) ~= 5 || any(~isnan(values))
            invalid('Direction %d unavailable target selection is invalid.', index);
        end
        return;
    end

    if ~isscalar(selection.selected_bin_index) || ...
            selection.selected_bin_index < 1 || ...
            selection.selected_bin_index > numel(frequency) || ...
            selection.selected_bin_index ~= round(selection.selected_bin_index)
        invalid('Direction %d target selection is invalid.', index);
    end
    selected = selection.selected_bin_index;
    curveValues = curve.smoothed_phase_speed_m_per_s(:);
    if ~isequaln(selection.selected_frequency_hz, frequency(selected)) || ...
            ~isequaln(selection.frequency_error_hz, ...
                frequency(selected) - target.requested_hz) || ...
            ~isequaln(selection.selected_phase_speed_m_per_s, ...
                curveValues(selected))
        invalid('Direction %d selected-bin provenance is inconsistent.', index);
    end
end

function validate_phase_gradient(value, target, count)
    require_exact_fields(value, {'enabled', 'frequency_source', ...
        'target_frequency_reference', 'input', 'directions'}, 'phase_gradient');
    if ~islogical(value.enabled) || ~isscalar(value.enabled) || ...
            ~isequal(value.frequency_source, "acquisition_row.frequency_Hz") || ...
            ~isequal(value.target_frequency_reference, "dispersion.target_frequency.requested_hz") || ...
            ~isstruct(value.directions)
        invalid('Phase-gradient enable state or frequency provenance is invalid.');
    end
    require_scalar_struct(value.input, 'phase_gradient.input');
    if ~value.enabled
        if ~isempty(value.directions) || ~isempty(fieldnames(value.input))
            invalid('Disabled phase gradient must have empty directions and input metadata.');
        end
        return;
    end
    if ~isfinite(target.requested_hz) || numel(value.directions) ~= count
        invalid('Enabled phase gradient requires a physical target and all direction slots.');
    end
    input = value.input;
    require_exact_fields(input, {'source', 'quantity', 'units', 'layout', ...
        'estimator', 'difference_axis'}, 'phase_gradient.input');
    if ~isequal(input.source, "phase.surface") || ...
            ~isequal(input.quantity, "phase_increment") || ~isequal(input.units, "rad") || ...
            ~isequal(input.layout, "lateral_time") || ~isequal(input.difference_axis, "time") || ...
            ~isstring(input.estimator) || ~isscalar(input.estimator) || ...
            ~ismember(input.estimator, ["loupas", "unwrap_then_difference"])
        invalid('Phase-gradient input must describe the pre-filter surface phase increments.');
    end
    scalars = {'phase_slope_rad_per_m', 'wavenumber_cycles_per_m', ...
        'phase_speed_m_per_s', 'r_squared', 'phase_rmse_rad', ...
        'spatial_sample_count', 'spatial_span_mm'};
    for index = 1:count
        direction = value.directions(index);
        require_exact_fields(direction, [{'status'}, scalars], 'phase_gradient direction');
        for field = scalars
            number = direction.(field{1});
            if ~isnumeric(number) || ~isreal(number) || ~isscalar(number)
                invalid('Phase-gradient %s must be a real numeric scalar.', field{1});
            end
        end
        if ~isstring(direction.status) || ~isscalar(direction.status) || ...
                ~ismember(direction.status, ["valid", "nonfinite_signal", ...
                    "undefined_projection", "degenerate_slope"]) || ...
                ~isfinite(direction.spatial_sample_count) || direction.spatial_sample_count < 3 || ...
                direction.spatial_sample_count ~= round(direction.spatial_sample_count) || ...
                ~isfinite(direction.spatial_span_mm) || direction.spatial_span_mm <= 0
            invalid('Phase-gradient status or sampled spatial extent is invalid.');
        end
        estimates = cellfun(@(field) direction.(field), scalars(1:5));
        if direction.status == "valid"
            if any(~isfinite(estimates)) || direction.wavenumber_cycles_per_m <= 0 || ...
                    direction.phase_speed_m_per_s <= 0 || direction.phase_rmse_rad < 0 || ...
                    direction.r_squared > 1 || ...
                    direction.wavenumber_cycles_per_m ~= abs(direction.phase_slope_rad_per_m)/(2*pi) || ...
                    direction.phase_speed_m_per_s ~= target.requested_hz/direction.wavenumber_cycles_per_m
                invalid('Valid phase-gradient estimates are physically inconsistent.');
            end
        elseif any(~isnan(estimates))
            invalid('Invalid phase-gradient directions must preserve NaN estimates.');
        end
    end
end

function validate_gradient_provenance(result)
    gradient = result.dispersion.estimators.phase_gradient;
    if ~gradient.enabled, return; end
    config = result.processing.config;
    try
        % Reuse the acquisition-frequency trust boundary, including canonical text/cell inputs.
        editable = config.DispersionAnalysisOptions;
        editable.target_frequency = rmfield(result.dispersion.target_frequency, 'requested_hz');
        editable.phase_gradient = struct('enabled', true);
        filter = struct('frequency', struct('center_hz', result.dispersion.target_frequency.requested_hz));
        [~, resolved] = oce.config.resolveDispersionAnalysisOptions(editable, filter, ...
            struct2table(result.acquisition.source_row, 'AsArray', true));
        assert(resolved.enabled);
        for name = ["quantity", "units", "layout", "estimator"]
            assert(isequal(gradient.input.(name), config.MotionOptions.surface.(name)));
        end
        assert(isequal(gradient.input.difference_axis, config.MotionOptions.difference_axis));
        assert(all(isfield(config.MotionOptions.surface, ...
            {'surface_reference', 'depth_offset_samples', 'aggregation_band_samples', 'smoothing', 'loupas'})));
    catch exception
        invalid('Phase-gradient acquisition/configuration provenance is inconsistent: %s', exception.message);
    end
end

function validate_angular(angular, dispersion, borders)
    require_scalar_struct(angular, 'angular');
    require_exact_fields(angular, {'unit', 'layout', 'ordering', ...
        'full_circle_angles_deg', 'source_direction_indices', ...
        'phase_speed_m_per_s', 'mean_thickness_mm'}, 'angular');
    nDirections = numel(dispersion.directions);
    indices = angular.source_direction_indices(:);
    if string(angular.unit) ~= "deg" || string(angular.layout) ~= "angle" || ...
            string(angular.ordering) ~= "counterclockwise_full_circle" || ...
            ~isequal(sort(indices), (1:nDirections)') || ...
            numel(angular.full_circle_angles_deg) ~= nDirections || ...
            numel(angular.phase_speed_m_per_s) ~= nDirections || ...
            numel(angular.mean_thickness_mm) ~= nDirections
        invalid('Angular units, layout, permutation, or sizes are invalid.');
    end
    directionalPhase = reshape(arrayfun(@(item) ...
        item.target_selection.selected_phase_speed_m_per_s, ...
        dispersion.estimators.kf_ridge.directions), [], 1);
    if ~isequaln(angular.phase_speed_m_per_s(:), ...
            directionalPhase(indices)) || ...
            ~isequaln(angular.mean_thickness_mm(:), ...
                borders.directional_mean_thickness_mm(indices))
        invalid('Angular arrays do not match their source-direction permutation.');
    end
end

function validate_statistics(statistics, angular)
    require_scalar_struct(statistics, 'statistics');
    require_exact_fields(statistics, {'phase_speed', 'thickness'}, ...
        'statistics');
    [meanPhase, stdPhase, rangePhase] = ...
        oce.results.computeScalarStatistics(angular.phase_speed_m_per_s);
    [meanThickness, stdThickness, rangeThickness] = ...
        oce.results.computeScalarStatistics(angular.mean_thickness_mm * 1e3);
    phase = statistics.phase_speed;
    thickness = statistics.thickness;
    require_scalar_struct(phase, 'statistics.phase_speed');
    require_exact_fields(phase, {'quantity', 'units', 'mean_m_per_s', ...
        'standard_deviation_m_per_s', 'range_m_per_s'}, ...
        'statistics.phase_speed');
    require_scalar_struct(thickness, 'statistics.thickness');
    require_exact_fields(thickness, {'quantity', 'units', 'source_units', ...
        'conversion_factor', 'mean_um', 'standard_deviation_um', ...
        'range_um'}, 'statistics.thickness');
    if string(phase.quantity) ~= "phase_speed" || ...
            string(phase.units) ~= "m/s" || ...
            ~isequaln([phase.mean_m_per_s, ...
                phase.standard_deviation_m_per_s, phase.range_m_per_s], ...
                [meanPhase, stdPhase, rangePhase]) || ...
            string(thickness.quantity) ~= "mean_physical_thickness" || ...
            string(thickness.units) ~= "um" || ...
            string(thickness.source_units) ~= "mm" || ...
            thickness.conversion_factor ~= 1e3 || ...
            ~isequaln([thickness.mean_um, ...
                thickness.standard_deviation_um, thickness.range_um], ...
                [meanThickness, stdThickness, rangeThickness])
        invalid('Persisted statistics are inconsistent with angular arrays.');
    end
end

function require_scalar_struct(value, label)
    if ~isstruct(value) || ~isscalar(value)
        invalid('%s must be a scalar struct.', label);
    end
end

function require_exact_fields(value, expected, label)
    require_scalar_struct(value, label);
    if ~isempty(setxor(fieldnames(value), expected))
        invalid('%s fields do not match schema version 3.', label);
    end
end

function invalid(message, varargin)
    error('OCE:Result:InvalidContract', message, varargin{:});
end

function value = conditional(condition, trueValue, falseValue)
    if condition, value = trueValue; else, value = falseValue; end
end
