function validateReconstructionResult(result)
%VALIDATERECONSTRUCTIONRESULT Validate the maintained reconstruction schema.

    required = ["complex_volume"; "amplitude"; "log_amplitude"; ...
        "axes"; "crop"; "geometry"; "provenance"];
    if ~isstruct(result) || ~isscalar(result) || ...
            ~isequal(string(fieldnames(result)), required)
        error('OCE:Reconstruction:InvalidResult', ...
            'Reconstruction result fields do not match the maintained schema.');
    end
    validate_quantity(result.complex_volume, "complex_oct_amplitude", ...
        "arbitrary_complex_amplitude", "lateral_depth_time");
    validate_quantity(result.amplitude, "mean_temporal_oct_amplitude", ...
        "arbitrary_amplitude", "depth_lateral");
    validate_quantity(result.log_amplitude, "log_oct_amplitude", ...
        "dB_relative", "depth_lateral");
    if result.log_amplitude.definition ~= ...
            "20*log10(mean_temporal_oct_amplitude)"
        error('OCE:Reconstruction:InvalidResult', ...
            'Log-amplitude definition is invalid.');
    end
    requiredAxes = ["lateral"; "depth"; "time"];
    if ~isstruct(result.axes) || ...
            ~isequal(string(fieldnames(result.axes)), requiredAxes)
        error('OCE:Reconstruction:InvalidAxes', ...
            'Reconstruction axes must contain lateral, depth, and time.');
    end
    validate_axis(result.axes.lateral, "sample", "lateral");
    validate_axis(result.axes.depth, "mm", "depth");
    validate_axis(result.axes.time, "s", "time");
    validate_geometry(result.geometry);
    validate_axis_interval(result.axes.depth.values, ...
        result.geometry.depth_sample_interval_mm);

    valuesSize = size(result.complex_volume.values);
    if numel(valuesSize) < 3
        valuesSize(3) = 1;
    end
    expectedAmplitude = [valuesSize(2), valuesSize(1)];
    if ~isequal(size(result.amplitude.values), expectedAmplitude) || ...
            ~isequal(size(result.log_amplitude.values), expectedAmplitude) || ...
            numel(result.axes.lateral.values) ~= valuesSize(1) || ...
            numel(result.axes.depth.values) ~= valuesSize(2) || ...
            numel(result.axes.time.values) ~= valuesSize(3) || ...
            result.geometry.lateral_sample_count ~= valuesSize(1) || ...
            result.geometry.depth_sample_count ~= valuesSize(2) || ...
            result.geometry.time_sample_count ~= valuesSize(3)
        error('OCE:Reconstruction:InvalidLayout', ...
            'Reconstruction arrays, geometry, and axes do not match layouts.');
    end
    if ~isequaln(result.amplitude.values, ...
            mean(abs(result.complex_volume.values), 3)') || ...
            ~isequaln(result.log_amplitude.values, ...
            real(20 * log10(result.amplitude.values)))
        error('OCE:Reconstruction:InvalidResult', ...
            'Derived reconstruction quantities do not match their definitions.');
    end
end

function validate_quantity(value, quantity, units, layout)
    required = ["values"; "quantity"; "units"; "layout"];
    actual = string(fieldnames(value));
    if startsWith(quantity, "log_")
        required(end + 1) = "definition";
    end
    if ~isstruct(value) || ~isscalar(value) || ...
            ~isequal(actual, required) || value.quantity ~= quantity || ...
            value.units ~= units || value.layout ~= layout
        error('OCE:Reconstruction:InvalidResult', ...
            'Reconstruction quantity contract is invalid: %s.', quantity);
    end
end

function validate_axis(axisValue, units, layout)
    required = ["values"; "units"; "meaning"; "layout"];
    if ~isstruct(axisValue) || ~isscalar(axisValue) || ...
            ~isequal(string(fieldnames(axisValue)), required) || ...
            axisValue.units ~= units || axisValue.layout ~= layout || ...
            ~isnumeric(axisValue.values) || isempty(axisValue.values) || ...
            any(~isfinite(axisValue.values)) || ...
            (numel(axisValue.values) > 1 && ...
             any(diff(axisValue.values(:)) <= 0))
        error('OCE:Reconstruction:InvalidAxes', ...
            'Reconstruction %s axis is invalid.', layout);
    end
end

function validate_axis_interval(values, interval)
    values = values(:);
    if numel(values) == 1
        valid = isnan(interval);
    else
        % Account only for roundoff from constructing a uniform physical axis.
        valid = isfinite(interval) && all(abs(diff(values) - interval) <= ...
            16 * eps(max(abs(values))));
    end
    if ~valid
        error('OCE:Reconstruction:InvalidGeometry', ...
            'Depth interval must match the reconstruction depth axis.');
    end
end

function validate_geometry(geometry)
    required = ["spectral_sample_count"; "prepared_spectral_sample_count"; ...
        "fft_sample_count"; "temporal_repetition_count"; ...
        "available_depth_sample_count"; "lateral_sample_count"; ...
        "depth_sample_count"; "time_sample_count"; ...
        "depth_sample_interval_mm"; "time_sample_interval_s"];
    if ~isstruct(geometry) || ~isscalar(geometry) || ...
            ~isequal(string(fieldnames(geometry)), required)
        error('OCE:Reconstruction:InvalidGeometry', ...
            ['Reconstruction geometry must contain only storage/depth/time ' ...
             'dimensions; acquisition-specific geometry belongs elsewhere.']);
    end
    positiveInteger = required(1:8);
    for index = 1:numel(positiveInteger)
        value = geometry.(positiveInteger(index));
        if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
                value <= 0 || value ~= round(value)
            error('OCE:Reconstruction:InvalidGeometry', ...
                'Reconstruction geometry field %s must be a positive integer.', ...
                positiveInteger(index));
        end
    end
    if geometry.spectral_sample_count ~= geometry.prepared_spectral_sample_count || ...
            geometry.fft_sample_count ~= geometry.prepared_spectral_sample_count || ...
            geometry.available_depth_sample_count ~= floor(geometry.fft_sample_count / 2)
        error('OCE:Reconstruction:InvalidGeometry', ...
            'Maintained OCT requires equal raw, prepared, and FFT sample counts.');
    end
    intervalNames = ["depth_sample_interval_mm"; "time_sample_interval_s"];
    for index = 1:numel(intervalNames)
        value = geometry.(intervalNames(index));
        if ~isnumeric(value) || ~isscalar(value) || ...
                ~(isnan(value) || (isfinite(value) && value > 0))
            error('OCE:Reconstruction:InvalidGeometry', ...
                'Reconstruction geometry interval %s is invalid.', ...
                intervalNames(index));
        end
    end
end
