function geometry = buildAcquisitionGeometry(rawDescriptor, scanGeometry)
%BUILDACQUISITIONGEOMETRY Interpret neutral raw dimensions as acquisition geometry.

    scanGeometry = normalize_geometry(scanGeometry);
    validate_descriptor(rawDescriptor);

    switch scanGeometry
        case "angular_bmodes"
            samplesPerBmode = rawDescriptor.Bframes_in_3Dscan;
            bmodeCount = rawDescriptor.No_3Dscans;
            bmodeWidthMm = resolve_angular_width(rawDescriptor);
            bmodeAxisMm = linspace(0, bmodeWidthMm, samplesPerBmode);
            geometry = struct( ...
                'spectral_sample_count', rawDescriptor.samples_in_Aline, ...
                'temporal_repetition_count', rawDescriptor.Alines_in_Bframe, ...
                'available_depth_sample_count', ...
                    floor(rawDescriptor.samples_in_Aline / 2), ...
                'lateral_sample_count', samplesPerBmode * bmodeCount, ...
                'bmode_count', bmodeCount, ...
                'samples_per_bmode', samplesPerBmode, ...
                'bmode_scan_width_mm', bmodeWidthMm, ...
                'bmode_lateral_axis_mm', bmodeAxisMm, ...
                'lateral_sample_interval_mm', sample_interval(bmodeAxisMm));
        case "raster"
            % One B-mode is one B-scan along x; consecutive B-modes step
            % along y. Positions follow acquisition order from 0 mm.
            [fastLengthMm, slowLengthMm] = resolve_raster_lengths(rawDescriptor);
            samplesPerBmode = rawDescriptor.Bframes_in_3Dscan;
            bmodeCount = rawDescriptor.No_3Dscans;
            bmodeAxisMm = linspace(0, fastLengthMm, samplesPerBmode);
            slowAxisMm = linspace(0, slowLengthMm, bmodeCount);
            if bmodeCount == 1
                slowAxisMm = 0;
            end
            geometry = struct( ...
                'spectral_sample_count', rawDescriptor.samples_in_Aline, ...
                'temporal_repetition_count', rawDescriptor.Alines_in_Bframe, ...
                'available_depth_sample_count', ...
                    floor(rawDescriptor.samples_in_Aline / 2), ...
                'lateral_sample_count', samplesPerBmode * bmodeCount, ...
                'bmode_count', bmodeCount, ...
                'samples_per_bmode', samplesPerBmode, ...
                'bmode_scan_width_mm', fastLengthMm, ...
                'bmode_lateral_axis_mm', bmodeAxisMm, ...
                'lateral_sample_interval_mm', sample_interval(bmodeAxisMm), ...
                'raster', struct( ...
                    'fast_scan_length_mm', fastLengthMm, ...
                    'slow_scan_length_mm', slowLengthMm, ...
                    'slow_axis_mm', slowAxisMm, ...
                    'slow_sample_interval_mm', sample_interval(slowAxisMm)));
        otherwise
            error('OCE:Acquisition:UnsupportedScanGeometry', ...
                'Unsupported scan geometry "%s".', scanGeometry);
    end
end

function value = normalize_geometry(value)
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error('OCE:Acquisition:MissingScanGeometry', ...
            'scanGeometry must be a text scalar.');
    end
    value = lower(strtrim(string(value)));
    if ismissing(value) || strlength(value) == 0
        error('OCE:Acquisition:MissingScanGeometry', ...
            'scanGeometry must not be empty.');
    end
end

function widthMm = resolve_angular_width(rawDescriptor)
    % Historical headers record the B-mode length as the vertical scan length.
    if ~isfield(rawDescriptor, 'bscan_length_mm')
        widthMm = rawDescriptor.Ver_scan_length_mm;
        return;
    end
    widthMm = uniform_bscan_length(rawDescriptor.bscan_length_mm, ...
        rawDescriptor.No_3Dscans);
end

function [fastLengthMm, slowLengthMm] = resolve_raster_lengths(rawDescriptor)
    if ~isfield(rawDescriptor, 'bscan_length_mm') || ...
            ~isfield(rawDescriptor, 'raster_bidirectional')
        error('OCE:Acquisition:InvalidRawDescriptor', ...
            ['Raster geometry requires bscan_length_mm and ' ...
             'raster_bidirectional in the raw descriptor.']);
    end
    if ~islogical(rawDescriptor.raster_bidirectional) || ...
            ~isscalar(rawDescriptor.raster_bidirectional)
        error('OCE:Acquisition:InvalidRawDescriptor', ...
            'rawDescriptor.raster_bidirectional must be a logical scalar.');
    end
    if rawDescriptor.raster_bidirectional
        error('OCE:Acquisition:UnsupportedScanGeometry', ...
            'Bidirectional raster acquisitions are not supported.');
    end
    fastLengthMm = uniform_bscan_length(rawDescriptor.bscan_length_mm, ...
        rawDescriptor.No_3Dscans);
    slowLengthMm = rawDescriptor.Ver_scan_length_mm;
    if rawDescriptor.No_3Dscans > 1 && ~(slowLengthMm > 0)
        error('OCE:Acquisition:InvalidRawDescriptor', ...
            'Raster slow-axis scan length must be positive.');
    end
end

function widthMm = uniform_bscan_length(lengths, bmodeCount)
    if ~isnumeric(lengths) || numel(lengths) ~= bmodeCount || ...
            any(~isfinite(lengths)) || any(lengths <= 0)
        error('OCE:Acquisition:InvalidRawDescriptor', ...
            ['rawDescriptor.bscan_length_mm must hold one positive finite ' ...
             'length per B-scan.']);
    end
    % One local lateral axis serves every B-mode, so lengths must agree
    % (e.g. meridians of an elliptical x/y field are rejected).
    if max(abs(lengths - lengths(1))) > 1e-9 * max(1, lengths(1))
        error('OCE:Acquisition:UnsupportedScanGeometry', ...
            'B-scans of unequal physical length are not supported.');
    end
    widthMm = double(lengths(1));
end

function validate_descriptor(value)
    required = ["samples_in_Aline"; "Alines_in_Bframe"; ...
        "Bframes_in_3Dscan"; "No_3Dscans"; "Ver_scan_length_mm"];
    if ~isstruct(value) || ~isscalar(value)
        error('OCE:Acquisition:InvalidRawDescriptor', ...
            'rawDescriptor must be a scalar struct.');
    end
    for index = 1:numel(required)
        name = required(index);
        if ~isfield(value, name)
            error('OCE:Acquisition:InvalidRawDescriptor', ...
                'rawDescriptor is missing required field %s.', name);
        end
    end
    positiveIntegers = ["samples_in_Aline"; "Alines_in_Bframe"; ...
        "Bframes_in_3Dscan"; "No_3Dscans"];
    for index = 1:numel(positiveIntegers)
        name = positiveIntegers(index);
        item = value.(name);
        if ~isnumeric(item) || ~isscalar(item) || ~isfinite(item) || ...
                item <= 0 || item ~= round(item)
            error('OCE:Acquisition:InvalidRawDescriptor', ...
                'rawDescriptor.%s must be a positive integer.', name);
        end
    end
    width = value.Ver_scan_length_mm;
    if ~isnumeric(width) || ~isscalar(width) || ~isfinite(width) || width < 0
        error('OCE:Acquisition:InvalidRawDescriptor', ...
            'rawDescriptor.Ver_scan_length_mm must be finite and nonnegative.');
    end
end

function interval = sample_interval(axisValues)
    if numel(axisValues) < 2
        interval = NaN;
    else
        interval = axisValues(2) - axisValues(1);
    end
end
