function state = buildAcquisitionState(measurement, configForRun, varargin)
%BUILDACQUISITIONSTATE Build explicit acquisition and reconstruction state.
% ShowProgress is an execution-only option passed to reconstruction.

    parser = inputParser;
    addParameter(parser, 'ShowProgress', false, ...
        @(value) islogical(value) && isscalar(value));
    parse(parser, varargin{:});
    showProgress = parser.Results.ShowProgress;

    validate_inputs(measurement, configForRun);
    rawDescriptor = measurement.raw_descriptor;
    resolvedSystem = configForRun.OCTSystemOptions;
    resolvedSampleOptics = configForRun.SampleOpticalOptions;
    validate_oct_system_options(resolvedSystem);
    validate_sample_optical_options(resolvedSampleOptics);

    octSystem = struct( ...
        'profile', resolvedSystem.profile, ...
        'system_type', resolvedSystem.system_type, ...
        'center_wavelength', resolvedSystem.center_wavelength, ...
        'center_wavelength_source', ...
            resolvedSystem.center_wavelength_source, ...
        'a_scan_rate', resolvedSystem.a_scan_rate, ...
        'a_scan_rate_source', resolvedSystem.a_scan_rate_source, ...
        'depth_sampling_calibration', resolvedSystem.depth_sampling_calibration, ...
        'spectral_sampling', resolvedSystem.spectral_sampling, ...
        'spectral_preprocessing', resolvedSystem.spectral_preprocessing);
    sampleOptics = resolvedSampleOptics;
    scanGeometry = string(configForRun.AcquisitionOptions.scan_geometry);
    acquisitionGeometry = oce.acquisition.buildAcquisitionGeometry( ...
        rawDescriptor, scanGeometry);

    if size(measurement.rawdata, 3) ~= acquisitionGeometry.lateral_sample_count
        error('OCE:Acquisition:InvalidRawDimensions', ...
            ['Raw acquisition lateral storage does not match resolved geometry: ' ...
             'expected %d, actual %d.'], ...
            acquisitionGeometry.lateral_sample_count, ...
            size(measurement.rawdata, 3));
    end
    if showProgress
        fprintf('Reconstruction: starting\n');
    end
    reconstruction = oce.acquisition.reconstructComplexVolume( ...
        measurement, octSystem, sampleOptics, acquisitionGeometry, ...
        configForRun.resolved_crop, ...
        'ShowProgress', showProgress);
    if showProgress
        fprintf('Reconstruction: complete\n');
    end

    state = struct( ...
        'metadata', struct( ...
            'acquisition_mode', string( ...
                configForRun.AcquisitionOptions.acquisition_mode), ...
            'scan_geometry', scanGeometry, ...
            'raw_descriptor', compact_descriptor(rawDescriptor)), ...
        'system', struct('oct', octSystem), ...
        'sample', struct('optics', sampleOptics), ...
        'geometry', compose_geometry(acquisitionGeometry, reconstruction), ...
        'raw', struct( ...
            'spectra', measurement.rawdata, ...
            'quantity', "raw_oct_spectral_samples", ...
            'units', "digitizer_counts", ...
            'layout', "spectral_time_lateral", ...
            'descriptor', rawDescriptor), ...
        'reconstruction', reconstruction);
end

function validate_inputs(measurement, configForRun)
    if ~isstruct(measurement) || ...
            ~isfield(measurement, 'raw_descriptor') || ...
            ~isfield(measurement, 'rawdata')
        error('OCE:Acquisition:InvalidRawMeasurement', ...
            'measurement must contain raw_descriptor and rawdata.');
    end
    if ~isstruct(configForRun) || ...
            ~isfield(configForRun, 'OCTSystemOptions') || ...
            ~isfield(configForRun, 'SampleOpticalOptions')
        error('OCE:Acquisition:MissingSystemParameter', ...
            ['configForRun.OCTSystemOptions and SampleOpticalOptions ' ...
             'are required.']);
    end
    validate_acquisition_taxonomy(configForRun);
    if ~isfield(configForRun, 'resolved_crop') || ...
            ~isstruct(configForRun.resolved_crop)
        error('OCE:Acquisition:InvalidParameterSchema', ...
            'configForRun.resolved_crop is required.');
    end
end

function validate_oct_system_options(options)
    required = ["profile"; "system_type"; "center_wavelength"; ...
        "a_scan_rate"; "depth_sampling_calibration"; ...
        "spectral_sampling"; "spectral_preprocessing"];
    if ~isstruct(options) || ~isscalar(options)
        error('OCE:Acquisition:InvalidParameterSchema', ...
            'configForRun.OCTSystemOptions must be a scalar struct.');
    end
    for index = 1:numel(required)
        name = required(index);
        if ~isfield(options, name)
            error('OCE:Acquisition:MissingSystemParameter', ...
                'Resolved OCT system is missing %s.', name);
        end
    end
end

function validate_sample_optical_options(options)
    if ~isstruct(options) || ~isscalar(options) || ...
            ~isfield(options, 'refractive_index') || ...
            ~isstruct(options.refractive_index) || ...
            ~isfield(options.refractive_index, 'value') || ...
            ~isfield(options.refractive_index, 'source')
        error('OCE:Acquisition:InvalidParameterSchema', ...
            'Resolved SampleOpticalOptions are required.');
    end
end

function validate_acquisition_taxonomy(configForRun)
    if ~isfield(configForRun, 'AcquisitionOptions') || ...
            ~isstruct(configForRun.AcquisitionOptions) || ...
            ~isfield(configForRun.AcquisitionOptions, 'acquisition_mode') || ...
            ~isfield(configForRun.AcquisitionOptions, 'scan_geometry')
        error('OCE:Acquisition:InvalidAcquisitionOptions', ...
            'Resolved acquisition_mode and scan_geometry are required.');
    end
    if string(configForRun.AcquisitionOptions.acquisition_mode) ~= "mb_mode"
        error('OCE:Acquisition:UnsupportedAcquisitionMode', ...
            'buildAcquisitionState supports only acquisition mode "mb_mode".');
    end
end

function geometry = compose_geometry(acquisitionGeometry, reconstruction)
    geometry = acquisitionGeometry;
    geometry.depth_sample_count = reconstruction.geometry.depth_sample_count;
    geometry.time_sample_count = reconstruction.geometry.time_sample_count;
    geometry.depth_sample_interval_mm = ...
        reconstruction.geometry.depth_sample_interval_mm;
    geometry.time_sample_interval_s = ...
        reconstruction.geometry.time_sample_interval_s;
end

function descriptor = compact_descriptor(rawDescriptor)
    names = intersect(fieldnames(rawDescriptor), ...
        {'type', 'pattern_control', 'No_3Dscans', ...
         'Bframes_in_3Dscan', 'Alines_in_Bframe', ...
         'samples_in_Aline', 'Hor_scan_length_mm', ...
         'Ver_scan_length_mm', 'bscan_length_mm', 'bscan_angle_deg', ...
         'bscan_storage_reversed', 'raster_bidirectional', ...
         'a_scan_rate_hz', 'excitation'}, 'stable');
    descriptor = struct();
    for index = 1:numel(names)
        descriptor.(names{index}) = rawDescriptor.(names{index});
    end
end
