function result = reconstructComplexVolume(measurement, octSystem, ...
        sampleOptics, acquisitionGeometry, resolvedCrop, varargin)
%RECONSTRUCTCOMPLEXVOLUME Reconstruct geometry-neutral OCT products.
% ShowProgress is an execution-only option and does not affect reconstruction.
% SpectralContext optionally reuses prepareSpectralSamples' validated context
% across payload blocks, so a selected global background is fixed at seams.

    parser = inputParser;
    addParameter(parser, 'ShowProgress', false, ...
        @(value) islogical(value) && isscalar(value));
    addParameter(parser, 'SpectralContext', [], ...
        @(value) isempty(value) || (isstruct(value) && isscalar(value)));
    parse(parser, varargin{:});
    showProgress = parser.Results.ShowProgress;

    validate_inputs(measurement, octSystem, sampleOptics, ...
        acquisitionGeometry, resolvedCrop);

    spectralWindow = hann(acquisitionGeometry.spectral_sample_count);
    spectralContext = parser.Results.SpectralContext;
    if isempty(spectralContext)
        spectralContext = oce.acquisition.prepareSpectralSamples( ...
            measurement.rawdata, octSystem);
    end
    complexValues = complex(zeros( ...
        acquisitionGeometry.lateral_sample_count, ...
        resolvedCrop.depth.sample_count, ...
        resolvedCrop.time.sample_count));
    % Accumulated per position so large rasters never need a second
    % volume-sized abs() temporary; values equal mean(abs(volume),3)'.
    amplitudeValues = zeros(resolvedCrop.depth.sample_count, ...
        acquisitionGeometry.lateral_sample_count);
    timeRange = resolvedCrop.time.start_index_inclusive: ...
        resolvedCrop.time.end_index_inclusive;
    depthRange = resolvedCrop.depth.start_index_inclusive: ...
        resolvedCrop.depth.end_index_inclusive;

    nextProgressPercent = 10;
    for position = 1:acquisitionGeometry.lateral_sample_count
        fringes = oce.acquisition.prepareSpectralSamples( ...
            measurement.rawdata, octSystem, timeRange, position, ...
            spectralContext, "reconstruction");
        spectrum = fft(spectralWindow .* fringes, [], 1);
        preparedSampleCount = size(fringes, 1);
        fftSampleCount = size(spectrum, 1);
        retainedSpectrum = spectrum(depthRange, :);
        complexValues(position, :, :) = retainedSpectrum;
        amplitudeValues(:, position) = mean(abs(retainedSpectrum), 2);

        if showProgress
            completedPercent = floor(100 * position / ...
                acquisitionGeometry.lateral_sample_count);
            while nextProgressPercent <= 100 && ...
                    completedPercent >= nextProgressPercent
                print_progress(nextProgressPercent);
                nextProgressPercent = nextProgressPercent + 10;
            end
        end
    end

    lateralStorageIndex = 1:acquisitionGeometry.lateral_sample_count;
    refractiveIndex = sampleOptics.refractive_index.value;
    intervalInAirUm = depth_interval_in_air( ...
        octSystem.depth_sampling_calibration, ...
        acquisitionGeometry.spectral_sample_count, fftSampleCount);
    depthAxisMm = (0:resolvedCrop.depth.sample_count - 1)' * ...
        intervalInAirUm * 1e-3 / refractiveIndex;
    timeAxisS = (0:resolvedCrop.time.sample_count - 1) / ...
        (octSystem.a_scan_rate * 1000);
    logAmplitudeValues = real(20 * log10(amplitudeValues));

    result = struct( ...
        'complex_volume', struct( ...
            'values', complexValues, ...
            'quantity', "complex_oct_amplitude", ...
            'units', "arbitrary_complex_amplitude", ...
            'layout', "lateral_depth_time"), ...
        'amplitude', struct( ...
            'values', amplitudeValues, ...
            'quantity', "mean_temporal_oct_amplitude", ...
            'units', "arbitrary_amplitude", ...
            'layout', "depth_lateral"), ...
        'log_amplitude', struct( ...
            'values', logAmplitudeValues, ...
            'quantity', "log_oct_amplitude", ...
            'units', "dB_relative", ...
            'layout', "depth_lateral", ...
            'definition', "20*log10(mean_temporal_oct_amplitude)"), ...
        'axes', struct( ...
            'lateral', axis_contract(lateralStorageIndex, "sample", ...
                "lateral_storage_index", "lateral"), ...
            'depth', axis_contract(depthAxisMm, "mm", ...
                "refractive_corrected_depth", "depth"), ...
            'time', axis_contract(timeAxisS, "s", ...
                "acquisition_time", "time")), ...
        'crop', resolvedCrop, ...
        'geometry', reconstruction_geometry_contract( ...
            acquisitionGeometry, preparedSampleCount, fftSampleCount, ...
            resolvedCrop, depthAxisMm, timeAxisS), ...
        'provenance', struct( ...
            'source', "raw_acquisition_spectra", ...
            'window_function', "Hann", ...
            'fft_direction', "forward_along_spectral_axis", ...
            'retained_spectrum', "resolved_depth_crop_of_fft", ...
            'depth_sampling_calibration', octSystem.depth_sampling_calibration, ...
            'refractive_index', refractiveIndex, ...
            'refractive_index_source', ...
                sampleOptics.refractive_index.source, ...
            'center_wavelength_um', octSystem.center_wavelength, ...
            'oct_system_profile', octSystem.profile, ...
            'oct_system_type', octSystem.system_type, ...
            'spectral_sampling_method', ...
                octSystem.spectral_sampling.method, ...
            'background_method', octSystem.spectral_preprocessing. ...
                background_method, ...
            'spectral_resampling_method', ...
                octSystem.spectral_preprocessing.resampling_method, ...
            'spectral_interpolation_method', ...
                octSystem.spectral_preprocessing.interpolation_method));
    oce.results.validateReconstructionResult(result);
end

function intervalUm = depth_interval_in_air(calibration, spectralCount, fftCount)
    switch calibration.method
        case "native_fft_interval"
            intervalUm = calibration.interval_um;
        case "reference_fft_interval"
            if spectralCount ~= calibration.spectral_sample_count
                error('OCE:Acquisition:DepthCalibrationMismatch', ...
                    ['Depth calibration covers %d spectral samples; received %d. ' ...
                     'Supply a calibration for the actual spectral acquisition.'], ...
                    calibration.spectral_sample_count, spectralCount);
            end
            intervalUm = calibration.interval_um * ...
                calibration.reference_fft_sample_count / fftCount;
        otherwise
            error('OCE:Acquisition:InvalidDepthCalibration', ...
                'Unsupported depth sampling calibration method.');
    end
end

function print_progress(percent)
    completedBlocks = percent / 10;
    bar = [repmat('#', 1, completedBlocks), ...
        repmat('.', 1, 10 - completedBlocks)];
    fprintf('Reconstruction [%s] %d%%\n', bar, percent);
end

function axisValue = axis_contract(values, units, meaning, layout)
    axisValue = struct('values', values, 'units', units, ...
        'meaning', meaning, 'layout', layout);
end

function geometry = reconstruction_geometry_contract( ...
        acquisitionGeometry, preparedCount, fftCount, crop, depthAxisMm, timeAxisS)
    geometry = struct( ...
        'spectral_sample_count', ...
            acquisitionGeometry.spectral_sample_count, ...
        'prepared_spectral_sample_count', preparedCount, ...
        'fft_sample_count', fftCount, ...
        'temporal_repetition_count', ...
            acquisitionGeometry.temporal_repetition_count, ...
        'available_depth_sample_count', ...
            floor(fftCount / 2), ...
        'lateral_sample_count', acquisitionGeometry.lateral_sample_count, ...
        'depth_sample_count', crop.depth.sample_count, ...
        'time_sample_count', crop.time.sample_count, ...
        'depth_sample_interval_mm', sample_interval(depthAxisMm), ...
        'time_sample_interval_s', sample_interval(timeAxisS));
end

function interval = sample_interval(axisValues)
    if numel(axisValues) < 2
        interval = NaN;
    else
        interval = axisValues(2) - axisValues(1);
    end
end

function validate_inputs(measurement, octSystem, sampleOptics, ...
        acquisitionGeometry, resolvedCrop)
    if ~isstruct(measurement) || ~isfield(measurement, 'rawdata')
        error('OCE:Acquisition:InvalidRawMeasurement', ...
            'measurement.rawdata is required.');
    end
    requiredOct = ["a_scan_rate"; "depth_sampling_calibration"; ...
        "center_wavelength"; "profile"; "system_type"; ...
        "spectral_sampling"; "spectral_preprocessing"];
    requiredGeometry = ["spectral_sample_count"; ...
        "temporal_repetition_count"; "available_depth_sample_count"; ...
        "lateral_sample_count"];
    requiredRange = ["start_index_inclusive"; "end_index_inclusive"; ...
        "sample_count"];
    assert_fields(octSystem, requiredOct, 'octSystem');
    assert_fields(sampleOptics, "refractive_index", 'sampleOptics');
    assert_fields(sampleOptics.refractive_index, ["value"; "source"], ...
        'sampleOptics.refractive_index');
    assert_fields(acquisitionGeometry, requiredGeometry, ...
        'acquisitionGeometry');
    assert_fields(resolvedCrop, ["depth"; "time"], 'resolvedCrop');
    assert_fields(resolvedCrop.depth, requiredRange, 'resolvedCrop.depth');
    assert_fields(resolvedCrop.time, requiredRange, 'resolvedCrop.time');
    validate_positive_scalar_fields(octSystem, ...
        "a_scan_rate");
    assert_fields(octSystem.depth_sampling_calibration, ...
        ["method"; "interval_um"; "source"], 'depth_sampling_calibration');
    validate_positive_scalar_fields(octSystem.depth_sampling_calibration, "interval_um");
    validate_positive_scalar_fields(sampleOptics.refractive_index, "value");
    centerWavelength = octSystem.center_wavelength;
    if ~isnumeric(centerWavelength) || ~isscalar(centerWavelength) || ...
            ~(isnan(centerWavelength) || ...
              (isfinite(centerWavelength) && centerWavelength > 0))
        error('OCE:Acquisition:InvalidSystemParameter', ...
            'center_wavelength must be positive or NaN when unknown.');
    end

    if size(measurement.rawdata, 1) ~= ...
            acquisitionGeometry.spectral_sample_count
        error('OCE:Acquisition:InvalidRawDimensions', ...
            'Raw spectral length does not match reconstruction geometry.');
    end
    if size(measurement.rawdata, 3) < ...
            acquisitionGeometry.lateral_sample_count
        error('OCE:Acquisition:InvalidRawDimensions', ...
            'Raw acquisition has fewer lateral storage positions than required.');
    end
    if size(measurement.rawdata, 2) < resolvedCrop.time.end_index_inclusive
        error('OCE:Acquisition:InvalidRawDimensions', ...
            'Raw acquisition has fewer time samples than required.');
    end
    if floor(acquisitionGeometry.spectral_sample_count / 2) < ...
            resolvedCrop.depth.end_index_inclusive
        error('OCE:Acquisition:InvalidCrop', ...
            'Requested depth range exceeds the retained FFT half-spectrum.');
    end
    validate_range(resolvedCrop.depth, 'Depth');
    validate_range(resolvedCrop.time, 'Time');
end

function validate_positive_scalar_fields(source, names)
    for index = 1:numel(names)
        value = source.(names(index));
        if ~isnumeric(value) || ~isscalar(value) || ...
                ~isfinite(value) || value <= 0
            error('OCE:Acquisition:InvalidSystemParameter', ...
                '%s must be a positive finite scalar.', names(index));
        end
    end
end

function validate_range(rangeValue, label)
    expected = rangeValue.end_index_inclusive - ...
        rangeValue.start_index_inclusive + 1;
    if expected ~= rangeValue.sample_count
        error('OCE:Acquisition:InvalidCrop', ...
            '%s crop does not match resolved sample_count.', label);
    end
end

function assert_fields(source, names, label)
    if ~isstruct(source)
        error('OCE:Acquisition:InvalidParameterSchema', ...
            '%s must be a struct.', label);
    end
    for index = 1:numel(names)
        if ~isfield(source, names(index))
            error('OCE:Acquisition:MissingSystemParameter', ...
                '%s is missing required field: %s.', label, names(index));
        end
    end
end
