function [artifacts, polarResults] = generateRequestedOutputs( ...
        result, inputs, outputDirectory, resolvedRun, artifacts)
%GENERATEREQUESTEDOUTPUTS Route optional plots and video to maintained owners.

    plots = resolvedRun.plotting;
    products = result.products;
    outputOptions = resolvedRun.output_options;
    displayLimitsDb = ...
        inputs.acquisition_parameters.preview_display.bmode_intensity_limits_db;
    timeSampleStartIndex = double( ...
        products.reconstruction.crop.time.start_index_inclusive);
    [~, filePrefix] = oce.pipeline.resolveOutputDirectory(inputs);

    if plots.reconstruction_preview
        artifacts = append_artifacts(artifacts, ...
            oce.plotting.saveReconstructionPreview( ...
            products.reconstruction, displayLimitsDb, outputDirectory, ...
            'FilePrefix', filePrefix));
    end
    if plots.border_preview
        artifacts = append_artifacts(artifacts, ...
            oce.plotting.saveBorderPreview(products.reconstruction, ...
            products.borders, result.acquisition_state.system.oct, ...
            displayLimitsDb, outputDirectory, 'FilePrefix', filePrefix));
    end
    if plots.filter_preview
        artifacts = append_artifacts(artifacts, ...
            oce.plotting.saveFilterPreviews(products.phase, products.filter, ...
            products.reconstruction, result.acquisition_state.geometry, ...
            outputDirectory, ...
            'CLimMode', outputOptions.phase_clim_mode, ...
            'CLim', outputOptions.phase_clim, ...
            'FilePrefix', filePrefix));
    end
    if resolvedRun.video.filtered_motion
        artifacts = append_artifacts(artifacts, ...
            oce.video.createFilteredMotionVideo( ...
                products.filter, products.phase, products.reconstruction, ...
                products.borders, result.acquisition_state.geometry, ...
                result.config_for_run.VideoOptions, outputDirectory, ...
                'BmodeDisplayLimitsDb', displayLimitsDb, ...
                'CLimMode', outputOptions.video_clim_mode, ...
                'CLim', outputOptions.video_clim, ...
                'ShowProgress', false, ...
                'FilePrefix', filePrefix));
    end
    if plots.dispersion_window_context
        localAxisMm = result.acquisition_state.geometry.bmode_lateral_axis_mm;
        for index = 1:numel(products.windows.bmodes)
            artifacts = append_artifacts(artifacts, ...
                oce.plotting.saveDispersionWindowContext( ...
                    products.windows, products.filter, localAxisMm, ...
                    index, outputDirectory, ...
                    'CLimMode', outputOptions.phase_clim_mode, ...
                    'CLim', outputOptions.phase_clim, ...
                    'TimeSampleStartIndex', timeSampleStartIndex, ...
                    'FilePrefix', filePrefix));
        end
    end
    if plots.kf_plots
        for index = 1:products.dispersion.scan_axis_count
            artifacts = append_artifacts(artifacts, ...
                oce.plotting.saveDispersionKfPreview( ...
                    products.dispersion, index, outputDirectory, ...
                    'FilePrefix', filePrefix));
        end
    end
    if plots.dispersion_plots
        for index = 1:products.dispersion.scan_axis_count
            artifacts = append_artifacts(artifacts, ...
                oce.plotting.saveSpeedDispersionPreview( ...
                    products.dispersion, index, outputDirectory, ...
                    'FilePrefix', filePrefix));
        end
    end

    polarResults = struct();
    if plots.polar_plots
        [polarArtifacts, polarResults] = ...
            oce.plotting.savePolarPhaseResults( ...
                result.outputs.scientific_result, outputDirectory, ...
                'CloseFigures', resolvedRun.output_options.close_figures, ...
                'FilePrefix', filePrefix);
        artifacts = append_artifacts(artifacts, polarArtifacts);
    end
end

function destination = append_artifacts(destination, source)
    destination = [destination; string(source(:))];
end
