function [fig, details] = plotDispersionWindowContext(windowResult, ...
        filterResult, localLateralAxisMm, bmodeIndex, varargin)
%PLOTDISPERSIONWINDOWCONTEXT Overlay resolved ROIs on one space-time B-mode.
% The base map, CLim, delay alignment, and standalone layout are rendered by
% plotBmodeSpaceTime. This function owns only center/ROI overlays.

    parser = inputParser;
    addParameter(parser, 'CLimMode', "robust");
    addParameter(parser, 'CLim', []);
    addParameter(parser, 'Axes', []);
    addParameter(parser, 'TimeSampleStartIndex', 1, @valid_time_sample_start);
    parse(parser, varargin{:});
    validate_inputs(windowResult, filterResult, localLateralAxisMm, bmodeIndex);

    visualDelay = double(filterResult.design.delay_samples) * ...
        double(filterResult.applied);
    geometry = context_geometry(windowResult, localLateralAxisMm);
    suppliedAxes = parser.Results.Axes;
    timeSampleStartIndex = double(parser.Results.TimeSampleStartIndex);
    timeCount = numel(filterResult.time_axis_s);
    timeSampleIndices = timeSampleStartIndex + (0:timeCount - 1);
    dt = double(windowResult.sample_interval_s);
    if string(filterResult.surface_postprocessed.quantity) == "wrapped_phase"
        displayTimeAxisS = (timeSampleIndices - 1) * dt;
    else
        displayTimeAxisS = (timeSampleIndices - 0.5) * dt;
    end
    [fig, basePreview] = oce.plotting.plotBmodeSpaceTime( ...
        filterResult.surface_postprocessed.values, ...
        displayTimeAxisS * 1e3, ...
        filterResult.surface_postprocessed.units, geometry, ...
        "Window context", ...
        'CLimMode', parser.Results.CLimMode, ...
        'CLim', parser.Results.CLim, ...
        'BmodeIndices', bmodeIndex, ...
        'DelaySamples', visualDelay, ...
        'TimeSampleIndices', timeSampleIndices, ...
        'Axes', suppliedAxes);

    bmode = windowResult.bmodes(bmodeIndex);
    baseAxes = basePreview.primary_axes(1);
    if isempty(suppliedAxes)
        overlayAxes = physical_roi_axes(baseAxes, localLateralAxisMm, ...
            basePreview.display_time_samples, ...
            basePreview.display_time_axis_ms);
        leftRectangle = physical_roi_rectangle(overlayAxes, bmode.left);
        rightRectangle = physical_roi_rectangle(overlayAxes, bmode.right);
        centerLine = xline(overlayAxes, bmode.center.x_coordinate_mm, ...
            '-', 'center', 'Color', [1 1 1], ...
            'LineWidth', 1.6, 'FontWeight', 'bold', ...
            'LabelOrientation', 'horizontal', ...
            'LabelHorizontalAlignment', 'center', ...
            'LabelVerticalAlignment', 'top');
    else
        overlayAxes = baseAxes;
        hold(overlayAxes, 'on');
        leftRectangle = sample_roi_rectangle(overlayAxes, bmode.left);
        rightRectangle = sample_roi_rectangle(overlayAxes, bmode.right);
        centerLine = xline(overlayAxes, ...
            bmode.center.local_lateral_index, ...
            '-', 'center', 'Color', [1 1 1], ...
            'LineWidth', 1.6, 'FontWeight', 'bold', ...
            'LabelOrientation', 'horizontal', ...
            'LabelHorizontalAlignment', 'center', ...
            'LabelVerticalAlignment', 'top');
    end
    leftLabel = roi_label(overlayAxes, bmode.left, leftRectangle);
    rightLabel = roi_label(overlayAxes, bmode.right, rightRectangle);

    details = struct( ...
        'bmode_index', bmodeIndex, ...
        'center_metadata', bmode.center, ...
        'left_metadata', rmfield(bmode.left, 'values'), ...
        'right_metadata', rmfield(bmode.right, 'values'), ...
        'image', basePreview.image_handles(1), ...
        'axes', overlayAxes, ...
        'base_axes', baseAxes, ...
        'left_rectangle', leftRectangle, ...
        'right_rectangle', rightRectangle, ...
        'center_line', centerLine, ...
        'left_label', leftLabel, ...
        'right_label', rightLabel, ...
        'visual_delay_samples', visualDelay, ...
        'time_sample_start_index', timeSampleStartIndex, ...
        'source_time_indices', basePreview.source_time_indices, ...
        'display_time_indices', basePreview.display_time_indices, ...
        'colorbar', basePreview.colorbar, ...
        'space_time_preview', basePreview);
end

function geometry = context_geometry(windowResult, localLateralAxisMm)
    geometry = struct( ...
        'bmode_count', numel(windowResult.bmodes), ...
        'samples_per_bmode', numel(localLateralAxisMm), ...
        'bmode_scan_width_mm', ...
            double(localLateralAxisMm(end) - localLateralAxisMm(1)));
end

function ax = physical_roi_axes(baseAxes, lateralAxisMm, timeSamples, timeAxisMs)
    % Same layout tile as the image; limits are the image's sample-edge
    % limits mapped to mm/ms so physical ROIs land on the displayed pixels.
    lateralCount = numel(lateralAxisMm);
    xLimitsMm = interp1(1:lateralCount, double(lateralAxisMm(:)'), ...
        baseAxes.XLim, 'linear', 'extrap');
    yLimitsMs = interp1(double(timeSamples(:)'), double(timeAxisMs(:)'), ...
        baseAxes.YLim, 'linear', 'extrap');
    ax = axes(baseAxes.Parent, 'Color', 'none', ...
        'XLim', xLimitsMm, 'YLim', yLimitsMs, ...
        'YDir', baseAxes.YDir, 'XTick', [], 'YTick', [], ...
        'HitTest', 'off', 'PickableParts', 'none', ...
        'HandleVisibility', 'off');
    ax.Layout.Tile = baseAxes.Layout.Tile;
    hold(ax, 'on');
end

function handle = physical_roi_rectangle(ax, window)
    xRange = double(window.x_axis_mm([1 end]));
    tRange = double(window.time_axis_s([1 end])) * 1e3;
    handle = rectangle(ax, 'Position', [xRange(1), tRange(1), ...
        diff(xRange), diff(tRange)], 'EdgeColor', [1 1 1], ...
        'LineStyle', ':', 'LineWidth', 1.8);
end

function handle = sample_roi_rectangle(ax, window)
    xRange = double(window.local_lateral_indices([1 end]));
    tRange = double(window.time_indices([1 end]));
    handle = rectangle(ax, 'Position', [xRange(1), tRange(1), ...
        diff(xRange), diff(tRange)], 'EdgeColor', [1 1 1], ...
        'LineStyle', ':', 'LineWidth', 1.8);
end

function handle = roi_label(ax, window, rectangleHandle)
    position = rectangleHandle.Position;
    yLimits = ylim(ax);
    timeMargin = 0.02 * range(yLimits);
    labelTime = position(2) + position(4) + timeMargin;
    verticalAlignment = 'top';
    if labelTime > yLimits(2)
        labelTime = position(2) - timeMargin;
        verticalAlignment = 'bottom';
    end
    xIndices = window.local_lateral_indices([1 end]);
    tIndices = window.time_indices([1 end]);
    label = sprintf('%s ROI\nx: %d:%d | t: %d:%d', ...
        char(window.direction), xIndices(1), xIndices(2), ...
        tIndices(1), tIndices(2));
    handle = text(ax, position(1) + position(3) / 2, labelTime, label, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', verticalAlignment, ...
        'Color', [1 1 1], 'FontSize', 8, 'FontWeight', 'bold', ...
        'BackgroundColor', [0 0 0], 'Margin', 2, ...
        'Clipping', 'on');
end

function validate_inputs(windowResult, filterResult, xAxisMm, bmodeIndex)
    if ~isstruct(windowResult) || ~isscalar(windowResult) || ...
            ~isfield(windowResult, 'bmodes') || ...
            bmodeIndex < 1 || bmodeIndex > numel(windowResult.bmodes)
        error('OCE:Plotting:InvalidWindowResult', ...
            'windowResult does not contain the requested B-mode.');
    end
    requiredFilter = {'surface_postprocessed', 'time_axis_s', ...
        'applied', 'design'};
    if ~isstruct(filterResult) || any(~isfield(filterResult, requiredFilter)) || ...
            ~isfield(filterResult.surface_postprocessed, 'values') || ...
            ~isfield(filterResult.surface_postprocessed, 'units') || ...
            ~isfield(filterResult.design, 'delay_samples')
        error('OCE:Plotting:InvalidFilterResult', ...
            ['filterResult surface values, units, time axis, and filter ' ...
             'design are required.']);
    end
    delay = double(filterResult.design.delay_samples) * ...
        double(filterResult.applied);
    timeCount = numel(filterResult.time_axis_s);
    if ~isscalar(delay) || ~isfinite(delay) || delay < 0 || ...
            delay ~= round(delay) || delay >= timeCount - 1
        error('OCE:Plotting:InvalidFilterResult', ...
            'Visual filter delay must leave at least two time samples.');
    end
    bmode = windowResult.bmodes(bmodeIndex);
    sampleCount = diff(bmode.global_lateral_range) + 1;
    if ~isnumeric(xAxisMm) || numel(xAxisMm) ~= sampleCount || ...
            any(~isfinite(xAxisMm)) || any(diff(xAxisMm(:)) <= 0)
        error('OCE:Plotting:InvalidWindowAxis', ...
            'localLateralAxisMm must match one complete B-mode.');
    end
end

function tf = valid_time_sample_start(value)
    tf = isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value >= 1 && value == round(value);
end
