function data = prepareEnfaceMotionVisualization(filterResult, ...
        reconstructionResult, geometry, varargin)
%PREPAREENFACEMOTIONVISUALIZATION Arrange raster surface motion as XY frames.
% data = prepareEnfaceMotionVisualization(filterResult, reconstructionResult,
%     geometry, 'MedianWindow', [3 3])
%
% Inputs are the filtered surface phase (lateral-by-time), the reconstruction
% crop/time sampling and the raster acquisition geometry. Every raster
% position is synchronized to its own excitation trigger, so one time sample
% across all positions forms one en-face frame. Display processing only:
% FIR delay is compensated visually, each pixel's temporal mean is removed and
% an optional spatial median is applied per frame. Scientific arrays are not
% modified. Output frames use layout y_x_time with Cartesian x/y axes in mm,
% positions measured from the first acquired A-line/B-scan.

    parser = inputParser;
    addParameter(parser, 'MedianWindow', [3 3], @valid_median_window);
    parse(parser, varargin{:});
    medianWindow = parser.Results.MedianWindow;

    validate_inputs(filterResult, reconstructionResult, geometry);
    values = double(filterResult.surface.values);
    samplesPerBmode = double(geometry.samples_per_bmode);
    bmodeCount = double(geometry.bmode_count);
    if size(values, 1) ~= samplesPerBmode * bmodeCount
        error('OCE:Plotting:InvalidEnfaceGeometry', ...
            'Surface rows must equal samples_per_bmode * bmode_count.');
    end

    visualDelay = double(filterResult.design.delay_samples) * ...
        double(filterResult.applied);
    sourceTimeIndices = (visualDelay + 1):size(values, 2);
    if isempty(sourceTimeIndices)
        error('OCE:Plotting:InvalidEnfaceTime', ...
            'The filter delay leaves no displayable time samples.');
    end
    values = values(:, sourceTimeIndices);
    invalid = false(size(values, 1), 1);
    if isfield(filterResult, 'invalid_rows') && ...
            isfield(filterResult.invalid_rows, 'mask')
        invalid = logical(filterResult.invalid_rows.mask(:));
    end
    invalid = invalid | any(~isfinite(values), 2);
    values(invalid, :) = 0;
    values = values - mean(values, 2);

    % Storage order is fast-axis position within each B-scan, then B-scan.
    fastSlowTime = reshape(values, samplesPerBmode, bmodeCount, []);
    invalidFastSlow = reshape(invalid, samplesPerBmode, bmodeCount);
    % Raster B-scans run along x and step along y: frames are [y, x, time].
    frames = permute(fastSlowTime, [2 1 3]);
    invalidYX = invalidFastSlow.';
    xAxisMm = double(geometry.bmode_lateral_axis_mm(:)');
    yAxisMm = double(geometry.raster.slow_axis_mm(:)');

    for timeIndex = 1:size(frames, 3)
        frames(:, :, timeIndex) = oce.plotting.postprocessMotionOverlayFrame( ...
            frames(:, :, timeIndex), medianWindow);
    end
    frames(repmat(invalidYX, 1, 1, size(frames, 3))) = NaN;

    cropStartIndex = double( ...
        reconstructionResult.crop.time.start_index_inclusive);
    dt = double(reconstructionResult.geometry.time_sample_interval_s);
    displaySampleIndices = cropStartIndex + (0:numel(sourceTimeIndices) - 1);
    if string(filterResult.surface.quantity) == "wrapped_phase"
        timeAxisS = (displaySampleIndices - 1) * dt;
    else
        % A phase increment belongs between two consecutive M-repetitions.
        timeAxisS = (displaySampleIndices - 0.5) * dt;
    end

    data = struct( ...
        'frames', frames, ...
        'layout', "y_x_time", ...
        'valid_mask', ~invalidYX, ...
        'x_axis_mm', xAxisMm, ...
        'y_axis_mm', yAxisMm, ...
        'time_axis_s', timeAxisS, ...
        'time_axis_ms', timeAxisS * 1e3, ...
        'quantity', string(filterResult.surface.quantity), ...
        'units', string(filterResult.surface.units), ...
        'filter_applied', logical(filterResult.applied), ...
        'median_window', medianWindow);
end

function validate_inputs(filterResult, reconstructionResult, geometry)
    if ~isstruct(filterResult) || ~isscalar(filterResult) || ...
            ~isfield(filterResult, 'applied') || ...
            ~isfield(filterResult, 'surface') || ...
            ~isfield(filterResult.surface, 'values') || ...
            ~isfield(filterResult.surface, 'quantity') || ...
            ~isfield(filterResult.surface, 'units') || ...
            ~isfield(filterResult, 'design') || ...
            ~isfield(filterResult.design, 'delay_samples')
        error('OCE:Plotting:InvalidEnfaceMotion', ...
            'A filter_result with surface values and FIR design is required.');
    end
    if ~isnumeric(filterResult.surface.values) || ...
            ~ismatrix(filterResult.surface.values) || ...
            isempty(filterResult.surface.values)
        error('OCE:Plotting:InvalidEnfaceMotion', ...
            'filter_result.surface.values must be a lateral-by-time matrix.');
    end
    if ~isstruct(reconstructionResult) || ...
            ~isfield(reconstructionResult, 'crop') || ...
            ~isfield(reconstructionResult, 'geometry') || ...
            ~isfield(reconstructionResult.geometry, 'time_sample_interval_s')
        error('OCE:Plotting:InvalidEnfaceMotion', ...
            'reconstruction_result crop and time sampling are required.');
    end
    if ~isstruct(geometry) || ~isfield(geometry, 'raster') || ...
            ~isfield(geometry, 'samples_per_bmode') || ...
            ~isfield(geometry, 'bmode_count') || ...
            ~isfield(geometry, 'bmode_lateral_axis_mm')
        error('OCE:Plotting:InvalidEnfaceGeometry', ...
            'En-face motion requires raster acquisition geometry.');
    end
end

function tf = valid_median_window(value)
    tf = isempty(value) || (isnumeric(value) && isvector(value) && ...
        numel(value) == 2 && all(isfinite(value)) && ...
        all(value >= 1) && all(value == round(value)));
end
