function data = prepareMotionVisualization(depthProduct, ...
        reconstructionResult, borderResult, geometry, timeAxisS, ...
        depthOptions, varargin)
%PREPAREMOTIONVISUALIZATION Align depth-motion arrays for preview or output.
% This function prepares visualization arrays only and never changes results.

    parser = inputParser;
    addParameter(parser, 'BmodeMode', "representative", ...
        @(x) (ischar(x) || (isstring(x) && isscalar(x))) && ...
        ismember(lower(string(x)), ["representative", "all"]));
    parse(parser, varargin{:});

    if ~isstruct(depthProduct) || ~isfield(depthProduct, 'values') || ...
            ~isnumeric(depthProduct.values) || ndims(depthProduct.values) ~= 3
        error('OCE:Plotting:InvalidDepthMotion', ...
            'depthProduct.values must be lateral-by-depth-by-time.');
    end
    if ~isstruct(borderResult) || ~isfield(borderResult, 'intensityMask') || ...
            ~islogical(borderResult.intensityMask)
        error('OCE:Plotting:InvalidMotionMask', ...
            'borderResult.intensityMask is required.');
    end
    depthValues = depthProduct.values;
    selection = oce.plotting.resolveBmodeLayout( ...
        geometry, size(depthValues, 1), parser.Results.BmodeMode);
    timeAxisS = double(timeAxisS(:)');
    if numel(timeAxisS) ~= size(depthValues, 3) || ...
            any(~isfinite(timeAxisS)) || any(diff(timeAxisS) <= 0)
        error('OCE:Plotting:InvalidMotionTimeAxis', ...
            'timeAxisS must match the depth-motion time dimension.');
    end

    fullDepthAxis = reconstructionResult.axes.depth.values(:);
    fullDepthCount = numel(fullDepthAxis);
    phaseDepthCount = size(depthValues, 2);
    [depthAxisMm, backgroundRows] = resolve_depth_alignment( ...
        fullDepthAxis, phaseDepthCount, depthOptions);
    logAmplitude = reconstructionResult.log_amplitude.values;
    if size(logAmplitude, 1) ~= fullDepthCount || ...
            ~isequal(size(borderResult.intensityMask), size(logAmplitude))
        error('OCE:Plotting:InvalidMotionGeometry', ...
            'Reconstruction and intensity mask dimensions must match.');
    end
    [surfaceMode, anteriorIndices, posteriorIndices] = ...
        resolve_geometry_indices(borderResult, size(logAmplitude, 2));

    panels = repmat(struct('bmode_index', [], 'angle_deg', [], ...
        'phase_values', [], 'background_db', [], 'intensity_mask', [], ...
        'geometry_mask', [], 'visualization_mask', []), ...
        numel(selection.indices), 1);
    for index = 1:numel(selection.indices)
        range = selection.global_lateral_ranges(index, 1): ...
            selection.global_lateral_ranges(index, 2);
        panels(index).bmode_index = selection.indices(index);
        panels(index).angle_deg = selection.angles_deg(index);
        panels(index).phase_values = permute( ...
            depthValues(range, :, :), [2 1 3]);
        panels(index).background_db = logAmplitude(backgroundRows, range);
        panels(index).intensity_mask = ...
            borderResult.intensityMask(backgroundRows, range);
        panels(index).geometry_mask = build_geometry_mask( ...
            backgroundRows, anteriorIndices(range), posteriorIndices(range), ...
            surfaceMode);
        panels(index).visualization_mask = ...
            panels(index).geometry_mask & panels(index).intensity_mask;
    end

    data = struct( ...
        'panels', panels, ...
        'selection', selection, ...
        'local_lateral_axis_mm', selection.local_lateral_axis_mm, ...
        'depth_axis_mm', depthAxisMm, ...
        'time_axis_s', timeAxisS, ...
        'time_axis_ms', timeAxisS * 1e3, ...
        'phase_units', string(depthProduct.units));
end

function [depthAxisMm, rows] = resolve_depth_alignment( ...
        fullDepthAxis, phaseDepthCount, options)
    fullDepthCount = numel(fullDepthAxis);
    if phaseDepthCount == fullDepthCount
        rows = 1:fullDepthCount;
        depthAxisMm = fullDepthAxis;
        return;
    end
    if ~isstruct(options) || ~isfield(options, 'estimator') || ...
            string(options.estimator) ~= "loupas" || ...
            ~isfield(options, 'loupas') || ...
            ~isfield(options.loupas, 'axial_window_samples')
        error('OCE:Plotting:UnsupportedDepthAlignment', ...
            ['Depth-motion size differs from reconstruction depth and no ' ...
             'Loupas window metadata is available for preview alignment.']);
    end
    window = options.loupas.axial_window_samples;
    if ~isnumeric(window) || ~isscalar(window) || ~isfinite(window) || ...
            window < 2 || phaseDepthCount ~= fullDepthCount - window + 1
        error('OCE:Plotting:UnsupportedDepthAlignment', ...
            'Loupas depth dimensions do not match the configured axial window.');
    end
    centers = (1:phaseDepthCount) + (double(window) - 1) / 2;
    rows = min(fullDepthCount, max(1, round(centers)));
    depthAxisMm = interp1(1:fullDepthCount, fullDepthAxis, centers, 'linear');
    depthAxisMm = depthAxisMm(:);
end

function [surfaceMode, anterior, posterior] = ...
        resolve_geometry_indices(borderResult, lateralCount)
    if ~isfield(borderResult, 'surface_mode') || ...
            ~(ischar(borderResult.surface_mode) || ...
            (isstring(borderResult.surface_mode) && ...
            isscalar(borderResult.surface_mode)))
        error('OCE:Plotting:InvalidMotionGeometry', ...
            'borderResult.surface_mode is required for motion visualization.');
    end
    surfaceMode = lower(string(borderResult.surface_mode));
    if ~ismember(surfaceMode, ["anterior_posterior", "anterior_only"])
        error('OCE:Plotting:InvalidMotionGeometry', ...
            'Unsupported borderResult.surface_mode for motion visualization.');
    end
    if ~isfield(borderResult, 'indices') || ...
            ~isstruct(borderResult.indices) || ...
            ~isfield(borderResult.indices, 'anterior') || ...
            ~isfield(borderResult.indices, 'posterior') || ...
            ~isnumeric(borderResult.indices.anterior) || ...
            ~isnumeric(borderResult.indices.posterior)
        error('OCE:Plotting:InvalidMotionGeometry', ...
            'borderResult.indices anterior/posterior fields are required.');
    end
    anterior = double(borderResult.indices.anterior(:)');
    posterior = double(borderResult.indices.posterior(:)');
    if numel(anterior) ~= lateralCount || numel(posterior) ~= lateralCount
        error('OCE:Plotting:InvalidMotionGeometry', ...
            'Border index counts must match the reconstruction lateral dimension.');
    end
end

function mask = build_geometry_mask(rows, anterior, posterior, surfaceMode)
    rows = double(rows(:));
    mask = false(numel(rows), numel(anterior));
    for lateralIndex = 1:numel(anterior)
        anteriorIndex = anterior(lateralIndex);
        if ~isfinite(anteriorIndex)
            continue;
        end
        if surfaceMode == "anterior_only"
            mask(:, lateralIndex) = rows >= anteriorIndex - 5;
            continue;
        end
        posteriorIndex = posterior(lateralIndex);
        if ~isfinite(posteriorIndex) || posteriorIndex < anteriorIndex
            continue;
        end
        mask(:, lateralIndex) = ...
            rows >= anteriorIndex - 5 & rows <= posteriorIndex + 5;
    end
end
