function [artifacts, polarResults] = savePolarPhaseResults(oceResult, outputDirectory, varargin)
%SAVEPOLARPHASERESULTS Render and persist phase-speed/thickness polar plots.
% FilePrefix (default "") starts every file name, e.g. the acquisition
% name: <FilePrefix>_<name>.

    if ~isfolder(outputDirectory)
        error('OCE:Plotting:InvalidOutputDirectory', ...
            'An existing output directory is required.');
    end

    p = inputParser;
    addParameter(p, 'CloseFigures', false, @islogical);
    addParameter(p, 'UseTemplate', true, @islogical);
    addParameter(p, 'TemplateFile', 'FigModelPolarPlot.fig', ...
        @(x) ischar(x) || isstring(x));
    addParameter(p, 'CentralFrequencyHz', [], ...
        @(x) isempty(x) || (isnumeric(x) && isscalar(x) && isfinite(x)));
    addParameter(p, 'ComparePhaseGradient', true, @islogical);
    addParameter(p, 'FilePrefix', "", @(value) ischar(value) || (isstring(value) && isscalar(value)));
    parse(p, varargin{:});
    stems = ["PolarThickness"; "PolarPhaseSpeed"];
    if strlength(p.Results.FilePrefix) > 0
        stems = string(p.Results.FilePrefix) + "_" + stems;
    end

    templateFile = string(p.Results.TemplateFile);
    if strlength(templateFile) > 0 && ~isfile(templateFile)
        candidate = string(fullfile(outputDirectory, templateFile));
        if isfile(candidate)
            templateFile = candidate;
        end
    end

    [figures, statistics] = oce.plotting.plotPolarPhaseResults( ...
        oceResult, ...
        'UseTemplate', p.Results.UseTemplate, ...
        'TemplateFile', templateFile, ...
        'CentralFrequencyHz', p.Results.CentralFrequencyHz, ...
        'ComparePhaseGradient', p.Results.ComparePhaseGradient);

    artifacts = [ ...
        string(fullfile(outputDirectory, stems(1) + ".fig")); ...
        string(fullfile(outputDirectory, stems(1) + ".png")); ...
        string(fullfile(outputDirectory, stems(2) + ".fig")); ...
        string(fullfile(outputDirectory, stems(2) + ".png"))];

    saveas(figures(1), artifacts(1));
    saveas(figures(1), artifacts(2));
    saveas(figures(2), artifacts(3));
    saveas(figures(2), artifacts(4));

    polarResults = struct( ...
        'generated_artifacts', artifacts, ...
        'mean_thickness_um', statistics.mean_thickness_um, ...
        'std_thickness_um', statistics.std_thickness_um, ...
        'range_thickness_um', statistics.range_thickness_um, ...
        'mean_phase_speed_m_per_s', statistics.mean_phase_speed_m_per_s, ...
        'std_phase_speed_m_per_s', statistics.std_phase_speed_m_per_s, ...
        'range_phase_speed_m_per_s', statistics.range_phase_speed_m_per_s, ...
        'central_frequency_hz', statistics.central_frequency_hz);

    if p.Results.CloseFigures
        close(figures(isgraphics(figures)));
    end
end
