function artifacts = saveBorderPreview(reconstructionResult, borderResult, ...
        ~, displayLimitsDb, outputDir)
%SAVEBORDERPREVIEW Save the common border and intensity-mask previews.

    artifacts = [ ...
        string(fullfile(outputDir, 'BorderPreview_pixels.fig')); ...
        string(fullfile(outputDir, 'BorderPreview_pixels.png')); ...
        string(fullfile(outputDir, 'BorderMaskPreview.fig')); ...
        string(fullfile(outputDir, 'BorderMaskPreview.png'))];
    borderFigure = figure('Name', 'Border preview');
    borderAxes = axes(borderFigure);
    maskFigure = figure('Name', 'Intensity mask preview');
    maskAxes = axes(maskFigure);
    oce.plotting.plotBorderPreview(borderAxes, maskAxes, ...
        reconstructionResult, borderResult, displayLimitsDb);
    oce.plotting.applyPreviewStyle(borderFigure, borderAxes, ...
        'FigureSize', [820 520]);
    oce.plotting.applyPreviewStyle(maskFigure, maskAxes, ...
        'FigureSize', [820 520]);
    saveas(borderFigure, artifacts(1));
    saveas(borderFigure, artifacts(2));
    saveas(maskFigure, artifacts(3));
    saveas(maskFigure, artifacts(4));
end
