function artifacts = saveSpeedDispersionPreview(analysis, scanAxisIndex, outputDir)
%SAVESPEEDDISPERSIONPREVIEW Save one directional-pair dispersion preview.

    angleDeg = analysis.scan_axis_angles_deg(scanAxisIndex);
    figHandle = oce.plotting.plotSpeedDispersionPreview(analysis, scanAxisIndex);
    artifacts = [string(fullfile(outputDir, sprintf( ...
        'SpeedDispersion_scanAxis%02d_%0.1fdeg.fig', ...
        scanAxisIndex, angleDeg))); ...
        string(fullfile(outputDir, sprintf( ...
        'SpeedDispersion_scanAxis%02d_%0.1fdeg.png', ...
        scanAxisIndex, angleDeg)))];
    saveas(figHandle, artifacts(1));
    saveas(figHandle, artifacts(2));
end
