function artifacts = saveFilterPreviews(phaseResult, filterResult, ...
        reconstructionResult, geometry, outputDir, varargin)
%SAVEFILTERPREVIEWS Save temporal-filter diagnostics and filtered space-time.
% Saved filter previews default to all B-modes; callers may request the
% representative diagnostic layout explicitly.

    parser = inputParser;
    addParameter(parser, 'CLimMode', "robust");
    addParameter(parser, 'CLim', []);
    addParameter(parser, 'BmodeMode', "all");
    parse(parser, varargin{:});

    figures = oce.plotting.plotFilterPreviews( ...
        phaseResult, filterResult, reconstructionResult, geometry, ...
        'CLimMode', parser.Results.CLimMode, ...
        'CLim', parser.Results.CLim, ...
        'BmodeMode', parser.Results.BmodeMode);
    artifacts = [ ...
        string(fullfile(outputDir, 'TemporalFilterSpectrum.fig')); ...
        string(fullfile(outputDir, 'TemporalFilterSpectrum.tif')); ...
        string(fullfile(outputDir, 'TemporalFilterTimeProfile.fig')); ...
        string(fullfile(outputDir, 'TemporalFilterTimeProfile.tif')); ...
        string(fullfile(outputDir, 'FilteredSpaceTime.fig')); ...
        string(fullfile(outputDir, 'FilteredSpaceTime.tif'))];

    for figureIndex = 1:numel(figures)
        artifactIndex = 2 * figureIndex - 1;
        drawnow;
        figures(figureIndex).SizeChangedFcn = [];
        saveas(figures(figureIndex), artifacts(artifactIndex));
        saveas(figures(figureIndex), artifacts(artifactIndex + 1));
    end
end
