function ui = createDispersionWindowTunerUI( ...
        workingOptions, methods, centerValues, spatialManualValue, ...
        temporalManualValue, callbacks)
%CREATEDISPERSIONWINDOWTUNERUI Build dispersion-window tuning controls.

    bmodeCount = numel(centerValues);
    window = uifigure( ...
        'Name', 'Dispersion-window tuning', ...
        'Position', [50 30 1500 960], ...
        'CloseRequestFcn', callbacks.cancel);
    mainGrid = uigridlayout(window, [1 2]);
    mainGrid.ColumnWidth = {'1x', 500};
    mainGrid.RowHeight = {'1x'};
    mainGrid.Padding = [14 14 14 14];
    mainGrid.ColumnSpacing = 16;

    previewAxes = uiaxes(mainGrid);
    previewAxes.Layout.Row = 1;
    previewAxes.Layout.Column = 1;

    controlsPanel = uipanel(mainGrid, ...
        'Title', 'Dispersion-window configuration');
    controlsPanel.Layout.Row = 1;
    controlsPanel.Layout.Column = 2;
    rowCount = bmodeCount + 19;
    controls = uigridlayout(controlsPanel, [rowCount 1]);
    rowHeights = repmat({34}, 1, rowCount);
    rowHeights{3} = 42;
    rowHeights(end - 2:end) = {30, 42, 42};
    controls.RowHeight = rowHeights;
    controls.ColumnWidth = {'1x'};
    controls.Padding = [10 10 10 10];
    controls.RowSpacing = 3;

    bmodeItems = "B-mode " + string(1:bmodeCount);
    bmodeSelector = method_row(controls, 1, 'Preview B-mode', ...
        bmodeItems, bmodeItems(1), callbacks.preview_bmode_changed);

    centerSelector = method_row(controls, 2, 'Center method', ...
        methods.center, workingOptions.center.method, ...
        callbacks.center_method_changed);
    resolvedCenterLabel = uilabel(controls, ...
        'Text', '', 'HorizontalAlignment', 'center', ...
        'FontSize', 10, 'WordWrap', 'on');
    resolvedCenterLabel.Layout.Row = 3;

    centerFields = cell(bmodeCount, 1);
    for index = 1:bmodeCount
        row = index + 3;
        centerIndex = index;
        centerFields{index} = numeric_row(controls, row, ...
            sprintf('Manual center - B-mode %d', index), ...
            centerValues(index), ...
            @(source, ~) callbacks.center_changed( ...
                centerIndex, source.Value), true);
    end

    nextRow = bmodeCount + 4;
    searchGrid = uigridlayout(controls, [1 3]);
    searchGrid.Layout.Row = nextRow;
    searchGrid.ColumnWidth = {230, '1x', '1x'};
    uilabel(searchGrid, 'Text', 'Center search range (fraction)');
    searchStartField = uieditfield(searchGrid, 'numeric', ...
        'Value', workingOptions.center.search_range_fraction(1));
    searchEndField = uieditfield(searchGrid, 'numeric', ...
        'Value', workingOptions.center.search_range_fraction(2));
    searchStartField.ValueChangedFcn = callbacks.search_range_changed;
    searchEndField.ValueChangedFcn = callbacks.search_range_changed;

    rmsSmoothingField = numeric_row(controls, nextRow + 1, ...
        'RMS smoothing span fraction', ...
        workingOptions.center.max_rms_phase_increment.smoothing_span_fraction, ...
        callbacks.rms_smoothing_changed, false);
    mirroredHalfWidthField = numeric_row(controls, nextRow + 2, ...
        'Mirrored half-width fraction', ...
        workingOptions.center.max_mirrored_correlation.half_width_fraction, ...
        callbacks.mirrored_half_width_changed, false);
    mirroredScoreSmoothingField = numeric_row(controls, nextRow + 3, ...
        'Mirrored score smoothing fraction', ...
        workingOptions.center.max_mirrored_correlation. ...
            score_smoothing_span_fraction, ...
        callbacks.mirrored_score_smoothing_changed, false);

    spatialSelector = method_row(controls, nextRow + 4, 'Spatial method', ...
        methods.spatial, workingOptions.spatial.method, ...
        callbacks.spatial_method_changed);
    spatialFractionField = numeric_row(controls, nextRow + 5, ...
        'Spatial fraction of B-mode', ...
        workingOptions.spatial.interval_fraction, ...
        callbacks.spatial_fraction_changed, false);
    spatialManualField = numeric_row(controls, nextRow + 6, ...
        'Spatial interval count', spatialManualValue, ...
        callbacks.spatial_manual_changed, true);

    leftOffsetField = numeric_row(controls, nextRow + 7, ...
        'Left directional offset (samples)', ...
        workingOptions.directional_offsets.left_samples, ...
        callbacks.left_offset_changed, true);
    rightOffsetField = numeric_row(controls, nextRow + 8, ...
        'Right directional offset (samples)', ...
        workingOptions.directional_offsets.right_samples, ...
        callbacks.right_offset_changed, true);

    temporalSelector = method_row(controls, nextRow + 9, 'Temporal method', ...
        methods.temporal, workingOptions.temporal.method, ...
        callbacks.temporal_method_changed);
    startField = numeric_row(controls, nextRow + 10, ...
        'Temporal start sample (absolute)', ...
        workingOptions.temporal.start_index_inclusive, ...
        callbacks.start_changed, true);
    cycleField = numeric_row(controls, nextRow + 11, ...
        'Temporal duration (excitation cycles)', ...
        workingOptions.temporal.cycle_count, callbacks.cycle_changed, false);
    temporalManualField = numeric_row(controls, nextRow + 12, ...
        'Temporal interval count', temporalManualValue, ...
        callbacks.temporal_manual_changed, true);

    statusLabel = uilabel(controls, ...
        'Text', 'Ready', 'HorizontalAlignment', 'center');
    statusLabel.Layout.Row = rowCount - 2;
    acceptButton = uibutton(controls, 'push', ...
        'Text', 'Accept dispersion windows', ...
        'ButtonPushedFcn', callbacks.accept);
    acceptButton.Layout.Row = rowCount - 1;
    cancelButton = uibutton(controls, 'push', ...
        'Text', 'Cancel', 'ButtonPushedFcn', callbacks.cancel);
    cancelButton.Layout.Row = rowCount;

    ui = struct( ...
        'window', window, ...
        'preview_axes', previewAxes, ...
        'bmode_selector', bmodeSelector, ...
        'center_selector', centerSelector, ...
        'resolved_center_label', resolvedCenterLabel, ...
        'center_fields', {centerFields}, ...
        'search_start_field', searchStartField, ...
        'search_end_field', searchEndField, ...
        'rms_smoothing_field', rmsSmoothingField, ...
        'mirrored_half_width_field', mirroredHalfWidthField, ...
        'mirrored_score_smoothing_field', mirroredScoreSmoothingField, ...
        'spatial_selector', spatialSelector, ...
        'spatial_fraction_field', spatialFractionField, ...
        'spatial_manual_field', spatialManualField, ...
        'left_offset_field', leftOffsetField, ...
        'right_offset_field', rightOffsetField, ...
        'temporal_selector', temporalSelector, ...
        'start_field', startField, ...
        'cycle_field', cycleField, ...
        'temporal_manual_field', temporalManualField, ...
        'status_label', statusLabel);
end

function selector = method_row(parent, row, labelText, items, value, callback)
    grid = uigridlayout(parent, [1 2]);
    grid.Layout.Row = row;
    grid.ColumnWidth = {230, '1x'};
    uilabel(grid, 'Text', labelText);
    selector = uidropdown(grid, 'Items', cellstr(string(items)), ...
        'Value', char(string(value)));
    selector.ValueChangedFcn = callback;
end

function field = numeric_row(parent, row, labelText, value, callback, integer)
    grid = uigridlayout(parent, [1 2]);
    grid.Layout.Row = row;
    grid.ColumnWidth = {280, '1x'};
    uilabel(grid, 'Text', labelText);
    field = uieditfield(grid, 'numeric', 'Value', value, ...
        'RoundFractionalValues', logical(integer));
    field.ValueChangedFcn = callback;
end
