function options = getOCTSystemOptions(profile)
%GETOCTSYSTEMOPTIONS Build editable maintained OCT-system parameters.

    if nargin ~= 1
        error('OCE:Config:InvalidOCTSystemProfile', ...
            'One OCT system profile is required.');
    end
    profile = normalize_profile(profile);

    switch profile
        case "swept_source_1300"
            options = base_options( ...
                profile, 1.300, "profile_supplied", ...
                200, "profile_supplied", ...
                7.1, "profile_supplied");
            options.spectral_sampling = struct( ...
                'method', "fft_ready_uniform_k", ...
                'lambda_start_nm', [], ...
                'lambda_end_nm', [], ...
                'parameter_source', "historical_fft_ready_assumption");
            options.spectral_preprocessing = struct( ...
                'background_method', "none", ...
                'resampling_method', "none", ...
                'interpolation_method', "none", ...
                'extrapolation', false);

        case "spectral_domain_1040"
            options = base_options( ...
                profile, 1.0441, "experimentally_characterized", ...
                50, "profile_supplied", ...
                3.57, "experimentally_characterized");
            options.spectral_sampling = struct( ...
                'method', "linear_wavelength_endpoints", ...
                'lambda_start_nm', 945.672, ...
                'lambda_end_nm', 1122.28, ...
                'parameter_source', "assumed_linear_wavelength_endpoints");
            options.spectral_preprocessing = spectral_domain_preprocessing();

        case "spectral_domain_1310"
            lambdaStartNm = 1261.36;
            lambdaEndNm = 1472.76;
            options = base_options( ...
                profile, 1.310, "nominal_system_wavelength", ...
                50, "profile_supplied", ...
                1.48, "experimentally_characterized");
            % Air calibration measured with padding; reconstruction retains
            % the 2048 prepared samples and derives 1.48 * 8192 / 2048 um/bin.
            options.depth_sampling_calibration.method = "reference_fft_interval";
            options.depth_sampling_calibration.spectral_sample_count = 2048;
            options.depth_sampling_calibration.reference_fft_sample_count = 8192;
            options.spectral_sampling = struct( ...
                'method', "linear_wavelength_endpoints", ...
                'lambda_start_nm', lambdaStartNm, ...
                'lambda_end_nm', lambdaEndNm, ...
                'parameter_source', "system_configuration");
            options.spectral_preprocessing = spectral_domain_preprocessing();

        otherwise
            error('OCE:Config:UnknownOCTSystemProfile', ...
                ['Unsupported OCT system profile "%s". Supported profiles ' ...
                 'are "swept_source_1300", "spectral_domain_1040", and ' ...
                 '"spectral_domain_1310".'], profile);
    end

    oce.config.resolveOCTSystemOptions(options);
end

function options = base_options(profile, centerWavelength, centerSource, ...
        aScanRate, aScanRateSource, intervalUm, calibrationSource)
    options = struct( ...
        'profile', profile, ...
        'center_wavelength', centerWavelength, ...
        'center_wavelength_source', centerSource, ...
        'a_scan_rate', aScanRate, ...
        'a_scan_rate_source', aScanRateSource, ...
        'depth_sampling_calibration', struct( ...
            'method', "native_fft_interval", ...
            'interval_um', intervalUm, ...
            'source', calibrationSource), ...
        'spectral_sampling', struct(), ...
        'spectral_preprocessing', struct());
end

function preprocessing = spectral_domain_preprocessing()
    preprocessing = struct( ...
        'background_method', "sample_derived_global_median", ...
        'resampling_method', "uniform_inverse_wavelength", ...
        'interpolation_method', "pchip", ...
        'extrapolation', false);
end

function profile = normalize_profile(value)
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error('OCE:Config:InvalidOCTSystemProfile', ...
            'OCT system profile must be a text scalar.');
    end
    profile = lower(strtrim(string(value)));
    if ismissing(profile) || strlength(profile) == 0
        error('OCE:Config:InvalidOCTSystemProfile', ...
            'OCT system profile must not be empty.');
    end
end
