function resolved = resolveSampleOpticalOptions(options)
%RESOLVESAMPLEOPTICALOPTIONS Resolve one canonical effective sample index.

    if ~isstruct(options) || ~isscalar(options) || ...
            ~isequal(string(fieldnames(options)), "refractive_index")
        error('OCE:Config:InvalidSampleOpticalOptions', ...
            ['SampleOpticalOptions must contain exactly one field: ' ...
             'refractive_index.']);
    end
    value = options.refractive_index;
    required = ["value"; "source"];
    if ~isstruct(value) || ~isscalar(value) || ...
            ~isequal(string(fieldnames(value)), required) || ...
            ~isnumeric(value.value) || ~isscalar(value.value) || ...
            ~isfinite(value.value) || value.value <= 0 || ...
            ~(ischar(value.source) || ...
              (isstring(value.source) && isscalar(value.source))) || ...
            ismissing(string(value.source)) || ...
            strlength(strtrim(string(value.source))) == 0
        error('OCE:Config:InvalidSampleOpticalOptions', ...
            ['SampleOpticalOptions.refractive_index requires a positive ' ...
             'finite scalar value and a nonempty source.']);
    end
    resolved = struct('refractive_index', struct( ...
        'value', double(value.value), 'source', string(value.source)));
end
