function resolved = resolveFilterOptions(configForRun, surfacePhase, octSystem)
%RESOLVEFILTEROPTIONS Resolve temporal-filtering options for one acquisition.

    if ~isstruct(configForRun) || ~isfield(configForRun, 'FilterOptions') || ...
            ~isstruct(configForRun.FilterOptions)
        error('OCE:Filtering:MissingOption', ...
            'config_for_run must contain scalar struct FilterOptions.');
    end
    options = configForRun.FilterOptions;
    require_fields(options, {'enabled', 'method', 'frequency', 'order', ...
        'diagnostic', 'surface_postprocessing', 'invalid_row_policy'}, ...
        'FilterOptions');

    enabled = validate_logical_scalar(options.enabled, ...
        'FilterOptions.enabled');
    method = validate_method(options.method);
    [samplingFrequencyHz, sampleIntervalS, nyquistFrequencyHz] = ...
        resolve_sampling(octSystem);
    [frequency, clampLow, clampHigh] = resolve_frequency( ...
        options.frequency, configForRun, nyquistFrequencyHz);
    order = validate_positive_integer(options.order, ...
        'OCE:Filtering:InvalidOrder', 'FilterOptions.order');
    diagnostic = resolve_diagnostic(options.diagnostic, surfacePhase);
    postprocessing = resolve_postprocessing( ...
        options.surface_postprocessing);
    invalidRowPolicy = validate_invalid_row_policy( ...
        options.invalid_row_policy);

    if clampLow
        warning('OCE:Filtering:PassbandClampedLow', ...
            'Requested low passband edge was <= 0 Hz; using 1 Hz.');
    end
    if clampHigh
        warning('OCE:Filtering:PassbandClampedHigh', ...
            ['Requested high passband edge reached or exceeded Nyquist; ' ...
             'using 0.95 times Nyquist.']);
    end

    resolved = struct( ...
        'enabled', enabled, ...
        'method', method, ...
        'sampling_frequency_hz', samplingFrequencyHz, ...
        'sample_interval_s', sampleIntervalS, ...
        'nyquist_frequency_hz', nyquistFrequencyHz, ...
        'frequency', frequency, ...
        'order', order, ...
        'diagnostic', diagnostic, ...
        'surface_postprocessing', postprocessing, ...
        'invalid_row_policy', invalidRowPolicy);
end

function method = validate_method(value)
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error('OCE:Filtering:MissingOption', ...
            'FilterOptions.method must be the string "fir_bandpass".');
    end
    method = string(value);
    if strlength(method) == 0
        error('OCE:Filtering:MissingOption', ...
            'FilterOptions.method is required.');
    end
    if method ~= "fir_bandpass"
        error('OCE:Filtering:InvalidMethod', ...
            'Unsupported filtering method "%s"; use "fir_bandpass".', method);
    end
end

function [samplingFrequencyHz, sampleIntervalS, nyquistFrequencyHz] = ...
        resolve_sampling(octSystem)
    if ~isstruct(octSystem) || ~isfield(octSystem, 'a_scan_rate') || ...
            ~isnumeric(octSystem.a_scan_rate) || ...
            ~isscalar(octSystem.a_scan_rate) || ...
            ~isfinite(octSystem.a_scan_rate) || octSystem.a_scan_rate <= 0
        error('OCE:Filtering:InvalidSampling', ...
            'OCT_system.a_scan_rate must be a positive finite scalar in kHz.');
    end
    samplingFrequencyHz = double(octSystem.a_scan_rate) * 1000;
    sampleIntervalS = 1 / samplingFrequencyHz;
    nyquistFrequencyHz = samplingFrequencyHz / 2;
end

function [frequency, clampLow, clampHigh] = resolve_frequency( ...
        options, configForRun, nyquistFrequencyHz)
    if ~isstruct(options) || ~isscalar(options)
        error('OCE:Filtering:MissingOption', ...
            'FilterOptions.frequency must be a scalar struct.');
    end
    require_fields(options, {'selection_source', 'column', 'center_hz', ...
        'bandwidth'}, 'FilterOptions.frequency');
    source = validate_string_scalar(options.selection_source, ...
        'OCE:Filtering:InvalidFrequency', ...
        'FilterOptions.frequency.selection_source');

    switch source
        case "acquisition_row"
            column = validate_string_scalar(options.column, ...
                'OCE:Filtering:InvalidFrequency', ...
                'FilterOptions.frequency.column');
            if ~isempty(options.center_hz)
                error('OCE:Filtering:InvalidFrequency', ...
                    ['FilterOptions.frequency.center_hz must be empty when ' ...
                     'selection_source="acquisition_row".']);
            end
            if ~isfield(configForRun, 'acquisition_row') || ...
                    ~istable(configForRun.acquisition_row) || ...
                    height(configForRun.acquisition_row) ~= 1 || ...
                    ~ismember(char(column), ...
                    configForRun.acquisition_row.Properties.VariableNames)
                error('OCE:Filtering:MissingCenterFrequency', ...
                    ['Acquisition metadata must contain one value in column ' ...
                     '"%s", or use manual_configuration.'], column);
            end
            rawValue = configForRun.acquisition_row.(char(column));
            centerHz = numeric_scalar(rawValue);
            metadata = struct('column', column, ...
                'value', metadata_value(rawValue));

        case "manual_configuration"
            centerHz = numeric_scalar(options.center_hz);
            metadata = struct('center_hz', centerHz);

        otherwise
            error('OCE:Filtering:InvalidFrequencySource', ...
                ['Unsupported frequency selection_source "%s"; use ' ...
                 '"acquisition_row" or "manual_configuration".'], source);
    end

    if isempty(centerHz)
        error('OCE:Filtering:MissingCenterFrequency', ...
            ['A center frequency is required. Correct acquisition metadata ' ...
             'or use manual_configuration.']);
    end
    if ~isnumeric(centerHz) || ~isscalar(centerHz) || ...
            ~isfinite(centerHz) || centerHz <= 0 || ...
            centerHz >= nyquistFrequencyHz
        error('OCE:Filtering:InvalidFrequency', ...
            'Center frequency must be positive, finite, and below Nyquist.');
    end

    bandwidth = resolve_bandwidth(options.bandwidth, centerHz);
    requested = [centerHz - bandwidth / 2, centerHz + bandwidth / 2];
    effective = requested;
    clampLow = requested(1) <= 0;
    clampHigh = requested(2) >= nyquistFrequencyHz;
    if clampLow
        effective(1) = 1;
    end
    if clampHigh
        effective(2) = 0.95 * nyquistFrequencyHz;
    end
    if any(~isfinite(requested)) || effective(1) <= 0 || ...
            effective(2) >= nyquistFrequencyHz || ...
            effective(1) >= effective(2)
        error('OCE:Filtering:InvalidPassband', ...
            ['Resolved passband must contain two increasing frequencies ' ...
             'strictly between 0 Hz and Nyquist.']);
    end

    clampMetadata = struct( ...
        'low_was_clamped', clampLow, ...
        'high_was_clamped', clampHigh, ...
        'low_clamp_hz', 1, ...
        'high_clamp_fraction_of_nyquist', 0.95);
    frequency = struct( ...
        'selection_source', source, ...
        'selection_metadata', metadata, ...
        'center_hz', centerHz, ...
        'bandwidth_hz', bandwidth, ...
        'requested_passband_hz', requested, ...
        'effective_passband_hz', effective, ...
        'passband_was_clamped', clampLow || clampHigh, ...
        'clamp_metadata', clampMetadata);
end

function bandwidthHz = resolve_bandwidth(options, centerHz)
    if ~isstruct(options) || ~isscalar(options)
        error('OCE:Filtering:MissingOption', ...
            'FilterOptions.frequency.bandwidth must be a scalar struct.');
    end
    require_fields(options, {'mode', 'fraction', 'hz'}, ...
        'FilterOptions.frequency.bandwidth');
    mode = validate_string_scalar(options.mode, ...
        'OCE:Filtering:InvalidBandwidth', ...
        'FilterOptions.frequency.bandwidth.mode');
    switch mode
        case "fraction_of_center"
            fraction = options.fraction;
            if ~isnumeric(fraction) || ~isscalar(fraction) || ...
                    ~isfinite(fraction) || fraction <= 0
                error('OCE:Filtering:InvalidBandwidth', ...
                    'Bandwidth fraction must be a positive finite scalar.');
            end
            bandwidthHz = double(fraction) * centerHz;
        case "absolute_hz"
            bandwidthHz = options.hz;
            if ~isnumeric(bandwidthHz) || ~isscalar(bandwidthHz) || ...
                    ~isfinite(bandwidthHz) || bandwidthHz <= 0
                error('OCE:Filtering:InvalidBandwidth', ...
                    'Absolute bandwidth must be a positive finite scalar in Hz.');
            end
            bandwidthHz = double(bandwidthHz);
        otherwise
            error('OCE:Filtering:InvalidBandwidthMode', ...
                ['Unsupported bandwidth mode "%s"; use ' ...
                 '"fraction_of_center" or "absolute_hz".'], mode);
    end
end

function diagnostic = resolve_diagnostic(options, surfacePhase)
    if ~isstruct(options) || ~isscalar(options)
        error('OCE:Filtering:MissingOption', ...
            'FilterOptions.diagnostic must be a scalar struct.');
    end
    require_fields(options, {'fft_length', 'line_index'}, ...
        'FilterOptions.diagnostic');
    fftLength = validate_positive_integer(options.fft_length, ...
        'OCE:Filtering:InvalidDiagnostic', ...
        'FilterOptions.diagnostic.fft_length');
    if ~isnumeric(surfacePhase) || ~ismatrix(surfacePhase) || ...
            isempty(surfacePhase)
        error('OCE:Filtering:InvalidDiagnostic', ...
            'Surface phase must be a nonempty numeric lateral-by-time matrix.');
    end
    configuredLine = options.line_index;
    if isempty(configuredLine)
        usedLine = [];
    else
        configuredLine = validate_positive_integer(configuredLine, ...
            'OCE:Filtering:InvalidDiagnostic', ...
            'FilterOptions.diagnostic.line_index');
        usedLine = min(configuredLine, size(surfacePhase, 1));
    end
    diagnostic = struct( ...
        'fft_length', fftLength, ...
        'line_index', configuredLine, ...
        'line_index_used', usedLine);
end

function options = resolve_postprocessing(options)
    if ~isstruct(options) || ~isscalar(options)
        error('OCE:Filtering:MissingOption', ...
            'FilterOptions.surface_postprocessing must be a scalar struct.');
    end
    require_fields(options, {'remove_temporal_mean', 'median'}, ...
        'FilterOptions.surface_postprocessing');
    removeMean = validate_logical_scalar(options.remove_temporal_mean, ...
        'FilterOptions.surface_postprocessing.remove_temporal_mean');
    medianOptions = options.median;
    if ~isstruct(medianOptions) || ~isscalar(medianOptions)
        error('OCE:Filtering:InvalidPostprocessing', ...
            'Surface median options must be a scalar struct.');
    end
    require_fields(medianOptions, {'enabled', 'window_samples'}, ...
        'FilterOptions.surface_postprocessing.median');
    medianEnabled = validate_logical_scalar(medianOptions.enabled, ...
        'FilterOptions.surface_postprocessing.median.enabled');
    window = medianOptions.window_samples;
    if ~isnumeric(window) || ~isvector(window) || numel(window) ~= 2 || ...
            any(~isfinite(window)) || any(window < 1) || ...
            any(window ~= round(window))
        error('OCE:Filtering:InvalidPostprocessing', ...
            ['Median window_samples must contain two positive finite ' ...
             'integer values [lateral time].']);
    end
    options = struct( ...
        'remove_temporal_mean', removeMean, ...
        'median', struct('enabled', medianEnabled, ...
            'window_samples', reshape(double(window), 1, 2)));
end

function policy = validate_invalid_row_policy(value)
    policy = validate_string_scalar(value, ...
        'OCE:Filtering:UnsupportedInvalidRowPolicy', ...
        'FilterOptions.invalid_row_policy');
    if policy ~= "zero_surface_and_matching_depth"
        error('OCE:Filtering:UnsupportedInvalidRowPolicy', ...
            'Unsupported invalid-row policy "%s".', policy);
    end
end

function value = validate_logical_scalar(value, fieldPath)
    if ~islogical(value) || ~isscalar(value)
        error('OCE:Filtering:InvalidOption', ...
            '%s must be a logical scalar.', fieldPath);
    end
end

function value = validate_positive_integer(value, identifier, fieldPath)
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value <= 0 || value ~= round(value)
        error(identifier, '%s must be a positive finite integer scalar.', ...
            fieldPath);
    end
    value = double(value);
end

function value = validate_string_scalar(value, identifier, fieldPath)
    if ~(ischar(value) || (isstring(value) && isscalar(value))) || ...
            strlength(string(value)) == 0
        error(identifier, '%s must be a nonempty string scalar.', fieldPath);
    end
    value = string(value);
end

function value = numeric_scalar(raw)
    value = [];
    if isnumeric(raw) && isscalar(raw)
        value = double(raw);
    elseif iscell(raw) && isscalar(raw)
        value = numeric_scalar(raw{1});
    elseif ischar(raw) || (isstring(raw) && isscalar(raw))
        candidate = str2double(string(raw));
        if ~isnan(candidate)
            value = candidate;
        end
    end
end

function value = metadata_value(raw)
    if iscell(raw) && isscalar(raw)
        raw = raw{1};
    end
    if isnumeric(raw) && isscalar(raw)
        value = double(raw);
    elseif ischar(raw) || (isstring(raw) && isscalar(raw))
        value = string(raw);
    else
        value = string(class(raw));
    end
end

function require_fields(source, names, owner)
    for index = 1:numel(names)
        if ~isfield(source, names{index})
            error('OCE:Filtering:MissingOption', ...
                '%s is missing required field %s.', owner, names{index});
        end
    end
end
