function [resolved, phaseGradient] = resolveDispersionAnalysisOptions(editable, resolvedFilter, acquisitionRow)
%RESOLVEDISPERSIONANALYSISOPTIONS Resolve strict dispersion-analysis intent.
% The first output retains the maintained k-f contract. The second output is
% phase-gradient intent; enabling it requires physical acquisition
% metadata and capturing both outputs. Neither filter center nor passband alone
% establishes a physical excitation frequency.

    require_exact_struct(editable, ...
        {'method', 'spectrum', 'ridge', 'phase_speed', 'target_frequency', ...
         'phase_gradient'}, ...
        "DispersionAnalysisOptions");
    method = supported_string(editable.method, "windowed_fft_ridge", ...
        'OCE:DispersionAnalysis:UnsupportedMethod', 'method');

    require_exact_struct(editable.spectrum, {'fft', 'crop', 'window'}, ...
        "DispersionAnalysisOptions.spectrum");
    require_exact_struct(editable.spectrum.fft, ...
        {'time_bin_count', 'spatial_bin_count'}, ...
        "DispersionAnalysisOptions.spectrum.fft");
    validate_odd_integer(editable.spectrum.fft.time_bin_count, ...
        "spectrum.fft.time_bin_count");
    validate_odd_integer(editable.spectrum.fft.spatial_bin_count, ...
        "spectrum.fft.spatial_bin_count");
    require_exact_struct(editable.spectrum.crop, ...
        {'maximum_frequency_hz', 'maximum_wavenumber_per_m'}, ...
        "DispersionAnalysisOptions.spectrum.crop");
    validate_positive_scalar(editable.spectrum.crop.maximum_frequency_hz, ...
        "spectrum.crop.maximum_frequency_hz");
    validate_positive_scalar( ...
        editable.spectrum.crop.maximum_wavenumber_per_m, ...
        "spectrum.crop.maximum_wavenumber_per_m");
    require_exact_struct(editable.spectrum.window, {'time', 'space'}, ...
        "DispersionAnalysisOptions.spectrum.window");
    editable.spectrum.window.time = validate_window_axis( ...
        editable.spectrum.window.time, "time");
    editable.spectrum.window.space = validate_window_axis( ...
        editable.spectrum.window.space, "space");

    require_exact_struct(editable.ridge, ...
        {'maximum_wavenumber_jump_per_m', 'minimum_relative_magnitude', ...
         'interpolation'}, "DispersionAnalysisOptions.ridge");
    validate_nonnegative_scalar( ...
        editable.ridge.maximum_wavenumber_jump_per_m, ...
        "ridge.maximum_wavenumber_jump_per_m");
    value = editable.ridge.minimum_relative_magnitude;
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 0 || value > 1
        invalid('ridge.minimum_relative_magnitude must be within [0, 1].');
    end
    require_exact_struct(editable.ridge.interpolation, ...
        {'method', 'extrapolate'}, ...
        "DispersionAnalysisOptions.ridge.interpolation");
    editable.ridge.interpolation.method = supported_string( ...
        editable.ridge.interpolation.method, "linear", ...
        'OCE:Config:InvalidDispersionAnalysisOptions', ...
        'ridge.interpolation.method');
    if ~islogical(editable.ridge.interpolation.extrapolate) || ...
            ~isscalar(editable.ridge.interpolation.extrapolate) || ...
            ~editable.ridge.interpolation.extrapolate
        invalid(['ridge.interpolation.extrapolate must be logical true ' ...
            'for windowed_fft_ridge.']);
    end

    require_exact_struct(editable.phase_speed, {'smoothing'}, ...
        "DispersionAnalysisOptions.phase_speed");
    require_exact_struct(editable.phase_speed.smoothing, ...
        {'method', 'span_fraction'}, ...
        "DispersionAnalysisOptions.phase_speed.smoothing");
    editable.phase_speed.smoothing.method = supported_string( ...
        editable.phase_speed.smoothing.method, "lowess", ...
        'OCE:Config:InvalidDispersionAnalysisOptions', ...
        'phase_speed.smoothing.method');
    span = editable.phase_speed.smoothing.span_fraction;
    if ~isnumeric(span) || ~isscalar(span) || ~isfinite(span) || ...
            span <= 0 || span > 1
        invalid('phase_speed.smoothing.span_fraction must be within (0, 1].');
    end

    require_exact_struct(editable.target_frequency, {'source'}, ...
        "DispersionAnalysisOptions.target_frequency");
    editable.target_frequency.source = supported_string( ...
        editable.target_frequency.source, ...
        ["resolved_filter_center", "not_available"], ...
        'OCE:Config:InvalidDispersionAnalysisOptions', ...
        'target_frequency.source');
    if editable.target_frequency.source == "resolved_filter_center"
        targetHz = resolved_target_frequency(resolvedFilter);
    else
        targetHz = NaN;
    end

    require_exact_struct(editable.phase_gradient, {'enabled'}, ...
        "DispersionAnalysisOptions.phase_gradient");
    enabled = editable.phase_gradient.enabled;
    if ~islogical(enabled) || ~isscalar(enabled)
        invalid('phase_gradient.enabled must be a logical scalar.');
    end
    phaseGradient = struct('enabled', enabled, ...
        'target_frequency_hz', NaN, ...
        'frequency_source', "acquisition_row.frequency_Hz");
    if enabled
        if nargin < 3
            error('OCE:PhaseGradient:InvalidPhysicalFrequency', ...
                'Quasi-harmonic acquisition metadata are required.');
        end
        frequencyHz = physical_frequency(acquisitionRow);
        if ~isfinite(targetHz) || targetHz ~= frequencyHz
            error('OCE:PhaseGradient:TargetFrequencyMismatch', ...
                ['The k-f target must equal acquisition_row.frequency_Hz. ' ...
                 'No filter-center substitution is made.']);
        end
        phaseGradient.target_frequency_hz = frequencyHz;
        if nargout < 2
            error('OCE:PhaseGradient:RuntimeOutputRequired', ...
                'Capture the runtime phase-gradient options in the second output.');
        end
    end
    resolved = rmfield(editable, 'phase_gradient');
    resolved.method = method;
    resolved.target_frequency.requested_hz = targetHz;
end

function frequencyHz = physical_frequency(row)
    if ~istable(row) || height(row) ~= 1 || ...
            ~all(ismember({'excitation_type', 'frequency_Hz'}, ...
                row.Properties.VariableNames))
        error('OCE:PhaseGradient:InvalidPhysicalFrequency', ...
            'A canonical acquisition row with excitation_type and frequency_Hz is required.');
    end
    excitation = string(row.excitation_type);
    frequencyHz = row.frequency_Hz;
    % Match the canonical scalar representations accepted by filter options.
    while iscell(frequencyHz) && isscalar(frequencyHz)
        frequencyHz = frequencyHz{1};
    end
    if ischar(frequencyHz) || (isstring(frequencyHz) && isscalar(frequencyHz))
        frequencyHz = str2double(string(frequencyHz));
    end
    if ~isscalar(excitation) || ismissing(excitation) || ...
            excitation ~= "quasi_harmonic" || ~isnumeric(frequencyHz) || ...
            ~isreal(frequencyHz) || ~isscalar(frequencyHz) || ...
            ~isfinite(frequencyHz) || frequencyHz <= 0
        error('OCE:PhaseGradient:InvalidPhysicalFrequency', ...
            'Phase gradient requires a positive physical quasi-harmonic frequency.');
    end
    frequencyHz = double(frequencyHz);
end

function axisOptions = validate_window_axis(axisOptions, axisName)
    pathValue = "DispersionAnalysisOptions.spectrum.window." + axisName;
    require_exact_struct(axisOptions, {'enabled', 'method'}, pathValue);
    if ~islogical(axisOptions.enabled) || ~isscalar(axisOptions.enabled)
        invalid('spectrum.window.%s.enabled must be a logical scalar.', ...
            axisName);
    end
    axisOptions.method = supported_string(axisOptions.method, ...
        "hann_symmetric", 'OCE:Config:InvalidDispersionAnalysisOptions', ...
        "spectrum.window." + axisName + ".method");
end

function frequencyHz = resolved_target_frequency(filterOptions)
    if ~isstruct(filterOptions) || ~isscalar(filterOptions) || ...
            ~isfield(filterOptions, 'frequency') || ...
            ~isstruct(filterOptions.frequency) || ...
            ~isfield(filterOptions.frequency, 'center_hz')
        error('OCE:DispersionAnalysis:InvalidResolvedFilter', ...
            ['resolved_filter.frequency.center_hz is required to resolve ' ...
             'the dispersion target frequency.']);
    end
    frequencyHz = filterOptions.frequency.center_hz;
    if ~isnumeric(frequencyHz) || ~isscalar(frequencyHz) || ...
            ~isfinite(frequencyHz) || frequencyHz <= 0
        error('OCE:DispersionAnalysis:InvalidTargetFrequency', ...
            'The resolved filter center must be positive and finite.');
    end
end

function require_exact_struct(value, expectedFields, pathValue)
    if ~isstruct(value) || ~isscalar(value)
        invalid('%s must be a scalar struct.', pathValue);
    end
    actual = fieldnames(value);
    missing = expectedFields(~ismember(expectedFields, actual));
    extra = actual(~ismember(actual, expectedFields));
    if ~isempty(missing) || ~isempty(extra)
        invalid('%s fields are invalid. Missing=%s; extra=%s.', pathValue, ...
            join_names(missing), join_names(extra));
    end
end

function value = supported_string(value, supported, identifier, fieldName)
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error(identifier, '%s must be a supported string scalar.', fieldName);
    end
    value = lower(strtrim(string(value)));
    if ~any(value == supported)
        error(identifier, 'Unsupported %s: %s.', fieldName, value);
    end
end

function validate_odd_integer(value, fieldName)
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 3 || value ~= round(value) || mod(value, 2) == 0
        invalid('%s must be an odd integer greater than or equal to 3.', ...
            fieldName);
    end
end

function validate_positive_scalar(value, fieldName)
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value <= 0
        invalid('%s must be a positive finite scalar.', fieldName);
    end
end

function validate_nonnegative_scalar(value, fieldName)
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
        invalid('%s must be a nonnegative finite scalar.', fieldName);
    end
end

function value = join_names(names)
    if isempty(names), value = '<none>'; else, value = strjoin(names, ', '); end
end

function invalid(message, varargin)
    error('OCE:Config:InvalidDispersionAnalysisOptions', message, varargin{:});
end
