function result = analyzeWindows(windowResult, thicknessMm, resolvedOptions, varargin)
%ANALYZEWINDOWS Produce structured directional dispersion-analysis results.
% PhaseGradientOptions is the resolver's second output. When enabled,
% SurfacePhase supplies the pre-FIR phase_increment product and
% PhaseTimeStartIndex identifies its first absolute acquisition interval.
% Both estimators use the same resolved windows. Diagnostic vectors remain runtime-only.

    parser = inputParser;
    addParameter(parser, 'UseParallel', false, ...
        @(value) islogical(value) && isscalar(value));
    addParameter(parser, 'PhaseGradientOptions', []);
    addParameter(parser, 'SurfacePhase', []);
    addParameter(parser, 'PhaseTimeStartIndex', []);
    parse(parser, varargin{:});
    useParallel = parser.Results.UseParallel;

    scanAxisCount = validate_inputs( ...
        windowResult, thicknessMm, resolvedOptions);
    gradientOptions = parser.Results.PhaseGradientOptions;
    gradientEnabled = ~isempty(gradientOptions);
    if gradientEnabled
        if ~isstruct(gradientOptions) || ~isscalar(gradientOptions) || ...
                ~isequal(sort(fieldnames(gradientOptions)), ...
                sort({'enabled'; 'target_frequency_hz'; 'frequency_source'})) || ...
                ~islogical(gradientOptions.enabled) || ~isscalar(gradientOptions.enabled)
            error('OCE:PhaseGradient:InvalidOptions', ...
                'Resolved runtime phase-gradient options are required.');
        end
        gradientEnabled = gradientOptions.enabled;
    end
    if gradientEnabled
        validate_phase_source(parser.Results.SurfacePhase, ...
            parser.Results.PhaseTimeStartIndex, windowResult, gradientOptions, ...
            resolvedOptions.target_frequency.requested_hz);
    end
    directions = repmat(empty_direction(), 2 * scanAxisCount, 1);

    if useParallel
        directionWindows = cell(2 * scanAxisCount, 1);
        directionScanAxes = zeros(2 * scanAxisCount, 1);
        directionThicknessMm = zeros(2 * scanAxisCount, 1);
        for scanAxisIndex = 1:scanAxisCount
            leftIndex = scanAxisIndex * 2 - 1;
            rightIndex = scanAxisIndex * 2;
            left = windowResult.bmodes(scanAxisIndex).left;
            right = windowResult.bmodes(scanAxisIndex).right;
            directionWindows{leftIndex} = left;
            directionWindows{rightIndex} = right;
            directionScanAxes([leftIndex rightIndex]) = scanAxisIndex;
            directionThicknessMm(leftIndex) = mean( ...
                thicknessMm(left.global_lateral_indices), 'omitnan');
            directionThicknessMm(rightIndex) = mean( ...
                thicknessMm(right.global_lateral_indices), 'omitnan');
        end

        directionResults = cell(2 * scanAxisCount, 1);
        source = windowResult.source;
        parfor directionIndex = 1:(2 * scanAxisCount)
            directionResults{directionIndex} = analyze_direction( ...
                directionWindows{directionIndex}, ...
                directionScanAxes(directionIndex), ...
                directionThicknessMm(directionIndex), source, ...
                resolvedOptions);
        end
        for directionIndex = 1:(2 * scanAxisCount)
            directions(directionIndex) = directionResults{directionIndex};
        end
    else
        for scanAxisIndex = 1:scanAxisCount
            leftIndex = scanAxisIndex * 2 - 1;
            rightIndex = scanAxisIndex * 2;
            left = windowResult.bmodes(scanAxisIndex).left;
            right = windowResult.bmodes(scanAxisIndex).right;
            directions(leftIndex) = analyze_direction(left, scanAxisIndex, ...
                mean(thicknessMm(left.global_lateral_indices), 'omitnan'), ...
                windowResult.source, resolvedOptions);
            directions(rightIndex) = analyze_direction(right, scanAxisIndex, ...
                mean(thicknessMm(right.global_lateral_indices), 'omitnan'), ...
                windowResult.source, resolvedOptions);
        end
    end

    anglesDeg = 0:180 / scanAxisCount: ...
        180 / scanAxisCount * (scanAxisCount - 1);
    result = struct( ...
        'method', resolvedOptions.method, ...
        'options', resolvedOptions, ...
        'target_frequency', resolvedOptions.target_frequency, ...
        'directions', directions, ...
        'scan_axis_angles_deg', anglesDeg, ...
        'scan_axis_count', scanAxisCount);
    result.phase_gradient = struct('enabled', gradientEnabled, ...
        'target_frequency_hz', NaN, 'frequency_source', "acquisition_row.frequency_Hz", ...
        'input', struct(), ...
        'directions', struct([]));
    if gradientEnabled
        result.phase_gradient.target_frequency_hz = gradientOptions.target_frequency_hz;
        phase = parser.Results.SurfacePhase;
        result.phase_gradient.input = rmfield(phase, 'values');
        cropStart = parser.Results.PhaseTimeStartIndex;
        gradientDirections = cell(2 * scanAxisCount, 1);
        for index = 1:(2 * scanAxisCount)
            scanAxisIndex = ceil(index / 2);
            direction = directions(index).direction;
            window = windowResult.bmodes(scanAxisIndex).(direction);
            % time_indices are absolute increment indices, not FIR columns.
            phaseColumns = window.time_indices - cropStart + 1;
            values = phase.values(window.global_lateral_indices, phaseColumns);
            gradientDirections{index} = oce.dispersion.computePhaseGradientSpeed( ...
                values, window.x_axis_mm, window.time_axis_s, ...
                gradientOptions.target_frequency_hz);
        end
        result.phase_gradient.directions = vertcat(gradientDirections{:});
    end
end

function validate_phase_source(phase, cropStart, windows, options, targetHz)
    if ~isscalar(options.target_frequency_hz) || ...
            ~isnumeric(options.target_frequency_hz) || ...
            ~isreal(options.target_frequency_hz) || ...
            ~isfinite(options.target_frequency_hz) || options.target_frequency_hz <= 0 || ...
            options.target_frequency_hz ~= targetHz || ...
            ~isequal(options.frequency_source, "acquisition_row.frequency_Hz")
        error('OCE:PhaseGradient:InvalidPhysicalFrequency', ...
            'Physical frequency provenance must match the common k-f target.');
    end
    required = {'values', 'quantity', 'units', 'layout', 'estimator', 'difference_axis'};
    if ~isstruct(phase) || ~isscalar(phase) || any(~isfield(phase, required)) || ...
            ~isequal(phase.quantity, "phase_increment") || ...
            ~isequal(phase.units, "rad") || ~isequal(phase.layout, "lateral_time") || ...
            ~isequal(phase.difference_axis, "time") || ...
            ~ismember(string(phase.estimator), ["loupas", "unwrap_then_difference"]) || ...
            ~isnumeric(phase.values) || ~ismatrix(phase.values) || ...
            ~isequal(size(phase.values), windows.source.signal_size)
        error('OCE:PhaseGradient:InvalidPhaseSource', ...
            'The matching pre-filter surface phase_increment product is required.');
    end
    if ~isnumeric(cropStart) || ~isscalar(cropStart) || ~isfinite(cropStart) || ...
            cropStart < 1 || cropStart ~= round(cropStart)
        error('OCE:PhaseGradient:InvalidTimeAlignment', ...
            'PhaseTimeStartIndex must be the absolute first cropped acquisition sample.');
    end
    for index = 1:numel(windows.bmodes)
        for name = ["left", "right"]
            window = windows.bmodes(index).(name);
            columns = window.time_indices - cropStart + 1;
            expectedTime = (window.time_indices - 0.5) * windows.sample_interval_s;
            if numel(columns) ~= size(window.values, 2) || ...
                    any(columns < 1 | columns > size(phase.values, 2)) || ...
                    any(columns ~= round(columns)) || any(diff(columns) ~= 1) || ...
                    ~isequal(window.time_axis_s, expectedTime)
                error('OCE:PhaseGradient:InvalidTimeAlignment', ...
                    'Resolved windows must use absolute increment indices and midpoint times.');
            end
        end
    end
end

function result = analyze_direction(window, scanAxisIndex, thicknessMm, ...
        source, options)
    core = oce.dispersion.computeDirectionalPhaseSpeed( ...
        window, source, options);
    result = struct( ...
        'scan_axis_index', scanAxisIndex, ...
        'direction', core.direction, ...
        'spectrum', core.spectrum, ...
        'ridge', core.ridge, ...
        'phase_speed_curve', core.phase_speed_curve, ...
        'target_selection', core.target_selection, ...
        'mean_thickness_mm', thicknessMm);
end

function value = empty_direction()
    value = struct( ...
        'scan_axis_index', [], ...
        'direction', "", ...
        'spectrum', struct(), ...
        'ridge', struct(), ...
        'phase_speed_curve', struct(), ...
        'target_selection', struct(), ...
        'mean_thickness_mm', []);
end

function scanAxisCount = validate_inputs(result, thicknessMm, options)
    if ~isstruct(result) || ~isscalar(result) || ...
            ~isfield(result, 'source') || ...
            ~isfield(result, 'bmodes') || isempty(result.bmodes)
        error('OCE:DispersionAnalysis:InvalidWindowResult', ...
            'window_result must contain source metadata and B-modes.');
    end
    requiredSource = {'quantity', 'units', 'layout'};
    if ~isstruct(result.source) || any(~isfield(result.source, requiredSource)) || ...
            string(result.source.quantity) ~= "phase_increment" || ...
            string(result.source.units) ~= "rad" || ...
            string(result.source.layout) ~= "lateral_time"
        error('OCE:DispersionAnalysis:InvalidWindowResult', ...
            'window_result source must be phase_increment in rad/lateral_time.');
    end
    if ~isstruct(options) || ~isscalar(options) || ...
            ~isfield(options, 'method') || ...
            string(options.method) ~= "windowed_fft_ridge" || ...
            ~isfield(options, 'target_frequency') || ...
            ~isfield(options.target_frequency, 'requested_hz')
        error('OCE:DispersionAnalysis:InvalidResolvedOptions', ...
            'Resolved DispersionAnalysisOptions are required.');
    end
    scanAxisCount = numel(result.bmodes);
    required = {'left', 'right', 'global_lateral_range'};
    for scanAxisIndex = 1:scanAxisCount
        bmode = result.bmodes(scanAxisIndex);
        if any(~isfield(bmode, required))
            error('OCE:DispersionAnalysis:InvalidWindowResult', ...
                'Every B-mode must contain left and right windows.');
        end
        validate_window(bmode.left, "left");
        validate_window(bmode.right, "right");
    end
    expectedRows = result.bmodes(end).global_lateral_range(2);
    if ~isnumeric(thicknessMm) || ~isvector(thicknessMm) || ...
            numel(thicknessMm) ~= expectedRows
        error('OCE:DispersionAnalysis:InvalidThickness', ...
            'Thickness must contain one value per global lateral sample.');
    end
end

function validate_window(window, expectedDirection)
    required = {'direction', 'values', 'x_axis_mm', 'time_axis_s', ...
        'global_lateral_indices'};
    if ~isstruct(window) || ~isscalar(window) || ...
            any(~isfield(window, required)) || ...
            string(window.direction) ~= expectedDirection
        error('OCE:DispersionAnalysis:InvalidWindowResult', ...
            'Resolved directional window metadata is invalid.');
    end
    if size(window.values, 1) ~= numel(window.global_lateral_indices) || ...
            size(window.values, 1) ~= numel(window.x_axis_mm) || ...
            size(window.values, 2) ~= numel(window.time_axis_s)
        error('OCE:DispersionAnalysis:InvalidWindowResult', ...
            'Resolved window values, indices, and axes must match.');
    end
end
