function [spectrumResult, ridgeResult] = computeDispersionSpectrum(values, xAxisMm, timeAxisS, options, inputMetadata, direction)
%COMPUTEDISPERSIONSPECTRUM Compute the maintained windowed FFT and ridge.

    [surfacePhaseMap, sampleIntervalS, spatialIntervalM, direction] = ...
        validate_inputs(values, xAxisMm, timeAxisS, options, direction);
    if direction == "left"
        surfacePhaseMap = flip(surfacePhaseMap, 2);
    end

    fftTimeCount = options.spectrum.fft.time_bin_count;
    fftSpaceCount = options.spectrum.fft.spatial_bin_count;
    frequencyLimitHz = options.spectrum.crop.maximum_frequency_hz;
    wavenumberLimit = options.spectrum.crop.maximum_wavenumber_per_m;
    maximumJump = options.ridge.maximum_wavenumber_jump_per_m;
    magnitudeFraction = options.ridge.minimum_relative_magnitude;

    windowedMap = apply_spectrum_window( ...
        surfacePhaseMap, options.spectrum.window);
    magnitudeMap = abs(fftshift(fft2( ...
        windowedMap, fftTimeCount, fftSpaceCount)))';
    temporalDiagnosticMap = apply_time_window( ...
        surfacePhaseMap, options.spectrum.window.time);
    temporalMagnitude = abs(fftshift(fft( ...
        temporalDiagnosticMap, fftTimeCount)))';
    frequencyAxis = centered_fft_axis(fftTimeCount, sampleIntervalS);
    wavenumberAxis = centered_fft_axis(fftSpaceCount, spatialIntervalM);
    centerTime = (fftTimeCount + 1) / 2;
    centerSpace = (fftSpaceCount + 1) / 2;
    spanSpace = knnsearch( ...
        wavenumberAxis(centerSpace:end)', wavenumberLimit, 'K', 1) - 1;
    spanTime = knnsearch( ...
        frequencyAxis(centerTime:end)', frequencyLimitHz, 'K', 1) - 1;
    magnitudeMap = magnitudeMap(:, end:-1:1);
    temporalMagnitude = temporalMagnitude(:, end:-1:1);
    temporalMagnitude = temporalMagnitude(:, ...
        centerTime:centerTime + spanTime);
    croppedMagnitude = magnitudeMap( ...
        centerSpace:centerSpace + spanSpace, ...
        centerTime:centerTime + spanTime);
    frequencyHz = frequencyAxis(centerTime:centerTime + spanTime);
    wavenumberPerM = wavenumberAxis(centerSpace:centerSpace + spanSpace);

    [ridgeWavenumber, ridgeMagnitude, validMask, interpolatedMask, ...
        extrapolatedMask] = extract_ridge(croppedMagnitude, frequencyHz, ...
        wavenumberPerM, maximumJump, magnitudeFraction, ...
        options.ridge.interpolation);

    spectrumResult = struct( ...
        'method', "windowed_fft_ridge", ...
        'input', struct( ...
            'quantity', string(inputMetadata.quantity), ...
            'units', string(inputMetadata.units), ...
            'layout', "time_space", ...
            'source_layout', string(inputMetadata.layout), ...
            'direction', direction, ...
            'sample_interval_s', sampleIntervalS, ...
            'spatial_interval_m', spatialIntervalM), ...
        'frequency_axis_hz', frequencyHz, ...
        'wavenumber_axis_per_m', wavenumberPerM, ...
        'magnitude', croppedMagnitude, ...
        'temporal_magnitude_mean', mean(temporalMagnitude, 1)', ...
        'fft', struct( ...
            'time_bin_count', fftTimeCount, ...
            'spatial_bin_count', fftSpaceCount), ...
        'crop', options.spectrum.crop, ...
        'window', spectrum_window_provenance( ...
            options.spectrum.window, size(surfacePhaseMap)));
    ridgeResult = struct( ...
        'wavenumber_per_m', ridgeWavenumber, ...
        'magnitude', ridgeMagnitude, ...
        'valid_mask', validMask, ...
        'interpolated_mask', interpolatedMask, ...
        'extrapolated_mask', extrapolatedMask, ...
        'parameters', options.ridge);
end

function axisValues = centered_fft_axis(sampleCount, sampleInterval)
    halfSpan = (sampleCount - 1) / 2;
    binSpacing = 1 / (sampleCount * sampleInterval);
    axisValues = (-halfSpan:halfSpan) * binSpacing;
end

function windowedMap = apply_spectrum_window(surfacePhaseMap, options)
    persistent cachedSpaceSampleCount cachedSpaceWindow
    windowedMap = apply_time_window(surfacePhaseMap, options.time);
    if options.space.enabled
        sampleCount = size(surfacePhaseMap, 2);
        if isempty(cachedSpaceSampleCount) || ...
                cachedSpaceSampleCount ~= sampleCount
            cachedSpaceSampleCount = sampleCount;
            cachedSpaceWindow = hann(sampleCount, "symmetric").';
        end
        windowedMap = windowedMap .* cachedSpaceWindow;
    end
end

function windowedMap = apply_time_window(surfacePhaseMap, options)
    persistent cachedTimeSampleCount cachedTimeWindow
    windowedMap = surfacePhaseMap;
    if options.enabled
        sampleCount = size(surfacePhaseMap, 1);
        if isempty(cachedTimeSampleCount) || ...
                cachedTimeSampleCount ~= sampleCount
            cachedTimeSampleCount = sampleCount;
            cachedTimeWindow = hann(sampleCount, "symmetric");
        end
        windowedMap = windowedMap .* cachedTimeWindow;
    end
end

function provenance = spectrum_window_provenance(options, mapSize)
    provenance = struct( ...
        'time', struct( ...
            'enabled', options.time.enabled, ...
            'method', options.time.method, ...
            'sample_count', mapSize(1)), ...
        'space', struct( ...
            'enabled', options.space.enabled, ...
            'method', options.space.method, ...
            'sample_count', mapSize(2)));
end

function [map, dt, dx, direction] = validate_inputs( ...
        values, xAxisMm, timeAxisS, options, direction)
    if ~isnumeric(values) || ~ismatrix(values) || ...
            size(values, 1) < 2 || size(values, 2) < 2
        error('OCE:DispersionAnalysis:InvalidWindowValues', ...
            'Window values must contain at least two samples per dimension.');
    end
    if ~isnumeric(xAxisMm) || ~isvector(xAxisMm) || ...
            numel(xAxisMm) ~= size(values, 1) || ...
            any(~isfinite(xAxisMm)) || any(diff(xAxisMm(:)) <= 0)
        error('OCE:DispersionAnalysis:InvalidSpaceAxis', ...
            'Window x_axis_mm must match values and increase.');
    end
    if ~isnumeric(timeAxisS) || ~isvector(timeAxisS) || ...
            numel(timeAxisS) ~= size(values, 2) || ...
            any(~isfinite(timeAxisS)) || any(diff(timeAxisS(:)) <= 0)
        error('OCE:DispersionAnalysis:InvalidTimeAxis', ...
            'Window time_axis_s must match values and increase.');
    end
    direction = lower(strtrim(string(direction)));
    if ~isscalar(direction) || ~ismember(direction, ["left", "right"])
        error('OCE:DispersionAnalysis:InvalidDirection', ...
            'Window direction must be left or right.');
    end
    fftTimeCount = options.spectrum.fft.time_bin_count;
    fftSpaceCount = options.spectrum.fft.spatial_bin_count;
    if fftTimeCount < size(values, 2) || fftSpaceCount < size(values, 1)
        error('OCE:DispersionAnalysis:FFTTooSmall', ...
            'FFT bin counts must not be smaller than the input window.');
    end
    map = values';
    xRelativeMm = xAxisMm(:)' - xAxisMm(1);
    % Preserve the accepted millisecond subtraction/conversion order.
    timeAxisMs = timeAxisS(:)' * 1e3;
    timeRelativeMs = timeAxisMs - timeAxisMs(1);
    dt = timeRelativeMs(2) * 1e-3;
    dx = xRelativeMm(2) * 1e-3;
end

function [ridge, peakMagnitude, validMask, interpolatedMask, ...
        extrapolatedMask] = extract_ridge(magnitude, frequency, wavenumber, ...
        maximumJump, magnitudeFraction, interpolation)
    nFrequency = numel(frequency);
    peakWavenumber = nan(1, nFrequency);
    peakMagnitude = nan(1, nFrequency);
    for index = 1:nFrequency
        [peakAmplitude, peakLocation] = findpeaks( ...
            magnitude(:, index), wavenumber, ...
            'NPeaks', 2, 'SortStr', 'descend');
        if ~isempty(peakLocation)
            peakWavenumber(index) = peakLocation(1);
            peakMagnitude(index) = peakAmplitude(1);
            sameAmplitude = numel(peakLocation) > 1 && ...
                abs(peakAmplitude(1) - peakAmplitude(2)) < 2e-16;
            if sameAmplitude && index > 1 && ...
                    ~isnan(peakWavenumber(index - 1))
                firstDelta = abs(peakLocation(1) - ...
                    peakWavenumber(index - 1));
                secondDelta = abs(peakLocation(2) - ...
                    peakWavenumber(index - 1));
                if secondDelta < maximumJump && secondDelta < firstDelta
                    peakWavenumber(index) = peakLocation(2);
                    peakMagnitude(index) = peakAmplitude(2);
                end
            end
        end
    end
    magnitudeThreshold = max(peakMagnitude, [], 'omitnan') * ...
        magnitudeFraction;
    ridge = peakWavenumber;
    ridge(peakMagnitude < magnitudeThreshold) = nan;
    missingMask = isnan(ridge);
    validMask = ~missingMask;
    interpolatedMask = false(size(missingMask));
    extrapolatedMask = false(size(missingMask));
    if any(missingMask)
        validIndices = find(validMask);
        if ~isempty(validIndices)
            interpolatedMask(missingMask) = ...
                find(missingMask) >= validIndices(1) & ...
                find(missingMask) <= validIndices(end);
            extrapolatedMask = missingMask & ~interpolatedMask;
        end
        extrapolation = conditional(interpolation.extrapolate, ...
            'extrap', NaN);
        ridge(missingMask) = interp1(frequency(validMask), ...
            ridge(validMask), frequency(missingMask), ...
            char(interpolation.method), extrapolation);
    end
end

function value = conditional(condition, trueValue, falseValue)
    if condition, value = trueValue; else, value = falseValue; end
end
