function test_pipeline_single_contract(context)
%TEST_PIPELINE_SINGLE_CONTRACT Verify fixed products and side-effect ownership.

    stages = ["reconstruction"; "borders"; "phase_estimation"; ...
        "filtering"; "dispersion_windows"; "dispersion_analysis"; ...
        "scientific_result"];
    for index = 1:numel(stages)
        resolved = oce.config.resolveRunOptions(struct( ...
            'stop_after', stages(index)));
        if resolved.stop_after ~= stages(index) || ...
                ~isequal(resolved.required_products, stages(1:index))
            error('OCE:PipelineTest:StopAfter', ...
                'Static product order is invalid for %s.', stages(index));
        end
    end
    assert_identifier('OCE:Pipeline:UnknownStopAfter', @() ...
        oce.config.resolveRunOptions(struct('stop_after', 'unknown')));
    assert_identifier('OCE:Pipeline:InvalidOutputOption', @() ...
        oce.config.resolveRunOptions(struct(), struct('unexpected', true)));
    assert_identifier('OCE:Pipeline:InvalidOutputOption', @() ...
        oce.config.resolveRunOptions(struct(), ...
            struct('save_dispersion_window_preview', true)));
    assert_identifier('OCE:Pipeline:MissingRequiredProduct', @() ...
        oce.config.resolveRunOptions( ...
            struct('stop_after', 'reconstruction'), ...
            struct('save_polar_plots', true)));
    assert_identifier('OCE:Pipeline:MissingRequiredProduct', @() ...
        oce.config.resolveRunOptions( ...
            struct('stop_after', 'filtering'), ...
            struct('save_dispersion_window_context', true)));
    assert_identifier('OCE:Pipeline:MissingRequiredProduct', @() ...
        oce.config.resolveRunOptions( ...
            struct('stop_after', 'dispersion_windows'), ...
            struct('save_kf_plots', true)));
    assert_identifier('OCE:Pipeline:MissingRequiredProduct', @() ...
        oce.config.resolveRunOptions( ...
            struct('stop_after', 'borders'), ...
            struct('save_filtered_motion_video', true)));
    assert_identifier('OCE:Pipeline:InvalidOutputCLimMode', @() ...
        oce.config.resolveRunOptions(struct(), ...
            struct('phase_clim_mode', "unknown")));
    assert_identifier('OCE:Pipeline:UnexpectedOutputCLim', @() ...
        oce.config.resolveRunOptions(struct(), struct('video_clim', 0.5)));
    assert_identifier('OCE:Pipeline:InvalidOutputCLim', @() ...
        oce.config.resolveRunOptions(struct(), ...
            struct('video_clim_mode', "manual", 'video_clim', -0.5)));
    assert_identifier('OCE:Pipeline:InvalidParallelOptions', @() ...
        oce.config.resolveRunOptions(struct('parallel', true)));
    assert_identifier('OCE:Pipeline:InvalidParallelOptions', @() ...
        oce.config.resolveRunOptions(struct('parallel', ...
            struct('enabled', 1))));
    assert_identifier('OCE:Pipeline:InvalidParallelOptions', @() ...
        oce.config.resolveRunOptions(struct('parallel', ...
            struct('worker_count', 0))));

    resolvedContext = oce.config.resolveRunOptions( ...
        struct('stop_after', 'dispersion_windows'), ...
        struct('save_dispersion_window_context', true));
    if ~resolvedContext.plotting.dispersion_window_context
        error('OCE:PipelineTest:OutputResolution', ...
            'Dispersion-window context output did not resolve.');
    end
    resolvedKf = oce.config.resolveRunOptions( ...
        struct('stop_after', 'dispersion_analysis'), ...
        struct('save_kf_plots', true));
    if ~resolvedKf.plotting.kf_plots
        error('OCE:PipelineTest:OutputResolution', ...
            'k-f plot output did not resolve.');
    end
    resolvedVideo = oce.config.resolveRunOptions( ...
        struct('stop_after', 'filtering'), ...
        struct('save_filtered_motion_video', true));
    defaults = resolvedVideo.output_options;
    if ~resolvedVideo.video.filtered_motion || ...
            defaults.phase_clim_mode ~= "robust" || ...
            ~isempty(defaults.phase_clim) || ...
            defaults.video_clim_mode ~= "robust" || ...
            ~isempty(defaults.video_clim)
        error('OCE:PipelineTest:OutputResolution', ...
            'Unified CLim output defaults did not resolve.');
    end
    if ~resolvedVideo.parallel.enabled || ...
            resolvedVideo.parallel.worker_count ~= 4 || ...
            resolvedVideo.parallel.pool_type ~= "processes" || ...
            resolvedVideo.parallel.active
        error('OCE:PipelineTest:ParallelResolution', ...
            'Default parallel execution options did not resolve.');
    end
    resolvedSerial = oce.config.resolveRunOptions(struct('parallel', ...
        struct('enabled', false, 'worker_count', 2)));
    if resolvedSerial.parallel.enabled || ...
            resolvedSerial.parallel.worker_count ~= 2 || ...
            resolvedSerial.parallel.active
        error('OCE:PipelineTest:ParallelResolution', ...
            'Explicit serial execution options did not resolve.');
    end
    resolvedManual = oce.config.resolveRunOptions( ...
        struct('stop_after', 'filtering'), ...
        struct('save_filtered_motion_video', true, ...
            'phase_clim_mode', "manual", 'phase_clim', 0.25, ...
            'video_clim_mode', "manual", 'video_clim', 0.5));
    if resolvedManual.output_options.phase_clim_mode ~= "manual" || ...
            resolvedManual.output_options.phase_clim ~= 0.25 || ...
            resolvedManual.output_options.video_clim_mode ~= "manual" || ...
            resolvedManual.output_options.video_clim ~= 0.5
        error('OCE:PipelineTest:CLimResolution', ...
            'Manual phase/video CLim policy did not resolve.');
    end
    expectedResolvedFields = ["stop_after"; "required_products"; ...
        "return_intermediate_products"; "parallel"; "plotting"; "video"; ...
        "persistence"; "output_options"; "requires_output_directory"];
    if ~isequal(string(fieldnames(resolvedVideo)), expectedResolvedFields)
        error('OCE:PipelineTest:OutputResolution', ...
            'Resolved run fields changed unexpectedly.');
    end

    fixture = create_pipeline_fixture();
    intendedResults = fullfile(fixture.io.root, 'Results', ...
        fixture.io.subExperiment);
    if isfolder(intendedResults)
        rmdir(intendedResults, 's');
    end
    transcript = evalc(['runOutput = oce.pipeline.runSingleAcquisition(' ...
        'fixture.io.root, fixture.io.subExperiment, "R004", ' ...
        '"Key", "run_id", "RunOptions", ' ...
        'struct("stop_after", "reconstruction"));']);
    result = runOutput.pipeline_result;
    if result.status.completed_through ~= "reconstruction" || ...
            ~isequal(result.status.available_products, "reconstruction") || ...
            result.status.scientific_result_available || ...
            result.status.persisted || ...
            ~isempty(result.status.generated_artifacts) || ...
            ~isfield(result.products, 'reconstruction') || ...
            numel(fieldnames(result.products)) ~= 1 || ...
            isfolder(intendedResults)
        error('OCE:PipelineTest:PartialRun', ...
            'In-memory reconstruction run violated its product contract.');
    end
    if contains(transcript, 'OCE acquisition processing') || ...
            contains(transcript, 'Parallel execution:')
        error('OCE:PipelineTest:DomainTranscript', ...
            'Reconstruction-only execution emitted unexpected runtime output.');
    end

    calculation = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'processPreparedAcquisition.m'));
    entrypoint = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'runSingleAcquisition.m'));
    parallelOwner = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'prepareParallelExecution.m'));
    depthOwner = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+motion', 'computeDepthResolvedPhase.m'));
    surfaceOwner = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+motion', 'computeSurfacePhase.m'));
    dispersionOwner = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+dispersion', 'analyzeWindows.m'));
    outputRouter = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'private', 'generateRequestedOutputs.m'));
    experimentDriver = fileread(fullfile(context.repoRoot, 'workflows', ...
        'run_experiment_batch.m'));
    manualDriver = fileread(fullfile(context.repoRoot, 'workflows', ...
        'run_acquisition_stepwise.m'));
    videoOwner = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+video', 'createFilteredMotionVideo.m'));
    animationOwner = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', 'showDepthMotionAnimation.m'));
    forbiddenCalculation = ["mkdir("; "saveas("; ...
        "saveScientificResult"; "fprintf("; "warning("; "parpool("];
    for index = 1:numel(forbiddenCalculation)
        if contains(calculation, forbiddenCalculation(index))
            error('OCE:PipelineTest:CalculationSideEffect', ...
                'Calculation contains forbidden side effect: %s.', ...
                forbiddenCalculation(index));
        end
    end
    calls = ["oce.io.readRawAcquisition"; ...
        "oce.acquisition.buildAcquisitionState"; ...
        "oce.borders.detectAndMask"; ...
        "oce.motion.computeDepthResolvedPhase"; ...
        "oce.filtering.filterPhaseResults"; ...
        "oce.dispersion.buildWindows"; ...
        "oce.dispersion.analyzeWindows"; ...
        "oce.results.buildScientificResult"];
    positions = arrayfun(@(name) strfind(calculation, name), calls, ...
        'UniformOutput', false);
    if any(cellfun(@isempty, positions)) || ...
            any(diff(cellfun(@(value) value(1), positions)) <= 0)
        error('OCE:PipelineTest:ProductOrder', ...
            'The explicit scientific product order changed.');
    end
    parallelRouting = [ ...
        "'UseParallel', useParallel"; ...
        "resolvedRun.parallel.active"];
    if any(~contains(calculation, parallelRouting)) || ...
            ~contains(entrypoint, 'oce.pipeline.prepareParallelExecution') || ...
            ~contains(parallelOwner, 'parpool("Processes"') || ...
            ~contains(parallelOwner, "gcp('nocreate')") || ...
            ~contains(depthOwner, 'parfor lateralIndex') || ...
            ~contains(surfaceOwner, 'parfor lateralIndex') || ...
            ~contains(dispersionOwner, 'parfor directionIndex')
        error('OCE:PipelineTest:ParallelOwnership', ...
            'Parallel execution ownership or routing is incomplete.');
    end
    requiredOutputOwners = ["oce.plotting.saveDispersionWindowContext"; ...
        "oce.plotting.saveDispersionKfPreview"; ...
        "oce.plotting.saveSpeedDispersionPreview"; ...
        "oce.plotting.savePolarPhaseResults"; ...
        "oce.video.createFilteredMotionVideo"];
    if count(entrypoint, 'oce.io.saveScientificResult') ~= 1 || ...
            ~contains(entrypoint, 'generateRequestedOutputs') || ...
            any(~contains(outputRouter, requiredOutputOwners)) || ...
            contains(outputRouter, 'oce.io.saveScientificResult') || ...
            contains(entrypoint, 'RunDispersion')
        error('OCE:PipelineTest:PersistenceOwnership', ...
            'Single-run persistence/output ownership is invalid.');
    end
    requiredRouting = [ ...
        "'CLimMode', outputOptions.phase_clim_mode"; ...
        "'CLim', outputOptions.phase_clim"; ...
        "'CLimMode', outputOptions.video_clim_mode"; ...
        "'CLim', outputOptions.video_clim"];
    oldManualNames = ["phase_preview_clim"; "filter_preview_clim"; ...
        "complete_space_time_clim"; "filtered_motion_clim"];
    if any(~contains(outputRouter, requiredRouting)) || ...
            ~contains(experimentDriver, '''phase_clim_mode'', "robust"') || ...
            ~contains(experimentDriver, '''video_clim_mode'', "robust"') || ...
            ~contains(manualDriver, 'phase_clim_mode = "robust"') || ...
            ~contains(manualDriver, 'video_clim_mode = "robust"') || ...
            any(contains(manualDriver, oldManualNames)) || ...
            ~contains(videoOwner, 'oce.plotting.resolveMotionOverlayCLim') || ...
            ~contains(animationOwner, 'oce.plotting.resolveMotionOverlayCLim')
        error('OCE:PipelineTest:CLimOwnership', ...
            'Unified phase/video CLim configuration or routing is incomplete.');
    end
    clear fixture
end

function assert_identifier(expected, callback)
    try
        callback();
    catch ME
        if string(ME.identifier) == string(expected)
            return;
        end
        error('OCE:PipelineTest:WrongIdentifier', ...
            'Expected %s, actual %s.', expected, ME.identifier);
    end
    error('OCE:PipelineTest:MissingError', ...
        'Expected error %s was not raised.', expected);
end
