function test_pipeline_workflow_contract(context)
%TEST_PIPELINE_WORKFLOW_CONTRACT Verify human workflows call canonical APIs.

    files = ["process_single_acquisition.m"; "process_acquisition_batch.m"; ...
        "run_experiment_batch.m"; "summarize_subexperiment_results.m"; ...
        "summarize_experiment_results.m"; ...
        "run_acquisition_stepwise.m"; "run_raster_enface_stepwise.m"];
    calls = ["oce.pipeline.runSingleAcquisition"; ...
        "oce.pipeline.runBatchProcessing"; "oce.pipeline.runBatchProcessing"; ...
        "oce.pipeline.runSubexperimentSummary"; ...
        "oce.pipeline.runExperimentSummary"; ...
        "oce.acquisition.prepareSingleFileInputs"; ...
        "oce.video.createEnfaceMotionVideo"];
    for index = 1:numel(files)
        pathValue = fullfile(context.repoRoot, 'workflows', files(index));
        if ~isfile(pathValue)
            error('OCE:PipelineTest:WorkflowMissing', 'Missing %s.', pathValue);
        end
        source = fileread(pathValue);
        if ~contains(source, calls(index)) || contains(source, 'cd(') || ...
                contains(source, 'assignin(') || contains(source, 'evalin(')
            error('OCE:PipelineTest:Workflow', ...
                'Invalid workflow contract: %s.', pathValue);
        end
    end

    initializerPath = fullfile(context.repoRoot, 'workflows', 'private', ...
        'initialize_repository.m');
    if ~isfile(initializerPath)
        error('OCE:PipelineTest:WorkflowInitialization', ...
            'Shared workflow initialization helper is missing.');
    end

    % Callable workflow functions can resolve the workflows/private helper.
    callableIndices = [1 2];
    for index = callableIndices
        source = fileread(fullfile(context.repoRoot, 'workflows', files(index)));
        if count(source, 'initialize_repository();') ~= 1 || ...
                contains(source, 'function initialize_repository')
            error('OCE:PipelineTest:WorkflowInitialization', ...
                'Callable workflow initialization is invalid in %s.', files(index));
        end
    end

    % Section-oriented script drivers must initialize directly from the active
    % Editor file. Do not use mfilename('fullpath'): Run Section may resolve it
    % to MATLAB's temporary section-execution file instead of the real driver.
    driverIndices = [3 4 5 6];
    requiredDriverInitialization = [ ...
        "workflow_file = matlab.desktop.editor.getActiveFilename"; ...
        "startup_file = fullfile(repository_root, 'startup.m')"; ...
        "run(startup_file);"];
    for index = driverIndices
        source = fileread(fullfile(context.repoRoot, 'workflows', files(index)));
        if contains(source, 'initialize_repository();') || ...
                contains(source, "mfilename('fullpath')") || ...
                any(~contains(source, requiredDriverInitialization))
            error('OCE:PipelineTest:WorkflowInitialization', ...
                'Section-oriented driver initialization is invalid in %s.', ...
                files(index));
        end
    end

    initializerSource = fileread(initializerPath);
    if count(initializerSource, 'startup;') ~= 1 || ...
            ~contains(initializerSource, 'onCleanup') || ...
            ~contains(initializerSource, 'restore_path')
        error('OCE:PipelineTest:WorkflowInitialization', ...
            'Shared workflow initialization changed its maintained behavior.');
    end

    experimentPath = fullfile(context.repoRoot, 'workflows', ...
        'run_experiment_batch.m');
    experimentSource = fileread(experimentPath);
    required = ["oce.interaction.tuneBorderDetection"; ...
        "oce.motion.computeSurfacePhase"; ...
        "oce.filtering.filterSurfacePhase"; ...
        "oce.interaction.selectTemporalFilterPassband"; ...
        "oce.interaction.tuneDispersionWindows"; ...
        "oce.config.buildProcessingConfigForAcquisition"; ...
        "oce.config.saveProcessingConfig"; ...
        "oce.pipeline.runBatchProcessing"; ...
        "selection_source = ""acquisition_row"""; ...
        "require_one_text_value(rows, 'acquisition_mode')"; ...
        "require_one_text_value(rows, 'scan_geometry')"; ...
        "require_one_text_value(rows, 'oct_system_profile')"; ...
        "require_one_text_value(rows, 'excitation_type')"; ...
        "getOCTSystemOptions(oct_system_profile)"; ...
        "'AcquisitionMode', acquisition_mode"; ...
        "'ScanGeometry', scan_geometry"; ...
        "phantom_surface_mode = ""anterior_posterior"""; ...
        "previous_border_surface_mode"; ...
        "previous_window_excitation_type"; ...
        "processing_config.BorderOptions.methods.phantom.surface_mode"; ...
        "dispersion_center_method = ""max_mirrored_correlation"""; ...
        "dispersion_spatial_method"; "dispersion_temporal_method"; ...
        """to_end"""; ...
        "dispersion_time_hann_enabled = true"; ...
        "dispersion_space_hann_enabled = false"; ...
        "show_representative_kf_preview = true"; ...
        "show_representative_speed_preview = true"; ...
        "'save_filter_preview', true"; ...
        "'save_dispersion_window_context', true"; ...
        "'save_kf_plots', true"; ...
        "'save_filtered_motion_video', true"; ...
        "'phase_clim_mode', ""robust"""; ...
        "'phase_clim', []"; ...
        "'video_clim_mode', ""robust"""; ...
        "'video_clim', []"; ...
        "run_batches_after_preparation"; ...
        "%% 3. INTERACTIVE PREPARATION OF ALL SUB-EXPERIMENTS"; ...
        "%% 4. AUTOMATIC BATCH EXECUTION AFTER ALL CONFIGURATIONS ARE READY"];
    forbiddenPreparation = ["oce.motion.computeDepthResolvedPhase"; ...
        "oce.filtering.applySurfaceTemporalFilter"];
    forbiddenHardcodes = [ ...
        "oct_system_profile = ""spectral_domain_1040"""; ...
        "'AcquisitionMode', ""mb_mode"""; ...
        "'ScanGeometry', ""angular_bmodes"""];
    if any(~contains(experimentSource, required)) || ...
            contains(experimentSource, 'experiment_root = string(experiment_root);') || ...
            any(contains(experimentSource, forbiddenPreparation)) || ...
            any(contains(experimentSource, forbiddenHardcodes))
        error('OCE:PipelineTest:ExperimentPreparation', ...
            ['Experiment preparation must use canonical acquisition-row ' ...
             'taxonomy without workflow hardcoding.']);
    end

    subexperimentSummarySource = fileread(fullfile(context.repoRoot, ...
        'workflows', 'summarize_subexperiment_results.m'));
    requiredSubexperimentSummary = [ ...
        "subexperiments_to_summarize = ""all"""; ...
        "oce.io.loadExperimentalLog"; ...
        "available_subexperiments"; ...
        "for sub_index = 1:numel(subexperiments)"; ...
        "oce.pipeline.runSubexperimentSummary"; ...
        "summary_results"];
    if any(~contains(subexperimentSummarySource, requiredSubexperimentSummary))
        error('OCE:PipelineTest:SubexperimentSummarySelection', ...
            ['Sub-experiment summary workflow must support one, many, or all ' ...
             'sub-experiments through the experimental log.']);
    end

    manualSource = fileread(fullfile(context.repoRoot, 'workflows', ...
        'run_acquisition_stepwise.m'));
    manualRequired = ["phase_clim_mode = ""robust"""; ...
        "phase_clim = []"; "video_clim_mode = ""robust"""; ...
        "video_clim = []"; ...
        "phantom_surface_mode = ""anterior_posterior"""; ...
        "processing_config.BorderOptions.methods.phantom.surface_mode"; ...
        "'CLimMode', phase_clim_mode"; "'CLim', phase_clim"; ...
        "'CLimMode', video_clim_mode"; "'CLim', video_clim"];
    retiredManualCLim = ["phase_preview_clim"; "filter_preview_clim"; ...
        "complete_space_time_clim"; "filtered_motion_clim"];
    if any(~contains(manualSource, manualRequired)) || ...
            any(contains(manualSource, retiredManualCLim))
        error('OCE:PipelineTest:ManualCLimPolicy', ...
            ['Manual workflow must expose shared phase/video CLim policies ' ...
             'and the canonical phantom surface mode.']);
    end

    retiredWorkflows = ["migrate_acquisition_metadata.m"; ...
        "migrate_scientific_results.m"];
    for index = 1:numel(retiredWorkflows)
        pathValue = fullfile(context.repoRoot, 'workflows', retiredWorkflows(index));
        if isfile(pathValue)
            error('OCE:PipelineTest:RetiredWorkflow', ...
                'Retired migration workflow still exists: %s.', pathValue);
        end
    end

    saveLocations = strfind(experimentSource, ...
        'oce.config.saveProcessingConfig');
    tunerLocations = strfind(experimentSource, ...
        'oce.interaction.tuneDispersionWindows');
    batchLocations = strfind(experimentSource, ...
        'oce.pipeline.runBatchProcessing');
    preparationSection = strfind(experimentSource, ...
        '%% 3. INTERACTIVE PREPARATION OF ALL SUB-EXPERIMENTS');
    batchSection = strfind(experimentSource, ...
        '%% 4. AUTOMATIC BATCH EXECUTION AFTER ALL CONFIGURATIONS ARE READY');
    if numel(saveLocations) ~= 1 || isempty(tunerLocations) || ...
            numel(batchLocations) ~= 1 || isempty(preparationSection) || ...
            isempty(batchSection) || ...
            saveLocations(1) <= tunerLocations(1) || ...
            saveLocations(1) <= preparationSection(1) || ...
            batchSection(1) <= saveLocations(1) || ...
            batchLocations(1) <= batchSection(1)
        error('OCE:PipelineTest:ExperimentPersistence', ...
            ['All sub-experiments must be tuned and persisted before the ' ...
             'single automatic batch-execution phase begins.']);
    end

    actual = sort(reshape(string({dir(fullfile( ...
        context.repoRoot, 'workflows', '*.m')).name}), [], 1));
    if ~isequal(sort(files), actual)
        error('OCE:PipelineTest:WorkflowFiles', ...
            'Maintained workflow inventory changed. Expected=%s; actual=%s.', ...
            strjoin(sort(files), ', '), strjoin(actual, ', '));
    end
end
