function test_manual_single_file_workflow_contract(context)
%TEST_MANUAL_SINGLE_FILE_WORKFLOW_CONTRACT Verify manual/batch convergence.

    fixture = create_io_acquisition_fixture();
    parameterData = load(fullfile(fixture.paramsDir, ...
        'Params_synthetic_subexperiment.mat'), 'acquisition_parameters');
    processingConfig = oce.config.getDefaultProcessingConfig("in_vivo_eye");
    metadata = canonical_manual_metadata();

    standaloneRoot = tempname;
    mkdir(standaloneRoot);
    standaloneCleanup = onCleanup(@() remove_tree(standaloneRoot));
    standaloneFile = fullfile(standaloneRoot, 'standalone.bin');
    copyfile(fullfile(fixture.dataDir, 'synthetic_a.bin'), standaloneFile);

    inputs = oce.acquisition.prepareSingleFileInputs( ...
        standaloneFile, parameterData.acquisition_parameters, metadata, ...
        processingConfig);
    assert_standalone_preparation(inputs, standaloneFile, standaloneRoot);

    config = oce.config.buildProcessingConfigForAcquisition(inputs);
    if config.AcquisitionOptions.acquisition_mode ~= "mb_mode" || ...
            config.AcquisitionOptions.scan_geometry ~= "angular_bmodes" || ...
            config.BorderOptions.method ~= "in_vivo_corneal" || ...
            config.resolved_crop.depth.sample_count ~= 3 || ...
            config.DispersionAnalysisOptions.target_frequency.source ~= ...
                "resolved_filter_center"
        error('OCE:ManualWorkflowTest:Configuration', ...
            'Manual metadata did not resolve through the shared config API.');
    end

    pulseMetadata = metadata;
    pulseMetadata.excitation_type = "pulse";
    pulseMetadata.frequency_Hz = NaN;
    pulseInputs = oce.acquisition.prepareSingleFileInputs( ...
        standaloneFile, parameterData.acquisition_parameters, pulseMetadata, ...
        processingConfig);
    pulseConfig = oce.config.buildProcessingConfigForAcquisition(pulseInputs);
    if ~isnan(pulseInputs.acquisition_row.frequency_Hz) || ...
            pulseConfig.DispersionAnalysisOptions.target_frequency.source ~= ...
                "not_available"
        error('OCE:ManualWorkflowTest:PulseConfiguration', ...
            'Pulse metadata must preserve unavailable physical target frequency.');
    end

    resolvedRun = oce.config.resolveRunOptions( ...
        struct('stop_after', "reconstruction"));
    result = oce.pipeline.processPreparedAcquisition(inputs, config, resolvedRun);
    if result.status.completed_through ~= "reconstruction" || ...
            ~isfield(result, 'acquisition_state') || ...
            ~isfield(result.products, 'reconstruction') || ...
            isfield(result.products.reconstruction.geometry, ...
                'bmode_lateral_axis_mm')
        error('OCE:ManualWorkflowTest:Products', ...
            'Standalone inputs did not produce maintained reconstruction products.');
    end

    % frequency_Hz = [] reads the CH2 frequency of the GUI generator header.
    headerMetadata = metadata;
    headerMetadata.frequency_Hz = [];
    headerInputs = oce.acquisition.prepareSingleFileInputs( ...
        fullfile(fixture.rawDir, fixture.octoceFilename), ...
        parameterData.acquisition_parameters, headerMetadata, ...
        processingConfig);
    if headerInputs.acquisition_row.frequency_Hz ~= ...
            fixture.generatorFrequencyHz
        error('OCE:ManualWorkflowTest:HeaderFrequency', ...
            'frequency_Hz = [] must use the generator header frequency.');
    end
    assert_identifier('OCE:Acquisition:MissingExcitationFrequency', @() ...
        oce.acquisition.prepareSingleFileInputs( ...
            standaloneFile, parameterData.acquisition_parameters, ...
            headerMetadata, processingConfig));

    legacyMetadata = metadata;
    legacyMetadata.acquisition_protocol = "angular_bmodes";
    assert_identifier('OCE:Acquisition:LegacySingleFileMetadata', @() ...
        oce.acquisition.prepareSingleFileInputs( ...
            standaloneFile, parameterData.acquisition_parameters, ...
            legacyMetadata, processingConfig));

    legacyStudyMetadata = metadata;
    legacyStudyMetadata = rmfield(legacyStudyMetadata, 'excitation_type');
    legacyStudyMetadata.study_type = "quasi_harmonic";
    assert_identifier('OCE:Acquisition:LegacySingleFileMetadata', @() ...
        oce.acquisition.prepareSingleFileInputs( ...
            standaloneFile, parameterData.acquisition_parameters, ...
            legacyStudyMetadata, processingConfig));

    assert_batch_manual_parity(fixture);
    assert_no_batch_dependency(context.repoRoot);
    assert_driver_contract(context.repoRoot);
    clear standaloneCleanup fixture
end

function metadata = canonical_manual_metadata()
    metadata = struct( ...
        'sample_type', "in_vivo_eye", ...
        'excitation_type', "quasi_harmonic", ...
        'frequency_Hz', 1200, ...
        'experiment_type', "manual_single", ...
        'acquisition_mode', "mb_mode", ...
        'scan_geometry', "angular_bmodes", ...
        'oct_system_profile', "swept_source_1300");
end

function assert_standalone_preparation(inputs, standaloneFile, standaloneRoot)
    rowNames = string(inputs.acquisition_row.Properties.VariableNames);
    if isfile(fullfile(standaloneRoot, 'experimental_log.xlsx')) || ...
            string(inputs.filename) ~= "standalone.bin" || ...
            ~strcmp(inputs.fullfile, standaloneFile) || ...
            height(inputs.acquisition_row) ~= 1 || ...
            string(inputs.acquisition_row.filename) ~= "standalone.bin" || ...
            string(inputs.acquisition_row.run_id) ~= "standalone" || ...
            string(inputs.acquisition_row.excitation_type) ~= "quasi_harmonic" || ...
            string(inputs.acquisition_row.acquisition_mode) ~= "mb_mode" || ...
            string(inputs.acquisition_row.scan_geometry) ~= ...
                "angular_bmodes" || ...
            string(inputs.acquisition_row.oct_system_profile) ~= ...
                "swept_source_1300" || ...
            any(ismember(["acquisition_protocol", "scan_type", ...
                "study_type"], rowNames)) || ...
            ~isempty(inputs.processingConfigFile) || ...
            ~isempty(inputs.paramsInfo.paramsFile) || ...
            isfolder(inputs.resultsDir)
        error('OCE:ManualWorkflowTest:Preparation', ...
            'Standalone preparation violated its canonical in-memory contract.');
    end
end

function assert_batch_manual_parity(fixture)
    oce.io.loadExperimentalLog( ...
        fixture.logPath, 'SaveAcquisitionParams', true);
    batchInputs = oce.acquisition.prepareProcessingInputs( ...
        fixture.root, fixture.subExperiment, "R004", ...
        'Key', 'run_id', 'RequireProcessingConfig', true);
    manualInputs = oce.acquisition.prepareSingleFileInputs( ...
        batchInputs.fullfile, batchInputs.acquisition_parameters, ...
        table2struct(batchInputs.acquisition_row), ...
        batchInputs.processing_config);
    batchConfig = oce.config.buildProcessingConfigForAcquisition(batchInputs);
    manualConfig = oce.config.buildProcessingConfigForAcquisition(manualInputs);
    batchConfig = rmfield(batchConfig, 'metadata');
    manualConfig = rmfield(manualConfig, 'metadata');
    if ~isequaln(batchConfig, manualConfig)
        error('OCE:ManualWorkflowTest:Parity', ...
            ['Equivalent batch and manual metadata/configuration did not ' ...
             'resolve to equivalent effective configuration.']);
    end
end

function assert_no_batch_dependency(repoRoot)
    source = fileread(fullfile(repoRoot, 'src', '+oce', ...
        '+acquisition', 'prepareSingleFileInputs.m'));
    forbidden = ["oce.io.loadExperimentalLog"; ...
        "oce.io.loadSubexperimentParameters"; "AcquisitionParams_"];
    if any(contains(source, forbidden))
        error('OCE:ManualWorkflowTest:BatchDependency', ...
            'Standalone preparation depends on a batch-only artifact.');
    end
end

function assert_driver_contract(repoRoot)
    pathValue = fullfile(repoRoot, 'workflows', ...
        'run_acquisition_stepwise.m');
    source = fileread(pathValue);
    sections = ["%% 0. INITIALIZATION"; "%% 1. ACQUISITION SELECTION"; ...
        "%% 2. ACQUISITION PARAMETER PREPARATION"; ...
        "%% 3. PROCESSING CONFIGURATION"; "%% 4. RECONSTRUCTION"; ...
        "%% 5. BORDER DETECTION"; "%% 6. PHASE ESTIMATION"; ...
        "%% 6A. OPTIONAL RAW DEPTH-MOTION ANIMATION"; ...
        "%% 7. TEMPORAL FILTERING"; ...
        "%% 7A. OPTIONAL COMPLETE SPACE-TIME"; ...
        "%% 7B. OPTIONAL FILTERED MOTION VIDEO"; ...
        "%% 8. DISPERSION WINDOWS"; "%% 9. DISPERSION ANALYSIS"; ...
        "%% 10. SCIENTIFIC RESULT"; "%% 11. OPTIONAL PERSISTENCE"];
    calls = ["oce.acquisition.prepareSingleFileInputs"; ...
        "oce.acquisition.buildAcquisitionState"; ...
        "oce.borders.detectAndMask"; ...
        "oce.motion.computeDepthResolvedPhase"; ...
        "oce.filtering.filterPhaseResults"; ...
        "oce.dispersion.buildWindows"; ...
        "oce.dispersion.analyzeWindows"; ...
        "oce.results.buildScientificResult"];

    positions = locate_tokens(source, sections, ...
        'OCE:ManualWorkflowTest:Driver');
    locate_tokens(source, calls, 'OCE:ManualWorkflowTest:Driver');
    if contains(source, 'oce.pipeline.processPreparedAcquisition')
        error('OCE:ManualWorkflowTest:Driver', ...
            'Manual driver must expose scientific products explicitly.');
    end

    assert_acquisition_sections(source, positions);
    assert_scientific_sections(source, positions);
    assert_optional_sections(source, positions);
    assert_progress_contract(source);
end

function positions = locate_tokens(source, tokens, identifier)
    locations = arrayfun(@(token) strfind(source, token), tokens, ...
        'UniformOutput', false);
    if any(cellfun(@isempty, locations))
        error(identifier, 'Required manual workflow token is missing.');
    end
    positions = cellfun(@(item) item(1), locations);
    if numel(tokens) > 1 && any(diff(positions) <= 0)
        error(identifier, 'Manual workflow sequence is not maintained.');
    end
end

function assert_acquisition_sections(source, positions)
    preparation = section_text(source, positions, 3);
    requiredPreparation = [ ...
        "oct_system_profile ="; ...
        "oce.config.getOCTSystemOptions(oct_system_profile)"; ...
        "acquisition_mode = ""mb_mode"""; ...
        "scan_geometry = ""automatic"""; ...
        "[acquisition_parameters, ~, measurement]"; ...
        "oce.acquisition.prepareAcquisitionParameters"; ...
        "'AcquisitionMode', acquisition_mode"; ...
        "'ScanGeometry', scan_geometry"; ...
        "'OCTSystemOptions', oct_system_options"];
    if any(~contains(preparation, requiredPreparation))
        error('OCE:ManualWorkflowTest:AcquisitionPreparation', ...
            'Section 2 does not own complete standalone acquisition intent.');
    end

    configuration = section_text(source, positions, 4);
    downstream = ["processing_config.BorderOptions"; ...
        "processing_config.MotionOptions"; "processing_config.FilterOptions"; ...
        "processing_config.DispersionWindowOptions"; ...
        "processing_config.DispersionAnalysisOptions"];
    requiredConfiguration = ["sample_type ="; "excitation_type ="; ...
        "frequency_Hz ="; "acquisition_metadata = struct"; ...
        "processing_inputs.acquisition_row.run_id"];
    if any(contains(configuration, downstream)) || ...
            any(~contains(configuration, requiredConfiguration))
        error('OCE:ManualWorkflowTest:HumanConfiguration', ...
            'Section 3 duplicates or misplaces scientific configuration.');
    end

    reconstruction = section_text(source, positions, 5);
    if contains(reconstruction, 'oce.io.readRawAcquisition') || ...
            ~contains(reconstruction, 'oce.acquisition.buildAcquisitionState') || ...
            ~contains(reconstruction, 'measurement, config_for_run') || ...
            contains(reconstruction, ...
                'config_for_run.AcquisitionOptions.scan_geometry')
        error('OCE:ManualWorkflowTest:RawGeometryBoundary', ...
            ['Manual reconstruction must reuse the prepared raw measurement; ' ...
             'geometry is interpreted by buildAcquisitionState.']);
    end
end

function assert_scientific_sections(source, positions)
    border = section_text(source, positions, 6);
    if ~contains(border, 'border_selection = "automatic"') || ...
            ~contains(border, 'border_tuning = "interactive"') || ...
            ~contains(border, 'oce.interaction.tuneBorderDetection')
        error('OCE:ManualWorkflowTest:BorderConfiguration', ...
            'Border section does not preserve maintained tuning.');
    end

    motion = section_text(source, positions, 7);
    filtering = section_text(source, positions, 9);
    windows = section_text(source, positions, 12);
    analysis = section_text(source, positions, 13);
    required = { ...
        motion, ["processing_config.MotionOptions"; ...
            "oce.config.resolvePhaseEstimationOptions"]; ...
        filtering, ["processing_config.FilterOptions.enabled"; ...
            "oce.filtering.filterPhaseResults"]; ...
        windows, ["processing_config.DispersionWindowOptions"; ...
            "oce.config.resolveDispersionWindowOptions"; ...
            "acquisition_state.geometry.bmode_lateral_axis_mm"]; ...
        analysis, ["processing_config.DispersionAnalysisOptions"; ...
            "oce.config.resolveDispersionAnalysisOptions"; ...
            "oce.plotting.plotDispersionKfPreview"; ...
            "oce.plotting.plotSpeedDispersionPreview"]};
    for index = 1:size(required, 1)
        if any(~contains(required{index, 1}, required{index, 2}))
            error('OCE:ManualWorkflowTest:ScientificSection', ...
                'A scientific section does not own its maintained intent.');
        end
    end
    if contains(analysis, 'fft2(')
        error('OCE:ManualWorkflowTest:AnalysisDiagnostics', ...
            'Dispersion diagnostics must reuse the maintained analysis result.');
    end
end

function assert_optional_sections(source, positions)
    rawAnimation = section_text(source, positions, 8);
    if ~contains(rawAnimation, 'show_raw_depth_motion_animation = false') || ...
            ~contains(rawAnimation, 'oce.plotting.showDepthMotionAnimation') || ...
            contains(rawAnimation, 'oce.motion.compute')
        error('OCE:ManualWorkflowTest:RawAnimation', ...
            'Raw depth-motion preview must reuse phase results.');
    end

    completeSpaceTime = section_text(source, positions, 10);
    if ~contains(completeSpaceTime, 'oce.plotting.plotCompleteSpaceTime') || ...
            ~contains(completeSpaceTime, 'exist(''filter_result'', ''var'')')
        error('OCE:ManualWorkflowTest:CompleteSpaceTime', ...
            'Complete space-time must support filtered and phase-only input.');
    end

    video = section_text(source, positions, 11);
    % Either default is allowed; the video must stay behind its own flag.
    if isempty(regexp(video, 'generate_filtered_motion_video = (true|false);', 'once')) || ...
            ~contains(video, 'if generate_filtered_motion_video') || ...
            ~contains(video, 'oce.video.createFilteredMotionVideo')
        error('OCE:ManualWorkflowTest:Video', ...
            'Filtered video must remain an independent opt-in output.');
    end

    persistence = section_text(source, positions, 15);
    requiredPersistence = [ ...
        "manual_output.save_kf_preview = false"; ...
        "oce.plotting.saveDispersionKfPreview"; ...
        "'BmodeMode', ""representative"""];
    if any(~contains(persistence, requiredPersistence))
        error('OCE:ManualWorkflowTest:Persistence', ...
            ['Manual persistence must save k-f diagnostics explicitly and ' ...
             'keep the filter space-time preview representative.']);
    end
end

function assert_progress_contract(source)
    % Informational summaries (acquisition header, generator) may be printed;
    % progress reporting itself (bars, rewritten lines, percentages) may not.
    printed = regexp(source, 'fprintf\([^\n]*', 'match');
    progressLike = contains(source, 'waitbar(') || ...
        any(contains(printed, ["\r", "%%"]));
    if progressLike || ...
            ~contains(source, 'manual_show_progress = true') || ...
            ~contains(source, '''ShowProgress'', manual_show_progress')
        error('OCE:ManualWorkflowTest:ProgressOwnership', ...
            'Manual execution progress must be controlled by maintained owners.');
    end
end

function text = section_text(source, positions, index)
    if index < numel(positions)
        text = extractBetween(source, positions(index), positions(index + 1) - 1);
    else
        text = extractAfter(source, positions(index) - 1);
    end
end

function assert_identifier(expected, action)
    try
        action();
        actual = "<no error>";
    catch ME
        actual = string(ME.identifier);
    end
    if actual ~= string(expected)
        error('OCE:ManualWorkflowTest:ErrorIdentifier', ...
            'Expected identifier=%s; actual=%s.', expected, actual);
    end
end

function remove_tree(folder)
    if isfolder(folder)
        rmdir(folder, 's');
    end
end
