function test_plotting_individual_contract(~)
%TEST_PLOTTING_INDIVIDUAL_CONTRACT Validate individual and preview artifacts.

    fixture = create_plotting_fixture(tempname);
    oldVisibility = get(groot, 'defaultFigureVisible');
    cleanup = onCleanup(@() cleanup_test(fixture.rootDir, oldVisibility));
    set(groot, 'defaultFigureVisible', 'off');

    before = findall(groot, 'Type', 'figure');
    scientificResult = oce.io.loadScientificResult( ...
        fullfile(fixture.phaseDir, 'PhaseSpeed.mat'));
    [polarFigures, renderResult] = oce.plotting.plotPolarPhaseResults( ...
        scientificResult, 'UseTemplate', false);
    created = setdiff(findall(groot, 'Type', 'figure'), before);
    if numel(created) ~= 2 || numel(polarFigures) ~= 2
        error('OCE:PlottingTest:MissingFigure', ...
            'Polar rendering must create thickness and phase-speed figures.');
    end
    renderFiles = dir(fullfile(fixture.phaseDir, 'Polar*.*'));
    if ~isempty(renderFiles)
        error('OCE:PlottingTest:RendererPersistence', ...
            'plotPolarPhaseResults must not persist files.');
    end
    expectedRenderFields = {'mean_thickness_um'; 'std_thickness_um'; ...
        'range_thickness_um'; 'mean_phase_speed_m_per_s'; ...
        'std_phase_speed_m_per_s'; 'range_phase_speed_m_per_s'; ...
        'central_frequency_hz'};
    if ~isequal(fieldnames(renderResult), expectedRenderFields)
        error('OCE:PlottingTest:RenderResultFields', ...
            'Polar renderer result fields changed.');
    end
    close(created);

    [artifacts, result] = oce.plotting.savePolarPhaseResults( ...
        scientificResult, fixture.phaseDir, ...
        'UseTemplate', false, 'CloseFigures', false);
    actualFields = fieldnames(result);
    expectedResultFields = {'generated_artifacts'; ...
        'mean_thickness_um'; 'std_thickness_um'; 'range_thickness_um'; ...
        'mean_phase_speed_m_per_s'; 'std_phase_speed_m_per_s'; ...
        'range_phase_speed_m_per_s'; 'central_frequency_hz'};
    if ~isequal(actualFields, expectedResultFields) || ...
            ~isequal(string(artifacts(:)), string(result.generated_artifacts(:)))
        error('OCE:PlottingTest:ResultFields', ...
            'Polar persistence result contract changed.');
    end
    individualListing = dir(fullfile(fixture.phaseDir, 'Polar*.*'));
    files = sort(reshape(string({individualListing.name}), [], 1));
    expectedIndividualFiles = sort([ ...
        "PolarPhaseSpeed.fig"; "PolarPhaseSpeed.png"; ...
        "PolarThickness.fig"; "PolarThickness.png"]);
    if ~isequal(files, expectedIndividualFiles)
        error('OCE:PlottingTest:IndividualFiles', ...
            'Individual plotting artifact inventory changed.');
    end
    if any([individualListing.bytes] <= 0)
        error('OCE:PlottingTest:EmptyFile', ...
            'An individual plotting artifact is empty.');
    end
    close(setdiff(findall(groot, 'Type', 'figure'), before));

    out = fullfile(fixture.rootDir, 'previews'); mkdir(out);
    reconstruction = make_reconstruction_result( ...
        fixture.Bmode, fixture.Xaxis, fixture.Zaxis, ...
        fixture.filterResult.time_axis_s);
    borderResult = struct('intensityMask', fixture.Mask, ...
        'indices', fixture.indices, ...
        'anteriorSurface', fixture.anteriorSurface, ...
        'posteriorSurface', fixture.posteriorSurface);
    previewGeometry = struct( ...
        'bmode_count', 2, ...
        'samples_per_bmode', 4, ...
        'bmode_scan_width_mm', 0.5);
    filterResult = fixture.filterResult;
    filterResult.surface_postprocessed.units = "rad";

    borderFigure = figure('Visible', 'off');
    maskFigure = figure('Visible', 'off');
    graphics = oce.plotting.plotBorderPreview(axes(borderFigure), ...
        axes(maskFigure), reconstruction, borderResult, ...
        fixture.bmode_intensity_limits_db);
    if ~isequal(graphics.anteriorLine.YData(:), ...
            fixture.anteriorSurface(:, 2)) || ...
            ~isequal(graphics.posteriorLine.YData(:), ...
                fixture.posteriorSurface(:, 2))
        error('OCE:PlottingTest:BorderCurves', ...
            'Common border preview does not show anterior and posterior curves.');
    end
    expectedMaskPreview = reconstruction.log_amplitude.values .* fixture.Mask;
    if ~isequal(graphics.maskImage.CData, expectedMaskPreview)
        error('OCE:PlottingTest:MaskPreview', ...
            'Common mask preview does not apply intensityMask.');
    end
    close([borderFigure maskFigure]);
    reconstructionBefore = reconstruction;
    reconstructionFigure = oce.plotting.plotReconstructionPreview( ...
        reconstruction, fixture.bmode_intensity_limits_db);
    reconstructionImage = findobj(reconstructionFigure, 'Type', 'Image');
    if numel(reconstructionImage) ~= 1 || ...
            ~isequal(reconstructionImage.CData, ...
                reconstruction.log_amplitude.values) || ...
            ~isequaln(reconstruction, reconstructionBefore)
        error('OCE:PlottingTest:ReconstructionDisplayIdentity', ...
            ['Final reconstruction preview must display the maintained ' ...
             'reconstruction result without altering it.']);
    end
    close(reconstructionFigure);
    oce.plotting.saveReconstructionPreview(reconstruction, ...
        fixture.bmode_intensity_limits_db, out);
    oce.plotting.saveBorderPreview(reconstruction, borderResult, ...
        fixture.OCT_system, fixture.bmode_intensity_limits_db, out);
    phaseResult = struct('surface', fixture.inputSurfacePhase);
    [filterFigures, filterDetails] = oce.plotting.plotFilterPreviews( ...
        phaseResult, filterResult, reconstruction, previewGeometry);
    if filterDetails.profile_alignment.delay_samples ~= ...
            filterResult.design.delay_samples || ...
            filterDetails.space_time.delay_samples ~= ...
                filterResult.design.delay_samples || ...
            ~isequal(filterDetails.space_time.source_time_indices, ...
                filterResult.design.delay_samples + 1: ...
                numel(filterResult.time_axis_s))
        error('OCE:PlottingTest:VisualDelayCompensation', ...
            'FIR profile and space-time visual delay alignment changed.');
    end
    close(filterFigures);
    oce.plotting.saveFilterPreviews(phaseResult, ...
        filterResult, reconstruction, previewGeometry, out);
    [completeFigure, completeDetails] = oce.plotting.plotCompleteSpaceTime( ...
        phaseResult, filterResult, reconstruction, previewGeometry);
    if completeDetails.source ~= "filtered" || ...
            completeDetails.preview.selection.mode ~= "all" || ...
            completeDetails.preview.delay_samples ~= ...
                filterResult.design.delay_samples
        error('OCE:PlottingTest:FilteredCompleteSpaceTime', ...
            'Complete space-time did not select the applied filtered source.');
    end
    close(completeFigure);
    disabledFilter = filterResult;
    disabledFilter.applied = false;
    disabledFilter.design.applied = false;
    [completeFigure, completeDetails] = oce.plotting.plotCompleteSpaceTime( ...
        phaseResult, disabledFilter, reconstruction, previewGeometry);
    if completeDetails.source ~= "phase" || ...
            completeDetails.preview.delay_samples ~= 0
        error('OCE:PlottingTest:UnfilteredCompleteSpaceTime', ...
            'Disabled filtering must fall back to unfiltered phase data.');
    end
    close(completeFigure);
    oce.plotting.saveCompleteSpaceTime(phaseResult, [], ...
        reconstruction, previewGeometry, out);
    assert_filter_passthrough_preview(fixture, previewGeometry);
    analysisFixture = create_dispersion_analysis_fixture();
    analysis = oce.dispersion.analyzeWindows( ...
        analysisFixture.window_result, analysisFixture.DistBorder, ...
        analysisFixture.DispersionAnalysisOptions);
    assert_dispersion_diagnostics(analysis, context_repo_root());
    oce.plotting.saveSpeedDispersionPreview(analysis, 1, out);
    details = dir(out); details = details(~[details.isdir]);
    previewFiles = sort(reshape(string({details.name}), [], 1));
    expectedPreviewFiles = sort([ ...
        "ReconstructionPreview.fig"; "ReconstructionPreview.png"; ...
        "BorderPreview_pixels.fig"; "BorderPreview_pixels.png"; ...
        "BorderMaskPreview.fig"; "BorderMaskPreview.png"; ...
        "TemporalFilterSpectrum.fig"; "TemporalFilterSpectrum.png"; ...
        "TemporalFilterTimeProfile.fig"; "TemporalFilterTimeProfile.png"; ...
        "FilteredSpaceTime.fig"; "FilteredSpaceTime.png"; ...
        "CompleteSpaceTime.fig"; "CompleteSpaceTime.png"; ...
        "SpeedDispersion_scanAxis01_0.0deg.fig"; ...
        "SpeedDispersion_scanAxis01_0.0deg.png"]);
    if ~isequal(previewFiles, expectedPreviewFiles)
        error('OCE:PlottingTest:PreviewFiles', ...
            'Preview artifact inventory changed.');
    end
    if any([details.bytes] <= 0)
        error('OCE:PlottingTest:EmptyFile', 'A preview output is empty.');
    end
    assert_enface_motion(fixture.rootDir);

    beforeClose = findall(groot, 'Type', 'figure');
    marker = figure('Visible', 'off');
    oce.plotting.closeGeneratedFigures(beforeClose, true);
    if isvalid(marker)
        error('OCE:PlottingTest:Lifecycle', ...
            'Generated figure was not closed.');
    end
    clear cleanup
end

function assert_dispersion_diagnostics(analysis, repoRoot)
    windowFixture = create_dispersion_windows_fixture();
    config = windowFixture.cases.maxRmsPhaseIncrement;
    windowResult = oce.dispersion.buildWindows(config, ...
        windowFixture.filter_result, windowFixture.x_axis_mm, ...
        windowFixture.resolved_filter, windowFixture.geometry);
    windowBefore = windowResult;
    filterBefore = windowFixture.filter_result;
    [contextFigure, contextDetails] = ...
        oce.plotting.plotDispersionWindowContext(windowResult, ...
            windowFixture.filter_result, windowFixture.x_axis_mm, 1);
    expectedRange = windowResult.bmodes(1).global_lateral_range(1): ...
        windowResult.bmodes(1).global_lateral_range(2);
    delay = windowFixture.filter_result.design.delay_samples;
    expectedMap = windowFixture.filter_result.surface_postprocessed.values( ...
        expectedRange, delay + 1:end);
    left = windowResult.bmodes(1).left;
    expectedLeftTime = left.time_axis_s(1) * 1e3;
    leftLabelText = join(string(contextDetails.left_label.String(:)), " ");
    rightLabelText = join(string(contextDetails.right_label.String(:)), " ");
    if ~isequaln(contextDetails.center_metadata, ...
            windowResult.bmodes(1).center) || ...
            ~isequaln(contextDetails.image.CData, expectedMap') || ...
            string(contextDetails.axes.YDir) ~= "reverse" || ...
            contextDetails.center_line.Value ~= ...
                windowResult.bmodes(1).center.x_coordinate_mm || ...
            ~isequal(contextDetails.left_rectangle.EdgeColor, [1 1 1]) || ...
            ~isequal(contextDetails.right_rectangle.EdgeColor, [1 1 1]) || ...
            string(contextDetails.left_rectangle.LineStyle) ~= ":" || ...
            string(contextDetails.right_rectangle.LineStyle) ~= ":" || ...
            ~isequal(contextDetails.center_line.Color, [1 1 1]) || ...
            contextDetails.visual_delay_samples ~= delay || ...
            contextDetails.left_rectangle.Position(2) ~= expectedLeftTime || ...
            ~contains(leftLabelText, "x: 1:10") || ...
            ~contains(leftLabelText, "t: 10:60") || ...
            ~contains(rightLabelText, "x: 12:21") || ...
            ~contains(rightLabelText, "t: 10:60") || ...
            isfield(contextDetails, 'information_box') || ...
            ~isequaln(windowResult, windowBefore) || ...
            ~isequaln(windowFixture.filter_result, filterBefore)
        error('OCE:PlottingTest:DispersionWindowContext', ...
            ['Window context must apply display-only FIR alignment and use ' ...
             'clean metadata-derived ROI overlays without recomputation.']);
    end
    close(contextFigure);

    unfiltered = windowFixture.filter_result;
    unfiltered.applied = false;
    unfiltered.design.applied = false;
    [unfilteredFigure, unfilteredDetails] = ...
        oce.plotting.plotDispersionWindowContext(windowResult, unfiltered, ...
            windowFixture.x_axis_mm, 1);
    expectedUnfiltered = unfiltered.surface_postprocessed.values( ...
        expectedRange, :);
    if unfilteredDetails.visual_delay_samples ~= 0 || ...
            ~isequaln(unfilteredDetails.image.CData, expectedUnfiltered')
        error('OCE:PlottingTest:DispersionWindowContextPassthrough', ...
            'An unapplied filter must not invent visual delay compensation.');
    end
    close(unfilteredFigure);

    analysisBefore = analysis;
    [kfFigure, kfDetails] = oce.plotting.plotDispersionKfPreview(analysis, 1);
    if kfDetails.source ~= "analysis.directions.spectrum_and_ridge" || ...
            ~isequal(kfDetails.ridge_lines(1).YData(:), ...
                analysis.directions(1).ridge.wavenumber_per_m(:)) || ...
            ~isequaln(analysis, analysisBefore)
        error('OCE:PlottingTest:DispersionKfReuse', ...
            'k-f preview must reuse preserved spectrum and ridge outputs.');
    end
    close(kfFigure);

    assert(isempty(oce.plotting.plotPhaseGradientPreview(analysis, 1)));
    gradient = struct('status', "valid", 'phase_speed_m_per_s', 2, ...
        'r_squared', 0.98, 'phase_rmse_rad', 0.02, ...
        'diagnostic', struct('x_axis_mm', [-1; 0; 1], ...
            'unwrapped_phase_rad', [0; 0.1; 0.3], 'fitted_phase_rad', [-0.02; 0.14; 0.28]));
    analysis.phase_gradient.enabled = true;
    analysis.phase_gradient.target_frequency_hz = 1000;
    analysis.phase_gradient.directions = [gradient; gradient];
    analysis.phase_gradient.directions(2).status = "nonfinite_signal";
    analysis.phase_gradient.directions(2).phase_speed_m_per_s = NaN;
    analysis.phase_gradient.directions(2).r_squared = NaN;
    analysis.phase_gradient.directions(2).phase_rmse_rad = NaN;
    analysis.phase_gradient.directions(2).diagnostic.unwrapped_phase_rad = [];
    analysis.phase_gradient.directions(2).diagnostic.fitted_phase_rad = [];
    analysisBefore = analysis;
    [gradientFigure, graphics] = oce.plotting.plotPhaseGradientPreview(analysis, 1);
    assert(isequal(graphics.phase_lines(1).XData(:), gradient.diagnostic.x_axis_mm));
    assert(isequal(graphics.phase_lines(1).YData(:), gradient.diagnostic.unwrapped_phase_rad));
    assert(isequal(graphics.fit_lines(1).YData(:), gradient.diagnostic.fitted_phase_rad));
    assert(~isgraphics(graphics.phase_lines(2)) && ...
        contains(join(string(graphics.axes(2).Title.String)), "nonfinite_signal"));
    assert(isequaln(analysis, analysisBefore));
    close(gradientFigure);
    kfSource = fileread(fullfile(repoRoot, 'src', '+oce', '+plotting', ...
        'plotDispersionKfPreview.m'));
    if contains(kfSource, 'fft2(') || ...
            contains(kfSource, 'computeDispersionSpectrum')
        error('OCE:PlottingTest:DispersionKfRecomputation', ...
            'k-f plotting must not recompute the scientific spectrum.');
    end

    yLimitAnalysis = analysis;
    yLimitAnalysis.directions(1).phase_speed_curve. ...
        smoothed_phase_speed_m_per_s(1) = Inf;
    yLimitAnalysis.directions(1).phase_speed_curve. ...
        smoothed_phase_speed_m_per_s(2) = NaN;
    yLimitAnalysis.directions(1).phase_speed_curve. ...
        smoothed_phase_speed_m_per_s(3) = 1e6;
    yLimitAnalysis.directions(1).target_selection. ...
        selected_phase_speed_m_per_s = 18;
    yLimit = oce.plotting.resolveSpeedPreviewYLimit(yLimitAnalysis, 1);
    if yLimit(1) ~= 0 || yLimit(2) < 20 || yLimit(2) < 1.1 * 18 || ...
            yLimit(2) >= 1e5
        error('OCE:PlottingTest:SpeedPreviewYLimit', ...
            ['Speed preview limit must include the target, retain the ' ...
             '20 m/s floor, and resist non-finite/localized outliers.']);
    end
end

function repoRoot = context_repo_root()
    testFolder = fileparts(mfilename('fullpath'));
    repoRoot = fileparts(fileparts(testFolder));
end

function assert_filter_passthrough_preview(fixture, previewGeometry)
    disabledRoot = fullfile(fixture.rootDir, 'disabled_filter_preview');
    mkdir(disabledRoot);
    disabled = fixture.filterResult;
    disabled.applied = false;
    disabled.design.applied = false;
    disabled.design.coefficients = [];
    disabled.design.delay_samples = 0;
    disabled.surface.values = fixture.inputSurfacePhase.values;
    disabled.surface_postprocessed.units = "rad";
    before = findall(groot, 'Type', 'figure');
    reconstruction = make_reconstruction_result( ...
        fixture.Bmode, fixture.Xaxis, fixture.Zaxis, ...
        fixture.filterResult.time_axis_s);
    phaseResult = struct('surface', fixture.inputSurfacePhase);
    oce.plotting.saveFilterPreviews( ...
        phaseResult, disabled, reconstruction, previewGeometry, disabledRoot);
    created = setdiff(findall(groot, 'Type', 'figure'), before);
    legends = findall(created, 'Type', 'Legend');
    labels = strings(0, 1);
    for index = 1:numel(legends)
        labels = [labels; string(legends(index).String(:))]; %#ok<AGROW>
    end
    if ~any(contains(lower(labels), "passthrough"))
        error('OCE:PlottingTest:MissingPassthroughLabel', ...
            'Disabled filtering preview must identify passthrough explicitly.');
    end
    close(created);
end

function assert_enface_motion(rootDir)
    % Raster storage: fast-axis A-lines within each B-scan, then B-scans.
    samplesPerBmode = 4;
    bmodeCount = 3;
    timeCount = 9;
    delaySamples = 2;
    [fastIndex, slowIndex] = ndgrid(1:samplesPerBmode, 1:bmodeCount);
    spatialCode = 10 * slowIndex(:) + fastIndex(:);
    surfaceValues = spatialCode .* sin(0.7 * (1:timeCount));
    geometry = struct( ...
        'samples_per_bmode', samplesPerBmode, ...
        'bmode_count', bmodeCount, ...
        'bmode_lateral_axis_mm', linspace(0, 3, samplesPerBmode), ...
        'raster', struct('slow_axis_mm', linspace(0, 2, bmodeCount)));
    filterResult = struct( ...
        'applied', true, ...
        'surface', struct('values', surfaceValues, ...
            'quantity', "phase_increment", 'units', "rad"), ...
        'design', struct('delay_samples', delaySamples), ...
        'invalid_rows', struct('mask', [true; false(11, 1)]));
    reconstruction = struct( ...
        'crop', struct('time', struct('start_index_inclusive', 5)), ...
        'geometry', struct('time_sample_interval_s', 2e-5));

    data = oce.plotting.prepareEnfaceMotionVisualization( ...
        filterResult, reconstruction, geometry, 'MedianWindow', []);
    retained = surfaceValues(:, delaySamples + 1:end);
    retained = retained - mean(retained, 2);
    expectedFrames = permute(reshape(retained, samplesPerBmode, ...
        bmodeCount, []), [2 1 3]);
    expectedFrames(1, 1, :) = NaN;
    expectedTimeS = (5 + (0:timeCount - delaySamples - 1) - 0.5) * 2e-5;
    if ~isequal(size(data.frames), [bmodeCount samplesPerBmode ...
                timeCount - delaySamples]) || ...
            max(abs(data.frames(2:end) - expectedFrames(2:end)), [], 'all') > 1e-12 || ...
            any(~isnan(data.frames(1, 1, :))) || data.valid_mask(1, 1) || ...
            ~isequal(data.x_axis_mm, linspace(0, 3, samplesPerBmode)) || ...
            ~isequal(data.y_axis_mm, linspace(0, 2, bmodeCount)) || ...
            max(abs(data.time_axis_s - expectedTimeS)) > 1e-15
        error('OCE:PlottingTest:EnfaceLayout', ...
            'En-face frames must map raster storage to y-by-x-by-time.');
    end

    before = findall(groot, 'Type', 'figure');
    oce.plotting.plotEnfaceMotionSnapshots( ...
        filterResult, reconstruction, geometry, 'SnapshotCount', 3);
    created = setdiff(findall(groot, 'Type', 'figure'), before);
    if numel(created) ~= 1 || numel(findall(created, 'Type', 'Axes')) ~= 3
        error('OCE:PlottingTest:EnfaceSnapshots', ...
            'En-face snapshots must render one figure with requested frames.');
    end
    close(created);

    videoDir = fullfile(rootDir, 'enface_video');
    videoPath = oce.video.createEnfaceMotionVideo( ...
        filterResult, reconstruction, geometry, ...
        struct('time_start_idx', 1, 'max_frames', 3, 'frame_rate', 10, ...
            'filename', "Enface.mp4"), ...
        videoDir, 'ShowProgress', false);
    videoInfo = dir(videoPath);
    if isempty(videoInfo) || videoInfo.bytes <= 0 || ...
            ~isempty(setdiff(findall(groot, 'Type', 'figure'), before))
        error('OCE:PlottingTest:EnfaceVideo', ...
            'En-face video must write one MP4 and close its figure.');
    end
    unfiltered = filterResult;
    unfiltered.applied = false;
    try
        oce.video.createEnfaceMotionVideo(unfiltered, reconstruction, ...
            geometry, struct('time_start_idx', 1, 'max_frames', 1, ...
                'frame_rate', 10, 'filename', "Unused.mp4"), videoDir);
        detected = false;
    catch ME
        detected = strcmp(ME.identifier, 'OCE:Video:FilteringRequired');
    end
    if ~detected
        error('OCE:PlottingTest:EnfaceVideoFilter', ...
            'En-face video must require an applied filter.');
    end

    assert_structural_enface(rootDir, geometry);
end

function assert_structural_enface(rootDir, geometry)
    lateralCount = geometry.samples_per_bmode * geometry.bmode_count;
    depthCount = 5;
    timeCount = 6;
    sampleCount = lateralCount * depthCount * timeCount;
    volume = reshape(complex(1 + mod((1:sampleCount) * 7, 13), ...
        cos(1:sampleCount)), lateralCount, depthCount, timeCount);
    reconstruction = struct( ...
        'complex_volume', struct('values', volume, ...
            'layout', "lateral_depth_time"), ...
        'crop', struct('time', struct('start_index_inclusive', 11)), ...
        'axes', struct('depth', struct('values', (0:depthCount - 1)' * 0.01)));

    enface = oce.acquisition.computeStructuralEnface(reconstruction, geometry, ...
        'AScanAverageCount', 3, 'FirstMRepetition', 12, ...
        'DepthRangeIndices', [2 4]);
    % Amplitude averaged over M-repetitions 12:14 (local 2:4), then depth 2:4.
    expected = mean(mean(abs(volume(:, 2:4, 2:4)), 3), 2);
    expected = reshape(expected, geometry.samples_per_bmode, ...
        geometry.bmode_count).';
    if ~isequal(size(enface.values), [geometry.bmode_count ...
                geometry.samples_per_bmode]) || ...
            max(abs(enface.values - expected), [], 'all') > 1e-12 || ...
            max(abs(enface.log_values - 20 * log10(expected)), [], 'all') > 1e-9 || ...
            enface.a_scan_average.count ~= 3 || ...
            enface.a_scan_average.first_m_repetition ~= 12 || ...
            enface.a_scan_average.last_m_repetition ~= 14 || ...
            ~isequal(enface.depth_average.crop_indices, [2 4]) || ...
            max(abs(enface.depth_average.range_mm - [0.01 0.03])) > 1e-12 || ...
            ~isequal(enface.y_axis_mm, geometry.raster.slow_axis_mm)
        error('OCE:PlottingTest:StructuralEnface', ...
            ['Structural en-face must average N A-scans, then depth, and ' ...
             'map raster storage to y-by-x.']);
    end
    try
        oce.acquisition.computeStructuralEnface(reconstruction, geometry, ...
            'AScanAverageCount', 6, 'FirstMRepetition', 12);
        detected = false;
    catch ME
        detected = strcmp(ME.identifier, 'OCE:Acquisition:InvalidEnfaceAveraging');
    end
    if ~detected
        error('OCE:PlottingTest:StructuralEnfaceRange', ...
            'A-scan averaging beyond the reconstructed repetitions must fail.');
    end

    before = findall(groot, 'Type', 'figure');
    artifacts = oce.plotting.saveStructuralEnface(enface, ...
        fullfile(rootDir, 'structural_enface'));
    created = setdiff(findall(groot, 'Type', 'figure'), before);
    if ~isequal(endsWith(artifacts, [".fig"; ".png"]), [true; true]) || ...
            ~all(arrayfun(@isfile, artifacts)) || numel(created) ~= 1
        error('OCE:PlottingTest:StructuralEnfaceExport', ...
            'Structural en-face must export one figure as FIG and PNG.');
    end
    close(created);
end

function cleanup_test(rootDir, oldVisibility)
    close all force; set(groot, 'defaultFigureVisible', oldVisibility);
    if isfolder(rootDir), rmdir(rootDir, 's'); end
end
