function resolution = manualIntervalCount(options, ~)
%MANUALINTERVALCOUNT Resolve an explicit spatial interval count.

    resolution = struct( ...
        'method', "manual_interval_count", ...
        'interval_count', options.manual_interval_count, ...
        'sample_count', options.manual_interval_count + 1, ...
        'requested_fraction', []);
end
