function test_io_acquisition_contract(~)
%TEST_IO_ACQUISITION_CONTRACT Validate maintained I/O and acquisition behavior.

    fixture = create_io_acquisition_fixture();
    root = fixture.root;
    subExperiment = fixture.subExperiment;

    acquisitionParamsPath = fullfile(fixture.paramsDir, ...
        'AcquisitionParams_synthetic_subexperiment.mat');
    [readOnlyTable, ~, readOnlyPaths] = oce.io.loadExperimentalLog(fixture.logPath);
    if isfile(acquisitionParamsPath) || ...
            ~isempty(fieldnames(readOnlyPaths)) || height(readOnlyTable) ~= 2
        error('OCE:IOTest:UnexpectedLogPersistence', ...
            'loadExperimentalLog must be read-only by default.');
    end

    [logTable, sheetTables, savedPaths] = oce.io.loadExperimentalLog( ...
        fixture.logPath, 'SaveAcquisitionParams', true);
    if height(logTable) ~= 2 || ~isfield(sheetTables, 'Experiment') || ...
            isempty(fieldnames(savedPaths)) || ~isfile(acquisitionParamsPath)
        error('OCE:IOTest:ExperimentalLog', ...
            'Experimental log loading or explicit persistence changed.');
    end
    missingColumns = setdiff(fixture.expectedColumns, ...
        string(logTable.Properties.VariableNames));
    if ~isempty(missingColumns)
        error('OCE:IOTest:ExperimentalLog', ...
            'Experimental log is missing columns: %s.', ...
            strjoin(missingColumns, ', '));
    end

    [acquisitionParameters, acquisitionTable, paramsInfo] = ...
        oce.io.loadSubexperimentParameters(root, subExperiment);
    if height(acquisitionTable) ~= 2 || isempty(paramsInfo)
        error('OCE:IOTest:SubexperimentParameters', ...
            'Subexperiment parameter loading is incomplete.');
    end
    assert_acquisition_parameter_schema(acquisitionParameters);

    inputs = oce.acquisition.prepareProcessingInputs( ...
        root, subExperiment, "R004", 'Key', 'run_id', ...
        'RequireProcessingConfig', true);
    assert_crop_resolution(inputs);
    if string(inputs.acquisition_row.run_id) ~= "R004" || ...
            ~isfield(inputs, 'processing_config') || ...
            ~isfield(inputs, 'acquisition_header')
        error('OCE:IOTest:ProcessingInputs', ...
            'Prepared processing inputs are incomplete.');
    end

    validFiles = oce.acquisition.validateAcquisitionFiles( ...
        root, subExperiment, acquisitionTable);
    runInfo = oce.pipeline.prepareAcquisitionRun( ...
        root, subExperiment, "R004", 'Key', 'run_id', 'ValidateFiles', true);
    if ~validFiles.isValid || ~runInfo.file_validation.isValid || ...
            isfield(runInfo, 'ready_for_processing')
        error('OCE:IOTest:SyntheticPipeline', ...
            'Synthetic preparation contract is invalid.');
    end

    create_empty_file(fullfile(fixture.dataDir, 'orphan.bin'));
    invalidFiles = oce.acquisition.validateAcquisitionFiles( ...
        root, subExperiment, acquisitionTable);
    if invalidFiles.isValid || ...
            ~ismember("orphan.bin", string(invalidFiles.notListedInLog))
        error('OCE:IOTest:FileValidation', ...
            'Orphan acquisition file was not detected.');
    end

    headerTranscript = evalc( ...
        'header = oce.io.readAcquisitionHeader(fixture.rawFilename, fixture.rawDir);');
    rawTranscript = evalc( ...
        ['measurement = oce.io.readRawAcquisition(fixture.rawFilename, ' ...
         'fixture.rawDir);']);
    if ~isempty(headerTranscript) || ~isempty(rawTranscript) || ...
            ~isequaln(header, measurement.raw_descriptor) || ...
            ~isequal(size(measurement.rawdata), [8 4 6])
        error('OCE:IOTest:RawReader', ...
            'Header/raw reader contract changed or emitted console output.');
    end
    if header.binary_format.family ~= "historical_full" || ...
            header.binary_format.source_layout ~= ...
                "spectral_time_local_lateral_bmode" || ...
            header.binary_format.samples_in_Aline_source ~= "header" || ...
            header.binary_format.trailing_payload_classification ~= "none"
        error('OCE:IOTest:HistoricalBinaryFormat', ...
            'Historical binary format provenance is invalid.');
    end
    trailingMeasurement = oce.io.readRawAcquisition( ...
        fixture.trailingRawFilename, fixture.rawDir);
    trailingFormat = trailingMeasurement.raw_descriptor.binary_format;
    if trailingFormat.trailing_payload_classification ~= ...
                "historical_declared_dimensions_boundary" || ...
            trailingFormat.trailing_payload_uint16_count ~= 1 || ...
            ~isequal(trailingMeasurement.rawdata, measurement.rawdata)
        error('OCE:IOTest:HistoricalReadBoundary', ...
            'Historical declared-dimension provenance is invalid.');
    end

    compactHeader = oce.io.readAcquisitionHeader( ...
        fixture.compactFilename, fixture.rawDir);
    compactMeasurement = oce.io.readRawAcquisition( ...
        fixture.compactFilename, fixture.rawDir);
    reported = compactHeader.binary_format.reported_dimensions;
    expectedFirstValues = [1; 801; 1601; 2401; 3201; 4001; 4801; 5601];
    if compactHeader.binary_format.family ~= "compact" || ...
            compactHeader.binary_format.source_layout ~= ...
                "spectral_time_local_lateral_bmode" || ...
            compactHeader.binary_format.samples_in_Aline_source ~= ...
                "payload_size" || ...
            reported.samples_in_Aline ~= 1 || ...
            reported.Bframes_in_3Dscan ~= 2 || ...
            reported.No_3Dscans ~= 4 || ...
            compactHeader.samples_in_Aline ~= 8 || ...
            compactHeader.Alines_in_Bframe ~= 100 || ...
            compactHeader.Bframes_in_3Dscan ~= 4 || ...
            compactHeader.No_3Dscans ~= 2 || ...
            ~isempty(compactHeader.pattern_control) || ...
            ~isequal(size(compactMeasurement.rawdata), [8 100 8]) || ...
            ~isequal(compactMeasurement.rawdata, ...
                fixture.compactExpectedRaw) || ...
            ~isequal(squeeze(compactMeasurement.rawdata(1, 1, :)), ...
                expectedFirstValues)
        error('OCE:IOTest:CompactRawReader', ...
            'Compact header or storage normalization is invalid.');
    end
    baseOptions = struct('acquisition_mode', "mb_mode", ...
        'scan_geometry_selection', "automatic", 'scan_geometry', "");
    acquisitionRow = table("mb_mode", "angular_bmodes", ...
        'VariableNames', {'acquisition_mode', 'scan_geometry'});
    compactOptions = oce.config.resolveAcquisitionOptions( ...
        baseOptions, acquisitionRow, compactHeader);
    compactGeometry = oce.acquisition.buildAcquisitionGeometry( ...
        compactMeasurement.raw_descriptor, compactOptions.scan_geometry);
    if compactOptions.scan_geometry ~= "angular_bmodes" || ...
            compactOptions.source_metadata.samples_in_aline ~= ...
                compactHeader.samples_in_Aline || ...
            compactGeometry.bmode_count ~= 2 || ...
            compactGeometry.samples_per_bmode ~= 4 || ...
            compactGeometry.lateral_sample_count ~= 8
        error('OCE:IOTest:CompactGeometryResolution', ...
            'Compact raw dimensions did not resolve with canonical metadata.');
    end

    octoceHeaderTranscript = evalc( ...
        ['octoceHeader = oce.io.readAcquisitionHeader(' ...
         'fixture.octoceFilename, fixture.rawDir);']);
    octoceRawTranscript = evalc( ...
        ['octoceMeasurement = oce.io.readRawAcquisition(' ...
         'fixture.octoceFilename, fixture.rawDir);']);
    octoceFormat = octoceHeader.binary_format;
    octoceReported = octoceFormat.reported_dimensions;
    expectedAxisOrder = ["bscan", "aline", "m_repetition", "pixel"];
    if ~isempty(octoceHeaderTranscript) || ~isempty(octoceRawTranscript) || ...
            ~isequaln(octoceHeader, octoceMeasurement.raw_descriptor) || ...
            octoceFormat.family ~= "octoce_raw_v1" || ...
            octoceFormat.source_layout ~= ...
                "spectral_time_local_lateral_bmode" || ...
            octoceFormat.payload_offset_bytes ~= 65536 || ...
            octoceFormat.json_header_offset_bytes ~= 64 || ...
            octoceFormat.json_header_length_bytes <= 0 || ...
            octoceFormat.payload_dtype ~= "<u2" || ...
            octoceFormat.format_version ~= "1.0" || ...
            ~isequal(octoceFormat.axis_order, expectedAxisOrder) || ...
            octoceFormat.storage_layout ~= ...
                "C-order, contiguous, no sync samples" || ...
            octoceFormat.samples_in_Aline_source ~= "header" || ...
            octoceFormat.trailing_payload_classification ~= "none" || ...
            octoceReported.samples_in_Aline ~= 8 || ...
            octoceReported.Alines_in_Bframe ~= 4 || ...
            octoceReported.Bframes_in_3Dscan ~= 3 || ...
            octoceReported.No_3Dscans ~= 2 || ...
            octoceHeader.samples_in_Aline ~= 8 || ...
            octoceHeader.Alines_in_Bframe ~= 4 || ...
            octoceHeader.Bframes_in_3Dscan ~= 3 || ...
            octoceHeader.No_3Dscans ~= 2 || ...
            octoceHeader.Hor_scan_length_mm ~= 2.5 || ...
            octoceHeader.Ver_scan_length_mm ~= 2.5 || ...
            string(octoceHeader.type) ~= "meridians" || ...
            string(octoceHeader.pattern_control) ~= "meridians" || ...
            ~isequal(octoceHeader.bscan_length_mm, [2.5 2.5]) || ...
            ~isequal(octoceHeader.raster_bidirectional, false) || ...
            ~isa(octoceMeasurement.rawdata, 'uint16') || ...
            ~isequal(size(octoceMeasurement.rawdata), [8 4 6]) || ...
            ~isequal(octoceMeasurement.rawdata, fixture.octoceExpectedRaw)
        error('OCE:IOTest:OctoceRawReader', ...
            'OCTOCE raw v1 header or storage normalization is invalid.');
    end
    octoceGeometry = oce.acquisition.buildAcquisitionGeometry( ...
        octoceMeasurement.raw_descriptor, "angular_bmodes");
    if octoceGeometry.bmode_count ~= 2 || ...
            octoceGeometry.samples_per_bmode ~= 3 || ...
            octoceGeometry.lateral_sample_count ~= 6 || ...
            ~isequal(octoceGeometry.bmode_lateral_axis_mm, ...
                linspace(0, 2.5, 3))
        error('OCE:IOTest:OctoceGeometryResolution', ...
            'OCTOCE raw dimensions did not converge on canonical geometry.');
    end
    % OCTOCE planner lengths: linear/raster lines follow x (horizontal);
    % meridians of an x/y ellipse have unequal lengths and are rejected.
    linearDescriptor = octoceMeasurement.raw_descriptor;
    linearDescriptor.Hor_scan_length_mm = 6;
    linearDescriptor.Ver_scan_length_mm = 3;
    linearDescriptor.bscan_length_mm = [6 6];
    linearGeometry = oce.acquisition.buildAcquisitionGeometry( ...
        linearDescriptor, "angular_bmodes");
    ellipticalDescriptor = linearDescriptor;
    ellipticalDescriptor.bscan_length_mm = [6 3];
    assert_identifier('OCE:Acquisition:UnsupportedScanGeometry', @() ...
        oce.acquisition.buildAcquisitionGeometry( ...
            ellipticalDescriptor, "angular_bmodes"));
    rasterDescriptor = linearDescriptor;
    rasterGeometry = oce.acquisition.buildAcquisitionGeometry( ...
        rasterDescriptor, "raster");
    singleLineDescriptor = rasterDescriptor;
    singleLineDescriptor.No_3Dscans = 1;
    singleLineDescriptor.bscan_length_mm = 6;
    singleLineGeometry = oce.acquisition.buildAcquisitionGeometry( ...
        singleLineDescriptor, "raster");
    if linearGeometry.bmode_scan_width_mm ~= 6 || ...
            ~isequal(linearGeometry.bmode_lateral_axis_mm, linspace(0, 6, 3)) || ...
            rasterGeometry.bmode_count ~= 2 || ...
            rasterGeometry.samples_per_bmode ~= 3 || ...
            rasterGeometry.lateral_sample_count ~= 6 || ...
            rasterGeometry.bmode_scan_width_mm ~= 6 || ...
            ~isequal(rasterGeometry.bmode_lateral_axis_mm, linspace(0, 6, 3)) || ...
            ~isequal(rasterGeometry.raster.slow_axis_mm, linspace(0, 3, 2)) || ...
            ~isequal(singleLineGeometry.raster.slow_axis_mm, 0)
        error('OCE:IOTest:RasterGeometryResolution', ...
            'OCTOCE B-scan lengths did not resolve the physical lateral axes.');
    end
    bidirectionalDescriptor = rasterDescriptor;
    bidirectionalDescriptor.raster_bidirectional = true;
    assert_identifier('OCE:Acquisition:UnsupportedScanGeometry', @() ...
        oce.acquisition.buildAcquisitionGeometry( ...
            bidirectionalDescriptor, "raster"));

    assert_identifier('OCE:IO:InvalidAcquisitionHeader', @() ...
        oce.io.readAcquisitionHeader('missing.bin', fixture.rawDir));
    assert_identifier('OCE:IO:IncompleteAcquisition', @() ...
        oce.io.readRawAcquisition(fixture.truncatedRawFilename, fixture.rawDir));
    assert_identifier('OCE:IO:InvalidAcquisitionHeader', @() ...
        oce.io.readAcquisitionHeader( ...
            fixture.compactTrailingByteFilename, fixture.rawDir));
    assert_identifier('OCE:IO:InvalidAcquisitionHeader', @() ...
        oce.io.readAcquisitionHeader( ...
            fixture.compactNonIntegerFilename, fixture.rawDir));
    assert_identifier('OCE:IO:InvalidAcquisitionHeader', @() ...
        oce.io.readAcquisitionHeader( ...
            fixture.compactMissingFieldFilename, fixture.rawDir));
    assert_identifier('OCE:IO:InvalidAcquisitionHeader', @() ...
        oce.io.readAcquisitionHeader( ...
            fixture.unknownHeaderFilename, fixture.rawDir));
    assert_identifier('OCE:Acquisition:InvalidRawDescriptor', @() ...
        oce.acquisition.buildAcquisitionGeometry(header, "raster"));
    assert_identifier('OCE:Acquisition:UnsupportedScanGeometry', @() ...
        oce.acquisition.buildAcquisitionGeometry(header, "spiral"));
    assert_identifier('OCE:Acquisition:MissingScanGeometry', @() ...
        oce.acquisition.buildAcquisitionGeometry(header, ""));

    state = oce.acquisition.buildAcquisitionState( ...
        measurement, runInfo.config_for_run);
    expectedX = 1:6;
    expectedLocalX = linspace(0, 2.5, 3);
    expectedZ = (0:2)' * 7.1 * 1e-3 / 1.4;
    reconstruction = state.reconstruction;
    if state.geometry.bmode_count ~= 2 || ...
            state.geometry.samples_per_bmode ~= 3 || ...
            state.geometry.lateral_sample_count ~= 6 || ...
            ~isequal(reconstruction.axes.lateral.values, expectedX) || ...
            ~isequal(state.geometry.bmode_lateral_axis_mm, expectedLocalX) || ...
            ~isequal(reconstruction.axes.depth.values, expectedZ) || ...
            ~isequal(size(reconstruction.amplitude.values), [3 6]) || ...
            ~isequal(size(reconstruction.complex_volume.values), [6 3 4]) || ...
            isfield(reconstruction.geometry, 'bmode_count') || ...
            isfield(reconstruction.geometry, 'bmode_lateral_axis_mm')
        error('OCE:IOTest:AcquisitionState', ...
            'Acquisition/reconstruction geometry ownership changed.');
    end

    complexOutput = oce.acquisition.reconstructComplexVolume( ...
        fixture.complexMeasurement, fixture.OCT_system, ...
        fixture.sample_optics, fixture.geometry, fixture.resolved_crop);
    integerOutput = oce.acquisition.reconstructComplexVolume( ...
        fixture.integerMeasurement, fixture.OCT_system, ...
        fixture.sample_optics, fixture.geometry, fixture.resolved_crop);
    if ~isequal(size(integerOutput.complex_volume.values), ...
            size(complexOutput.complex_volume.values)) || ...
            ~all(isfinite(real(integerOutput.complex_volume.values)), 'all') || ...
            ~all(isfinite(imag(integerOutput.complex_volume.values)), 'all')
        error('OCE:IOTest:IntegerReconstruction', ...
            'Integer raw input reconstruction is invalid.');
    end
    assert_reconstruction_contract(complexOutput, 1:3, expectedZ);

    invalidLayout = complexOutput;
    invalidLayout.complex_volume.layout = "depth_lateral_time";
    assert_identifier('OCE:Reconstruction:InvalidResult', @() ...
        oce.results.validateReconstructionResult(invalidLayout));
    invalidAxes = complexOutput;
    invalidAxes.axes.depth.values(2) = invalidAxes.axes.depth.values(1);
    assert_identifier('OCE:Reconstruction:InvalidAxes', @() ...
        oce.results.validateReconstructionResult(invalidAxes));

    paramsContract = mat_contract(fullfile(fixture.paramsDir, ...
        'Params_synthetic_subexperiment.mat'));
    if ~isequal(paramsContract.variableNames, "acquisition_parameters") || ...
            ~isequal(paramsContract.variableClasses, "struct") || ...
            ~isequal(paramsContract.variableSizes, [1 1])
        error('OCE:IOTest:PersistedCropContract', ...
            'Params file does not contain only acquisition_parameters.');
    end
    configContract = mat_contract(fullfile(fixture.paramsDir, ...
        'ProcessingConfig_synthetic_subexperiment.mat'));
    if ~isequal(configContract.variableNames, "processing_config") || ...
            ~isequal(configContract.variableClasses, "struct")
        error('OCE:IOTest:PersistedConfigContract', ...
            'ProcessingConfig MAT contract changed.');
    end
    clear fixture
end

function assert_acquisition_parameter_schema(parameters)
    required = ["schema_version"; "acquisition_mode"; "scan_geometry"; ...
        "source"; "crop"; ...
        "preview_display"];
    if ~isequal(string(fieldnames(parameters)), required) || ...
            parameters.schema_version ~= 4 || ...
            parameters.acquisition_mode ~= "mb_mode" || ...
            parameters.scan_geometry ~= "angular_bmodes"
        error('OCE:IOTest:ParameterSchema', ...
            'Canonical acquisition_parameters schema is invalid.');
    end
    forbidden = ["NumLateralPos"; "NumMrept"; "DepthSize"; ...
        "NewDepthSize"; "NewTimeSize"; "Bmode"; "Jump_Lat_pos"];
    if any(isfield(parameters, forbidden))
        error('OCE:IOTest:ParameterSchema', ...
            'Canonical acquisition_parameters contains retired fields.');
    end
end

function assert_crop_resolution(inputs)
    parameters = inputs.acquisition_parameters;
    header = inputs.acquisition_header;
    crop = oce.acquisition.resolveCropOptions( ...
        parameters, header, "mb_mode", "angular_bmodes");
    if crop.depth.start_index_inclusive ~= 2 || ...
            crop.depth.end_index_inclusive ~= 4 || ...
            crop.depth.sample_count ~= 3 || ...
            crop.time.start_index_inclusive ~= 1 || ...
            crop.time.end_index_inclusive ~= 4 || ...
            crop.time.sample_count ~= 4 || ...
            crop.selection_source ~= "acquisition_parameters"
        error('OCE:IOTest:ResolvedCrop', 'Resolved crop values are invalid.');
    end

    invalid = parameters;
    invalid.schema_version = 3;
    assert_identifier('OCE:Acquisition:InvalidParameterSchema', @() ...
        oce.acquisition.resolveCropOptions(invalid, header, ...
            "mb_mode", "angular_bmodes"));
    assert_identifier('OCE:Acquisition:ScanGeometryMismatch', @() ...
        oce.acquisition.resolveCropOptions(parameters, header, ...
            "mb_mode", "spiral"));
    invalid = parameters;
    invalid.crop.depth.end_index_inclusive = 5;
    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        oce.acquisition.resolveCropOptions(invalid, header, ...
            "mb_mode", "angular_bmodes"));
    invalid = parameters;
    invalid.crop.time.end_index_inclusive = 5;
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        oce.acquisition.resolveCropOptions(invalid, header, ...
            "mb_mode", "angular_bmodes"));
end

function assert_reconstruction_contract(result, expectedX, expectedZ)
    oce.results.validateReconstructionResult(result);
    if result.complex_volume.quantity ~= "complex_oct_amplitude" || ...
            result.complex_volume.units ~= "arbitrary_complex_amplitude" || ...
            result.complex_volume.layout ~= "lateral_depth_time" || ...
            result.amplitude.quantity ~= "mean_temporal_oct_amplitude" || ...
            result.amplitude.units ~= "arbitrary_amplitude" || ...
            result.amplitude.layout ~= "depth_lateral" || ...
            result.log_amplitude.quantity ~= "log_oct_amplitude" || ...
            result.log_amplitude.units ~= "dB_relative" || ...
            result.log_amplitude.layout ~= "depth_lateral" || ...
            ~isequal(result.axes.lateral.values, expectedX) || ...
            ~isequal(result.axes.depth.values, expectedZ) || ...
            result.axes.time.units ~= "s" || ...
            result.provenance.window_function ~= "Hann" || ...
            isfield(result.geometry, 'bmode_count') || ...
            isfield(result.geometry, 'bmode_lateral_axis_mm')
        error('OCE:IOTest:ReconstructionContract', ...
            'Structured reconstruction metadata is invalid.');
    end
end

function contract = mat_contract(pathValue)
    info = whos('-file', pathValue);
    contract = struct( ...
        'variableNames', string({info.name})', ...
        'variableClasses', string({info.class})', ...
        'variableSizes', vertcat(info.size));
end

function create_empty_file(pathValue)
    fid = fopen(pathValue, 'w');
    if fid < 0
        error('OCE:IOTest:Fixture', 'Could not create %s.', pathValue);
    end
    fclose(fid);
end

function assert_identifier(expected, callback)
    try
        callback();
    catch ME
        if string(ME.identifier) == string(expected)
            return;
        end
        error('OCE:IOTest:WrongIdentifier', ...
            'Expected %s, actual %s.', expected, ME.identifier);
    end
    error('OCE:IOTest:MissingError', ...
        'Expected error %s was not raised.', expected);
end