function test_oct_system_reconstruction_contract(~)
%TEST_OCT_SYSTEM_RECONSTRUCTION_CONTRACT Verify system-aware OCT preparation.

    assert_historical_uniform_k_parity();
    assert_wavelength_resampling_recovers_peak();
    assert_sample_derived_global_median_matches_reference();
    assert_time_axis_and_filter_sampling();
    assert_physical_coordinate_contract();
    assert_phase_independent_of_depth_calibration();
end

function assert_phase_independent_of_depth_calibration()
    raw = 1500 + 250*cos((0:2047)'*0.17 + (0:8)*0.31);
    measurement = struct('rawdata', raw);
    motion = oce.config.resolvePhaseEstimationOptions( ...
        oce.config.getDefaultProcessingConfig("phantom").MotionOptions);
    for profile = ["swept_source_1300", "spectral_domain_1040", "spectral_domain_1310"]
        [system, optics, geometry, crop] = contracts(profile, 2048, 9, 1);
        original = oce.acquisition.reconstructComplexVolume( ...
            measurement, system, optics, geometry, crop);
        system.depth_sampling_calibration.interval_um = ...
            system.depth_sampling_calibration.interval_um * 1.1;
        optics.refractive_index.value = 1.7;
        changed = oce.acquisition.reconstructComplexVolume( ...
            measurement, system, optics, geometry, crop);
        assert(original.geometry.depth_sample_interval_mm ~= ...
            changed.geometry.depth_sample_interval_mm);
        assert(isequal(original.complex_volume, changed.complex_volume));
        assert(isequaln(oce.motion.computeDepthResolvedPhase( ...
            original.complex_volume.values, motion), ...
            oce.motion.computeDepthResolvedPhase(changed.complex_volume.values, motion)));
        assert(isequaln(oce.motion.computeSurfacePhase( ...
            original.complex_volume.values, 100, motion), ...
            oce.motion.computeSurfacePhase(changed.complex_volume.values, 100, motion)));
    end
end

function assert_physical_coordinate_contract()
    sampleCount = 16;
    repeatCount = 2;
    samplesPerBmode = 150;
    bmodeCount = 4;
    lateralCount = samplesPerBmode * bmodeCount;
    measurement = struct('rawdata', zeros( ...
        sampleCount, repeatCount, lateralCount));
    rawDescriptor = struct( ...
        'samples_in_Aline', sampleCount, ...
        'Alines_in_Bframe', repeatCount, ...
        'Bframes_in_3Dscan', samplesPerBmode, ...
        'No_3Dscans', bmodeCount, ...
        'Ver_scan_length_mm', 10);
    geometry = oce.acquisition.buildAcquisitionGeometry( ...
        rawDescriptor, "angular_bmodes");
    crop = struct( ...
        'depth', struct('start_index_inclusive', 1, ...
            'end_index_inclusive', 2, 'sample_count', 2), ...
        'time', struct('start_index_inclusive', 1, ...
            'end_index_inclusive', repeatCount, ...
            'sample_count', repeatCount));
    sampleOptics = oce.config.resolveSampleOpticalOptions( ...
        oce.config.getDefaultProcessingConfig( ...
            "in_vivo_eye").SampleOpticalOptions);
    profiles = ["swept_source_1300", "spectral_domain_1040"];
    expectedDz = [7.1, 3.57] * 1e-3 / 1.4;
    expectedLocalAxis = linspace(0, 10, samplesPerBmode);
    if ~isequal(geometry.bmode_lateral_axis_mm, expectedLocalAxis) || ...
            geometry.lateral_sample_interval_mm ~= 10 / 149
        error('OCE:OCTSystemTest:AcquisitionCoordinates', ...
            'Canonical angular-B-mode acquisition geometry is invalid.');
    end
    for index = 1:numel(profiles)
        octSystem = oce.config.resolveOCTSystemOptions( ...
            oce.config.getOCTSystemOptions(profiles(index)));
        result = oce.acquisition.reconstructComplexVolume( ...
            measurement, octSystem, sampleOptics, geometry, crop);
        if ~isequal(result.axes.lateral.values, 1:lateralCount) || ...
                isfield(result.geometry, 'bmode_lateral_axis_mm') || ...
                isfield(result.geometry, 'lateral_sample_interval_mm') || ...
                result.geometry.depth_sample_interval_mm ~= ...
                    expectedDz(index) || ...
                result.provenance.refractive_index ~= 1.4
            error('OCE:OCTSystemTest:PhysicalCoordinates', ...
                'Reconstruction coordinate ownership or calibration is invalid.');
        end
    end
end

function assert_historical_uniform_k_parity()
    sampleCount = 128;
    repeatCount = 9;
    lateralCount = 2;
    peakBin = 17;
    spectralIndex = (0:sampleCount - 1)';
    phase = reshape(linspace(0, pi / 2, repeatCount), 1, []);
    oneLateral = 1800 + 250 * cos( ...
        2 * pi * peakBin * spectralIndex / sampleCount + phase);
    raw = repmat(oneLateral, 1, 1, lateralCount);
    measurement = struct('rawdata', raw);
    [octSystem, sampleOptics, geometry, crop] = contracts( ...
        "swept_source_1300", sampleCount, repeatCount, lateralCount);

    result = oce.acquisition.reconstructComplexVolume( ...
        measurement, octSystem, sampleOptics, geometry, crop);
    expected = fft(hann(sampleCount) .* double(raw(:, :, 1)), [], 1);
    actual = squeeze(result.complex_volume.values(1, :, :));
    if ~isequaln(actual, expected(1:(sampleCount / 2), :))
        error('OCE:OCTSystemTest:HistoricalParity', ...
            'Swept-source reconstruction is not exactly the historical FFT.');
    end
    if result.provenance.oct_system_profile ~= ...
            "swept_source_1300" || ...
            result.provenance.background_method ~= "none" || ...
            result.provenance.spectral_resampling_method ~= "none"
        error('OCE:OCTSystemTest:HistoricalProvenance', ...
            'Swept-source reconstruction provenance is invalid.');
    end
end

function assert_wavelength_resampling_recovers_peak()
    sampleCount = 256;
    repeatCount = 21;
    lateralCount = 3;
    peakBin = 29;
    sd = oce.config.resolveOCTSystemOptions( ...
        oce.config.getOCTSystemOptions("spectral_domain_1040"));
    lambdaNm = linspace(sd.spectral_sampling.lambda_start_nm, ...
        sd.spectral_sampling.lambda_end_nm, sampleCount)';
    sigmaCm = 1e7 ./ lambdaNm;
    q = (sigmaCm - sigmaCm(1)) ./ ...
        (sigmaCm(end) - sigmaCm(1)) * (sampleCount - 1);
    temporalPhase = 2 * pi * (0:repeatCount - 1) / repeatCount;
    lateralPhase = reshape([0, 0.31, 0.67], 1, 1, []);
    raw = 2000 + 300 * cos( ...
        2 * pi * peakBin * q / sampleCount + ...
        reshape(temporalPhase, 1, [], 1) + lateralPhase);
    measurement = struct('rawdata', raw);

    [sdSystem, sampleOptics, geometry, crop] = contracts( ...
        "spectral_domain_1040", sampleCount, repeatCount, lateralCount);
    sdResult = oce.acquisition.reconstructComplexVolume( ...
        measurement, sdSystem, sampleOptics, geometry, crop);
    [ssSystem, ~, ~, ~] = contracts( ...
        "swept_source_1300", sampleCount, repeatCount, lateralCount);
    directResult = oce.acquisition.reconstructComplexVolume( ...
        measurement, ssSystem, sampleOptics, geometry, crop);

    sdProfile = mean(abs(sdResult.complex_volume.values), [1 3]);
    directProfile = mean(abs(directResult.complex_volume.values), [1 3]);
    search = 5:floor(sampleCount / 2);
    [~, sdRelative] = max(sdProfile(search));
    [~, directRelative] = max(directProfile(search));
    sdPeak = search(sdRelative);
    directPeak = search(directRelative);
    sdWidth = half_amplitude_width(sdProfile, sdPeak);
    directWidth = half_amplitude_width(directProfile, directPeak);
    expectedPeak = peakBin + 1;
    if abs(sdPeak - expectedPeak) > 1 || sdWidth >= directWidth
        error('OCE:OCTSystemTest:PeakRecovery', ...
            ['SD resampling did not recover the expected peak. ' ...
             'Expected=%d SD=%d/%d bins Direct=%d/%d bins.'], ...
            expectedPeak, sdPeak, sdWidth, directPeak, directWidth);
    end

    observed = squeeze(angle(sdResult.complex_volume.values(:, sdPeak, :)));
    expectedPhase = lateralPhase(:) + temporalPhase;
    phaseResidual = exp(1i * (observed - expectedPhase));
    if abs(mean(phaseResidual, 'all')) < 0.99
        error('OCE:OCTSystemTest:PhaseOrdering', ...
            'SD preparation changed temporal or lateral sample ordering.');
    end
    if sdResult.provenance.background_method ~= ...
            "sample_derived_global_median" || ...
            sdResult.provenance.spectral_resampling_method ~= ...
                "uniform_inverse_wavelength" || ...
            sdResult.provenance.spectral_interpolation_method ~= "pchip"
        error('OCE:OCTSystemTest:SDProvenance', ...
            'SD spectral preparation provenance is invalid.');
    end
end

function assert_sample_derived_global_median_matches_reference()
    sampleCount = 256;
    repeatCount = 7;
    lateralCount = 3;
    artifactBin = 11;
    reflectorBin = 41;

    sd = oce.config.resolveOCTSystemOptions( ...
        oce.config.getOCTSystemOptions("spectral_domain_1040"));
    lambdaNm = linspace(sd.spectral_sampling.lambda_start_nm, ...
        sd.spectral_sampling.lambda_end_nm, sampleCount)';
    sigmaCm = 1e7 ./ lambdaNm;
    sourceCoordinate = (sigmaCm - sigmaCm(1)) ./ ...
        (sigmaCm(end) - sigmaCm(1)) * (sampleCount - 1);
    targetCoordinate = (0:sampleCount - 1)';

    common = 1900 + 120 * cos( ...
        2 * pi * artifactBin * sourceCoordinate / sampleCount + 0.2);
    temporalPhase = reshape( ...
        2 * pi * (0:repeatCount - 1) / repeatCount, 1, []);
    lateralPhase = reshape([0, 0.4, 0.9], 1, 1, []);
    raw = common + 350 * cos( ...
        2 * pi * reflectorBin * sourceCoordinate / sampleCount + ...
        temporalPhase + lateralPhase);
    measurement = struct('rawdata', raw);

    lateralMedians = zeros(sampleCount, lateralCount);
    for position = 1:lateralCount
        lateralMedians(:, position) = median(raw(:, :, position), 2);
    end
    expectedBackground = median(lateralMedians, 2);

    [sdSystem, sampleOptics, geometry, crop] = contracts( ...
        "spectral_domain_1040", sampleCount, repeatCount, lateralCount);
    context = oce.acquisition.prepareSpectralSamples(raw, sdSystem);
    if ~isequaln(context.background_spectrum, expectedBackground)
        error('OCE:OCTSystemTest:BackgroundEstimator', ...
            'SD sample-derived global-median background estimate changed.');
    end

    result = oce.acquisition.reconstructComplexVolume( ...
        measurement, sdSystem, sampleOptics, geometry, crop);
    prepared = interp1(sourceCoordinate, ...
        double(raw(:, :, 1)) - expectedBackground, ...
        targetCoordinate, 'pchip');
    expected = fft(hann(sampleCount) .* prepared, [], 1);
    expected = expected(1:(sampleCount / 2), :);
    actual = squeeze(result.complex_volume.values(1, :, :));

    tolerance = max(abs(expected), [], 'all') * 1e-10 + 1e-10;
    if max(abs(actual - expected), [], 'all') > tolerance
        error('OCE:OCTSystemTest:BackgroundEstimator', ...
            ['SD reconstruction no longer applies the sample-derived ' ...
             'global-median background before inverse-wavelength resampling.']);
    end
end

function assert_time_axis_and_filter_sampling()
    sampleCount = 32;
    repeatCount = 16;
    lateralCount = 1;
    raw = reshape(1:(sampleCount * repeatCount), ...
        sampleCount, repeatCount, lateralCount);
    measurement = struct('rawdata', raw);
    profiles = ["swept_source_1300", "spectral_domain_1040"];
    expectedDt = [5e-6, 20e-6];
    expectedFs = [200e3, 50e3];
    for index = 1:numel(profiles)
        [octSystem, sampleOptics, geometry, crop] = contracts( ...
            profiles(index), sampleCount, repeatCount, lateralCount);
        result = oce.acquisition.reconstructComplexVolume( ...
            measurement, octSystem, sampleOptics, geometry, crop);
        if result.geometry.time_sample_interval_s ~= expectedDt(index)
            error('OCE:OCTSystemTest:TimeAxis', ...
                'Profile %s produced an incorrect time interval.', ...
                profiles(index));
        end

        config = oce.config.getDefaultProcessingConfig("phantom");
        config.FilterOptions.frequency.selection_source = ...
            "manual_configuration";
        config.FilterOptions.frequency.center_hz = 1000;
        surface = zeros(2, repeatCount);
        resolved = oce.config.resolveFilterOptions(config, surface, octSystem);
        if resolved.sampling_frequency_hz ~= expectedFs(index) || ...
                resolved.sample_interval_s ~= expectedDt(index)
            error('OCE:OCTSystemTest:FilterSampling', ...
                'Profile %s did not propagate temporal sampling.', ...
                profiles(index));
        end
    end
end

function [octSystem, sampleOptics, geometry, crop] = contracts( ...
        profile, sampleCount, repeatCount, lateralCount)
    octSystem = oce.config.resolveOCTSystemOptions( ...
        oce.config.getOCTSystemOptions(profile));
    sampleOptics = oce.config.resolveSampleOpticalOptions( ...
        oce.config.getDefaultProcessingConfig("phantom").SampleOpticalOptions);
    geometry = struct( ...
        'spectral_sample_count', sampleCount, ...
        'temporal_repetition_count', repeatCount, ...
        'available_depth_sample_count', sampleCount / 2, ...
        'lateral_sample_count', lateralCount);
    crop = struct( ...
        'depth', struct( ...
            'start_index_inclusive', 1, ...
            'end_index_inclusive', sampleCount / 2, ...
            'sample_count', sampleCount / 2), ...
        'time', struct( ...
            'start_index_inclusive', 1, ...
            'end_index_inclusive', repeatCount, ...
            'sample_count', repeatCount));
end

function width = half_amplitude_width(profile, peak)
    threshold = profile(peak) / 2;
    left = peak;
    right = peak;
    while left > 1 && profile(left - 1) >= threshold
        left = left - 1;
    end
    while right < numel(profile) && profile(right + 1) >= threshold
        right = right + 1;
    end
    width = right - left + 1;
end
