function test_config_domain_contract(~)
%TEST_CONFIG_DOMAIN_CONTRACT Validate maintained configuration behavior.

    assert_canonical_profiles();
    assert_oct_system_profiles();
    assert_sample_optical_profiles();
    assert_rejected_profiles();
    assert_border_sample_mapping();
    assert_build_for_acquisition();
    assert_per_acquisition_override();
    assert_acquisition_taxonomy_independence();
    assert_save_contract();
    assert_build_errors();
end

function assert_acquisition_taxonomy_independence()
    fixture = create_io_acquisition_fixture();
    header = oce.io.readAcquisitionHeader( ...
        fixture.rawFilename, fixture.rawDir);
    base = struct( ...
        'acquisition_mode', "mb_mode", ...
        'scan_geometry_selection', "manual", ...
        'scan_geometry', "angular_bmodes");
    row = table("mb_mode", "angular_bmodes", ...
        'VariableNames', {'acquisition_mode', 'scan_geometry'});
    resolved = oce.config.resolveAcquisitionOptions(base, row, header);
    if resolved.acquisition_mode ~= "mb_mode" || ...
            resolved.scan_geometry ~= "angular_bmodes" || ...
            resolved.acquisition_mode_source ~= ...
                "acquisition_row.acquisition_mode" || ...
            resolved.scan_geometry_source ~= "acquisition_row.scan_geometry"
        error('OCE:ConfigTest:AcquisitionTaxonomy', ...
            'Canonical acquisition taxonomy did not resolve from the row.');
    end
    invalidMode = base;
    invalidMode.acquisition_mode = "unsupported_mode";
    assert_identifier('OCE:Acquisition:UnsupportedAcquisitionMode', @() ...
        oce.config.resolveAcquisitionOptions(invalidMode, row, header));
    rasterBase = base;
    rasterBase.scan_geometry = "raster";
    rasterRow = table("mb_mode", "raster", ...
        'VariableNames', {'acquisition_mode', 'scan_geometry'});
    rasterResolved = oce.config.resolveAcquisitionOptions( ...
        rasterBase, rasterRow, header);
    if rasterResolved.scan_geometry ~= "raster"
        error('OCE:ConfigTest:RasterTaxonomy', ...
            'Raster scan geometry must resolve from the acquisition row.');
    end
    invalidGeometry = base;
    invalidGeometry.scan_geometry = "spiral";
    spiralRow = table("mb_mode", "spiral", ...
        'VariableNames', {'acquisition_mode', 'scan_geometry'});
    assert_identifier('OCE:Acquisition:UnsupportedScanGeometry', @() ...
        oce.config.resolveAcquisitionOptions( ...
            invalidGeometry, spiralRow, header));
    clear fixture
end

function assert_canonical_profiles()
    expectedFields = ["profile"; "created_by"; "created_at"; ...
        "AcquisitionOptions"; "OCTSystemOptions"; ...
        "SampleOpticalOptions"; ...
        "DispersionAnalysisOptions"; "FilterOptions"; "BorderOptions"; ...
        "MotionOptions"; "DispersionWindowOptions"; ...
        "VisualizationOptions"; "VideoOptions"; "per_acquisition"];
    profiles = ["phantom", "in_vivo_eye", "ex_vivo_eye"];
    for index = 1:numel(profiles)
        config = oce.config.getDefaultProcessingConfig(profiles(index));
        if ~isequal(string(fieldnames(config)), expectedFields) || ...
                config.profile ~= profiles(index) || ...
                config.AcquisitionOptions.acquisition_mode ~= "mb_mode" || ...
                config.AcquisitionOptions.scan_geometry_selection ~= "automatic" || ...
                config.AcquisitionOptions.scan_geometry ~= "" || ...
                config.OCTSystemOptions.profile ~= ...
                    "swept_source_1300" || ...
                isfield(config, 'OCT_defaults') || ...
                config.FilterOptions.method ~= "fir_bandpass" || ...
                config.FilterOptions.order ~= 100 || ...
                config.BorderOptions.selection ~= "automatic" || ...
                config.BorderOptions.methods.phantom.top_search_offset ~= 0 || ...
                config.BorderOptions.methods.phantom.top_index_offset ~= 2 || ...
                config.BorderOptions.methods.phantom.bottom_index_offset ~= 0 || ...
                config.MotionOptions.depth_resolved.quantity ~= "phase_increment" || ...
                config.MotionOptions.surface.estimator ~= "loupas" || ...
                config.DispersionWindowOptions.center.method ~= ...
                    "max_mirrored_correlation" || ...
                config.DispersionAnalysisOptions.method ~= "windowed_fft_ridge" || ...
                config.DispersionAnalysisOptions.phase_gradient.enabled || ...
                config.DispersionAnalysisOptions.spectrum.window.time.enabled || ...
                config.DispersionAnalysisOptions.spectrum.window.space.enabled || ...
                config.DispersionAnalysisOptions.spectrum.window.time.method ~= ...
                    "hann_symmetric" || ...
                config.DispersionAnalysisOptions.spectrum.window.space.method ~= ...
                    "hann_symmetric"
            error('OCE:ConfigTest:DefaultContract', ...
                'Default configuration contract changed for %s.', profiles(index));
        end
    end

    inVivo = oce.config.getDefaultProcessingConfig("in_vivo_eye");
    exVivo = oce.config.getDefaultProcessingConfig("ex_vivo_eye");
    if inVivo.BorderOptions.corneal_preprocessing.adaptive_threshold_k ~= 0.12 || ...
            exVivo.BorderOptions.corneal_preprocessing.adaptive_threshold_k ~= 0.09 || ...
            inVivo.BorderOptions.lateral_edge_exclusion.enabled || ...
            inVivo.BorderOptions.lateral_edge_exclusion.fraction_per_side ~= 0.02 || ...
            isfield(inVivo.BorderOptions.methods.phantom, 'edge_margin') || ...
            isfield(exVivo.BorderOptions.methods.adaptive_corneal, ...
                'remove_lateral_edges')
        error('OCE:ConfigTest:ProfileDefaults', ...
            'Profile-specific border defaults changed.');
    end
end

function assert_oct_system_profiles()
    ssOptions = oce.config.getOCTSystemOptions("swept_source_1300");
    ss = oce.config.resolveOCTSystemOptions(ssOptions);
    assert(ss.depth_sampling_calibration.method == "native_fft_interval");
    if ss.system_type ~= "swept_source" || ...
            ss.a_scan_rate ~= 200 || ss.depth_sampling_calibration.interval_um ~= 7.1 || ...
            isfield(ss, 'IDXrefrac') || ss.center_wavelength ~= 1.3 || ...
            ss.spectral_sampling.method ~= "fft_ready_uniform_k" || ...
            ss.spectral_preprocessing.background_method ~= "none" || ...
            ss.spectral_preprocessing.resampling_method ~= "none" || ...
            ss.spectral_preprocessing.interpolation_method ~= "none" || ...
            ss.spectral_preprocessing.extrapolation
        error('OCE:ConfigTest:OCTSystemProfile', ...
            'Historical swept-source profile changed.');
    end

    sdOptions = oce.config.getOCTSystemOptions("spectral_domain_1040");
    sd = oce.config.resolveOCTSystemOptions(sdOptions);
    assert(sd.depth_sampling_calibration.method == "native_fft_interval");
    if sd.system_type ~= "spectral_domain" || ...
            sd.a_scan_rate ~= 50 || sd.depth_sampling_calibration.interval_um ~= 3.57 || ...
            isfield(sd, 'IDXrefrac') || sd.center_wavelength ~= 1.0441 || ...
            sd.center_wavelength_source ~= ...
                "experimentally_characterized" || ...
            sd.depth_sampling_calibration.source ~= ...
                "experimentally_characterized" || ...
            sd.spectral_sampling.method ~= ...
                "linear_wavelength_endpoints" || ...
            sd.spectral_sampling.lambda_start_nm ~= 945.672 || ...
            sd.spectral_sampling.lambda_end_nm ~= 1122.28 || ...
            sd.spectral_preprocessing.background_method ~= ...
                "sample_derived_global_median" || ...
            sd.spectral_preprocessing.resampling_method ~= ...
                "uniform_inverse_wavelength" || ...
            sd.spectral_preprocessing.interpolation_method ~= "pchip" || ...
            sd.spectral_preprocessing.extrapolation
        error('OCE:ConfigTest:OCTSystemProfile', ...
            'Spectral-domain profile did not resolve supported evidence.');
    end

    edited = sdOptions;
    edited.center_wavelength = 1.045;
    edited.center_wavelength_source = "alignment_update";
    edited.a_scan_rate = 51;
    edited.a_scan_rate_source = "alignment_update";
    edited.depth_sampling_calibration.interval_um = 3.50;
    edited.depth_sampling_calibration.source = "alignment_update";
    edited.spectral_sampling.lambda_start_nm = 946.0;
    edited.spectral_sampling.lambda_end_nm = 1123.0;
    edited.spectral_sampling.parameter_source = "alignment_update";
    editedResolved = oce.config.resolveOCTSystemOptions(edited);
    if editedResolved.center_wavelength ~= 1.045 || ...
            editedResolved.a_scan_rate ~= 51 || ...
            editedResolved.depth_sampling_calibration.interval_um ~= 3.50 || ...
            editedResolved.spectral_sampling.lambda_start_nm ~= 946.0 || ...
            editedResolved.spectral_sampling.lambda_end_nm ~= 1123.0 || ...
            editedResolved.center_wavelength_source ~= "alignment_update" || ...
            editedResolved.depth_sampling_calibration.source ~= "alignment_update"
        error('OCE:ConfigTest:OCTSystemEditable', ...
            'Editable OCT-system calibration values were not preserved.');
    end

    assert_identifier('OCE:Config:UnknownOCTSystemProfile', @() ...
        oce.config.getOCTSystemOptions("unknown_system"));
    assert_identifier('OCE:Config:InvalidOCTSystemProfile', @() ...
        oce.config.getOCTSystemOptions(""));
    assert_identifier('OCE:Config:InvalidOCTSystemOptions', @() ...
        oce.config.resolveOCTSystemOptions(struct()));
    assert_identifier('OCE:Config:InvalidOCTSystemOptions', @() ...
        oce.config.resolveOCTSystemOptions( ...
            struct('profile', "spectral_domain_1040")));
    assert_identifier('OCE:Config:OCTSystemProfileMismatch', @() ...
        oce.config.resolveOCTSystemOptions(sdOptions, ...
            "swept_source_1300"));

    retired = rmfield(sdOptions, 'depth_sampling_calibration');
    retired.axial_pixel_res = 3.57;
    retired.axial_pixel_res_source = "experimentally_characterized";
    assert_identifier('OCE:Config:RetiredAxialSampling', @() ...
        oce.config.resolveOCTSystemOptions(retired));
    retired.depth_sampling_calibration = sdOptions.depth_sampling_calibration;
    assert_identifier('OCE:Config:RetiredAxialSampling', @() ...
        oce.config.resolveOCTSystemOptions(retired));

    invalid = sdOptions;
    invalid.depth_sampling_calibration.interval_um = NaN;
    assert_identifier('OCE:Config:InvalidOCTSystemOptions', @() ...
        oce.config.resolveOCTSystemOptions(invalid));
    invalid = oce.config.getOCTSystemOptions("spectral_domain_1310");
    invalid.depth_sampling_calibration.reference_fft_sample_count = 2047;
    assert_identifier('OCE:Config:InvalidOCTSystemOptions', @() ...
        oce.config.resolveOCTSystemOptions(invalid));
    invalid.depth_sampling_calibration.reference_fft_sample_count = 8192.5;
    assert_identifier('OCE:Config:InvalidOCTSystemOptions', @() ...
        oce.config.resolveOCTSystemOptions(invalid));
end

function assert_sample_optical_profiles()
    profiles = ["in_vivo_eye", "ex_vivo_eye", "phantom"];
    expectedSources = ["maintained_profile_default", ...
        "maintained_profile_default", ...
        "maintained_profile_default_material_override_required"];
    for index = 1:numel(profiles)
        options = oce.config.getDefaultProcessingConfig( ...
            profiles(index)).SampleOpticalOptions;
        resolved = oce.config.resolveSampleOpticalOptions(options);
        if resolved.refractive_index.value ~= 1.4 || ...
                resolved.refractive_index.source ~= expectedSources(index)
            error('OCE:ConfigTest:SampleOptics', ...
                'Sample optics did not resolve for %s.', profiles(index));
        end
    end

    assert_identifier('OCE:Config:InvalidSampleOpticalOptions', @() ...
        oce.config.resolveSampleOpticalOptions(struct()));

    explicit = struct('refractive_index', struct( ...
        'value', 1.41, 'source', "material_specific_override"));
    resolved = oce.config.resolveSampleOpticalOptions(explicit);
    if resolved.refractive_index.value ~= 1.41 || ...
            resolved.refractive_index.source ~= "material_specific_override"
        error('OCE:ConfigTest:SampleOpticsOverride', ...
            'Explicit refractive-index override did not resolve.');
    end
end

function assert_rejected_profiles()
    rejected = ["default", "inVivo", "invivo", "phantom_cyl", ...
        "phantom_eye", "invivo_eye", "exvivo_eye", "not_a_profile"];
    for index = 1:numel(rejected)
        assert_identifier('OCE:Config:InvalidProcessingProfile', @() ...
            oce.config.getDefaultProcessingConfig(rejected(index)));
    end
    assert_identifier('OCE:Config:InvalidProcessingProfile', @() ...
        oce.config.getDefaultProcessingConfig());
end

function assert_border_sample_mapping()
    profiles = ["phantom", "in_vivo_eye", "ex_vivo_eye"];
    expectedMethods = ["phantom", "in_vivo_corneal", "adaptive_corneal"];
    crop = struct('depth', struct('sample_count', 100));
    for index = 1:numel(profiles)
        base = oce.config.getDefaultProcessingConfig( ...
            profiles(index)).BorderOptions;
        row = table(profiles(index), 'VariableNames', {'sample_type'});
        resolved = oce.config.resolveBorderOptions(base, row, crop);
        if resolved.selection ~= "automatic" || ...
                resolved.method ~= expectedMethods(index) || ...
                resolved.selection_metadata.sample_type ~= profiles(index)
            error('OCE:ConfigTest:SampleBorderMapping', ...
                'Canonical sample_type %s resolved incorrectly.', profiles(index));
        end
    end

    base = oce.config.getDefaultProcessingConfig("phantom").BorderOptions;
    base.selection = "manual";
    base.method = "in_vivo_corneal";
    resolved = oce.config.resolveBorderOptions(base, table(), crop);
    if resolved.selection ~= "manual" || ...
            resolved.method ~= "in_vivo_corneal"
        error('OCE:ConfigTest:ManualBorderOverride', ...
            'Manual border override no longer resolves independently.');
    end

    base.selection = "automatic";
    rejectedSamples = ["inVivo", "invivo", "phantom_cyl", ...
        "phantom_eye", "invivo_eye", "exvivo_eye"];
    for index = 1:numel(rejectedSamples)
        row = table(rejectedSamples(index), ...
            'VariableNames', {'sample_type'});
        assert_identifier('OCE:Config:UnknownSampleType', @() ...
            oce.config.resolveBorderOptions(base, row, crop));
    end
end

function assert_build_for_acquisition()
    fixture = create_io_acquisition_fixture();
    persist_acquisition_params(fixture);
    inputs = oce.acquisition.prepareProcessingInputs( ...
        fixture.root, fixture.subExperiment, "R004", ...
        'Key', 'run_id', 'RequireProcessingConfig', true);
    config = oce.config.buildProcessingConfigForAcquisition(inputs);
    if config.AcquisitionOptions.acquisition_mode ~= "mb_mode" || ...
            config.AcquisitionOptions.scan_geometry ~= "angular_bmodes" || ...
            config.AcquisitionOptions.scan_geometry_source ~= ...
                "acquisition_row.scan_geometry" || ...
            config.BorderOptions.selection ~= "automatic" || ...
            config.BorderOptions.method ~= "phantom" || ...
            config.resolved_crop.depth.start_index_inclusive ~= 2 || ...
            config.resolved_crop.depth.end_index_inclusive ~= 4 || ...
            config.resolved_crop.time.start_index_inclusive ~= 1 || ...
            config.resolved_crop.time.end_index_inclusive ~= 4 || ...
            config.MotionOptions.depth_resolved.quantity ~= "phase_increment" || ...
            config.DispersionWindowOptions.boundary_policy ~= "shift_to_fit"
        error('OCE:ConfigTest:ResolvedContract', ...
            'Configuration resolution for a maintained acquisition changed.');
    end
    if config.OCTSystemOptions.profile ~= "swept_source_1300" || ...
            config.OCTSystemOptions.selection_source ~= ...
                "acquisition_row.oct_system_profile" || ...
            config.SampleOpticalOptions.refractive_index.value ~= 1.4 || ...
            isfield(config.OCTSystemOptions, 'IDXrefrac') || ...
            isfield(config, 'OCT_defaults')
        error('OCE:ConfigTest:ResolvedContract', ...
            'Acquisition-owned OCT system profile was not resolved.');
    end
    if ~isfield(config, 'processing_config_base') || ...
            ~isfield(config, 'acquisition_row') || ~isfield(config, 'metadata')
        error('OCE:ConfigTest:ResolvedContract', ...
            'Resolved configuration provenance is incomplete.');
    end
    clear fixture
end

function assert_per_acquisition_override()
    fixture = create_io_acquisition_fixture();
    persist_acquisition_params(fixture);
    inputs = oce.acquisition.prepareProcessingInputs( ...
        fixture.root, fixture.subExperiment, "R004", ...
        'Key', 'run_id', 'RequireProcessingConfig', true);
    override = struct();
    override.AcquisitionOptions = struct( ...
        'acquisition_mode', "mb_mode", ...
        'scan_geometry_selection', "manual", ...
        'scan_geometry', "angular_bmodes");
    override.BorderOptions = struct( ...
        'selection', "manual", 'method', "phantom");
    override.SampleOpticalOptions = struct('refractive_index', struct( ...
        'value', 1.41, 'source', "per_acquisition_material_override"));
    inputs.processing_config.per_acquisition.R004 = override;
    resolved = oce.config.buildProcessingConfigForAcquisition(inputs);
    if resolved.AcquisitionOptions.acquisition_mode ~= "mb_mode" || ...
            resolved.AcquisitionOptions.scan_geometry ~= "angular_bmodes" || ...
            resolved.AcquisitionOptions.scan_geometry_source ~= ...
                "acquisition_row.scan_geometry" || ...
            resolved.BorderOptions.selection ~= "manual" || ...
            resolved.BorderOptions.method ~= "phantom" || ...
            resolved.SampleOpticalOptions.refractive_index.value ~= 1.41 || ...
            resolved.SampleOpticalOptions.refractive_index.source ~= ...
                "per_acquisition_material_override"
        error('OCE:ConfigTest:Override', ...
            'Per-acquisition override did not resolve as maintained.');
    end
    clear fixture
end

function persist_acquisition_params(fixture)
    oce.io.loadExperimentalLog( ...
        fixture.logPath, 'SaveAcquisitionParams', true);
end

function assert_save_contract()
    root = tempname;
    mkdir(root);
    cleanup = onCleanup(@() remove_tree(root));
    config = oce.config.getDefaultProcessingConfig("phantom");
    pathValue = oce.config.saveProcessingConfig(root, "synthetic", config);
    if ~isfile(pathValue)
        error('OCE:ConfigTest:SaveContract', ...
            'ProcessingConfig file was not persisted.');
    end
    info = whos('-file', pathValue);
    if numel(info) ~= 1 || string(info.name) ~= "processing_config" || ...
            string(info.class) ~= "struct" || ~isequal(info.size, [1 1])
        error('OCE:ConfigTest:SaveContract', ...
            'ProcessingConfig MAT contract changed.');
    end
    loaded = load(pathValue, 'processing_config');
    if ~isequaln(loaded.processing_config, config)
        error('OCE:ConfigTest:SaveContract', ...
            'Persisted ProcessingConfig differs from the supplied config.');
    end
    clear cleanup
end

function assert_build_errors()
    assert_throws(@() oce.config.buildProcessingConfigForAcquisition([]));
    assert_identifier('OCE:Config:UnsupportedBuildOption', @() ...
        oce.config.buildProcessingConfigForAcquisition( ...
            struct('x', 1), 'Unexpected', true));

    fixture = create_io_acquisition_fixture();
    persist_acquisition_params(fixture);
    inputs = oce.acquisition.prepareProcessingInputs( ...
        fixture.root, fixture.subExperiment, "R004", ...
        'Key', 'run_id', 'RequireProcessingConfig', true);
    missing = rmfield(inputs, 'processing_config');
    assert_throws(@() oce.config.buildProcessingConfigForAcquisition(missing));
    empty = inputs; empty.processing_config = struct();
    assert_throws(@() oce.config.buildProcessingConfigForAcquisition(empty));
    clear fixture
end

function assert_identifier(expected, callback)
    try
        callback();
    catch ME
        if string(ME.identifier) == string(expected), return; end
        error('OCE:ConfigTest:WrongIdentifier', ...
            'Expected %s, actual %s.', expected, ME.identifier);
    end
    error('OCE:ConfigTest:MissingError', ...
        'Expected error %s was not raised.', expected);
end

function assert_throws(callback)
    try
        callback();
    catch
        return;
    end
    error('OCE:ConfigTest:MissingError', 'Expected an error but none was raised.');
end

function remove_tree(folder)
    if isfolder(folder), rmdir(folder, 's'); end
end
