function test_motion_domain_contract(~)
%TEST_MOTION_DOMAIN_CONTRACT Validate explicit phase-estimation contracts.

    fixture = create_motion_fixture();

    verify_direct_phase_contract();
    verify_unwrap_difference_contract();
    verify_surface_sampling_contract(fixture);
    verify_surface_loupas_coupling(fixture);
    verify_metadata_contract(fixture);
    verify_error_contracts(fixture);
end

function verify_surface_loupas_coupling(fixture)
    noSmoothingOptions = resolved_options(default_depth_options(), ...
        surface_options("phase_increment", "loupas", 3, 3, "none", []));
    noSmoothing = oce.motion.computeSurfacePhase( ...
        fixture.dynamicCplx, fixture.border, noSmoothingOptions);
    smoothedOptions = resolved_options(default_depth_options(), ...
        surface_options("phase_increment", "loupas", 3, 3, "lowess", 0.5));
    smoothed = oce.motion.computeSurfacePhase( ...
        fixture.dynamicCplx, fixture.border, smoothedOptions);

    expectedSingle = NaN(4, 6);
    expectedBand = NaN(4, 6);
    for lateralIndex = 1:4
        if ~isfinite(fixture.border(lateralIndex))
            continue;
        end
        estimate = oce.motion.estimateLoupasPhaseIncrement( ...
            squeeze(fixture.dynamicCplx(lateralIndex, :, :)), 3);
        adjusted = round(fixture.border(lateralIndex)) - round(3 / 2);
        adjusted = min(max(adjusted, 1), size(estimate, 1));
        expectedSingle(lateralIndex, :) = estimate(adjusted, :);
        band = adjusted:min(size(estimate, 1), adjusted + 2);
        trace = mean(estimate(band, :), 1).';
        expectedBand(lateralIndex, :) = smooth(trace, 0.5, 'lowess').';
    end
    assertExactNumericContract(expectedSingle, noSmoothing.values, ...
        'SurfacePhase.LoupasSingleDepthWithoutSmoothing');
    assertExactNumericContract(expectedBand, smoothed.values, ...
        'SurfacePhase.LoupasBandThenLowess');
end

function verify_direct_phase_contract()
    phase = reshape([0.2 2.9 -3.0 0.7], 1, 1, []);
    complexVolume = exp(-1i * phase);
    options = resolved_options(depth_options( ...
        "wrapped_phase", "direct_phase", [], "none", []), ...
        default_surface_options());
    result = oce.motion.computeDepthResolvedPhase(complexVolume, options);
    expected = -angle(complexVolume);
    assertExactNumericContract(expected, result.values, ...
        'DepthPhase.directPhaseSign');
    assert(isequal(size(result.values), [1 1 4]), ...
        'Wrapped phase must preserve T.');
end

function verify_unwrap_difference_contract()
    phase = reshape([2.8 3.1 3.4 3.7], 1, 1, []);
    complexVolume = exp(-1i * phase);
    options = resolved_options(depth_options( ...
        "phase_increment", "unwrap_then_difference", [], "none", []), ...
        default_surface_options());
    result = oce.motion.computeDepthResolvedPhase(complexVolume, options);
    expected = diff(unwrap(-angle(complexVolume), [], 3), 1, 3);
    assertExactNumericContract(expected, result.values, ...
        'DepthPhase.explicitWrapCrossing');
    assert(isequal(size(result.values), [1 1 3]), ...
        'Phase increment must produce T-1 without accumulation.');
end

function verify_surface_sampling_contract(fixture)
    options = resolved_options(default_depth_options(), surface_options( ...
        "wrapped_phase", "direct_phase", 3, [], "none", []));
    result = oce.motion.computeSurfacePhase( ...
        fixture.dynamicCplx, fixture.validBorder, options);
    expected = NaN(4, 7);
    for lateralIndex = 1:4
        surfaceIndex = fixture.validBorder(lateralIndex);
        band = surfaceIndex:(surfaceIndex + 2);
        expected(lateralIndex, :) = -angle(squeeze(mean( ...
            fixture.dynamicCplx(lateralIndex, band, :), 2)));
    end
    assertExactNumericContract(expected, result.values, ...
        'SurfacePhase.complexBandMean');

    offsetOptions = options;
    offsetOptions.surface.depth_offset_samples = 1;
    offset = oce.motion.computeSurfacePhase( ...
        fixture.dynamicCplx, [3 4 5 3], offsetOptions);
    assertExactNumericContract(result.values, offset.values, ...
        'SurfacePhase.explicitDepthOffset');
end

function verify_metadata_contract(fixture)
    options = resolved_options(default_depth_options(), ...
        default_surface_options());
    depth = oce.motion.computeDepthResolvedPhase(fixture.dynamicCplx, options);
    surface = oce.motion.computeSurfacePhase( ...
        fixture.dynamicCplx, fixture.validBorder, options);
    assert(depth.quantity == "phase_increment" && depth.units == "rad" && ...
        depth.estimator == "unwrap_then_difference" && ...
        depth.layout == "lateral_depth_time" && ...
        depth.difference_axis == "time");
    assert(surface.quantity == "phase_increment" && ...
        surface.units == "rad" && surface.estimator == "loupas" && ...
        surface.layout == "lateral_time" && ...
        surface.surface_reference == "anterior" && ...
        surface.depth_offset_samples == 0 && ...
        surface.aggregation_band_samples == 3);
    forbidden = ["displacement"; "velocity"; "optical_path_length"; ...
        "strain"; "strain_rate"];
    assert(~any(isfield(depth, forbidden)) && ...
        ~any(isfield(surface, forbidden)), ...
        'Phase results must not claim uncalibrated physical quantities.');
end

function verify_error_contracts(fixture)
    base = oce.config.getDefaultProcessingConfig("phantom").MotionOptions;
    cases = {
        @() oce.config.resolvePhaseEstimationOptions( ...
            rmfield(base, 'depth_resolved')), 'OCE:Motion:MissingOption';
        @() resolve_extra_field(base), 'OCE:Motion:InvalidOptions';
        @() resolve_changed(base, "depth_resolved.quantity", "velocity"), ...
            'OCE:Motion:InvalidQuantity';
        @() resolve_changed(base, "depth_resolved.estimator", "unknown"), ...
            'OCE:Motion:UnsupportedEstimator';
        @() resolve_changed(base, "depth_resolved.estimator", "direct_phase"), ...
            'OCE:Motion:InvalidEstimatorCombination';
        @() resolve_changed(base, ...
            "depth_resolved.smoothing.method", "gaussian"), ...
            'OCE:Motion:InvalidSmoothing';
        @() resolve_changed(base, ...
            "surface.surface_reference", "posterior"), ...
            'OCE:Motion:UnsupportedSurfaceReference';
        @() resolve_changed(base, ...
            "surface.aggregation_band_samples", 0), ...
            'OCE:Motion:InvalidSurfaceSampling';
        @() resolve_changed(base, ...
            "surface.depth_offset_samples", 0.5), ...
            'OCE:Motion:InvalidSurfaceSampling';
        @() resolve_changed(base, ...
            "surface.loupas.axial_window_samples", 1), ...
            'OCE:Motion:InvalidLoupasWindow';
        @() resolve_changed(base, ...
            "surface.smoothing.span_fraction", 0), ...
            'OCE:Motion:InvalidSmoothing';
        @() resolve_changed(base, "depth_resolved.quantity", 2), ...
            'OCE:Motion:InvalidQuantity';
        @() oce.motion.computeSurfacePhase(fixture.dynamicCplx, ...
            [9 9 9 9], resolved_options(default_depth_options(), ...
            default_surface_options())), ...
            'OCE:Motion:SurfaceBandOutOfRange'};
    for index = 1:size(cases, 1)
        assert_error(cases{index, 1}, cases{index, 2});
    end
end

function resolved = resolve_extra_field(base)
    base.retired_numeric_selector = 2;
    resolved = oce.config.resolvePhaseEstimationOptions(base);
end

function resolved = resolve_changed(base, path, value)
    names = split(path, ".");
    if numel(names) == 2
        base.(names(1)).(names(2)) = value;
    else
        base.(names(1)).(names(2)).(names(3)) = value;
    end
    resolved = oce.config.resolvePhaseEstimationOptions(base);
end

function resolved = resolved_options(depth, surface)
    base = struct('depth_resolved', depth, 'surface', surface, ...
        'show_progress', false);
    resolved = oce.config.resolvePhaseEstimationOptions(base);
end

function options = default_depth_options()
    options = depth_options( ...
        "phase_increment", "unwrap_then_difference", [], "lowess", 0.05);
end

function options = default_surface_options()
    options = surface_options( ...
        "phase_increment", "loupas", 3, 3, "lowess", 0.05);
end

function options = depth_options(quantity, estimator, window, method, span)
    options = struct('quantity', quantity, 'estimator', estimator, ...
        'loupas', struct('axial_window_samples', window), ...
        'smoothing', struct('method', method, 'span_fraction', span));
end

function options = surface_options( ...
        quantity, estimator, band, window, method, span)
    options = struct('quantity', quantity, 'estimator', estimator, ...
        'surface_reference', "anterior", 'depth_offset_samples', 0, ...
        'aggregation_band_samples', band, ...
        'loupas', struct('axial_window_samples', window), ...
        'smoothing', struct('method', method, 'span_fraction', span));
end

function assert_error(action, expectedIdentifier)
    try
        action();
    catch ME
        assert(strcmp(ME.identifier, expectedIdentifier), ...
            'Expected error %s; actual=%s.', expectedIdentifier, ME.identifier);
        return;
    end
    error('OCE:PhaseEstimationTest:MissingError', ...
        'Expected error %s was not raised.', expectedIdentifier);
end
