function test_spectral_domain_1310_contract(~)
%TEST_SPECTRAL_DOMAIN_1310_CONTRACT Verify maintained SD-1310 behavior.

    assert_profile_contract();
    assert_spectral_preparation_reference();
    assert_sampling_contract();
end

function assert_profile_contract()
    options = oce.config.getOCTSystemOptions("spectral_domain_1310");
    resolved = oce.config.resolveOCTSystemOptions(options);
    expectedLambdaStartNm = 1261.36;
    expectedLambdaEndNm = 1472.76;

    if resolved.profile ~= "spectral_domain_1310" || ...
            resolved.system_type ~= "spectral_domain" || ...
            resolved.center_wavelength ~= 1.310 || ...
            resolved.center_wavelength_source ~= "nominal_system_wavelength" || ...
            resolved.a_scan_rate ~= 50 || ...
            resolved.a_scan_rate_source ~= "profile_supplied" || ...
            resolved.depth_sampling_calibration.method ~= "reference_fft_interval" || ...
            resolved.depth_sampling_calibration.interval_um ~= 1.48 || ...
            resolved.depth_sampling_calibration.spectral_sample_count ~= 2048 || ...
            resolved.depth_sampling_calibration.reference_fft_sample_count ~= 8192 || ...
            resolved.depth_sampling_calibration.source ~= ...
                "experimentally_characterized" || ...
            resolved.spectral_sampling.method ~= ...
                "linear_wavelength_endpoints" || ...
            resolved.spectral_sampling.lambda_start_nm ~= expectedLambdaStartNm || ...
            resolved.spectral_sampling.lambda_end_nm ~= expectedLambdaEndNm || ...
            resolved.spectral_sampling.parameter_source ~= ...
                "system_configuration" || ...
            resolved.spectral_preprocessing.background_method ~= ...
                "sample_derived_global_median" || ...
            resolved.spectral_preprocessing.resampling_method ~= ...
                "uniform_inverse_wavelength" || ...
            resolved.spectral_preprocessing.interpolation_method ~= "pchip" || ...
            resolved.spectral_preprocessing.extrapolation
        error('OCE:SD1310Test:Profile', ...
            'Spectral-domain 1310 profile contract is invalid.');
    end

    edited = options;
    edited.spectral_sampling.lambda_start_nm = 1262.0;
    edited.spectral_sampling.lambda_end_nm = 1472.0;
    edited.spectral_sampling.parameter_source = "alignment_update";
    editedResolved = oce.config.resolveOCTSystemOptions(edited);
    if editedResolved.spectral_sampling.lambda_start_nm ~= 1262.0 || ...
            editedResolved.spectral_sampling.lambda_end_nm ~= 1472.0 || ...
            editedResolved.spectral_sampling.parameter_source ~= ...
                "alignment_update" || ...
            ~isequal(editedResolved.depth_sampling_calibration, ...
                resolved.depth_sampling_calibration)
        error('OCE:SD1310Test:EditableConfiguration', ...
            'SD-1310 system parameters are not editable through OCTSystemOptions.');
    end
end

function assert_spectral_preparation_reference()
    sampleCount = 256;
    repeatCount = 9;
    lateralCount = 3;
    reflectorBin = 31;

    system = oce.config.resolveOCTSystemOptions( ...
        oce.config.getOCTSystemOptions("spectral_domain_1310"));
    lambdaNm = linspace(system.spectral_sampling.lambda_start_nm, ...
        system.spectral_sampling.lambda_end_nm, sampleCount)';
    sigmaCm = 1e7 ./ lambdaNm;
    sourceCoordinate = (sigmaCm - sigmaCm(1)) ./ ...
        (sigmaCm(end) - sigmaCm(1)) * (sampleCount - 1);
    targetCoordinate = (0:sampleCount - 1)';

    temporalPhase = reshape( ...
        2 * pi * (0:repeatCount - 1) / repeatCount, 1, []);
    lateralPhase = reshape([0, 0.37, 0.81], 1, 1, []);
    raw = 1900 + 280 * cos( ...
        2 * pi * reflectorBin * sourceCoordinate / sampleCount + ...
        temporalPhase + lateralPhase);

    lateralMedians = zeros(sampleCount, lateralCount);
    for position = 1:lateralCount
        lateralMedians(:, position) = median(raw(:, :, position), 2);
    end
    expectedBackground = median(lateralMedians, 2);

    context = oce.acquisition.prepareSpectralSamples(raw, system);
    coordinateTolerance = 1e-12;
    if max(abs(context.source_coordinate - sourceCoordinate), [], 'all') > ...
            coordinateTolerance || ...
            ~isequal(context.target_coordinate, targetCoordinate)
        error('OCE:SD1310Test:Coordinates', ...
            'SD-1310 inverse-wavelength coordinates are invalid.');
    end

    actual = oce.acquisition.prepareSpectralSamples( ...
        raw, system, 1:repeatCount, 1, context, "reconstruction");
    expected = interp1(sourceCoordinate, ...
        double(raw(:, :, 1)) - expectedBackground, ...
        targetCoordinate, 'pchip');
    tolerance = max(abs(expected), [], 'all') * 1e-10 + 1e-10;
    if max(abs(actual - expected), [], 'all') > tolerance
        error('OCE:SD1310Test:Preparation', ...
            ['SD-1310 preparation does not match configured ascending-' ...
             'wavelength inverse-wavelength PCHIP processing.']);
    end
end

function assert_sampling_contract()
    system = oce.config.resolveOCTSystemOptions( ...
        oce.config.getOCTSystemOptions("spectral_domain_1310"));
    sampleCount = 2048;
    repeatCount = 9;
    raw = 1900 + 280*cos((0:sampleCount-1)' * 0.17 + (0:repeatCount-1)*0.31);
    measurement = struct('rawdata', raw);
    geometry = oce.acquisition.buildAcquisitionGeometry(struct( ...
        'samples_in_Aline', sampleCount, 'Alines_in_Bframe', repeatCount, ...
        'Bframes_in_3Dscan', 1, 'No_3Dscans', 1, 'Ver_scan_length_mm', 0), ...
        "angular_bmodes");
    crop = struct('depth', struct('start_index_inclusive', 1, ...
        'end_index_inclusive', 1024, 'sample_count', 1024), ...
        'time', struct('start_index_inclusive', 1, ...
        'end_index_inclusive', repeatCount, 'sample_count', repeatCount));
    sampleOptics = oce.config.resolveSampleOpticalOptions( ...
        oce.config.getDefaultProcessingConfig("phantom").SampleOpticalOptions);
    context = oce.acquisition.prepareSpectralSamples(raw, system);
    prepared = oce.acquisition.prepareSpectralSamples( ...
        raw, system, 1:repeatCount, 1, context, "reconstruction");
    referenceFft = fft(hann(sampleCount).*prepared, [], 1);
    result = oce.acquisition.reconstructComplexVolume( ...
        measurement, system, sampleOptics, geometry, crop);
    assert(size(prepared,1) == 2048 && ...
        result.geometry.spectral_sample_count == 2048 && ...
        result.geometry.prepared_spectral_sample_count == 2048 && ...
        result.geometry.fft_sample_count == 2048 && ...
        result.geometry.available_depth_sample_count == 1024);
    assert(isequal(squeeze(result.complex_volume.values), referenceFft(1:1024,:)), ...
        'SD1310 must retain the unpadded complex FFT exactly.');
    assert(result.geometry.depth_sample_interval_mm == 5.92e-3 / 1.4);
    assert(result.geometry.time_sample_interval_s == 20e-6);
    assert(isequal(result.provenance.depth_sampling_calibration, ...
        system.depth_sampling_calibration));

    sampleOptics.refractive_index.value = 1;
    air = oce.acquisition.reconstructComplexVolume( ...
        measurement, system, sampleOptics, geometry, crop);
    assert(air.geometry.depth_sample_interval_mm == 5.92e-3);
    assert(isequal(air.complex_volume, result.complex_volume));
    assert(max(abs(air.axes.depth.values/1.4 - result.axes.depth.values)) < 1e-12);

    crop.depth.start_index_inclusive = 17;
    crop.depth.end_index_inclusive = 48;
    crop.depth.sample_count = 32;
    cropped = oce.acquisition.reconstructComplexVolume( ...
        measurement, system, sampleOptics, geometry, crop);
    assert(cropped.axes.depth.values(1) == 0, 'Crop origin remains local.');
    assert(isequal(squeeze(cropped.complex_volume.values), referenceFft(17:48,:)));

    for field = ["fft_sample_count", "prepared_spectral_sample_count", ...
            "available_depth_sample_count", "depth_sample_interval_mm"]
        invalid = result;
        invalid.geometry.(field) = 2 * invalid.geometry.(field);
        assert_identifier('OCE:Reconstruction:InvalidGeometry', ...
            @() oce.results.validateReconstructionResult(invalid));
    end
    invalid = result;
    invalid.axes.depth.values(20) = invalid.axes.depth.values(20) + 1e-5;
    assert_identifier('OCE:Reconstruction:InvalidGeometry', ...
        @() oce.results.validateReconstructionResult(invalid));

    wrongCalibration = system;
    wrongCalibration.depth_sampling_calibration.spectral_sample_count = 4096;
    assert_identifier('OCE:Acquisition:DepthCalibrationMismatch', @() ...
        oce.acquisition.reconstructComplexVolume( ...
            measurement, wrongCalibration, sampleOptics, geometry, crop));
end

function assert_identifier(identifier, callback)
    try
        callback();
    catch ME
        assert(strcmp(ME.identifier, identifier), 'Unexpected error: %s', ME.message);
        return;
    end
    error('OCE:SD1310Test:MissingError', 'Expected %s.', identifier);
end
