function pipelineResult = processPreparedAcquisition(processingInputs, ...
        configForRun, resolvedRun)
%PROCESSPREPAREDACQUISITION Calculate the requested fixed-order products.
% This domain function is silent and performs no plotting or persistence.

    if nargin < 3 || isempty(resolvedRun)
        resolvedRun = oce.config.resolveRunOptions(struct(), struct());
    end
    validate_inputs(processingInputs, configForRun, resolvedRun);
    required = resolvedRun.required_products;
    useParallel = resolvedRun.parallel.active;
    products = struct();
    outputs = struct('scientific_result', struct());

    measurement = oce.io.readRawAcquisition( ...
        processingInputs.filename, processingInputs.filepath);
    acquisitionState = oce.acquisition.buildAcquisitionState( ...
        measurement, configForRun);
    products.reconstruction = acquisitionState.reconstruction;
    completed = "reconstruction";

    if requires_product(required, "borders")
        products.borders = oce.borders.detectAndMask( ...
            acquisitionState, configForRun.BorderOptions);
        completed = "borders";
    end

    if requires_product(required, "phase_estimation")
        complexValues = acquisitionState.reconstruction.complex_volume.values;
        phaseOptions = configForRun.MotionOptions;
        depthResult = oce.motion.computeDepthResolvedPhase( ...
            complexValues, phaseOptions, 'UseParallel', useParallel);
        surfaceResult = oce.motion.computeSurfacePhase( ...
            complexValues, products.borders.indices.anterior, phaseOptions, ...
            'UseParallel', useParallel);
        products.phase = struct( ...
            'depth_resolved', depthResult, ...
            'surface', surfaceResult, ...
            'options', phaseOptions);
        completed = "phase_estimation";
    end

    if requires_product(required, "filtering")
        octSystem = acquisitionState.system.oct;
        geometry = acquisitionState.geometry;
        [products.filter, resolvedFilter] = ...
            oce.filtering.filterPhaseResults(products.phase, ...
                configForRun, octSystem, geometry);
        configForRun.FilterOptions = resolvedFilter;
        completed = "filtering";
    end

    if requires_product(required, "dispersion_windows")
        [resolvedAnalysis, phaseGradientOptions] = oce.config.resolveDispersionAnalysisOptions( ...
            configForRun.DispersionAnalysisOptions, ...
            configForRun.FilterOptions, processingInputs.acquisition_row);
        configForRun.DispersionAnalysisOptions = resolvedAnalysis;
        products.windows = oce.dispersion.buildWindows( ...
            configForRun, products.filter, ...
            acquisitionState.geometry.bmode_lateral_axis_mm, ...
            configForRun.FilterOptions, acquisitionState.geometry);
        completed = "dispersion_windows";
    end

    if requires_product(required, "dispersion_analysis")
        products.dispersion = oce.dispersion.analyzeWindows( ...
            products.windows, products.borders.thickness, ...
            configForRun.DispersionAnalysisOptions, ...
            'UseParallel', useParallel, ...
            'PhaseGradientOptions', phaseGradientOptions, ...
            'SurfacePhase', products.phase.surface, ...
            'PhaseTimeStartIndex', configForRun.resolved_crop.time.start_index_inclusive);
        completed = "dispersion_analysis";
    end

    if requires_product(required, "scientific_result")
        outputs.scientific_result = oce.results.buildScientificResult( ...
            processingInputs, configForRun, products.windows, ...
            products.dispersion);
        completed = "scientific_result";
    end

    available = required(1:find(required == completed, 1));
    pipelineResult = struct( ...
        'status', struct( ...
            'completed_through', completed, ...
            'available_products', available, ...
            'scientific_result_available', ...
                completed == "scientific_result", ...
            'persisted', false, ...
            'generated_artifacts', strings(0, 1)), ...
        'acquisition_state', acquisitionState, ...
        'products', products, ...
        'outputs', outputs, ...
        'resolved_run', resolvedRun, ...
        'config_for_run', configForRun);
end

function validate_inputs(processingInputs, configForRun, resolvedRun)
    if ~isstruct(processingInputs) || ~isscalar(processingInputs)
        error('OCE:Pipeline:InvalidPreparedAcquisition', ...
            'processing_inputs must be a prepared scalar struct.');
    end
    if ~isstruct(configForRun) || ~isscalar(configForRun)
        error('OCE:Pipeline:InvalidResolvedConfiguration', ...
            'config_for_run must be a resolved scalar struct.');
    end
    if ~isstruct(resolvedRun) || ~isscalar(resolvedRun) || ...
            ~isfield(resolvedRun, 'required_products') || ...
            ~isfield(resolvedRun, 'parallel') || ...
            ~isstruct(resolvedRun.parallel) || ...
            ~isfield(resolvedRun.parallel, 'active') || ...
            ~islogical(resolvedRun.parallel.active) || ...
            ~isscalar(resolvedRun.parallel.active)
        error('OCE:Pipeline:InvalidRunOptions', ...
            'resolved_run must be produced by oce.config.resolveRunOptions.');
    end
end

function tf = requires_product(required, product)
    tf = any(required == product);
end
