function fixture = create_plotting_fixture(rootDir)
%CREATE_PLOTTING_FIXTURE Build lightweight deterministic plotting inputs.

    if nargin < 1 || strlength(string(rootDir)) == 0
        rootDir = tempname;
    end
    rootDir = string(rootDir);
    mkdir(rootDir);

    angles = [0; 90];
    frequencyValues = {'2500', '3500'};
    meanData = cell(2, 1);
    ci95Data = cell(2, 1);
    angleMeanData = cell(2, 1);
    angleCi95Data = cell(2, 1);
    for index = 1:2
        freq = [500; 1000; 1500];
        meanS = struct();
        meanS.full_circle_angles_deg = angles;
        meanS.angular_phase_speed_m_per_s = [4; 6] + index;
        meanS.angular_mean_thickness_mm = ([0.45; 0.55] + 0.01 * index) * 1e-3;
        meanS.direction_frequency_axes_hz = {freq, freq};
        meanS.direction_smoothed_phase_speed_m_per_s = {[3; 4; 5] + index, [4; 5; 6] + index};
        meanS.direction_temporal_diagnostic_magnitude = {[1; 3; 2], [2; 4; 1]};
        ciS = meanS;
        ciS.angular_phase_speed_m_per_s = [0.2; NaN];
        ciS.angular_mean_thickness_mm = [0.02; NaN] * 1e-3;
        ciS.direction_smoothed_phase_speed_m_per_s = {[0.1; 0.2; 0.1], [0.2; NaN; 0.2]};
        ciS.direction_temporal_diagnostic_magnitude = {[0.1; 0.1; 0.1], [0.2; NaN; 0.2]};
        meanData{index, 1} = meanS;
        ci95Data{index, 1} = ciS;

        angleMeanData{index, 1} = struct( ...
            'angular_phase_speed_m_per_s', mean(meanS.angular_phase_speed_m_per_s), ...
            'direction_frequency_axes_hz', freq, ...
            'direction_smoothed_phase_speed_m_per_s', mean([meanS.direction_smoothed_phase_speed_m_per_s{1}, meanS.direction_smoothed_phase_speed_m_per_s{2}], 2), ...
            'direction_temporal_diagnostic_magnitude', mean([meanS.direction_temporal_diagnostic_magnitude{1}, meanS.direction_temporal_diagnostic_magnitude{2}], 2));
        angleCi95Data{index, 1} = struct( ...
            'angular_phase_speed_m_per_s', 0.15, ...
            'direction_smoothed_phase_speed_m_per_s', [0.1; 0.1; 0.1], ...
            'direction_temporal_diagnostic_magnitude', [0.1; 0.1; 0.1]);
    end

    experiment = struct();
    experiment.design = struct( ...
        'dimension_keys', ["frequency_Hz", "rep_id"], ...
        'dimension_values', {{frequencyValues, {'1'}}}, ...
        'dimension_units', ["Hz", ""]);
    experiment.summary = struct( ...
        'repetition_mean_data', {meanData}, ...
        'repetition_ci95_data', {ci95Data}, ...
        'angle_mean_data', {angleMeanData}, ...
        'angle_ci95_data', {angleCi95Data});

    phaseDir = fullfile(rootDir, 'individual');
    mkdir(phaseDir);
    oce.io.saveScientificResult(phaseDir, make_polar_result(angles));

    fixture = struct();
    fixture.rootDir = rootDir;
    fixture.summaryRoot = fullfile(rootDir, 'summary');
    fixture.phaseDir = phaseDir;
    fixture.experiment = experiment;
    fixture.Bmode = reshape(linspace(20, 100, 48), 6, 8);
    fixture.Mask = fixture.Bmode > 60;
    fixture.Xaxis = linspace(0, 1, 8);
    fixture.Zaxis = linspace(0, 0.5, 6)';
    fixture.bmode_intensity_limits_db = [20 100];
    fixture.OCT_system = struct();
    fixture.sample_optics = struct('refractive_index', struct( ...
        'value', 1.4, 'source', "synthetic_fixture"));
    fixture.indices = struct( ...
        'anterior', [2 2 3 3 3 2 2 2], ...
        'posterior', [5 5 5 6 6 5 5 5]);
    fixture.anteriorSurface = [(1:numel(fixture.Xaxis))', ...
        fixture.Zaxis(fixture.indices.anterior(:))];
    fixture.posteriorSurface = [(1:numel(fixture.Xaxis))', ...
        fixture.Zaxis(fixture.indices.posterior(:))];
    timeAxisS = (0:7) * 1e-3;
    frequencyAxisHz = (0:7) * 100;
    inputLine = sin((0:7) * pi / 4);
    inputSurfaceValues = repmat(inputLine, 8, 1);
    coefficients = [0.25 0.5 0.25];
    outputSurfaceValues = filter(coefficients, 1, inputSurfaceValues, [], 2);
    surfaceMap = reshape(sin(1:64), 8, 8) * 0.02;
    fixture.inputSurfacePhase = struct( ...
        'values', inputSurfaceValues, ...
        'quantity', "phase_increment", ...
        'units', "rad", ...
        'layout', "lateral_time");
    fixture.filterResult = struct( ...
        'applied', true, ...
        'surface', struct('values', outputSurfaceValues), ...
        'surface_postprocessed', struct('values', surfaceMap), ...
        'time_axis_s', timeAxisS, ...
        'frequency_axis_hz', frequencyAxisHz, ...
        'design', struct( ...
            'applied', true, ...
            'method', "fir_bandpass", ...
            'coefficients', coefficients, ...
            'delay_samples', 1, ...
            'requested_passband_hz', [250 450], ...
            'effective_passband_hz', [250 450], ...
            'diagnostic', struct( ...
                'line_index_used', 1, ...
                'input_line', inputLine, ...
                'input_spectrum', fft(inputLine))));
    fixture.surfacePhaseMap = surfaceMap;
    left = make_plot_window("left", 1:3, 1:4, surfaceMap, ...
        fixture.Xaxis, timeAxisS);
    right = make_plot_window("right", 5:7, 1:4, surfaceMap, ...
        fixture.Xaxis, timeAxisS);
    fixture.windowResult = struct('bmodes', struct( ...
        'index', 1, 'global_lateral_range', [1 8], ...
        'center', struct('local_lateral_index', 4), ...
        'left', left, 'right', right));
end

function result = make_polar_result(angles)
    frequency = [500; 1200; 1500];
    phaseSpeed = [5; 7];
    thickness = [0.5; 0.6] * 1e-3;
    directionNames = ["left", "right"];
    directions = repmat(struct('scan_axis_index', [], 'direction', "", ...
        'spectrum', struct(), 'ridge', struct(), ...
        'phase_speed_curve', struct(), 'target_selection', struct(), ...
        'mean_thickness_mm', []), 2, 1);
    for index = 1:2
        curve = [phaseSpeed(index)-1; phaseSpeed(index); phaseSpeed(index)+1];
        directions(index) = struct( ...
            'scan_axis_index', 1, ...
            'direction', directionNames(index), ...
            'spectrum', struct('quantity', ...
                "mean_temporal_fft_magnitude_across_lateral_samples", ...
                'units', "arbitrary_magnitude", 'layout', "frequency", ...
                'temporal_diagnostic_magnitude', [1; 3; 2]), ...
            'ridge', struct(), ...
            'phase_speed_curve', struct('quantity', "phase_speed", ...
                'units', "m/s", 'layout', "frequency", ...
                'raw_phase_speed_m_per_s', curve, ...
                'smoothed_phase_speed_m_per_s', curve), ...
            'target_selection', struct('requested_frequency_hz', 1200, ...
                'selected_bin_index', 2, 'selected_frequency_hz', 1200, ...
                'frequency_error_hz', 0, ...
                'selected_wavenumber_per_m', 1200 / phaseSpeed(index), ...
                'selected_phase_speed_m_per_s', phaseSpeed(index)), ...
            'mean_thickness_mm', thickness(index));
    end
    [phaseMean, phaseStd, phaseRange] = ...
        oce.results.computeScalarStatistics(phaseSpeed);
    [thicknessMean, thicknessStd, thicknessRange] = ...
        oce.results.computeScalarStatistics(thickness * 1e3);
    processingConfig = struct( ...
        'AcquisitionOptions', struct('scan_geometry', "angular_bmodes"), ...
        'DispersionWindowOptions', struct( ...
            'spatial', struct('method', "fraction_of_bmode")));
    windows = struct( ...
        'source', struct('quantity', "phase_increment", ...
            'units', "rad", 'layout', "lateral_time"), ...
        'frequency', struct('requested_hz', 1200), ...
        'sample_interval_s', 1e-3, ...
        'resolved_options', struct( ...
            'spatial', struct('method', "fraction_of_bmode")), ...
        'bmodes', struct('index', 1), ...
        'provenance', struct( ...
            'source', "synthetic_fixture", 'limitations', strings(0, 1)));
    result = struct( ...
        'schema', struct('name', "oce_phase_speed_result", 'version', 3), ...
        'acquisition', struct('experiment_id', "synthetic", ...
            'subexperiment_id', "plotting", 'run_id', "R001", ...
            'sample_type', "phantom", 'protocol', "angular_bmodes", ...
            'source_row', struct('scan_geometry', "angular_bmodes")), ...
        'processing', struct('config', processingConfig), ...
        'borders', struct('quantity', ...
            "mean_physical_thickness_per_directional_dispersion_window", ...
            'units', "mm", 'layout', "direction", ...
            'ordering', "acquisition_direction_order", ...
            'directional_mean_thickness_mm', thickness), ...
        'windows', windows, ...
        'dispersion', struct('target_frequency', struct( ...
                'source', "resolved_filter_center", 'requested_hz', 1200), ...
            'direction_ordering', "acquisition_direction_order", ...
            'scan_axis_angles_deg', 0, 'scan_axis_count', 1, ...
            'directions', rmfield(directions, {'spectrum', 'ridge', ...
                'phase_speed_curve', 'target_selection', 'mean_thickness_mm'}), ...
            'estimators', struct('kf_ridge', struct('method', "windowed_fft_ridge", ...
                'frequency_axis_hz', frequency, 'frequency_axis_quantity', "temporal_frequency", ...
                'frequency_axis_units', "Hz", 'frequency_axis_layout', "frequency", ...
                'directions', rmfield(directions, {'scan_axis_index', 'direction', 'mean_thickness_mm'})), ...
                'phase_gradient', struct('enabled', false, ...
                    'frequency_source', "acquisition_row.frequency_Hz", ...
                    'target_frequency_reference', "dispersion.target_frequency.requested_hz", ...
                    'input', struct(), 'directions', struct([])))), ...
        'angular', struct('unit', "deg", 'layout', "angle", ...
            'ordering', "counterclockwise_full_circle", ...
            'full_circle_angles_deg', angles, ...
            'source_direction_indices', [1; 2], ...
            'phase_speed_m_per_s', phaseSpeed, ...
            'mean_thickness_mm', thickness), ...
        'statistics', struct( ...
            'phase_speed', struct('quantity', "phase_speed", ...
                'units', "m/s", 'mean_m_per_s', phaseMean, ...
                'standard_deviation_m_per_s', phaseStd, ...
                'range_m_per_s', phaseRange), ...
            'thickness', struct('quantity', "mean_physical_thickness", ...
                'units', "um", 'source_units', "mm", ...
                'conversion_factor', 1e3, 'mean_um', thicknessMean, ...
                'standard_deviation_um', thicknessStd, ...
                'range_um', thicknessRange)));
    for index = 1:numel(directions)
        result.dispersion.estimators.kf_ridge.directions(index).target_selection = ...
            rmfield(directions(index).target_selection, 'requested_frequency_hz');
    end
    oce.results.validateScientificResult(result);
end

function window = make_plot_window(direction, spaceIndices, timeIndices, ...
        values, xAxis, timeAxisS)
    window = struct('direction', direction, ...
        'local_lateral_indices', spaceIndices, ...
        'time_indices', timeIndices, ...
        'x_axis_mm', xAxis(spaceIndices), ...
        'time_axis_s', timeAxisS(timeIndices), ...
        'values', values(spaceIndices, timeIndices), ...
        'spatial_boundary', struct('shift_samples', 0));
end
