function fixture = create_io_acquisition_fixture()
%CREATE_IO_ACQUISITION_FIXTURE Build lightweight deterministic I/O inputs.

    fixture = struct();
    fixture.root = tempname;
    mkdir(fixture.root);
    fixture.cleanup = onCleanup(@() remove_tree(fixture.root));
    fixture.subExperiment = 'synthetic_subexperiment';
    fixture.dataDir = fullfile(fixture.root, 'Data', fixture.subExperiment);
    fixture.paramsDir = fullfile(fixture.root, 'Params', fixture.subExperiment);
    mkdir(fixture.dataDir);
    mkdir(fixture.paramsDir);

    [fixture.logPath, fixture.expectedColumns] = create_synthetic_log( ...
        fixture.root, fixture.subExperiment);
    create_parser_faithful_oct2_file( ...
        fullfile(fixture.dataDir, 'synthetic_a.bin'));
    create_parser_faithful_oct2_file( ...
        fullfile(fixture.dataDir, 'synthetic_b.bin'));

    acquisition_parameters = create_acquisition_parameters();
    save(fullfile(fixture.paramsDir, ...
        'Params_synthetic_subexperiment.mat'), 'acquisition_parameters');
    processing_config = oce.config.getDefaultProcessingConfig("phantom");
    oce.config.saveProcessingConfig( ...
        fixture.root, fixture.subExperiment, processing_config);

    fixture.rawDir = fullfile(fixture.root, 'raw');
    mkdir(fixture.rawDir);
    fixture.rawFilename = 'minimal_oct2.bin';
    create_parser_faithful_oct2_file( ...
        fullfile(fixture.rawDir, fixture.rawFilename));
    fixture.compactFilename = 'compact_oct2.bin';
    fixture.compactExpectedRaw = create_compact_oct2_file( ...
        fullfile(fixture.rawDir, fixture.compactFilename), 1, 0, "");
    fixture.octoceFilename = 'octoce_raw_v1.bin';
    % The DG4162 GUI records the generator in the .bin header.
    fixture.generatorFrequencyHz = 1250;
    fixture.octoceExpectedRaw = create_octoce_raw_v1_file( ...
        fullfile(fixture.rawDir, fixture.octoceFilename), struct(), ...
        generator_section(fixture.generatorFrequencyHz));
    % One synthetic file per GUI MB scan pattern; expected raw data are in
    % forward A-line order.
    fixture.octocePatterns = struct();
    fixture.octocePatterns.crosshair = create_octoce_pattern(fixture.rawDir, ...
        'octoce_crosshair.bin', struct('pattern', 'crosshair', 'bscans', 1, ...
        'x_length_mm', 2, 'y_length_mm', 2));
    fixture.octocePatterns.linear = create_octoce_pattern(fixture.rawDir, ...
        'octoce_linear.bin', struct('pattern', 'linear', 'bscans', 2, ...
        'orientation', 'vertical', 'linear_bidirectional', true, ...
        'x_length_mm', 1, 'y_length_mm', 3));
    fixture.octocePatterns.raster = create_octoce_pattern(fixture.rawDir, ...
        'octoce_raster_bidirectional.bin', struct('pattern', 'raster', ...
        'bscans', 3, 'raster_bidirectional', true, ...
        'x_length_mm', 2, 'y_length_mm', 1));
    fixture.octocePatterns.rings = create_octoce_pattern(fixture.rawDir, ...
        'octoce_rings.bin', struct('pattern', 'rings', 'bscans', 2, ...
        'alines', 8, 'x_length_mm', 2, 'y_length_mm', 2));
    fixture.octocePatterns.spiral = create_octoce_pattern(fixture.rawDir, ...
        'octoce_spiral.bin', struct('pattern', 'spiral', 'bscans', 2, ...
        'alines', 8, 'x_length_mm', 2, 'y_length_mm', 2));
    fixture.octoceBmFilename = 'octoce_bm.bin';
    create_octoce_raw_v1_file(fullfile(fixture.rawDir, ...
        fixture.octoceBmFilename), struct('mode', 'BM'));
    fixture.truncatedRawFilename = 'truncated_oct2.bin';
    create_parser_faithful_oct2_file( ...
        fullfile(fixture.rawDir, fixture.truncatedRawFilename), -1);
    fixture.trailingRawFilename = 'trailing_oct2.bin';
    create_parser_faithful_oct2_file( ...
        fullfile(fixture.rawDir, fixture.trailingRawFilename), 1);
    fixture.compactTrailingByteFilename = 'compact_trailing_byte.bin';
    create_compact_oct2_file(fullfile(fixture.rawDir, ...
        fixture.compactTrailingByteFilename), 1, 0, "", 1);
    fixture.compactNonIntegerFilename = 'compact_noninteger.bin';
    create_compact_oct2_file(fullfile(fixture.rawDir, ...
        fixture.compactNonIntegerFilename), 1, -1, "");
    fixture.compactMissingFieldFilename = 'compact_missing_field.bin';
    create_compact_oct2_file(fullfile(fixture.rawDir, ...
        fixture.compactMissingFieldFilename), 1, 0, ...
        "A-lines per B-frame");
    fixture.unknownHeaderFilename = 'unknown_header.bin';
    create_unknown_oct2_file(fullfile(fixture.rawDir, ...
        fixture.unknownHeaderFilename));

    fixture.complexMeasurement = struct();
    fixture.complexMeasurement.rawdata = reshape( ...
        double(1:(8 * 4 * 3)), 8, 4, 3);
    fixture.integerMeasurement = fixture.complexMeasurement;
    fixture.integerMeasurement.rawdata = uint16( ...
        fixture.integerMeasurement.rawdata);
    fixture.OCT_system = oce.config.resolveOCTSystemOptions( ...
        oce.config.getOCTSystemOptions("swept_source_1300"));
    fixture.sample_optics = oce.config.resolveSampleOpticalOptions( ...
        oce.config.getDefaultProcessingConfig("phantom").SampleOpticalOptions);
    fixture.geometry = struct( ...
        'spectral_sample_count', 8, ...
        'temporal_repetition_count', 4, ...
        'available_depth_sample_count', 4, ...
        'lateral_sample_count', 3, ...
        'bmode_count', 1, ...
        'samples_per_bmode', 3, ...
        'bmode_scan_width_mm', 1, ...
        'bmode_lateral_axis_mm', linspace(0, 1, 3), ...
        'lateral_sample_interval_mm', 0.5, ...
        'depth_sample_count', 3, 'time_sample_count', 4);
    fixture.resolved_crop = struct( ...
        'depth', struct('selection', "manual_indices", ...
            'start_index_inclusive', 2, 'end_index_inclusive', 4, ...
            'sample_count', 3), ...
        'time', struct('selection', "manual_indices", ...
            'start_index_inclusive', 1, 'end_index_inclusive', 4, ...
            'sample_count', 4), ...
        'selection_source', "acquisition_parameters");
end

function parameters = create_acquisition_parameters()
    header = struct( ...
        'samples_in_Aline', 8, ...
        'Alines_in_Bframe', 4, ...
        'Bframes_in_3Dscan', 3, ...
        'No_3Dscans', 2, ...
        'Hor_scan_length_mm', 1.5, ...
        'Ver_scan_length_mm', 2.5, ...
        'type', "raster", ...
        'pattern_control', "raster");
    parameters = struct( ...
        'schema_version', 4, ...
        'acquisition_mode', "mb_mode", ...
        'scan_geometry', "angular_bmodes", ...
        'source', struct('filename', "synthetic_a.bin", ...
            'header', header, ...
            'oct_system_profile', "swept_source_1300"), ...
        'crop', struct( ...
            'depth', struct('selection', "manual_indices", ...
                'start_index_inclusive', 2, ...
                'end_index_inclusive', 4), ...
            'time', struct('selection', "manual_indices", ...
                'start_index_inclusive', 1, ...
                'end_index_inclusive', 4)), ...
        'preview_display', struct( ...
            'bmode_intensity_limits_db', [0.2 0.8]));
end

function [logPath, requiredColumns] = create_synthetic_log(root, subExperiment)
    requiredColumns = [ ...
        "experiment_id", "sub_experiment", "run_id", "filename", ...
        "sample_type", "experiment_type", "excitation_type", ...
        "acquisition_mode", "scan_geometry", "oct_system_profile", ...
        "frequency_Hz", "rep_id"];
    optionalColumns = [ ...
        "status", "shape", "material", "proportion", "sample_id", ...
        "period_us", "lead_train", "voltage_mVpp", ...
        "scan_size_x_mm", "scan_size_y_mm", "alines_per_bscan", ...
        "m_repetitions", "bscan_count", ...
        "puff_delay_ms", "puff_on_ms", "puff_frequency_Hz", ...
        "load_id", "strain_percent"];
    columns = [requiredColumns optionalColumns];
    sectionRow = cellstr(build_section_row(columns));
    headerRow = cellstr(columns);
    rowA = make_log_row(columns, subExperiment, ...
        "R004", "synthetic_a.bin", "1200", "1", "A");
    rowB = make_log_row(columns, subExperiment, ...
        "R005", "synthetic_b.bin", "1500", "2", "B");
    logPath = fullfile(root, 'experimental_log.xlsx');
    writecell([sectionRow; headerRow; rowA; rowB], ...
        logPath, 'Sheet', 'Experiment');
end

function sections = build_section_row(columns)
    sections = repmat("Experiment", size(columns));
    sampleColumns = ["sample_type", "shape", "material", ...
        "proportion", "sample_id"];
    excitationColumns = ["excitation_type", "frequency_Hz", ...
        "period_us", "lead_train", "voltage_mVpp", ...
        "puff_delay_ms", "puff_on_ms", "puff_frequency_Hz"];
    acquisitionColumns = ["run_id", "filename", "acquisition_mode", ...
        "scan_geometry", "oct_system_profile", "rep_id", ...
        "scan_size_x_mm", "scan_size_y_mm", "alines_per_bscan", ...
        "m_repetitions", "bscan_count"];
    sections(ismember(columns, sampleColumns)) = "Sample";
    sections(ismember(columns, excitationColumns)) = "Excitation";
    sections(ismember(columns, acquisitionColumns)) = "Acquisition";
end

function row = make_log_row(columns, subExperiment, runID, filename, ...
        frequency, repetition, suffix)
    values = struct( ...
        'experiment_id', "E_SYNTH", ...
        'sub_experiment', string(subExperiment), ...
        'run_id', runID, ...
        'filename', filename, ...
        'sample_type', "phantom", ...
        'experiment_type', "synthetic_oce", ...
        'excitation_type', "synthetic", ...
        'acquisition_mode', "mb_mode", ...
        'scan_geometry', "angular_bmodes", ...
        'oct_system_profile', "swept_source_1300", ...
        'frequency_Hz', frequency, ...
        'rep_id', repetition, ...
        'status', "ready", ...
        'shape', "flat", ...
        'material', "phantom", ...
        'proportion', "1", ...
        'sample_id', "S" + suffix, ...
        'period_us', "833", ...
        'lead_train', "1", ...
        'voltage_mVpp', "100", ...
        'scan_size_x_mm', "1", ...
        'scan_size_y_mm', "1", ...
        'alines_per_bscan', "3", ...
        'm_repetitions', "4", ...
        'bscan_count', "2", ...
        'puff_delay_ms', "0", ...
        'puff_on_ms', "0", ...
        'puff_frequency_Hz', "0", ...
        'load_id', "L1", ...
        'strain_percent', "0");
    row = cell(1, numel(columns));
    for index = 1:numel(columns)
        row{index} = values.(columns(index));
    end
end

function create_parser_faithful_oct2_file(path, sampleCountAdjustment)
    if nargin < 2
        sampleCountAdjustment = 0;
    end
    labels = ["header", "acquisition_datetime", "sample_trigger_source", ...
        "sample_rate_MHz", "samples_in_Aline", "pre_trigger_samples", ...
        "pattern_control", "type", "Alines_in_Bframe", "Flyback_Aline_No", ...
        "Bframe_trigger_Aline_delay", "Bframes_in_3Dscan", "No_3Dscans", ...
        "Hor_scan_length_mm", "Ver_scan_length_mm", "use_background_scan", ...
        "use_reference_MZI_scan", "use_dual_edge_sampling_if_external", ...
        "Max_Alines_in_buffer", "Is_Calib_on", "No_calib_scan"];
    values = ["ignored", "2026-01-01T00:00:00", "internal", "100", "8", ...
        "0", "raster", "Raster", "4", "0", "0", "3", "2", "1.5", ...
        "2.5", "0", "0", "0", "4", "0", "0"];
    header = '';
    for idx = 1:numel(labels)
        header = [header char(labels(idx)) ': ' char(values(idx)) ...
            '  ' sprintf('\r\n')]; %#ok<AGROW>
    end
    fileID = fopen(path, 'w');
    if fileID < 0
        error('Could not create synthetic OCT2 fixture: %s', path);
    end
    cleanup = onCleanup(@() fclose(fileID));
    fwrite(fileID, uint16(numel(header)), 'uint16');
    fwrite(fileID, uint16(0), 'uint16');
    fwrite(fileID, uint8(header), 'uint8');
    sampleCount = 8 * 4 * 3 * 2 + sampleCountAdjustment;
    fwrite(fileID, uint16(1:sampleCount), 'uint16');
    clear cleanup
end

function expectedRaw = create_compact_oct2_file( ...
        path, reportedSamples, sampleCountAdjustment, omittedLabel, ...
        trailingByteCount)
    if nargin < 5
        trailingByteCount = 0;
    end
    spectralCount = 8;
    temporalCount = 100;
    bmodeCount = 2;
    spatialCount = 4;
    labels = [ ...
        "Date/Time scan acquisition start"; ...
        "Sample trigger source"; ...
        "# spectral samples per A-line"; ...
        "# pre-trigger samples"; ...
        "Scan type"; ...
        "A-lines per B-frame"; ...
        "Flyback duration in # A-lines"; ...
        "B-frame trigger delay in # A-lines"; ...
        "# of B-frames in 3D scan"; ...
        "# of 3D repeated scans"; ...
        "Horizontal scan length (mm)"; ...
        "Vertical scan length (mm)"; ...
        "Background subtraction"];
    values = [ ...
        "2026-08-15 12:00:00"; "Internal"; string(reportedSamples); ...
        "4"; "Raster"; string(temporalCount); "1"; "2"; ...
        string(bmodeCount); string(spatialCount); "10.000"; ...
        "10.000"; "0"];
    keep = labels ~= string(omittedLabel);
    labels = labels(keep);
    values = values(keep);
    header = '';
    for index = 1:numel(labels)
        header = [header char(labels(index)) ': ' char(values(index)) ...
            '; ' char(13)]; %#ok<AGROW>
    end

    sourceRaw = reshape(uint16(1:(spectralCount * temporalCount * ...
        spatialCount * bmodeCount)), spectralCount, temporalCount, ...
        spatialCount, bmodeCount);
    payload = sourceRaw(:);
    payload = payload(1:(numel(payload) + sampleCountAdjustment));
    fileID = fopen(path, 'w');
    if fileID < 0
        error('Could not create synthetic compact OCT2 fixture: %s', path);
    end
    cleanup = onCleanup(@() fclose(fileID));
    fwrite(fileID, uint16(numel(header)), 'uint16');
    fwrite(fileID, uint16(0), 'uint16');
    fwrite(fileID, uint8(header), 'uint8');
    fwrite(fileID, payload, 'uint16');
    fwrite(fileID, repmat(uint8(255), trailingByteCount, 1), 'uint8');
    clear cleanup

    expectedRaw = double(reshape(sourceRaw, spectralCount, ...
        temporalCount, spatialCount * bmodeCount));
end

function pattern = create_octoce_pattern(folder, filename, scanOverrides)
    pattern = struct('filename', filename, 'expected_raw', ...
        create_octoce_raw_v1_file(fullfile(folder, filename), scanOverrides));
end

function generator = generator_section(frequencyHz)
    % Header section 'generator' written by the DG4162 GUI.
    settings = struct('ch1_vpp', 0.5, 'ch2_frequency_hz', frequencyHz, ...
        'ch2_waveform', 'Pulso', 'ch2_delay_ms', 2, ...
        'excitation', 'Con contacto', 'ch2_burst_cycles', 3);
    state = struct('identity', 'Rigol Technologies,DG4162', ...
        'ch1_frequency_hz', 954900, 'ch1_vpp', 0.5, ...
        'ch2_function', 'PULS', 'ch2_frequency_hz', frequencyHz, ...
        'ch2_delay_ms', 2, 'ch2_burst_cycles', 3);
    generator = struct('model', 'RIGOL DG4162', 'settings', settings, ...
        'state', state, 'sequence', []);
end

function expectedRaw = create_octoce_raw_v1_file(path, scanOverrides, generator)
    if nargin < 2
        scanOverrides = struct();
    end
    spectralCount = 8;
    temporalCount = 4;
    samplesPerBmode = 3;
    bmodeCount = 2;
    if isfield(scanOverrides, 'alines')
        samplesPerBmode = scanOverrides.alines;
    end
    if isfield(scanOverrides, 'bscans')
        bmodeCount = scanOverrides.bscans;
    end
    payloadOffset = 65536;

    source = struct();
    source.axis_order = {'bscan', 'aline', 'm_repetition', 'pixel'};
    source.backend = 'synthetic';
    source.created_utc = '2026-09-12T22:07:29+00:00';
    source.dtype = '<u2';
    source.format = 'OCT/OCE raw acquisition';
    source.format_version = '1.0';
    source.hardware = struct( ...
        'effective_line_rate_hz', 50000, ...
        'spectral_samples', spectralCount);
    source.integrity = struct( ...
        'committed_alines', temporalCount * samplesPerBmode * bmodeCount, ...
        'expected_alines', temporalCount * samplesPerBmode * bmodeCount);
    source.planned_shape = [bmodeCount, samplesPerBmode, ...
        temporalCount, spectralCount];
    source.raw_storage = struct( ...
        'data_offset_bytes', payloadOffset, ...
        'layout', 'C-order, contiguous, no sync samples');
    source.scan = struct( ...
        'alines', samplesPerBmode, ...
        'bscans', bmodeCount, ...
        'm_repetitions', temporalCount, ...
        'mode', 'MB', ...
        'orientation', 'horizontal', ...
        'pattern', 'meridians', ...
        'raster_bidirectional', false, ...
        'x_length_mm', 2.5, ...
        'y_length_mm', 2.5);
    names = fieldnames(scanOverrides);
    for index = 1:numel(names)
        source.scan.(names{index}) = scanOverrides.(names{index});
    end
    % Crosshair stores [B, sweep_xy, A, M, pixel]; BM stores [B, M, A, pixel].
    lineCount = bmodeCount;
    if string(source.scan.pattern) == "crosshair"
        source.axis_order = {'bscan', 'sweep_xy', 'aline', ...
            'm_repetition', 'pixel'};
        source.planned_shape = [bmodeCount, 2, samplesPerBmode, ...
            temporalCount, spectralCount];
        lineCount = 2 * bmodeCount;
    elseif string(source.scan.mode) == "BM"
        source.axis_order = {'bscan', 'm_repetition', 'aline', 'pixel'};
        source.planned_shape = [bmodeCount, temporalCount, ...
            samplesPerBmode, spectralCount];
    end
    source.integrity.committed_alines = ...
        temporalCount * samplesPerBmode * lineCount;
    source.integrity.expected_alines = source.integrity.committed_alines;
    source.state = 'complete';
    if nargin >= 3
        source.generator = generator;
    end

    jsonBytes = unicode2native(jsonencode(source), 'UTF-8');
    jsonLength = numel(jsonBytes);
    if 64 + jsonLength > payloadOffset
        error('Synthetic OCTOCE JSON exceeds its payload offset.');
    end

    sourceRaw = reshape(uint16(1:(spectralCount * temporalCount * ...
        samplesPerBmode * lineCount)), spectralCount, temporalCount, ...
        samplesPerBmode, lineCount);

    fileID = fopen(path, 'w', 'ieee-le');
    if fileID < 0
        error('Could not create synthetic OCTOCE fixture: %s', path);
    end
    cleanup = onCleanup(@() fclose(fileID));
    fwrite(fileID, uint8(['OCTOCE1' char(0)]), 'uint8');
    fwrite(fileID, uint32(1), 'uint32');
    fwrite(fileID, uint32(3), 'uint32');
    fwrite(fileID, uint32(1), 'uint32');
    fwrite(fileID, uint32(jsonLength), 'uint32');
    fwrite(fileID, uint32(0), 'uint32');
    fwrite(fileID, uint32(payloadOffset), 'uint32');
    fwrite(fileID, zeros(32, 1, 'uint8'), 'uint8');
    fwrite(fileID, jsonBytes, 'uint8');
    headerBytes = 64 + jsonLength;
    fwrite(fileID, zeros(payloadOffset - headerBytes, 1, 'uint8'), 'uint8');
    fwrite(fileID, sourceRaw(:), 'uint16');
    clear cleanup

    % MB stores odd bidirectional raster and linear lines from their positive
    % end; the reader returns every line in forward order.
    oddLines = 2:2:lineCount;
    reversedLines = [];
    if isfield(source.scan, 'raster_bidirectional') && ...
            source.scan.raster_bidirectional && ...
            string(source.scan.pattern) == "raster"
        reversedLines = oddLines;
    elseif isfield(source.scan, 'linear_bidirectional') && ...
            source.scan.linear_bidirectional && ...
            string(source.scan.pattern) == "linear"
        reversedLines = oddLines;
    end
    sourceRaw(:, :, :, reversedLines) = sourceRaw(:, :, end:-1:1, reversedLines);
    expectedRaw = double(reshape(sourceRaw, spectralCount, ...
        temporalCount, samplesPerBmode * lineCount));
end

function create_unknown_oct2_file(path)
    header = ['Unknown acquisition field: value; ' char(13)];
    fileID = fopen(path, 'w');
    if fileID < 0
        error('Could not create unknown OCT2 fixture: %s', path);
    end
    cleanup = onCleanup(@() fclose(fileID));
    fwrite(fileID, uint16(numel(header)), 'uint16');
    fwrite(fileID, uint16(0), 'uint16');
    fwrite(fileID, uint8(header), 'uint8');
    clear cleanup
end

function remove_tree(folder)
    if isfolder(folder)
        rmdir(folder, 's');
    end
end