function fixture = create_dispersion_analysis_fixture()
%CREATE_DISPERSION_ANALYSIS_FIXTURE Build deterministic dispersion inputs.

    scanAxisCount = 3;
    samplesPerBmode = 41;
    numTime = 81;
    Xaxis = (0:(scanAxisCount * samplesPerBmode - 1)) * 0.1;
    Time = (0:(numTime - 1)) * 0.05;
    SpaceTime = zeros(scanAxisCount * samplesPerBmode, numTime);

    localX = (0:(samplesPerBmode - 1)) * 0.1e-3;
    timeSeconds = Time * 1e-3;
    for scanAxisIndex = 1:scanAxisCount
        [timeGrid, spaceGrid] = ndgrid(timeSeconds, localX);
        phaseOffset = (scanAxisIndex - 1) * pi / 7;
        signal = sin(2*pi*(1000*timeGrid - 500*spaceGrid) + phaseOffset) + ...
            0.35 * sin(2*pi*(1800*timeGrid - 900*spaceGrid));
        deterministicNoise = 0.002 * cos(2*pi*(370*timeGrid + 130*spaceGrid));
        globalRange = (scanAxisIndex - 1) * samplesPerBmode + ...
            (1:samplesPerBmode);
        SpaceTime(globalRange, :) = (signal + deterministicNoise)';
    end

    DistBorder = 0.45 + 0.01 * sin((1:size(SpaceTime, 1))' / 9);
    bmodes = repmat(struct('index', [], ...
        'global_lateral_range', [], 'center', [], ...
        'left', [], 'right', []), 1, scanAxisCount);
    for scanAxisIndex = 1:scanAxisCount
        firstIndex = (scanAxisIndex - 1) * samplesPerBmode + 1;
        globalRange = firstIndex:firstIndex + samplesPerBmode - 1;
        bmodes(scanAxisIndex).index = scanAxisIndex;
        bmodes(scanAxisIndex).global_lateral_range = ...
            [globalRange(1) globalRange(end)];
        bmodes(scanAxisIndex).center = struct( ...
            'method', "manual_local_index", ...
            'local_lateral_index', 21, ...
            'global_lateral_index', globalRange(21), ...
            'x_coordinate_mm', Xaxis(21));
        bmodes(scanAxisIndex).left = make_window("left", true, 1:20, ...
            globalRange(1:20), 1:numTime, Xaxis(1:samplesPerBmode), ...
            Time * 1e-3, SpaceTime);
        bmodes(scanAxisIndex).right = make_window("right", false, 21:40, ...
            globalRange(21:40), 1:numTime, Xaxis(1:samplesPerBmode), ...
            Time * 1e-3, SpaceTime);
    end
    windowResult = struct('source', struct( ...
        'quantity', "phase_increment", 'units', "rad", ...
        'layout', "lateral_time", 'filter_enabled', true, ...
        'filter_applied', true, 'signal_size', size(SpaceTime)), ...
        'frequency', struct('center_hz', 1000), ...
        'sample_interval_s', 5e-5, ...
        'resolved_options', struct(), 'bmodes', bmodes);

    editableOptions = struct( ...
        'phase_gradient', struct('enabled', false), ...
        'method', "windowed_fft_ridge", ...
        'spectrum', struct( ...
            'fft', struct('time_bin_count', 129, ...
                'spatial_bin_count', 65), ...
            'crop', struct('maximum_frequency_hz', 3000, ...
                'maximum_wavenumber_per_m', 2000), ...
            'window', struct( ...
                'time', struct('enabled', false, ...
                    'method', "hann_symmetric"), ...
                'space', struct('enabled', false, ...
                    'method', "hann_symmetric"))), ...
        'ridge', struct( ...
            'maximum_wavenumber_jump_per_m', 100, ...
            'minimum_relative_magnitude', 0.05, ...
            'interpolation', struct('method', "linear", ...
                'extrapolate', true)), ...
        'phase_speed', struct('smoothing', struct( ...
            'method', "lowess", 'span_fraction', 0.1)), ...
        'target_frequency', struct( ...
            'source', "resolved_filter_center"));

    fixture = struct();
    fixture.SpaceTime = SpaceTime;
    fixture.Xaxis = Xaxis;
    fixture.Time = Time;
    fixture.DistBorder = DistBorder;
    fixture.FilterOptions = struct( ...
        'frequency', struct('center_hz', 1000));
    fixture.DispersionAnalysisOptions = ...
        oce.config.resolveDispersionAnalysisOptions( ...
        editableOptions, fixture.FilterOptions);
    fixture.config_for_run = struct('profile', 'synthetic_dispersion', ...
        'AcquisitionOptions', struct( ...
            'acquisition_mode', "mb_mode", ...
            'scan_geometry', "angular_bmodes"), ...
        'DispersionWindowOptions', struct( ...
            'spatial', struct('method', "fraction_of_bmode")), ...
        'DispersionAnalysisOptions', editableOptions);
    fixture.window_result = windowResult;
    fixture.processing_inputs = struct( ...
        'experimentRoot', 'synthetic_experiment', ...
        'subExperiment', 'synthetic_subexperiment', ...
        'run_id', 'synthetic_run', ...
        'filename', fullfile('fixtures', 'synthetic.bin'), ...
        'resultsDir', fullfile('results', 'synthetic'), ...
        'acquisition_row', table("synthetic_experiment", ...
            "synthetic_run", "in_vivo_eye", ...
            'VariableNames', {'experiment_id', 'run_id', 'sample_type'}));
end

function window = make_window(direction, reverseSpatially, localIndices, ...
        globalIndices, timeIndices, localXAxis, timeAxisS, values)
    window = struct('direction', direction, ...
        'spatial_reversal_required', reverseSpatially, ...
        'local_lateral_indices', localIndices, ...
        'global_lateral_indices', globalIndices, ...
        'time_indices', timeIndices, ...
        'x_axis_mm', localXAxis(localIndices), ...
        'time_axis_s', timeAxisS(timeIndices), ...
        'values', values(globalIndices, timeIndices), ...
        'spatial_interval_count', numel(localIndices)-1, ...
        'spatial_sample_count', numel(localIndices), ...
        'temporal_interval_count', numel(timeIndices)-1, ...
        'temporal_sample_count', numel(timeIndices));
end
