function fixture = create_border_fixture()
%CREATE_BORDER_FIXTURE Build deterministic valid border inputs.

    nDepth = 1000;
    nCols = 120;
    x = 1:nCols;
    topIdx = 120 + round(3 * sin(2 * pi * x / nCols));
    bottomIdx = 320 + round(4 * cos(2 * pi * x / nCols));

    [rowGrid, colGrid] = ndgrid(1:nDepth, 1:nCols);
    Bmode = 1 + 0.01 * (sin(rowGrid / 19) + cos(colGrid / 11));
    for col = 1:nCols
        top = topIdx(col);
        bottom = bottomIdx(col);
        Bmode(top:bottom, col) = Bmode(top:bottom, col) + 5;
        Bmode(top-2:top+2, col) = Bmode(top-2:top+2, col) + 95;
        Bmode(bottom-2:bottom+2, col) = Bmode(bottom-2:bottom+2, col) + 75;
    end

    fixture.Xaxis = 1:nCols;
    fixture.localAxisMm = linspace(0, 6, nCols);
    fixture.Zaxis = (0:nDepth-1)' * 7.1e-3 / 1.4;
    fixture.Bmode = Bmode;
    fixture.geometry = struct( ...
        'lateral_sample_count', nCols, ...
        'samples_per_bmode', nCols, ...
        'bmode_count', 1, ...
        'bmode_scan_width_mm', 6, ...
        'bmode_lateral_axis_mm', fixture.localAxisMm, ...
        'depth_sample_count', nDepth, ...
        'depth_sample_interval_mm', fixture.Zaxis(2) - fixture.Zaxis(1));
    fixture.sample_optics = struct('refractive_index', struct( ...
        'value', 1.4, 'source', "synthetic_fixture"));
    fixture.defaultOptions = struct();
    fixture.explicitPhantomOptions = struct( ...
        'surface_mode', "anterior_posterior", ...
        'top_peak_multiplier', 25, ...
        'bottom_peak_multiplier', 19.5, ...
        'peak_window_size', 50, ...
        'top_index_offset', 4, ...
        'bottom_index_offset', 4, ...
        'max_depth_index', 900, ...
        'max_lateral_jump', 30, ...
        'max_jump_gap', 3, ...
        'smooth_span', 0.08, ...
        'bottom_search_offset', 250, ...
        'background_percentile', 10, ...
        'bottom_median_filter', [1 5], ...
        'thickness_smooth_span', 0.005, ...
        'thickness_smooth_method', 'lowess');
    fixture.explicitAdaptiveOptions = struct( ...
        'adaptive_threshold_k', 0.09, ...
        'adaptive_exclude_bottom_fraction', 1 / 4.5, ...
        'median_filter_size', [3 3], ...
        'vertical_cluster_min_fraction', 1 / 6, ...
        'filloutliers_method', "makima", ...
        'filloutliers_window', 16, ...
        'fit_margin_px', 10, ...
        'fit_extra_margin_top_px', 4, ...
        'fit_type', "poly5", ...
        'bottom_search_offset_px', 139, ...
        'apply_thickness_smoothing', false, ...
        'thickness_smooth_span', 0.005, ...
        'thickness_smooth_method', "lowess");
    fixture.explicitInVivoOptions = struct( ...
        'adaptive_threshold_k', 0.09, ...
        'adaptive_exclude_bottom_fraction', 1 / 4.5, ...
        'median_filter_size', [3 3], ...
        'vertical_projection_smooth_span_px', 25, ...
        'top_search_padding_px', 80, ...
        'min_band_height_px', 80, ...
        'vertical_artifact_enabled', true, ...
        'vertical_artifact_zscore', 3.5, ...
        'vertical_artifact_min_height_fraction', 0.35, ...
        'min_run_length_px', 3, ...
        'max_jump_px', 35, ...
        'fill_method', "makima", ...
        'smooth_method', "rlowess", ...
        'smooth_span_px', 25, ...
        'thickness_range_mm', [0.35 0.75], ...
        'bottom_signal_mode', "last", ...
        'apply_thickness_smoothing', false, ...
        'thickness_smooth_span', 0.005, ...
        'thickness_smooth_method', "lowess");
    fixture.emptyBmode = zeros(size(Bmode));
end
