function phaseIncrement = estimateLoupasPhaseIncrement(complexIQ, axialWindow)
%ESTIMATELOUPASPHASEINCREMENT Estimate temporal phase increments in radians.
%
% complexIQ is [depth, time]. axialWindow is the number of depth samples in
% the Loupas estimator. The output is [depth-axialWindow+1, time-1].
% This preserves the characterized estimator exactly: no unwrap, masking,
% coherence threshold, physical conversion, or time normalization is added.

    currentIQ = complexIQ(:, 1:end-1);
    currentI = real(currentIQ);
    currentQ = imag(currentIQ);
    nextIQ = complexIQ(:, 2:end);
    nextI = real(nextIQ);
    nextQ = imag(nextIQ);

    numeratorTemporal = ...
        currentQ .* nextI - currentI .* nextQ;
    denominatorTemporal = ...
        currentI .* nextI + currentQ .* nextQ;

    numeratorAxial = ...
        (currentQ(1:end-1, :) .* currentI(2:end, :) - ...
        currentI(1:end-1, :) .* currentQ(2:end, :)) + ...
        (nextQ(1:end-1, :) .* nextI(2:end, :) - ...
        nextI(1:end-1, :) .* nextQ(2:end, :));
    denominatorAxial = ...
        (currentI(1:end-1, :) .* currentI(2:end, :) + ...
        currentQ(1:end-1, :) .* currentQ(2:end, :)) + ...
        (nextI(1:end-1, :) .* nextI(2:end, :) + ...
        nextQ(1:end-1, :) .* nextQ(2:end, :));

    temporalWindow = ones(axialWindow, 1);
    summedTemporalNumerator = conv2( ...
        temporalWindow, 1, numeratorTemporal, 'valid');
    summedTemporalDenominator = conv2( ...
        temporalWindow, 1, denominatorTemporal, 'valid');

    axialGradientWindow = ones(axialWindow - 1, 1);
    summedAxialNumerator = conv2( ...
        axialGradientWindow, 1, numeratorAxial, 'valid');
    summedAxialDenominator = conv2( ...
        axialGradientWindow, 1, denominatorAxial, 'valid');

    phaseIncrement = atan2( ...
        summedTemporalNumerator, summedTemporalDenominator) ./ ...
        (1 + atan2(summedAxialNumerator, ...
        summedAxialDenominator) / (2 * pi));
end
