function test_plotting_individual_contract(~)
%TEST_PLOTTING_INDIVIDUAL_CONTRACT Validate individual and preview artifacts.

    fixture = create_plotting_fixture(tempname);
    oldVisibility = get(groot, 'defaultFigureVisible');
    cleanup = onCleanup(@() cleanup_test(fixture.rootDir, oldVisibility));
    set(groot, 'defaultFigureVisible', 'off');

    before = findall(groot, 'Type', 'figure');
    scientificResult = oce.io.loadScientificResult( ...
        fullfile(fixture.phaseDir, 'PhaseSpeed.mat'));
    [polarFigures, renderResult] = oce.plotting.plotPolarPhaseResults( ...
        scientificResult, 'UseTemplate', false);
    created = setdiff(findall(groot, 'Type', 'figure'), before);
    if numel(created) ~= 2 || numel(polarFigures) ~= 2
        error('OCE:PlottingTest:MissingFigure', ...
            'Polar rendering must create thickness and phase-speed figures.');
    end
    renderFiles = dir(fullfile(fixture.phaseDir, 'Polar*.*'));
    if ~isempty(renderFiles)
        error('OCE:PlottingTest:RendererPersistence', ...
            'plotPolarPhaseResults must not persist files.');
    end
    expectedRenderFields = {'mean_thickness_um'; 'std_thickness_um'; ...
        'range_thickness_um'; 'mean_phase_speed_m_per_s'; ...
        'std_phase_speed_m_per_s'; 'range_phase_speed_m_per_s'; ...
        'central_frequency_hz'};
    if ~isequal(fieldnames(renderResult), expectedRenderFields)
        error('OCE:PlottingTest:RenderResultFields', ...
            'Polar renderer result fields changed.');
    end
    close(created);

    [artifacts, result] = oce.plotting.savePolarPhaseResults( ...
        scientificResult, fixture.phaseDir, ...
        'UseTemplate', false, 'CloseFigures', false);
    actualFields = fieldnames(result);
    expectedResultFields = {'generated_artifacts'; ...
        'mean_thickness_um'; 'std_thickness_um'; 'range_thickness_um'; ...
        'mean_phase_speed_m_per_s'; 'std_phase_speed_m_per_s'; ...
        'range_phase_speed_m_per_s'; 'central_frequency_hz'};
    if ~isequal(actualFields, expectedResultFields) || ...
            ~isequal(string(artifacts(:)), string(result.generated_artifacts(:)))
        error('OCE:PlottingTest:ResultFields', ...
            'Polar persistence result contract changed.');
    end
    individualListing = dir(fullfile(fixture.phaseDir, 'Polar*.*'));
    files = sort(reshape(string({individualListing.name}), [], 1));
    expectedIndividualFiles = sort([ ...
        "PolarPhaseSpeed.fig"; "PolarPhaseSpeed.tif"; ...
        "PolarThickness.fig"; "PolarThickness.tif"]);
    if ~isequal(files, expectedIndividualFiles)
        error('OCE:PlottingTest:IndividualFiles', ...
            'Individual plotting artifact inventory changed.');
    end
    if any([individualListing.bytes] <= 0)
        error('OCE:PlottingTest:EmptyFile', ...
            'An individual plotting artifact is empty.');
    end
    close(setdiff(findall(groot, 'Type', 'figure'), before));

    out = fullfile(fixture.rootDir, 'previews'); mkdir(out);
    reconstruction = make_reconstruction_result( ...
        fixture.Bmode, fixture.Xaxis, fixture.Zaxis, ...
        fixture.filterResult.time_axis_s);
    borderResult = struct('intensityMask', fixture.Mask, ...
        'indices', fixture.indices, ...
        'anteriorSurface', fixture.anteriorSurface, ...
        'posteriorSurface', fixture.posteriorSurface);
    previewGeometry = struct( ...
        'bmode_count', 2, ...
        'samples_per_bmode', 4, ...
        'bmode_scan_width_mm', 0.5);
    filterResult = fixture.filterResult;
    filterResult.surface_postprocessed.units = "rad";

    borderFigure = figure('Visible', 'off');
    maskFigure = figure('Visible', 'off');
    graphics = oce.plotting.plotBorderPreview(axes(borderFigure), ...
        axes(maskFigure), reconstruction, borderResult, ...
        fixture.bmode_intensity_limits_db);
    if ~isequal(graphics.anteriorLine.YData(:), ...
            fixture.anteriorSurface(:, 2)) || ...
            ~isequal(graphics.posteriorLine.YData(:), ...
                fixture.posteriorSurface(:, 2))
        error('OCE:PlottingTest:BorderCurves', ...
            'Common border preview does not show anterior and posterior curves.');
    end
    expectedMaskPreview = reconstruction.log_amplitude.values .* fixture.Mask;
    if ~isequal(graphics.maskImage.CData, expectedMaskPreview)
        error('OCE:PlottingTest:MaskPreview', ...
            'Common mask preview does not apply intensityMask.');
    end
    close([borderFigure maskFigure]);
    reconstructionBefore = reconstruction;
    reconstructionFigure = oce.plotting.plotReconstructionPreview( ...
        reconstruction, fixture.bmode_intensity_limits_db);
    reconstructionImage = findobj(reconstructionFigure, 'Type', 'Image');
    if numel(reconstructionImage) ~= 1 || ...
            ~isequal(reconstructionImage.CData, ...
                reconstruction.log_amplitude.values) || ...
            ~isequaln(reconstruction, reconstructionBefore)
        error('OCE:PlottingTest:ReconstructionDisplayIdentity', ...
            ['Final reconstruction preview must display the maintained ' ...
             'reconstruction result without altering it.']);
    end
    close(reconstructionFigure);
    oce.plotting.saveReconstructionPreview(reconstruction, ...
        fixture.bmode_intensity_limits_db, out);
    oce.plotting.saveBorderPreview(reconstruction, borderResult, ...
        fixture.OCT_system, fixture.bmode_intensity_limits_db, out);
    phaseResult = struct('surface', fixture.inputSurfacePhase);
    [filterFigures, filterDetails] = oce.plotting.plotFilterPreviews( ...
        phaseResult, filterResult, reconstruction, previewGeometry);
    if filterDetails.profile_alignment.delay_samples ~= ...
            filterResult.design.delay_samples || ...
            filterDetails.space_time.delay_samples ~= ...
                filterResult.design.delay_samples || ...
            ~isequal(filterDetails.space_time.source_time_indices, ...
                filterResult.design.delay_samples + 1: ...
                numel(filterResult.time_axis_s))
        error('OCE:PlottingTest:VisualDelayCompensation', ...
            'FIR profile and space-time visual delay alignment changed.');
    end
    close(filterFigures);
    oce.plotting.saveFilterPreviews(phaseResult, ...
        filterResult, reconstruction, previewGeometry, out);
    [completeFigure, completeDetails] = oce.plotting.plotCompleteSpaceTime( ...
        phaseResult, filterResult, reconstruction, previewGeometry);
    if completeDetails.source ~= "filtered" || ...
            completeDetails.preview.selection.mode ~= "all" || ...
            completeDetails.preview.delay_samples ~= ...
                filterResult.design.delay_samples
        error('OCE:PlottingTest:FilteredCompleteSpaceTime', ...
            'Complete space-time did not select the applied filtered source.');
    end
    close(completeFigure);
    disabledFilter = filterResult;
    disabledFilter.applied = false;
    disabledFilter.design.applied = false;
    [completeFigure, completeDetails] = oce.plotting.plotCompleteSpaceTime( ...
        phaseResult, disabledFilter, reconstruction, previewGeometry);
    if completeDetails.source ~= "phase" || ...
            completeDetails.preview.delay_samples ~= 0
        error('OCE:PlottingTest:UnfilteredCompleteSpaceTime', ...
            'Disabled filtering must fall back to unfiltered phase data.');
    end
    close(completeFigure);
    oce.plotting.saveCompleteSpaceTime(phaseResult, [], ...
        reconstruction, previewGeometry, out);
    assert_filter_passthrough_preview(fixture, previewGeometry);
    analysisFixture = create_dispersion_analysis_fixture();
    analysis = oce.dispersion.analyzeWindows( ...
        analysisFixture.window_result, analysisFixture.DistBorder, ...
        analysisFixture.DispersionAnalysisOptions);
    assert_dispersion_diagnostics(analysis, context_repo_root());
    oce.plotting.saveSpeedDispersionPreview(analysis, 1, out);
    details = dir(out); details = details(~[details.isdir]);
    previewFiles = sort(reshape(string({details.name}), [], 1));
    expectedPreviewFiles = sort([ ...
        "ReconstructionPreview.fig"; "ReconstructionPreview.tif"; ...
        "BorderPreview_pixels.fig"; "BorderPreview_pixels.tif"; ...
        "BorderMaskPreview.fig"; "BorderMaskPreview.tif"; ...
        "TemporalFilterSpectrum.fig"; "TemporalFilterSpectrum.tif"; ...
        "TemporalFilterTimeProfile.fig"; "TemporalFilterTimeProfile.tif"; ...
        "FilteredSpaceTime.fig"; "FilteredSpaceTime.tif"; ...
        "CompleteSpaceTime.fig"; "CompleteSpaceTime.tif"; ...
        "SpeedDispersion_scanAxis01_0.0deg.fig"; ...
        "SpeedDispersion_scanAxis01_0.0deg.tif"]);
    if ~isequal(previewFiles, expectedPreviewFiles)
        error('OCE:PlottingTest:PreviewFiles', ...
            'Preview artifact inventory changed.');
    end
    if any([details.bytes] <= 0)
        error('OCE:PlottingTest:EmptyFile', 'A preview output is empty.');
    end
    beforeClose = findall(groot, 'Type', 'figure');
    marker = figure('Visible', 'off');
    oce.plotting.closeGeneratedFigures(beforeClose, true);
    if isvalid(marker)
        error('OCE:PlottingTest:Lifecycle', ...
            'Generated figure was not closed.');
    end
    clear cleanup
end

function assert_dispersion_diagnostics(analysis, repoRoot)
    windowFixture = create_dispersion_windows_fixture();
    config = windowFixture.cases.maxRmsPhaseIncrement;
    windowResult = oce.dispersion.buildWindows(config, ...
        windowFixture.filter_result, windowFixture.x_axis_mm, ...
        windowFixture.resolved_filter, windowFixture.geometry);
    windowBefore = windowResult;
    filterBefore = windowFixture.filter_result;
    [contextFigure, contextDetails] = ...
        oce.plotting.plotDispersionWindowContext(windowResult, ...
            windowFixture.filter_result, windowFixture.x_axis_mm, 1);
    expectedRange = windowResult.bmodes(1).global_lateral_range(1): ...
        windowResult.bmodes(1).global_lateral_range(2);
    delay = windowFixture.filter_result.design.delay_samples;
    expectedMap = windowFixture.filter_result.surface_postprocessed.values( ...
        expectedRange, delay + 1:end);
    left = windowResult.bmodes(1).left;
    expectedLeftTime = left.time_axis_s(1) * 1e3;
    leftLabelText = join(string(contextDetails.left_label.String(:)), " ");
    rightLabelText = join(string(contextDetails.right_label.String(:)), " ");
    if ~isequaln(contextDetails.center_metadata, ...
            windowResult.bmodes(1).center) || ...
            ~isequaln(contextDetails.image.CData, expectedMap') || ...
            string(contextDetails.axes.YDir) ~= "reverse" || ...
            contextDetails.center_line.Value ~= ...
                windowResult.bmodes(1).center.x_coordinate_mm || ...
            ~isequal(contextDetails.left_rectangle.EdgeColor, [1 1 1]) || ...
            ~isequal(contextDetails.right_rectangle.EdgeColor, [1 1 1]) || ...
            string(contextDetails.left_rectangle.LineStyle) ~= ":" || ...
            string(contextDetails.right_rectangle.LineStyle) ~= ":" || ...
            ~isequal(contextDetails.center_line.Color, [1 1 1]) || ...
            contextDetails.visual_delay_samples ~= delay || ...
            contextDetails.left_rectangle.Position(2) ~= expectedLeftTime || ...
            ~contains(leftLabelText, "x: 1:10") || ...
            ~contains(leftLabelText, "t: 10:60") || ...
            ~contains(rightLabelText, "x: 12:21") || ...
            ~contains(rightLabelText, "t: 10:60") || ...
            isfield(contextDetails, 'information_box') || ...
            ~isequaln(windowResult, windowBefore) || ...
            ~isequaln(windowFixture.filter_result, filterBefore)
        error('OCE:PlottingTest:DispersionWindowContext', ...
            ['Window context must apply display-only FIR alignment and use ' ...
             'clean metadata-derived ROI overlays without recomputation.']);
    end
    close(contextFigure);

    unfiltered = windowFixture.filter_result;
    unfiltered.applied = false;
    unfiltered.design.applied = false;
    [unfilteredFigure, unfilteredDetails] = ...
        oce.plotting.plotDispersionWindowContext(windowResult, unfiltered, ...
            windowFixture.x_axis_mm, 1);
    expectedUnfiltered = unfiltered.surface_postprocessed.values( ...
        expectedRange, :);
    if unfilteredDetails.visual_delay_samples ~= 0 || ...
            ~isequaln(unfilteredDetails.image.CData, expectedUnfiltered')
        error('OCE:PlottingTest:DispersionWindowContextPassthrough', ...
            'An unapplied filter must not invent visual delay compensation.');
    end
    close(unfilteredFigure);

    analysisBefore = analysis;
    [kfFigure, kfDetails] = oce.plotting.plotDispersionKfPreview(analysis, 1);
    if kfDetails.source ~= "analysis.directions.spectrum_and_ridge" || ...
            ~isequal(kfDetails.ridge_lines(1).YData(:), ...
                analysis.directions(1).ridge.wavenumber_per_m(:)) || ...
            ~isequaln(analysis, analysisBefore)
        error('OCE:PlottingTest:DispersionKfReuse', ...
            'k-f preview must reuse preserved spectrum and ridge outputs.');
    end
    close(kfFigure);

    assert(isempty(oce.plotting.plotPhaseGradientPreview(analysis, 1)));
    gradient = struct('status', "valid", 'phase_speed_m_per_s', 2, ...
        'r_squared', 0.98, 'phase_rmse_rad', 0.02, ...
        'diagnostic', struct('x_axis_mm', [-1; 0; 1], ...
            'unwrapped_phase_rad', [0; 0.1; 0.3], 'fitted_phase_rad', [-0.02; 0.14; 0.28]));
    analysis.phase_gradient.enabled = true;
    analysis.phase_gradient.target_frequency_hz = 1000;
    analysis.phase_gradient.directions = [gradient; gradient];
    analysis.phase_gradient.directions(2).status = "nonfinite_signal";
    analysis.phase_gradient.directions(2).phase_speed_m_per_s = NaN;
    analysis.phase_gradient.directions(2).r_squared = NaN;
    analysis.phase_gradient.directions(2).phase_rmse_rad = NaN;
    analysis.phase_gradient.directions(2).diagnostic.unwrapped_phase_rad = [];
    analysis.phase_gradient.directions(2).diagnostic.fitted_phase_rad = [];
    analysisBefore = analysis;
    [gradientFigure, graphics] = oce.plotting.plotPhaseGradientPreview(analysis, 1);
    assert(isequal(graphics.phase_lines(1).XData(:), gradient.diagnostic.x_axis_mm));
    assert(isequal(graphics.phase_lines(1).YData(:), gradient.diagnostic.unwrapped_phase_rad));
    assert(isequal(graphics.fit_lines(1).YData(:), gradient.diagnostic.fitted_phase_rad));
    assert(~isgraphics(graphics.phase_lines(2)) && ...
        contains(join(string(graphics.axes(2).Title.String)), "nonfinite_signal"));
    assert(isequaln(analysis, analysisBefore));
    close(gradientFigure);
    kfSource = fileread(fullfile(repoRoot, 'src', '+oce', '+plotting', ...
        'plotDispersionKfPreview.m'));
    if contains(kfSource, 'fft2(') || ...
            contains(kfSource, 'computeDispersionSpectrum')
        error('OCE:PlottingTest:DispersionKfRecomputation', ...
            'k-f plotting must not recompute the scientific spectrum.');
    end

    yLimitAnalysis = analysis;
    yLimitAnalysis.directions(1).phase_speed_curve. ...
        smoothed_phase_speed_m_per_s(1) = Inf;
    yLimitAnalysis.directions(1).phase_speed_curve. ...
        smoothed_phase_speed_m_per_s(2) = NaN;
    yLimitAnalysis.directions(1).phase_speed_curve. ...
        smoothed_phase_speed_m_per_s(3) = 1e6;
    yLimitAnalysis.directions(1).target_selection. ...
        selected_phase_speed_m_per_s = 18;
    yLimit = oce.plotting.resolveSpeedPreviewYLimit(yLimitAnalysis, 1);
    if yLimit(1) ~= 0 || yLimit(2) < 20 || yLimit(2) < 1.1 * 18 || ...
            yLimit(2) >= 1e5
        error('OCE:PlottingTest:SpeedPreviewYLimit', ...
            ['Speed preview limit must include the target, retain the ' ...
             '20 m/s floor, and resist non-finite/localized outliers.']);
    end
end

function repoRoot = context_repo_root()
    testFolder = fileparts(mfilename('fullpath'));
    repoRoot = fileparts(fileparts(testFolder));
end

function assert_filter_passthrough_preview(fixture, previewGeometry)
    disabledRoot = fullfile(fixture.rootDir, 'disabled_filter_preview');
    mkdir(disabledRoot);
    disabled = fixture.filterResult;
    disabled.applied = false;
    disabled.design.applied = false;
    disabled.design.coefficients = [];
    disabled.design.delay_samples = 0;
    disabled.surface.values = fixture.inputSurfacePhase.values;
    disabled.surface_postprocessed.units = "rad";
    before = findall(groot, 'Type', 'figure');
    reconstruction = make_reconstruction_result( ...
        fixture.Bmode, fixture.Xaxis, fixture.Zaxis, ...
        fixture.filterResult.time_axis_s);
    phaseResult = struct('surface', fixture.inputSurfacePhase);
    oce.plotting.saveFilterPreviews( ...
        phaseResult, disabled, reconstruction, previewGeometry, disabledRoot);
    created = setdiff(findall(groot, 'Type', 'figure'), before);
    legends = findall(created, 'Type', 'Legend');
    labels = strings(0, 1);
    for index = 1:numel(legends)
        labels = [labels; string(legends(index).String(:))]; %#ok<AGROW>
    end
    if ~any(contains(lower(labels), "passthrough"))
        error('OCE:PlottingTest:MissingPassthroughLabel', ...
            'Disabled filtering preview must identify passthrough explicitly.');
    end
    close(created);
end

function cleanup_test(rootDir, oldVisibility)
    close all force; set(groot, 'defaultFigureVisible', oldVisibility);
    if isfolder(rootDir), rmdir(rootDir, 's'); end
end
