function test_pipeline_batch_contract(~)
%TEST_PIPELINE_BATCH_CONTRACT Verify canonical single-run delegation/status.

    fixture = create_pipeline_fixture();
    output = oce.pipeline.runBatchProcessing( ...
        fixture.io.root, fixture.io.subExperiment, ...
        ["R2"; "R_FAIL"; "R1"], ...
        'SingleRunFunction', @single_stub, 'StopOnError', false, ...
        'RunOptions', struct('stop_after', 'scientific_result'), ...
        'OutputOptions', no_outputs());
    if ~isequal(output.acquisition_keys, ["R2"; "R_FAIL"; "R1"]) || ...
            ~isequal(string({output.results.status})', ...
                ["completed"; "failed"; "completed"]) || ...
            output.results(2).error_identifier ~= ...
                "OCE:Pipeline:StubFailure" || ...
            ~isequal(string(output.summary.Properties.VariableNames), ...
                ["run_id", "completed_through", "status", ...
                 "scientific_result_path", "generated_artifacts", ...
                 "error_identifier"])
        error('OCE:PipelineTest:BatchContract', ...
            'Batch status or summary contract is invalid.');
    end
    assert_identifier('OCE:Pipeline:StubFailure', @() ...
        oce.pipeline.runBatchProcessing(fixture.io.root, ...
        fixture.io.subExperiment, ["R_FAIL"; "R1"], ...
        'SingleRunFunction', @single_stub, 'StopOnError', true));
    assert_identifier('OCE:Pipeline:DuplicateAcquisitionKey', @() ...
        oce.pipeline.runBatchProcessing(fixture.io.root, ...
        fixture.io.subExperiment, ["R1"; "R1"], ...
        'SingleRunFunction', @single_stub));
    if output.results(1).mean_phase_speed_m_per_s ~= 1 || ...
            output.results(1).mean_thickness_um ~= 4 || ...
            output.results(1).completed_through ~= "scientific_result"
        error('OCE:PipelineTest:BatchMetrics', ...
            'Batch did not project structured scientific statistics.');
    end
    clear fixture
end

function output = single_stub(root, ~, key, varargin)
    if string(key) == "R_FAIL"
        error('OCE:Pipeline:StubFailure', 'Intentional stub failure.');
    end
    statistics = struct( ...
        'phase_speed', struct('mean_m_per_s', 1, ...
            'standard_deviation_m_per_s', 2, 'range_m_per_s', 3), ...
        'thickness', struct('mean_um', 4, ...
            'standard_deviation_um', 5, 'range_um', 6));
    pipelineResult = struct( ...
        'status', struct( ...
            'completed_through', "scientific_result", ...
            'available_products', "scientific_result", ...
            'scientific_result_available', true, ...
            'persisted', false, ...
            'generated_artifacts', strings(0, 1)), ...
        'outputs', struct('scientific_result', ...
            struct('statistics', statistics)));
    output = struct( ...
        'pipeline_result', pipelineResult, ...
        'resolved_output', struct('result_directory', ...
            string(fullfile(root, 'Results', key))), ...
        'polar_results', struct());
end

function options = no_outputs()
    options = struct( ...
        'save_scientific_result', false, ...
        'save_reconstruction_preview', false, ...
        'save_border_preview', false, ...
        'save_filter_preview', false, ...
        'save_dispersion_plots', false, ...
        'save_polar_plots', false, ...
        'close_figures', true);
end

function assert_identifier(expected, callback)
    try
        callback();
    catch ME
        if string(ME.identifier) == string(expected)
            return;
        end
        error('OCE:PipelineTest:WrongIdentifier', ...
            'Expected %s, actual %s.', expected, ME.identifier);
    end
    error('OCE:PipelineTest:MissingError', ...
        'Expected error %s was not raised.', expected);
end
