function test_pipeline_summary_contract(~)
%TEST_PIPELINE_SUMMARY_CONTRACT Validate canonical summary coordination.

    fixture = create_pipeline_fixture();
    resultFixture = fixture.results;
    before = pwd;
    [experiment, T] = oce.pipeline.runSubexperimentSummary( ...
        resultFixture.experimentRoot, resultFixture.subExperiment, ...
        'RootDir', resultFixture.summaryRoot, 'RunPlots', false, ...
        'ExportTable', true, 'SaveSummary', false);
    if ~strcmp(before, pwd) || ...
            ~isstruct(experiment) || ...
            ~isfield(experiment, 'result_schema') || ...
            experiment.result_schema ~= "oce_phase_speed_result" || ...
            ~istable(T)
        error('OCE:PipelineTest:SummaryContract', ...
            'Canonical structured-result summary coordination failed.');
    end

    expectedFrequency = ["3500"; "2500"; "4500"];
    expectedPhaseSpeed = [3; 6.5; 6];
    expectedRepetitionCount = [1; 3; 2];
    requiredColumns = ["frequency_Hz"; "phase_speed_mean_mps"; ...
        "phase_speed_n"];
    if height(T) ~= 3 || ...
            any(~ismember(requiredColumns, string(T.Properties.VariableNames))) || ...
            ~isequal(string(T.frequency_Hz), expectedFrequency) || ...
            ~isequal(T.phase_speed_mean_mps, expectedPhaseSpeed) || ...
            ~isequal(T.phase_speed_n, expectedRepetitionCount)
        error('OCE:PipelineTest:SummaryValues', ...
            ['Pipeline summary did not preserve the fixture statistics. ' ...
             'Expected frequencies=%s, phase speed=%s, n=%s.'], ...
            strjoin(expectedFrequency, ', '), ...
            mat2str(expectedPhaseSpeed'), ...
            mat2str(expectedRepetitionCount'));
    end

    angleMeans = experiment.summary.angle_mean_data;
    actualMeans = cellfun(@(value) ...
        value.angular_phase_speed_m_per_s, angleMeans(:));
    if ~isequal(actualMeans, expectedPhaseSpeed)
        error('OCE:PipelineTest:SummaryValues', ...
            ['Pipeline experiment summary and exported table disagree with ' ...
             'the known synthetic phase-speed means.']);
    end
    clear fixture
end
