function options = getDefaultBorderOptions(profile)
%GETDEFAULTBORDEROPTIONS Build editable border-detection defaults.

    options = struct();
    options.selection = "automatic";
    options.method = "";
    options.mask_threshold = 90;
    options.lateral_edge_exclusion = struct( ...
        'enabled', false, ...
        'fraction_per_side', 0.02);

    options.corneal_preprocessing = struct( ...
        'adaptive_threshold_k', 0.09, ...
        'adaptive_exclude_bottom_fraction', 1 / 4.5, ...
        'median_filter_size', [3 3]);

    options.methods = struct();
    options.methods.phantom = struct( ...
        'surface_mode', "anterior_posterior", ...
        'top_peak_multiplier', 25, ...
        'bottom_peak_multiplier', 19.5, ...
        'peak_window_size', 50, ...
        'top_search_offset', 0, ...
        'top_index_offset', 2, ...
        'bottom_index_offset', 0, ...
        'max_depth_index', [], ...
        'max_lateral_jump', 30, ...
        'max_jump_gap', 3, ...
        'smooth_span', 0.08, ...
        'bottom_search_offset', 250, ...
        'background_percentile', 10, ...
        'bottom_median_filter', [1 5], ...
        'thickness_smooth_span', 0.005, ...
        'thickness_smooth_method', 'lowess');
    options.methods.adaptive_corneal = struct( ...
        'vertical_cluster_min_fraction', 1 / 6, ...
        'filloutliers_method', "makima", ...
        'filloutliers_window', 16, ...
        'fit_margin_px', 10, ...
        'fit_extra_margin_top_px', 4, ...
        'fit_type', "poly5", ...
        'bottom_search_offset_px', 139, ...
        'apply_thickness_smoothing', false, ...
        'thickness_smooth_span', 0.005, ...
        'thickness_smooth_method', "lowess");
    options.methods.in_vivo_corneal = struct( ...
        'vertical_projection_smooth_span_px', 25, ...
        'top_search_padding_px', 45, ...
        'min_band_height_px', 80, ...
        'vertical_artifact_enabled', true, ...
        'vertical_artifact_zscore', 3.0, ...
        'vertical_artifact_min_height_fraction', 0.30, ...
        'min_run_length_px', 5, ...
        'max_jump_px', 30, ...
        'fill_method', "makima", ...
        'smooth_method', "rlowess", ...
        'smooth_span_px', 21, ...
        'thickness_range_mm', [0.50 0.80], ...
        'bottom_signal_mode', "last", ...
        'apply_thickness_smoothing', false, ...
        'thickness_smooth_span', 0.005, ...
        'thickness_smooth_method', "lowess");

    if profile == "in_vivo_eye"
        options.corneal_preprocessing.adaptive_threshold_k = 0.12;
    end
end
