function options = getDefaultMotionOptions()
%GETDEFAULTMOTIONOPTIONS Build editable phase-estimation defaults.

    options = struct();
    options.depth_resolved = struct( ...
        'quantity', "phase_increment", ...
        'estimator', "unwrap_then_difference", ...
        'loupas', struct('axial_window_samples', []), ...
        'smoothing', struct( ...
            'method', "lowess", ...
            'span_fraction', 0.05));
    options.surface = struct( ...
        'quantity', "phase_increment", ...
        'estimator', "loupas", ...
        'surface_reference', "anterior", ...
        'depth_offset_samples', 0, ...
        'aggregation_band_samples', 6, ...
        'loupas', struct('axial_window_samples', 20), ...
        'smoothing', struct( ...
            'method', "lowess", ...
            'span_fraction', 0.05));
    options.show_progress = false;
end
