function options = getDefaultDispersionAnalysisOptions()
%GETDEFAULTDISPERSIONANALYSISOPTIONS Build editable dispersion-analysis defaults.

    options = struct();
    options.method = "windowed_fft_ridge";
    options.phase_gradient = struct('enabled', false);
    options.spectrum = struct( ...
        'fft', struct( ...
            'time_bin_count', (2^13) + 1, ...
            'spatial_bin_count', (2^13) + 1), ...
        'crop', struct( ...
            'maximum_frequency_hz', 8000, ...
            'maximum_wavenumber_per_m', 1 / (0.3e-3)), ...
        'window', struct( ...
            'time', struct( ...
                'enabled', false, ...
                'method', "hann_symmetric"), ...
            'space', struct( ...
                'enabled', false, ...
                'method', "hann_symmetric")));
    options.ridge = struct( ...
        'maximum_wavenumber_jump_per_m', 40, ...
        'minimum_relative_magnitude', 0.01, ...
        'interpolation', struct( ...
            'method', "linear", ...
            'extrapolate', true));
    options.phase_speed = struct( ...
        'smoothing', struct( ...
            'method', "lowess", ...
            'span_fraction', 0.1));
    options.target_frequency = struct( ...
        'source', "resolved_filter_center");
end
