function resolution = toEnd(~, ~, sampleIntervalS, ...
        requestedIntervalCount, availableIntervalCount)
%TOEND Resolve a temporal window from its start to the crop end.

    intervalCount = min(requestedIntervalCount, availableIntervalCount);
    resolution = struct( ...
        'method', "to_end", ...
        'interval_count', intervalCount, ...
        'sample_count', intervalCount + 1, ...
        'requested_duration_s', requestedIntervalCount * sampleIntervalS, ...
        'effective_duration_s', intervalCount * sampleIntervalS, ...
        'requested_cycle_count', [], ...
        'represented_cycle_count', []);
end
