function test_parameter_preparation_chain_contract(context)
%TEST_PARAMETER_PREPARATION_CHAIN_CONTRACT Verify explicit preparation ownership.

    root = context.repoRoot;
    functions = [ ...
        "src/+oce/+io/loadExperimentalLog.m"; ...
        "src/+oce/+io/readAcquisitionHeader.m"; ...
        "src/+oce/+acquisition/prepareAcquisitionParameters.m"; ...
        "src/+oce/+config/getDefaultProcessingConfig.m"; ...
        "src/+oce/+config/saveProcessingConfig.m"; ...
        "src/+oce/+io/loadSubexperimentParameters.m"; ...
        "src/+oce/+acquisition/getAcquisitionRow.m"; ...
        "src/+oce/+acquisition/prepareProcessingInputs.m"; ...
        "src/+oce/+config/buildProcessingConfigForAcquisition.m"; ...
        "src/+oce/+config/resolveAcquisitionOptions.m"; ...
        "src/+oce/+config/resolveBorderOptions.m"; ...
        "src/+oce/+acquisition/validateAcquisitionFiles.m"; ...
        "src/+oce/+pipeline/prepareAcquisitionRun.m"; ...
        "src/+oce/+config/validateProcessingConfig.m"; ...
        "src/+oce/+config/private/applyProcessingConfigOverrides.m"];
    for idx = 1:numel(functions)
        if ~isfile(fullfile(root, replace(functions(idx), '/', filesep)))
            error('OCE:ParameterChain:MissingOwner', ...
                'Preparation owner is missing: %s.', functions(idx));
        end
    end

    assert_contains(functions(1), ...
        ["AcquisitionParams_", "acquisition_table"], root);
    assert_contains(functions(3), ...
        ["Params_", "acquisition_parameters"], root);
    assert_contains(functions(5), ...
        ["ProcessingConfig_", "processing_config"], root);

    inputPreparation = read_source(root, functions(8));
    inputCalls = [ ...
        "oce.io.loadSubexperimentParameters"; ...
        "oce.acquisition.getAcquisitionRow"; ...
        "oce.io.readAcquisitionHeader"];
    assert_call_order(inputPreparation, inputCalls, ...
        'OCE:ParameterChain:InputOrder', ...
        'Processing-input preparation order is not explicit.');
    if contains(inputPreparation, 'mkdir(')
        error('OCE:ParameterChain:UnexpectedOutputWrite', ...
            'prepareProcessingInputs must resolve resultsDir without creating it.');
    end

    preparation = read_source(root, functions(13));
    calls = [ ...
        "oce.acquisition.prepareProcessingInputs"; ...
        "oce.config.buildProcessingConfigForAcquisition"; ...
        "oce.acquisition.validateAcquisitionFiles"];
    assert_call_order(preparation, calls, 'OCE:ParameterChain:Order', ...
        'Per-acquisition preparation order is not explicit.');

    builder = read_source(root, functions(9));
    requiredInputs = ["processing_config", "acquisition_row", ...
        "acquisition_header", "acquisition_parameters", ...
        "oce.config.validateProcessingConfig", ...
        "processingConfig.OCTSystemOptions", ...
        "processingConfig.SampleOpticalOptions"];
    for idx = 1:numel(requiredInputs)
        if ~contains(builder, requiredInputs(idx))
            error('OCE:ParameterChain:ResolutionInput', ...
                'Run-config resolution is missing %s.', requiredInputs(idx));
        end
    end
    forbiddenCompatibility = ["validateRunProcessingConfig"; ...
        "optional_legacy_optics"; "remove_legacy_refractive_index"];
    if any(contains(builder, forbiddenCompatibility))
        error('OCE:ParameterChain:RunCompatibilityBoundary', ...
            'Run configuration must not retain compatibility adapters.');
    end
    if contains(builder, 'save(')
        error('OCE:ParameterChain:UnexpectedPersistence', ...
            'Per-acquisition resolution must not persist data.');
    end
    assert_call_order(builder, [ ...
        "applyProcessingConfigOverrides"; ...
        "oce.config.resolveAcquisitionOptions"; ...
        "oce.config.resolveBorderOptions"], ...
        'OCE:ParameterChain:BorderResolutionOrder', ...
        'Border options must resolve after per-acquisition overrides.');

    overrideOwner = read_source(root, functions(15));
    overrideTokens = ["processingConfig.per_acquisition"; ...
        "run_id"; "filename"; "merge_struct"];
    for idx = 1:numel(overrideTokens)
        if ~contains(overrideOwner, overrideTokens(idx))
            error('OCE:ParameterChain:OverrideOwnership', ...
                'Override owner is missing %s.', overrideTokens(idx));
        end
    end

    detected = false;
    try
        altered = calls([2 1 3]);
        if ~isequal(calls, altered)
            error('OCE:ParameterChain:Order', 'Injected order difference.');
        end
    catch ME
        detected = strcmp(ME.identifier, 'OCE:ParameterChain:Order');
    end
    if ~detected
        error('OCE:ParameterChain:NegativeControl', ...
            'Preparation-order negative control was not detected.');
    end

    catalog = fileread(fullfile(root, 'tests', 'runners', 'private', ...
        'repository_test_catalog.m'));
    assert_runner_registration(catalog, ...
        'test_parameter_preparation_chain_contract');
    assert_runner_registration(catalog, ...
        'test_maintained_terminology_contract');
end

function assert_call_order(source, calls, identifier, message)
    positions = arrayfun(@(name) strfind(source, name), calls, ...
        'UniformOutput', false);
    if any(cellfun(@isempty, positions))
        error('OCE:ParameterChain:MissingCall', ...
            'Preparation owner does not expose every required call.');
    end
    firstPositions = cellfun(@(item) item(1), positions);
    if any(diff(firstPositions) <= 0)
        error(identifier, message);
    end
end

function assert_runner_registration(catalog, testName)
    token = "@" + string(testName);
    if count(catalog, token) ~= 1
        error('OCE:ParameterChain:RunnerRegistration', ...
            'Expected one canonical catalog registration for %s.', testName);
    end
end

function assert_contains(relativePath, tokens, root)
    source = read_source(root, relativePath);
    for idx = 1:numel(tokens)
        if ~contains(source, tokens(idx))
            error('OCE:ParameterChain:PersistedContract', ...
                '%s does not preserve token %s.', relativePath, tokens(idx));
        end
    end
end

function source = read_source(root, relativePath)
    source = fileread(fullfile(root, replace(relativePath, '/', filesep)));
end
