function test_dispersion_windows_resolution(context)
%TEST_DISPERSION_WINDOWS_RESOLUTION Verify canonical strategy ownership.

    canonical = {
        'oce.config.resolveDispersionWindowOptions', 'src/+oce/+config/resolveDispersionWindowOptions.m';
        'oce.dispersion.buildWindows', 'src/+oce/+dispersion/buildWindows.m';
        'oce.dispersion.resolveCenterMethod', 'src/+oce/+dispersion/resolveCenterMethod.m';
        'oce.dispersion.centers.middle', 'src/+oce/+dispersion/+centers/middle.m';
        'oce.dispersion.centers.manualLocalIndex', 'src/+oce/+dispersion/+centers/manualLocalIndex.m';
        'oce.dispersion.centers.maxRmsPhaseIncrement', 'src/+oce/+dispersion/+centers/maxRmsPhaseIncrement.m';
        'oce.dispersion.centers.maxMirroredCorrelation', 'src/+oce/+dispersion/+centers/maxMirroredCorrelation.m';
        'oce.dispersion.resolveSpatialExtentMethod', 'src/+oce/+dispersion/resolveSpatialExtentMethod.m';
        'oce.dispersion.spatialextents.fractionOfBmode', 'src/+oce/+dispersion/+spatialextents/fractionOfBmode.m';
        'oce.dispersion.spatialextents.manualIntervalCount', 'src/+oce/+dispersion/+spatialextents/manualIntervalCount.m';
        'oce.dispersion.resolveWindowDurationMethod', 'src/+oce/+dispersion/resolveWindowDurationMethod.m';
        'oce.dispersion.windowdurations.manualIntervalCount', 'src/+oce/+dispersion/+windowdurations/manualIntervalCount.m';
        'oce.dispersion.windowdurations.cycleCount', 'src/+oce/+dispersion/+windowdurations/cycleCount.m';
        'oce.dispersion.windowdurations.toEnd', 'src/+oce/+dispersion/+windowdurations/toEnd.m'};
    assert_unique_locations(canonical, context.repoRoot);
    assert_resolver(@oce.dispersion.resolveCenterMethod, ...
        ["middle", "manual_local_index", "max_rms_phase_increment", ...
         "max_mirrored_correlation"], ...
        ["oce.dispersion.centers.middle", ...
         "oce.dispersion.centers.manualLocalIndex", ...
         "oce.dispersion.centers.maxRmsPhaseIncrement", ...
         "oce.dispersion.centers.maxMirroredCorrelation"]);
    assert_resolver(@oce.dispersion.resolveSpatialExtentMethod, ...
        ["fraction_of_bmode", "manual_interval_count"], ...
        ["oce.dispersion.spatialextents.fractionOfBmode", ...
         "oce.dispersion.spatialextents.manualIntervalCount"]);
    assert_resolver(@oce.dispersion.resolveWindowDurationMethod, ...
        ["manual_interval_count", "cycle_count", "to_end"], ...
        ["oce.dispersion.windowdurations.manualIntervalCount", ...
         "oce.dispersion.windowdurations.cycleCount", ...
         "oce.dispersion.windowdurations.toEnd"]);

    defaultConfig = oce.config.getDefaultProcessingConfig("phantom");
    if string(defaultConfig.DispersionWindowOptions.temporal.method) ~= "cycle_count" || ...
            defaultConfig.DispersionWindowOptions.temporal.cycle_count ~= 3
        error('OCE:DispersionWindows:DefaultDuration', ...
            'Canonical temporal default must be cycle_count=3.');
    end

    retiredSpatialOwner = "oce.dispersion.spatialextents.fractionOf" + ...
        "Meridian";
    retiredLegacyDurationOwner = ...
        "oce.dispersion.windowdurations." + "legacyFrequencyRule";
    assert_absent(["oce.dispersion.centers.manual", ...
        "oce.dispersion.centers.maxMotion", ...
        "oce.dispersion.centers.maxSymmetry", ...
        "oce.dispersion.resolveWindowWidthMethod", ...
        "oce.dispersion.windowwidths.fractionOfBscan", ...
        "oce.dispersion.windowwidths.manual", ...
        "oce.dispersion.windowdurations.manual", ...
        "oce.dispersion.windowdurations.cycles", ...
        retiredSpatialOwner, retiredLegacyDurationOwner]);
    assert_identifier(@() oce.dispersion.resolveCenterMethod("manual"), ...
        'OCE:DispersionWindows:UnsupportedCenterMethod');
    assert_identifier(@() oce.dispersion.resolveSpatialExtentMethod( ...
        "fraction_of_bscan"), ...
        'OCE:DispersionWindows:UnsupportedSpatialExtentMethod');
    retiredSpatialMethod = "fraction_of_" + "meridian";
    assert_identifier(@() oce.dispersion.resolveSpatialExtentMethod( ...
        retiredSpatialMethod), ...
        'OCE:DispersionWindows:UnsupportedSpatialExtentMethod');
    retiredLegacyMethod = "legacy_" + "frequency_rule";
    assert_identifier(@() oce.dispersion.resolveWindowDurationMethod( ...
        retiredLegacyMethod), ...
        'OCE:DispersionWindows:UnsupportedDurationMethod');
    invalidOptions = defaultConfig.DispersionWindowOptions;
    invalidOptions.temporal.method = retiredLegacyMethod;
    assert_identifier(@() oce.config.resolveDispersionWindowOptions( ...
        invalidOptions), 'OCE:Config:InvalidDispersionWindowOptions');
    assert_resolution_boundary(context.repoRoot);
end

function assert_resolution_boundary(repoRoot)
    configBuilder = fileread(fullfile(repoRoot, 'src', '+oce', '+config', ...
        'buildProcessingConfigForAcquisition.m'));
    windowBuilder = fileread(fullfile(repoRoot, 'src', '+oce', ...
        '+dispersion', 'buildWindows.m'));
    if count(configBuilder, 'oce.config.resolveDispersionWindowOptions') ~= 1
        error('OCE:DispersionWindows:ResolutionOwnership', ...
            ['buildProcessingConfigForAcquisition must resolve ' ...
             'DispersionWindowOptions exactly once.']);
    end
    if contains(windowBuilder, 'oce.config.resolveDispersionWindowOptions')
        error('OCE:DispersionWindows:ResolutionOwnership', ...
            'buildWindows must consume already-resolved DispersionWindowOptions.');
    end
end

function assert_resolver(resolver, names, expected)
    for index = 1:numel(names)
        actual = string(func2str(resolver(upper(names(index)))));
        if actual ~= expected(index)
            error('OCE:DispersionWindows:Resolver', ...
                '%s resolved to %s instead of %s.', ...
                names(index), actual, expected(index));
        end
    end
end

function assert_unique_locations(expected, repoRoot)
    for index = 1:size(expected, 1)
        locations = string(which(expected{index, 1}, '-all'));
        locations = locations(strlength(locations) > 0);
        target = fullfile(repoRoot, expected{index, 2});
        if numel(locations) ~= 1 || ...
                ~strcmpi(normalize(locations), normalize(target))
            error('OCE:DispersionWindows:Resolution', ...
                'Unexpected resolution for %s.', expected{index, 1});
        end
    end
end

function assert_absent(names)
    for index = 1:numel(names)
        if ~isempty(which(char(names(index)), '-all'))
            error('OCE:DispersionWindows:RetiredName', ...
                'Retired function still resolves: %s.', names(index));
        end
    end
end

function assert_identifier(callback, identifier)
    try
        callback();
    catch ME
        if strcmp(ME.identifier, identifier), return; end
    end
    error('OCE:DispersionWindows:ExpectedError', ...
        'Expected error %s.', identifier);
end

function value = normalize(value)
    value = replace(string(value), ["/", "\\"], filesep);
end
