function test_filtering_domain_resolution(context)
%TEST_FILTERING_DOMAIN_RESOLUTION Verify filtering ownership and caller use.

    canonical = {
        'oce.filtering.filterPhaseResults', ...
            'src/+oce/+filtering/filterPhaseResults.m';
        'oce.filtering.filterSurfacePhase', ...
            'src/+oce/+filtering/filterSurfacePhase.m';
        'oce.filtering.designTemporalFilter', ...
            'src/+oce/+filtering/designTemporalFilter.m';
        'oce.filtering.applySurfaceTemporalFilter', ...
            'src/+oce/+filtering/applySurfaceTemporalFilter.m';
        'oce.filtering.applyTemporalFilter', ...
            'src/+oce/+filtering/applyTemporalFilter.m';
        'oce.filtering.postprocessSurfacePhase', ...
            'src/+oce/+filtering/postprocessSurfacePhase.m'};
    assert_unique_locations(canonical, context.repoRoot);
    assert_package_contents(context.repoRoot, ...
        ["applySurfaceTemporalFilter.m", "applyTemporalFilter.m", ...
        "designTemporalFilter.m", "filterPhaseResults.m", ...
        "filterSurfacePhase.m", "postprocessSurfacePhase.m"]);

    forbidden = '\<(eval|evalin|assignin|cd)\s*\(';
    for idx = 1:size(canonical, 1)
        source = fileread(fullfile(context.repoRoot, canonical{idx, 2}));
        if ~isempty(regexp(source, forbidden, 'once'))
            error('OCE:RegressionFiltering:ImplicitState', ...
                'Forbidden implicit-state API found in %s.', canonical{idx, 1});
        end
    end

    callerPath = fullfile(context.repoRoot, 'src', '+oce', '+pipeline', ...
        'processPreparedAcquisition.m');
    caller = fileread(callerPath);
    if count(caller, 'oce.filtering.filterPhaseResults') ~= 1
        error('OCE:RegressionFiltering:Caller', ...
            'Maintained engine must call the shared filtering boundary once.');
    end
    if ~isempty(regexp(caller, ...
            'function\s+\[[^\]]*\]\s*=\s*build_temporal_filter', 'once')) || ...
            ~isempty(regexp(caller, ...
            'function\s+\[[^\]]*\]\s*=\s*apply_temporal_filter', 'once'))
        error('OCE:RegressionFiltering:DuplicateLocal', ...
            'Maintained engine retains duplicated local filtering logic.');
    end
    filterBoundary = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+filtering', 'filterPhaseResults.m'));
    if count(filterBoundary, 'oce.config.resolveFilterOptions') ~= 1 || ...
            count(filterBoundary, 'oce.filtering.designTemporalFilter') ~= 1 || ...
            count(filterBoundary, 'oce.filtering.applyTemporalFilter') ~= 1 || ...
            count(filterBoundary, 'oce.filtering.postprocessSurfacePhase') ~= 1
        error('OCE:RegressionFiltering:OptionOwnership', ...
            'Shared filtering resolution and application ownership is invalid.');
    end
    surfaceBoundary = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+filtering', 'filterSurfacePhase.m'));
    if count(surfaceBoundary, 'oce.config.resolveFilterOptions') ~= 1 || ...
            count(surfaceBoundary, 'oce.filtering.designTemporalFilter') ~= 1 || ...
            count(surfaceBoundary, ...
                'oce.filtering.applySurfaceTemporalFilter') ~= 1 || ...
            count(surfaceBoundary, ...
                'oce.filtering.postprocessSurfacePhase') ~= 1
        error('OCE:RegressionFiltering:SurfaceBoundaryOwnership', ...
            'Surface-only filtering ownership is invalid.');
    end
    fullApplication = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+filtering', 'applyTemporalFilter.m'));
    if count(fullApplication, 'oce.filtering.applySurfaceTemporalFilter') ~= 1
        error('OCE:RegressionFiltering:SurfaceOwnership', ...
            ['Full temporal filtering must reuse the single surface-only ' ...
             'application owner exactly once.']);
    end
    assert_retired_runtime_names_absent(context.repoRoot);
    plottingSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', 'plotFilterPreviews.m'));
    if ~isempty(regexp(plottingSource, '\<filter\s*\(', 'once')) || ...
            ~contains(plottingSource, 'Phase increment (rad)') || ...
            ~contains(plottingSource, 'Passthrough')
        error('OCE:RegressionFiltering:PlottingOwnership', ...
            ['Filtering preview must consume calculated results, use phase ' ...
             'units, and identify disabled passthrough.']);
    end
end

function assert_retired_runtime_names_absent(repoRoot)
    roots = {fullfile(repoRoot, 'src'), fullfile(repoRoot, 'workflows')};
    retired = {'FreqVal', '\<BW\>', 'frequency_low_Hz', ...
        'frequency_high_Hz', 'position_frequency', 'Frames1', ...
        'Frames1_border', 'Frame_BK', '\<SpaceTime\>', 'FilterCoef'};
    for rootIndex = 1:numel(roots)
        files = dir(fullfile(roots{rootIndex}, '**', '*.m'));
        for fileIndex = 1:numel(files)
            source = fileread(fullfile(files(fileIndex).folder, ...
                files(fileIndex).name));
            for nameIndex = 1:numel(retired)
                if ~isempty(regexp(source, retired{nameIndex}, 'once'))
                    error('OCE:RegressionFiltering:RetiredRuntimeName', ...
                        'Retired filtering name found in %s.', ...
                        fullfile(files(fileIndex).folder, files(fileIndex).name));
                end
            end
        end
    end
end

function assert_unique_locations(expected, repoRoot)
    for idx = 1:size(expected, 1)
        locations = string(which(expected{idx, 1}, '-all'));
        locations = locations(strlength(locations) > 0);
        if numel(locations) ~= 1
            error('OCE:RegressionFiltering:Resolution', ...
                'Expected one definition for %s; actual count=%d.', ...
                expected{idx, 1}, numel(locations));
        end
        expectedPath = fullfile(repoRoot, expected{idx, 2});
        if ~strcmpi(normalize_path(locations), normalize_path(expectedPath))
            error('OCE:RegressionFiltering:Resolution', ...
                '%s expected at %s; actual=%s.', ...
                expected{idx, 1}, expectedPath, locations);
        end
    end
end

function assert_package_contents(repoRoot, expected)
    files = dir(fullfile(repoRoot, 'src', '+oce', '+filtering', '*.m'));
    actual = sort(string({files.name}));
    if ~isequal(actual, sort(expected))
        error('OCE:RegressionFiltering:PackageContents', ...
            'Filtering package expected=%s; actual=%s.', ...
            strjoin(sort(expected), ', '), strjoin(actual, ', '));
    end
end

function value = normalize_path(value)
    value = replace(string(value), ["/", "\"], filesep);
end
