function test_config_domain_resolution(context)
%TEST_CONFIG_DOMAIN_RESOLUTION Verify canonical configuration ownership.

    canonical = {
        'oce.config.getDefaultProcessingConfig', ...
            'src/+oce/+config/getDefaultProcessingConfig.m';
        'oce.config.getOCTSystemOptions', ...
            'src/+oce/+config/getOCTSystemOptions.m';
        'oce.config.validateProcessingConfig', ...
            'src/+oce/+config/validateProcessingConfig.m';
        'oce.config.resolveOCTSystemOptions', ...
            'src/+oce/+config/resolveOCTSystemOptions.m';
        'oce.config.resolveSampleOpticalOptions', ...
            'src/+oce/+config/resolveSampleOpticalOptions.m';
        'oce.config.buildProcessingConfigForAcquisition', ...
            'src/+oce/+config/buildProcessingConfigForAcquisition.m';
        'oce.config.resolveAcquisitionOptions', ...
            'src/+oce/+config/resolveAcquisitionOptions.m';
        'oce.config.resolveBorderOptions', ...
            'src/+oce/+config/resolveBorderOptions.m';
        'oce.config.resolvePhaseEstimationOptions', ...
            'src/+oce/+config/resolvePhaseEstimationOptions.m';
        'oce.config.resolveDispersionWindowOptions', ...
            'src/+oce/+config/resolveDispersionWindowOptions.m';
        'oce.config.resolveDispersionAnalysisOptions', ...
            'src/+oce/+config/resolveDispersionAnalysisOptions.m';
        'oce.config.resolveRunOptions', ...
            'src/+oce/+config/resolveRunOptions.m';
        'oce.config.saveProcessingConfig', ...
            'src/+oce/+config/saveProcessingConfig.m'};
    assert_unique_locations(canonical, context.repoRoot, "canonical function");
    assert_absent(["get_default_processing_config", ...
        "build_processing_config_for_acquisition", "save_processing_config"]);

    packageFiles = dir(fullfile(context.repoRoot, "src", "+oce", "+config", "*.m"));
    actualNames = sort(string({packageFiles.name}));
    expectedNames = sort([ ...
        "getDefaultProcessingConfig.m", ...
        "getOCTSystemOptions.m", ...
        "validateProcessingConfig.m", ...
        "buildProcessingConfigForAcquisition.m", ...
        "resolveAcquisitionOptions.m", ...
        "resolveBorderOptions.m", ...
        "resolveDispersionWindowOptions.m", ...
        "resolveDispersionAnalysisOptions.m", ...
        "resolveFilterOptions.m", ...
        "resolvePhaseEstimationOptions.m", ...
        "resolveOCTSystemOptions.m", ...
        "resolveSampleOpticalOptions.m", ...
        "resolveRunOptions.m", ...
        "saveProcessingConfig.m"]);
    if ~isequal(actualNames, expectedNames)
        error('OCE:RegressionConfig:PackageContents', ...
            'Expected package files=%s; actual=%s.', ...
            strjoin(expectedNames, ', '), strjoin(actualNames, ', '));
    end

    assert_private_inventory(context.repoRoot);
    assert_readable_composition(context.repoRoot);
    assert_processing_config_validation();
    assert_dispersion_analysis_strict_window();
end

function assert_private_inventory(repoRoot)
    privateFiles = dir(fullfile(repoRoot, "src", "+oce", "+config", ...
        "private", "*.m"));
    actual = sort(string({privateFiles.name}));
    expected = sort([ ...
        "applyProcessingConfigOverrides.m", ...
        "getDefaultBorderOptions.m", ...
        "getDefaultDispersionAnalysisOptions.m", ...
        "getDefaultDispersionWindowOptions.m", ...
        "getDefaultFilterOptions.m", ...
        "getDefaultMotionOptions.m", ...
        "getDefaultSampleOpticalOptions.m", ...
        "resolveAcquisitionOCTSystem.m", ...
        "resolveRunVideoOptions.m"]);
    if ~isequal(actual, expected)
        error('OCE:RegressionConfig:PrivateContents', ...
            'Config private helpers expected=%s; actual=%s.', ...
            strjoin(expected, ', '), strjoin(actual, ', '));
    end
end

function assert_readable_composition(repoRoot)
    defaultsSource = fileread(fullfile(repoRoot, 'src', '+oce', '+config', ...
        'getDefaultProcessingConfig.m'));
    requiredDefaults = [ ...
        "processing_config.AcquisitionOptions = struct"; ...
        "oce.config.getOCTSystemOptions"; ...
        "getDefaultSampleOpticalOptions"; ...
        "getDefaultDispersionAnalysisOptions"; "getDefaultFilterOptions"; ...
        "getDefaultBorderOptions"; "getDefaultMotionOptions"; ...
        "getDefaultDispersionWindowOptions"; ...
        "processing_config.VisualizationOptions = struct"; ...
        "processing_config.VideoOptions = struct"; ...
        "oce.config.validateProcessingConfig"];
    forbiddenDefaults = ["getDefaultAcquisitionOptions"; ...
        "getDefaultOCTDefaults"; "OCT_defaults"; ...
        "getDefaultVisualizationOptions"; "getDefaultVideoOptions"];
    if any(~contains(defaultsSource, requiredDefaults)) || ...
            any(contains(defaultsSource, forbiddenDefaults))
        error('OCE:RegressionConfig:DefaultComposition', ...
            ['Default ProcessingConfig must keep simple values visible and ' ...
             'delegate only substantial domain defaults.']);
    end

    buildSource = fileread(fullfile(repoRoot, 'src', '+oce', '+config', ...
        'buildProcessingConfigForAcquisition.m'));
    requiredBuild = ["oce.config.validateProcessingConfig"; ...
        "applyProcessingConfigOverrides"; "resolveAcquisitionOCTSystem"; ...
        "oce.config.resolveSampleOpticalOptions"; ...
        "processingConfig.OCTSystemOptions"; ...
        "processingConfig.SampleOpticalOptions"; ...
        "resolveRunVideoOptions"];
    forbiddenBuild = ["validateRunProcessingConfig"; "optional_legacy_optics"; ...
        "remove_legacy_refractive_index"; "get_field_or_empty"; ...
        "apply_per_acquisition_overrides"; "merge_override_struct"; ...
        "compute_video_options"; "OCT_defaults"];
    if any(~contains(buildSource, requiredBuild)) || ...
            any(contains(buildSource, forbiddenBuild))
        error('OCE:RegressionConfig:RunComposition', ...
            'Run configuration builder retained compatibility or mixed responsibilities.');
    end
end

function assert_processing_config_validation()
    config = oce.config.getDefaultProcessingConfig("phantom");
    oce.config.validateProcessingConfig(config);

    missing = rmfield(config, 'FilterOptions');
    assert_identifier('OCE:Config:InvalidProcessingConfig', @() ...
        oce.config.validateProcessingConfig(missing));

    missingOptics = rmfield(config, 'OCTSystemOptions');
    assert_identifier('OCE:Config:InvalidProcessingConfig', @() ...
        oce.config.validateProcessingConfig(missingOptics));

    missingSample = rmfield(config, 'SampleOpticalOptions');
    assert_identifier('OCE:Config:InvalidProcessingConfig', @() ...
        oce.config.validateProcessingConfig(missingSample));

    retiredDefaults = config;
    retiredDefaults.OCT_defaults = struct('center_wavelength', 1.300);
    assert_identifier('OCE:Config:InvalidProcessingConfig', @() ...
        oce.config.validateProcessingConfig(retiredDefaults));

    extra = config;
    extra.retired_field = true;
    assert_identifier('OCE:Config:InvalidProcessingConfig', @() ...
        oce.config.validateProcessingConfig(extra));

    invalidOverride = config;
    invalidOverride.per_acquisition.R001 = 42;
    assert_identifier('OCE:Config:InvalidProcessingConfig', @() ...
        oce.config.validateProcessingConfig(invalidOverride));
end

function assert_dispersion_analysis_strict_window()
    config = oce.config.getDefaultProcessingConfig("phantom");
    options = config.DispersionAnalysisOptions;
    filter = struct('frequency', struct('center_hz', 1000));

    resolved = oce.config.resolveDispersionAnalysisOptions(options, filter);
    if resolved.spectrum.window.time.enabled || ...
            resolved.spectrum.window.space.enabled
        error('OCE:RegressionConfig:SpectrumWindowDefault', ...
            'Canonical default spectrum windows must remain explicitly OFF.');
    end

    missingWindow = options;
    missingWindow.spectrum = rmfield(missingWindow.spectrum, 'window');
    assert_identifier('OCE:Config:InvalidDispersionAnalysisOptions', @() ...
        oce.config.resolveDispersionAnalysisOptions(missingWindow, filter));
end

function assert_identifier(expected, action)
    try
        action();
        actual = "<no error>";
    catch ME
        actual = string(ME.identifier);
    end
    if actual ~= expected
        error('OCE:RegressionConfig:ErrorIdentifier', ...
            'Expected identifier=%s; actual=%s.', expected, actual);
    end
end

function assert_absent(names)
    for idx = 1:numel(names)
        if ~isempty(which(char(names(idx)), '-all'))
            error('OCE:RegressionConfig:RetiredAdapter', ...
                'Retired configuration adapter still resolves: %s.', names(idx));
        end
    end
end

function assert_unique_locations(expected, repoRoot, description)
    for idx = 1:size(expected, 1)
        name = expected{idx, 1};
        locations = string(which(name, '-all'));
        locations = locations(strlength(locations) > 0);
        if numel(locations) ~= 1
            error('OCE:RegressionConfig:Resolution', ...
                'Expected one %s resolution for %s; actual count=%d; values=%s.', ...
                description, name, numel(locations), strjoin(locations, ', '));
        end
        expectedPath = fullfile(repoRoot, expected{idx, 2});
        if ~strcmpi(normalize_path(locations(1)), normalize_path(expectedPath))
            error('OCE:RegressionConfig:Resolution', ...
                '%s %s expected at %s but resolved to %s.', ...
                description, name, expectedPath, locations(1));
        end
    end
end

function value = normalize_path(value)
    value = replace(string(value), ["/", "\"], filesep);
end
