function filtered = applyTemporalFilter(depthPhase, surfacePhase, design, invalidRowPolicy)
%APPLYTEMPORALFILTER Apply the resolved FIR or an exact phase passthrough.

    validate_inputs(depthPhase, surfacePhase, design, invalidRowPolicy);
    surfaceFiltered = oce.filtering.applySurfaceTemporalFilter( ...
        surfacePhase, design, invalidRowPolicy);
    depthValues = depthPhase.values;
    outputDepth = depthValues;
    invalidMask = surfaceFiltered.invalid_rows.mask;

    for lateralIndex = 1:size(surfacePhase.values, 1)
        depthSignal = squeeze(depthValues(lateralIndex, :, :));
        if invalidMask(lateralIndex)
            outputDepth(lateralIndex, :, :) = zeros( ...
                size(depthSignal), 'like', outputDepth);
        elseif any(isnan(depthSignal), 'all')
            error('OCE:Filtering:InvalidVolumetricMotion', ...
                ['Depth-resolved phase contains NaN values at lateral ' ...
                 'position %d while surface phase is finite.'], lateralIndex);
        elseif design.applied
            outputDepth(lateralIndex, :, :) = filter( ...
                design.coefficients, 1, depthSignal')';
        end
    end

    filtered = struct( ...
        'depth', phase_output(outputDepth, depthPhase, design.applied), ...
        'surface', surfaceFiltered.surface, ...
        'invalid_rows', surfaceFiltered.invalid_rows);
end

function output = phase_output(values, source, applied)
    output = struct( ...
        'values', values, ...
        'quantity', string(source.quantity), ...
        'units', string(source.units), ...
        'layout', string(source.layout), ...
        'applied', logical(applied));
end

function validate_inputs(depthPhase, surfacePhase, design, invalidRowPolicy)
    requiredPhase = {'values', 'quantity', 'units', 'layout'};
    if ~isstruct(depthPhase) || any(~isfield(depthPhase, requiredPhase)) || ...
            ~isnumeric(depthPhase.values) || ndims(depthPhase.values) ~= 3
        error('OCE:Filtering:InvalidPhaseInput', ...
            'Depth phase must contain numeric lateral-by-depth-by-time values.');
    end
    if ~isstruct(surfacePhase) || any(~isfield(surfacePhase, requiredPhase)) || ...
            ~isnumeric(surfacePhase.values) || ~ismatrix(surfacePhase.values)
        error('OCE:Filtering:InvalidPhaseInput', ...
            'Surface phase must contain numeric lateral-by-time values.');
    end
    if size(depthPhase.values, 1) ~= size(surfacePhase.values, 1) || ...
            size(depthPhase.values, 3) ~= size(surfacePhase.values, 2)
        error('OCE:Filtering:InvalidPhaseInput', ...
            'Depth and surface phase layouts must share lateral and time sizes.');
    end
    if ~isstruct(design) || ~isfield(design, 'applied') || ...
            ~isfield(design, 'coefficients') || ...
            (design.applied && isempty(design.coefficients)) || ...
            (~design.applied && ~isempty(design.coefficients))
        error('OCE:Filtering:InvalidDesign', ...
            'Filtering design has inconsistent applied/coefficient values.');
    end
    if string(invalidRowPolicy) ~= "zero_surface_and_matching_depth"
        error('OCE:Filtering:UnsupportedInvalidRowPolicy', ...
            'Unsupported invalid-row policy "%s".', string(invalidRowPolicy));
    end
end
