function [filterResult, resolvedOptions] = filterSurfacePhase( ...
        surfacePhaseResult, configForRun, octSystem, geometry)
%FILTERSURFACEPHASE Apply the maintained temporal filter to surface phase.

    resolvedOptions = oce.config.resolveFilterOptions( ...
        configForRun, surfacePhaseResult.values, octSystem);
    filterDesign = oce.filtering.designTemporalFilter( ...
        surfacePhaseResult.values, geometry, resolvedOptions);
    resolvedOptions.diagnostic.line_index_used = ...
        filterDesign.diagnostic.line_index_used;
    filteredSurface = oce.filtering.applySurfaceTemporalFilter( ...
        surfacePhaseResult, filterDesign, resolvedOptions.invalid_row_policy);
    surfacePostprocessed = oce.filtering.postprocessSurfacePhase( ...
        filteredSurface.surface, resolvedOptions.surface_postprocessing);

    filterResult = struct( ...
        'enabled', resolvedOptions.enabled, ...
        'method', resolvedOptions.method, ...
        'applied', filterDesign.applied, ...
        'surface', filteredSurface.surface, ...
        'surface_postprocessed', surfacePostprocessed, ...
        'invalid_rows', filteredSurface.invalid_rows, ...
        'design', filterDesign, ...
        'time_axis_s', filterDesign.time_axis_s, ...
        'frequency_axis_hz', filterDesign.frequency_axis_hz);
end
