function [result, resolvedOptions] = filterPhaseResults(phaseResult, ...
        configForRun, octSystem, geometry)
%FILTERPHASERESULTS Resolve and apply the maintained temporal filtering.

    if ~isstruct(phaseResult) || ~isscalar(phaseResult) || ...
            ~isfield(phaseResult, 'depth_resolved') || ...
            ~isfield(phaseResult, 'surface')
        error('OCE:Filtering:InvalidPhaseResult', ...
            ['phaseResult must contain depth_resolved and surface ' ...
             'products.']);
    end

    surfaceValues = phaseResult.surface.values;
    resolvedOptions = oce.config.resolveFilterOptions( ...
        configForRun, surfaceValues, octSystem);
    design = oce.filtering.designTemporalFilter( ...
        surfaceValues, geometry, resolvedOptions);
    resolvedOptions.diagnostic.line_index_used = ...
        design.diagnostic.line_index_used;
    filtered = oce.filtering.applyTemporalFilter( ...
        phaseResult.depth_resolved, phaseResult.surface, design, ...
        resolvedOptions.invalid_row_policy);
    depthTemporalMean = struct( ...
        'values', mean(filtered.depth.values, 3), ...
        'quantity', "phase_increment_temporal_mean", ...
        'units', "rad", ...
        'layout', "lateral_depth");
    surfacePostprocessed = oce.filtering.postprocessSurfacePhase( ...
        filtered.surface, resolvedOptions.surface_postprocessing);
    result = struct( ...
        'enabled', resolvedOptions.enabled, ...
        'method', resolvedOptions.method, ...
        'applied', design.applied, ...
        'depth', filtered.depth, ...
        'surface', filtered.surface, ...
        'depth_temporal_mean', depthTemporalMean, ...
        'surface_postprocessed', surfacePostprocessed, ...
        'invalid_rows', filtered.invalid_rows, ...
        'design', design, ...
        'time_axis_s', design.time_axis_s, ...
        'frequency_axis_hz', design.frequency_axis_hz);
end
