function result = postprocessSurfacePhase(surfacePhase, options)
%POSTPROCESSSURFACEPHASE Apply explicit surface phase postprocessing.

    validate_inputs(surfacePhase, options);
    values = surfacePhase.values;
    if options.remove_temporal_mean
        values = values - mean(values, 2);
    end
    if options.median.enabled
        values = medfilt2(values, options.median.window_samples, 'Symmetric');
    end

    result = struct( ...
        'values', values, ...
        'quantity', string(surfacePhase.quantity), ...
        'units', string(surfacePhase.units), ...
        'layout', string(surfacePhase.layout), ...
        'temporal_mean_removed', logical(options.remove_temporal_mean), ...
        'median_applied', logical(options.median.enabled), ...
        'median_window_samples', options.median.window_samples);
end

function validate_inputs(surfacePhase, options)
    requiredPhase = {'values', 'quantity', 'units', 'layout'};
    if ~isstruct(surfacePhase) || any(~isfield(surfacePhase, requiredPhase)) || ...
            ~isnumeric(surfacePhase.values) || ~ismatrix(surfacePhase.values)
        error('OCE:Filtering:InvalidPhaseInput', ...
            'Surface phase must contain numeric lateral-by-time values.');
    end
    if ~isstruct(options) || ...
            ~isfield(options, 'remove_temporal_mean') || ...
            ~isfield(options, 'median') || ...
            ~isstruct(options.median) || ...
            ~isfield(options.median, 'enabled') || ...
            ~isfield(options.median, 'window_samples')
        error('OCE:Filtering:InvalidPostprocessing', ...
            'Resolved surface postprocessing options are required.');
    end
    if ~islogical(options.remove_temporal_mean) || ...
            ~isscalar(options.remove_temporal_mean) || ...
            ~islogical(options.median.enabled) || ...
            ~isscalar(options.median.enabled)
        error('OCE:Filtering:InvalidPostprocessing', ...
            'Surface postprocessing enable fields must be logical scalars.');
    end
    window = options.median.window_samples;
    if ~isnumeric(window) || ~isvector(window) || numel(window) ~= 2 || ...
            any(~isfinite(window)) || any(window < 1) || ...
            any(window ~= round(window))
        error('OCE:Filtering:InvalidPostprocessing', ...
            'Median window must contain two positive finite integers.');
    end
end
