function [acceptedBorderOptions, borderResult] = tuneBorderDetection( ...
        acquisitionState, editableBorderOptions, acquisitionRow, ...
        resolvedCrop, displayLimitsDb)
%TUNEBORDERDETECTION Tune one maintained border method interactively.
% The returned editable options use explicit manual selection so they can be
% persisted with oce.config.saveProcessingConfig and reused headlessly.

    resolved = oce.config.resolveBorderOptions( ...
        editableBorderOptions, acquisitionRow, resolvedCrop);
    method = string(resolved.method);
    workingOptions = editableBorderOptions;
    workingOptions.selection = "manual";
    workingOptions.method = method;
    if method == "phantom"
        workingOptions = materialize_phantom_tuning_options( ...
            workingOptions, resolved.parameters);
    end
    currentResult = oce.borders.detectAndMask(acquisitionState, resolved);
    specifications = parameter_specifications(method);
    if method == "phantom" && resolved.surface_mode == "anterior_only"
        specifications = specifications( ...
            string({specifications.group}) ~= "Posterior");
    end

    acceptedBorderOptions = struct();
    borderResult = struct();
    cancelled = true;

    parameterValues = zeros(numel(specifications), 1);
    for index = 1:numel(specifications)
        parameterValues(index) = get_parameter( ...
            workingOptions, method, specifications(index));
    end
    callbacks = struct( ...
        'parameter_changed', ...
            @(index, value) detector_parameter_changed(index, value), ...
        'mask_changed', @(value) mask_threshold_changed(value), ...
        'accept', @accept_tuning, ...
        'cancel', @cancel_tuning);
    ui = createBorderTunerUI( ...
        method, specifications, parameterValues, ...
        workingOptions.mask_threshold, callbacks);

    render_preview();
    uiwait(ui.window);
    if isvalid(ui.window)
        delete(ui.window);
    end
    if cancelled
        error('OCE:Interaction:BorderTuningCancelled', ...
            'Border tuning was cancelled before borders were accepted.');
    end

    function detector_parameter_changed(index, proposedValue)
        specification = specifications(index);
        previousValue = get_parameter(workingOptions, method, specification);
        if specification.integer
            proposedValue = round(proposedValue);
        end
        workingOptions = set_parameter( ...
            workingOptions, method, specification, proposedValue);
        ui.status_label.Text = 'Detecting borders...';
        drawnow;
        try
            candidateResolved = oce.config.resolveBorderOptions( ...
                workingOptions, acquisitionRow, resolvedCrop);
            candidateResult = oce.borders.detectAndMask( ...
                acquisitionState, candidateResolved);
            currentResult = candidateResult;
            ui.sliders{index}.Value = proposedValue;
            ui.fields{index}.Value = proposedValue;
            render_preview();
            ui.status_label.Text = 'Ready';
        catch ME
            workingOptions = set_parameter( ...
                workingOptions, method, specification, previousValue);
            ui.sliders{index}.Value = previousValue;
            ui.fields{index}.Value = previousValue;
            ui.status_label.Text = 'Previous borders retained';
            uialert(ui.window, ME.message, 'Border detection failed');
        end
    end

    function mask_threshold_changed(proposedValue)
        previousValue = workingOptions.mask_threshold;
        try
            workingOptions.mask_threshold = proposedValue;
            currentResult.intensityMask = oce.borders.buildIntensityMask( ...
                acquisitionState.reconstruction, proposedValue);
            ui.mask_slider.Value = proposedValue;
            ui.mask_field.Value = proposedValue;
            render_preview();
            ui.status_label.Text = 'Ready';
        catch ME
            workingOptions.mask_threshold = previousValue;
            ui.mask_slider.Value = previousValue;
            ui.mask_field.Value = previousValue;
            ui.status_label.Text = 'Previous borders retained';
            uialert(ui.window, ME.message, 'Mask update failed');
        end
    end

    function render_preview()
        oce.plotting.plotBorderPreview(ui.border_axes, ui.mask_axes, ...
            acquisitionState.reconstruction, currentResult, displayLimitsDb);
        drawnow limitrate;
    end

    function accept_tuning(~, ~)
        acceptedBorderOptions = workingOptions;
        borderResult = currentResult;
        cancelled = false;
        uiresume(ui.window);
    end

    function cancel_tuning(~, ~)
        cancelled = true;
        uiresume(ui.window);
    end
end

function options = materialize_phantom_tuning_options(options, resolvedParameters)
    legacyFields = ["background_depth_range"; "background_lateral_range"; ...
        "min_depth_index"];
    for index = 1:numel(legacyFields)
        field = legacyFields(index);
        if isfield(options.methods.phantom, field)
            options.methods.phantom = rmfield(options.methods.phantom, field);
        end
    end
    if ~isfield(options.methods.phantom, 'surface_mode')
        options.methods.phantom.surface_mode = resolvedParameters.surface_mode;
    end
    if ~isfield(options.methods.phantom, 'background_percentile')
        options.methods.phantom.background_percentile = ...
            resolvedParameters.background_percentile;
    end
end

function specifications = parameter_specifications(method)
    shared = @(group, label, description, name, limits, integer) struct( ...
        'group', group, 'label', label, 'description', description, ...
        'scope', "shared", 'name', name, ...
        'index', 0, 'limits', limits, 'integer', integer);
    local = @(group, label, description, name, limits, integer) struct( ...
        'group', group, 'label', label, 'description', description, ...
        'scope', "method", 'name', name, ...
        'index', 0, 'limits', limits, 'integer', integer);
    indexed = @(group, label, description, name, element, limits) struct( ...
        'group', group, 'label', label, 'description', description, ...
        'scope', "method", 'name', name, ...
        'index', element, 'limits', limits, 'integer', false);

    switch method
        case "phantom"
            specifications = [ ...
                local("Anterior", 'Anterior peak threshold', ...
                    'Threshold offset used to accept the anterior peak', ...
                    'top_peak_multiplier', [1 60], false); ...
                local("Anterior", 'Peak threshold window', ...
                    'Samples used to establish the peak threshold', ...
                    'peak_window_size', [5 150], true); ...
                local("Anterior", 'Anterior search offset', ...
                    'Axial samples skipped before anterior peak detection', ...
                    'top_search_offset', [0 500], true); ...
                local("Anterior", 'Anterior index offset', ...
                    'Pixel correction applied after anterior peak detection', ...
                    'top_index_offset', [-20 30], true); ...
                local("Posterior", 'Posterior peak threshold', ...
                    'Threshold offset used to accept the posterior peak', ...
                    'bottom_peak_multiplier', [1 60], false); ...
                local("Posterior", 'Posterior search offset', ...
                    'Depth offset from the anterior border before posterior search', ...
                    'bottom_search_offset', [10 500], true); ...
                local("Posterior", 'Posterior index offset', ...
                    'Pixel correction applied after posterior peak detection', ...
                    'bottom_index_offset', [-20 30], true); ...
                local("Posterior", 'Background percentile', ...
                    'Low-intensity percentile used as posterior-search floor', ...
                    'background_percentile', [1 50], false); ...
                local("Trajectory", 'Maximum lateral jump', ...
                    'Jump threshold between adjacent border candidates', ...
                    'max_lateral_jump', [1 100], true); ...
                local("Trajectory", 'Maximum jump gap', ...
                    'Longest short excursion rejected between or at edges', ...
                    'max_jump_gap', [1 30], true); ...
                local("Trajectory", 'Smoothing span', ...
                    'Lateral LOWESS smoothing of accepted borders', ...
                    'smooth_span', [0.005 0.30], false)];
        case "adaptive_corneal"
            specifications = [ ...
                shared("Anterior", 'Adaptive threshold', ...
                    'Shared intensity threshold used before both border searches', ...
                    'adaptive_threshold_k', [0 1], false); ...
                local("Anterior", 'Top fit extension', ...
                    'Extra anterior fitting range near the lateral edges', ...
                    'fit_extra_margin_top_px', [0 80], true); ...
                local("Posterior", 'Posterior search offset', ...
                    'Depth offset from the anterior fit before posterior search', ...
                    'bottom_search_offset_px', [10 400], true); ...
                local("Trajectory", 'Fit margin', ...
                    'Lateral edge margin excluded from border polynomial fits', ...
                    'fit_margin_px', [0 80], true); ...
                local("Trajectory", 'Outlier-fill window', ...
                    'Neighborhood used to replace border outliers', ...
                    'filloutliers_window', [3 100], true)];
        case "in_vivo_corneal"
            specifications = [ ...
                shared("Anterior", 'Adaptive threshold', ...
                    'Shared intensity threshold used before both border searches', ...
                    'adaptive_threshold_k', [0 1], false); ...
                local("Anterior", 'Top search padding', ...
                    'Extra depth range around the estimated corneal band', ...
                    'top_search_padding_px', [0 200], true); ...
                local("Anterior", 'Minimum signal run', ...
                    'Minimum continuous signal run accepted for either surface', ...
                    'min_run_length_px', [1 30], true); ...
                indexed("Posterior", 'Thickness minimum (mm)', ...
                    'Minimum allowed anterior-posterior distance', ...
                    'thickness_range_mm', 1, [0.1 2]); ...
                indexed("Posterior", 'Thickness maximum (mm)', ...
                    'Maximum allowed anterior-posterior distance', ...
                    'thickness_range_mm', 2, [0.1 2]); ...
                local("Artifact rejection", 'Artifact z-score', ...
                    'Brightness threshold for rejecting abnormal columns', ...
                    'vertical_artifact_zscore', [0.5 10], false); ...
                local("Artifact rejection", 'Artifact height fraction', ...
                    'Minimum active column height flagged as artifact', ...
                    'vertical_artifact_min_height_fraction', [0.05 1], false); ...
                local("Trajectory", 'Maximum jump', ...
                    'Largest accepted border jump between columns', ...
                    'max_jump_px', [1 100], true); ...
                local("Trajectory", 'Smoothing span', ...
                    'Lateral smoothing width for accepted borders', ...
                    'smooth_span_px', [3 101], true)];
        otherwise
            error('OCE:Borders:UnsupportedMethod', ...
                'Unsupported border tuning method "%s".', method);
    end
end

function value = get_parameter(options, method, specification)
    if specification.scope == "shared"
        value = options.corneal_preprocessing.(specification.name);
    else
        value = options.methods.(char(method)).(specification.name);
    end
    if specification.index > 0
        value = value(specification.index);
    end
    value = double(value);
end

function options = set_parameter(options, method, specification, value)
    if specification.scope == "shared"
        options.corneal_preprocessing.(specification.name) = value;
        return;
    end
    if specification.index == 0
        options.methods.(char(method)).(specification.name) = value;
    else
        vector = options.methods.(char(method)).(specification.name);
        vector(specification.index) = value;
        options.methods.(char(method)).(specification.name) = vector;
    end
end
