function [fitresult, gof] = createFitGaussian(Xaxis_fitting, Motion_Fitting_1)
%CREATEFIT(XAXIS_FITTING,MOTION_FITTING_1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Xaxis_fitting
%      Y Output: Motion_Fitting_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Feb-2020 16:48:01


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Xaxis_fitting, Motion_Fitting_1 );

% Set up fittype and options.
ft = fittype( '(a1*exp(-((x-b1)/c1)^2))+d1', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.04 2.5 0.3 -0.01];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Motion profile', ['Gaussian fit, \sigma = ',num2str(fitresult.c1),' mm'], 'Location', 'NorthEast', 'Interpreter', 'tex' );
% % Label axes
% xlabel( 'x-axis (mm)', 'Interpreter', 'none' );
% ylabel( 'Particle velocity (Arb.)', 'Interpreter', 'none' );
% set(gca,'FontSize',14)
% grid on


