function test_maintained_terminology_contract(context)
%TEST_MAINTAINED_TERMINOLOGY_CONTRACT Reject temporary active naming.

    roots = [ ...
        fullfile(context.repoRoot, 'src'); ...
        fullfile(context.repoRoot, 'workflows')];
    temporaryPhase = ...
        '(?i)(^|[^A-Za-z0-9])Phase\s*(1|2|3|4|5A|5B)([^A-Za-z0-9]|$)';
    temporarySubphase = ...
        '(?i)(^|[^A-Za-z0-9])Phase\s*(5A|5B)([^A-Za-z0-9]|$)';
    historicalMonolith = '(?i)PP_MBmode';
    for rootIndex = 1:numel(roots)
        files = dir(fullfile(roots(rootIndex), '**', '*.m'));
        for fileIndex = 1:numel(files)
            pathValue = fullfile(files(fileIndex).folder, files(fileIndex).name);
            source = fileread(pathValue);
            assert_absent(files(fileIndex).name, temporaryPhase, pathValue);
            assert_absent(files(fileIndex).name, historicalMonolith, pathValue);
            assert_absent(source, temporaryPhase, pathValue);
            assert_absent(source, historicalMonolith, pathValue);
        end
    end

    activeDocs = [ ...
        "AGENTS.md"; ...
        "README.md"; ...
        "docs/processing_workflow.md"; ...
        "docs/dispersion_window_options.md"; ...
        "docs/repository/final_architecture.md"; ...
        "docs/project/scientific_audit.md"];
    for idx = 1:numel(activeDocs)
        pathValue = fullfile(context.repoRoot, ...
            replace(activeDocs(idx), '/', filesep));
        source = fileread(pathValue);
        assert_absent(source, temporarySubphase, pathValue);
        assert_absent(source, historicalMonolith, pathValue);
    end

    testRoots = ["contract", "integration", "regression", ...
        "unit", "helpers", "runners"];
    for rootIndex = 1:numel(testRoots)
        testRoot = fullfile(context.repoRoot, 'tests', testRoots(rootIndex));
        files = dir(fullfile(testRoot, '**', '*.m'));
        for fileIndex = 1:numel(files)
            pathValue = fullfile(files(fileIndex).folder, files(fileIndex).name);
            source = fileread(pathValue);
            assert_absent(files(fileIndex).name, temporaryPhase, pathValue);
            assert_absent(source, temporaryPhase, pathValue);
            if startsWith(strtrim(string(source)), "% MIGRATION_TEMP")
                error('OCE:Terminology:TemporaryName', ...
                    'Temporary migration marker found at the start of %s.', ...
                    pathValue);
            end
        end
    end

    assert_geometry_neutral_naming(context.repoRoot, testRoots);

    retiredComparator = fullfile(context.repoRoot, 'tests', 'helpers', ...
        'migration_compare_values.m');
    if isfile(retiredComparator) || ...
            ~isempty(which('migration_compare_values', '-all'))
        error('OCE:Terminology:TemporaryName', ...
            'Retired migration comparator still exists or resolves.');
    end

    plottingRoot = fullfile(context.repoRoot, 'src', '+oce', '+plotting');
    plottingFiles = dir(fullfile(plottingRoot, '**', '*.m'));
    for idx = 1:numel(plottingFiles)
        pathValue = fullfile(plottingFiles(idx).folder, plottingFiles(idx).name);
        assert_absent(fileread(pathValue), '(?i)Phase[0-9]', pathValue);
    end

    persistencePath = fullfile(context.repoRoot, 'src', '+oce', '+io', ...
        'saveScientificResult.m');
    persistenceSource = fileread(persistencePath);
    if ~contains(persistenceSource, "'PhaseSpeed.mat'") || ...
            ~contains(persistenceSource, "oce_result")
        error('OCE:Terminology:PhaseSpeedContract', ...
            'Scientific PhaseSpeed persistence contract changed.');
    end

    borderRoots = [ ...
        fullfile(context.repoRoot, 'src', '+oce', '+borders'); ...
        fullfile(context.repoRoot, 'src', '+oce', '+config')];
    for rootIndex = 1:numel(borderRoots)
        files = dir(fullfile(borderRoots(rootIndex), '**', '*.m'));
        for fileIndex = 1:numel(files)
            pathValue = fullfile(files(fileIndex).folder, files(fileIndex).name);
            source = fileread(pathValue);
            if contains(source, '"legacy"') || ...
                    contains(files(fileIndex).name, 'Legacy')
                error('OCE:Terminology:RetiredBorderMethod', ...
                    'Retired border method terminology found in %s.', pathValue);
            end
        end
    end

    coreContractFiles = [ ...
        "src/+oce/+acquisition/reconstructComplexVolume.m"; ...
        "src/+oce/+acquisition/buildAcquisitionState.m"; ...
        "src/+oce/+pipeline/processPreparedAcquisition.m"; ...
        "src/+oce/+pipeline/runSingleAcquisition.m"; ...
        "src/+oce/+pipeline/runBatchProcessing.m"];
    retiredContracts = ["Cplx_Matrix"; "Bmode_IntLog"; ...
        "RunDispersion"; "RunPolarPlots"; "PhaseSpeed_New"; ...
        "Thickness_New"; "ParamsDisp"];
    for fileIndex = 1:numel(coreContractFiles)
        pathValue = fullfile(context.repoRoot, ...
            replace(coreContractFiles(fileIndex), '/', filesep));
        source = fileread(pathValue);
        for termIndex = 1:numel(retiredContracts)
            if contains(source, retiredContracts(termIndex))
                error('OCE:Terminology:RetiredPipelineContract', ...
                    'Retired pipeline contract %s found in %s.', ...
                    retiredContracts(termIndex), pathValue);
            end
        end
    end
    if ~isempty(which('oce.plotting.saveBmodePreview', '-all'))
        error('OCE:Terminology:RetiredPipelineContract', ...
            'Retired reconstruction-preview function still resolves.');
    end

    detected = false;
    try
        injected = "Injected " + "Ph" + "ase 5A label";
        assert_absent(injected, temporarySubphase, ...
            "negative-control");
    catch ME
        detected = strcmp(ME.identifier, 'OCE:Terminology:TemporaryName');
    end
    if ~detected
        error('OCE:Terminology:NegativeControl', ...
            'Temporary-name negative control was not detected.');
    end
end

function assert_geometry_neutral_naming(repoRoot, testRoots)
    retired = [ ...
        "multiple_meridians"; ...
        "meridian_count"; ...
        "samples_per_meridian"; ...
        "meridian_scan_width_mm"; ...
        "meridian_lateral_axis_mm"; ...
        "fraction_of_meridian"; ...
        "fractionOfMeridian"; ...
        "MeridianMode"; ...
        "meridian_index"; ...
        "num_meridians"; ...
        "meridian_angles_deg"; ...
        "direction_meridian_indices"; ...
        "window_result.meridians"; ...
        "windows.meridians"; ...
        "summary.meridian"; ...
        "experiment_meridian_summary"; ...
        "spectral_time_spatial_meridian"; ...
        "PhysicalMeridian"; ...
        "ByMeridian"; ...
        "resolveMeridianLayout"; ...
        "plotMeridianSpaceTime"; ...
        "multimeridian"];

    allowed = fullfile(repoRoot, 'tests', 'contract', ...
        'test_maintained_terminology_contract.m');

    roots = [fullfile(repoRoot, 'src'); fullfile(repoRoot, 'workflows')];
    for index = 1:numel(testRoots)
        roots(end + 1, 1) = fullfile(repoRoot, 'tests', testRoots(index)); %#ok<AGROW>
    end

    for rootIndex = 1:numel(roots)
        files = dir(fullfile(roots(rootIndex), '**', '*.m'));
        for fileIndex = 1:numel(files)
            pathValue = fullfile(files(fileIndex).folder, files(fileIndex).name);
            if strcmpi(pathValue, allowed)
                continue;
            end
            source = string(fileread(pathValue));
            fileName = string(files(fileIndex).name);
            for termIndex = 1:numel(retired)
                term = retired(termIndex);
                if contains(source, term, 'IgnoreCase', true) || ...
                        contains(fileName, term, 'IgnoreCase', true)
                    error('OCE:Terminology:RetiredGeometryName', ...
                        'Retired generic geometry term %s found in %s.', ...
                        term, pathValue);
                end
            end
        end
    end
end

function assert_absent(source, expression, pathValue)
    if ~isempty(regexp(source, expression, 'once'))
        error('OCE:Terminology:TemporaryName', ...
            'Temporary maintained naming found in %s.', pathValue);
    end
end
