function test_plotting_domain_resolution(context)
%TEST_PLOTTING_DOMAIN_RESOLUTION Verify canonical plotting ownership.

    retiredMeridianToken = "Meri" + "dian";

    rootNames = ["plotPolarPhaseResults"; "savePolarPhaseResults"; ...
        "applyPreviewStyle"; "resolveBmodeLayout"; ...
        "plotBmodeSpaceTime"; "prepareMotionVisualization"; ...
        "postprocessMotionOverlayFrame"; ...
        "plotCompleteSpaceTime"; "saveCompleteSpaceTime"; ...
        "plotPhasePreview"; "plotFilterPreviews"; "plotPhaseGradientPreview"; ...
        "resolvePhasePreviewCLim"; "resolveMotionOverlayCLim"; ...
        "resolveSpeedPreviewYLimit"; ...
        "plotBorderPreview"; "saveReconstructionPreview"; ...
        "plotDispersionWindowContext"; "saveDispersionWindowContext"; ...
        "plotDispersionKfPreview"; "saveDispersionKfPreview"; ...
        "saveBorderPreview"; "saveFilterPreviews"; ...
        "saveSpeedDispersionPreview"; ...
        "closeGeneratedFigures"];
    for index = 1:numel(rootNames)
        qualified = "oce.plotting." + rootNames(index);
        locations = which(char(qualified), '-all');
        if ischar(locations), locations = {locations}; end
        expected = fullfile(context.repoRoot, 'src', '+oce', '+plotting', ...
            rootNames(index) + '.m');
        if numel(locations) ~= 1 || ~strcmpi(locations{1}, expected)
            error('OCE:RegressionPlotting:Resolution', ...
                'Expected one canonical definition for %s; actual=%s.', ...
                qualified, strjoin(string(locations), ', '));
        end
    end

    summaryRendererNames = [ ...
        "plotPhaseSpeedPolarSummary"; ...
        "plotThicknessPolarSummary"; ...
        "plotRepetitionAveragedDispersionSummary"; ...
        "plotAngleAveragedDispersionSummary"; ...
        "plotPhaseSpeedVsFrequencyByAngle"; ...
        "plotPhaseSpeedVsFrequencyAngleAveraged"; ...
        "plotPhaseSpeedVsFrequencyByScanAxis"];
    summarySaveNames = [ ...
        "savePhaseSpeedPolarSummary"; ...
        "saveThicknessPolarSummary"; ...
        "saveRepetitionAveragedDispersionSummary"; ...
        "saveAngleAveragedDispersionSummary"; ...
        "savePhaseSpeedVsFrequencyByAngle"; ...
        "savePhaseSpeedVsFrequencyAngleAveraged"; ...
        "savePhaseSpeedVsFrequencyByScanAxis"];
    summaryNames = [summaryRendererNames; summarySaveNames];

    for index = 1:numel(summaryNames)
        qualified = "oce.plotting.summary." + summaryNames(index);
        locations = which(char(qualified), '-all');
        if ischar(locations), locations = {locations}; end
        expected = fullfile(context.repoRoot, 'src', '+oce', '+plotting', ...
            '+summary', summaryNames(index) + '.m');
        if numel(locations) ~= 1 || ~strcmpi(locations{1}, expected)
            error('OCE:RegressionPlotting:SummaryResolution', ...
                'Expected one canonical summary definition for %s; actual=%s.', ...
                qualified, strjoin(string(locations), ', '));
        end
    end

    retiredHelpers = ["oce.plotting.resolvePreviewMeridians"; ...
        "oce.plotting.plotRepresentativeSpaceTime"; ...
        "oce.plotting.prepareRepresentativeMotionPreview"; ...
        "oce.plotting.plotDispersionWindowPreviews"; ...
        "oce.plotting.saveDispersionWindowPreviews"; ...
        "oce.plotting.resolve" + retiredMeridianToken + "Layout"; ...
        "oce.plotting.plot" + retiredMeridianToken + "SpaceTime"];
    for index = 1:numel(retiredHelpers)
        if ~isempty(which(char(retiredHelpers(index)), '-all'))
            error('OCE:RegressionPlotting:RetiredHelper', ...
                'Retired plotting helper still resolves: %s.', ...
                retiredHelpers(index));
        end
    end

    packageFiles = dir(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', '**', '*.m'));
    forbidden = '\<(eval|evalin|assignin|cd)\s*\(';
    for index = 1:numel(packageFiles)
        source = fileread(fullfile(packageFiles(index).folder, packageFiles(index).name));
        if ~isempty(regexp(source, forbidden, 'once'))
            error('OCE:RegressionPlotting:ForbiddenApi', ...
                'Forbidden API found in %s.', packageFiles(index).name);
        end
    end

    retired = ["plotExperimentAngleDispersionSummary"; ...
        "plotExperimentPhaseSpeedPolarSummary"; ...
        "plotExperimentRepetitionDispersionSummary"; ...
        "plotExperimentThicknessPolarSummary"; ...
        "plotPhaseSpeedVsFrequencyAngleAveraged"; ...
        "plotPhaseSpeedVsFrequencyByAngle"; ...
        "plotPhaseSpeedVsFrequencyBy" + retiredMeridianToken; ...
        "plot_polar_phase_results"];
    for index = 1:numel(retired)
        if ~isempty(which(char(retired(index)), '-all'))
            error('OCE:RegressionPlotting:RetiredAdapter', ...
                'Retired plotting adapter still resolves: %s.', retired(index));
        end
    end

    retiredSummaryPackage = [ ...
        "oce.plotting.summary.plotExperimentPhaseSpeedPolarSummary"; ...
        "oce.plotting.summary.plotExperimentThicknessPolarSummary"; ...
        "oce.plotting.summary.plotExperimentRepetitionDispersionSummary"; ...
        "oce.plotting.summary.plotExperimentAngleDispersionSummary"; ...
        "oce.plotting.summary.saveExperimentPhaseSpeedPolarSummary"; ...
        "oce.plotting.summary.saveExperimentThicknessPolarSummary"; ...
        "oce.plotting.summary.saveExperimentRepetitionDispersionSummary"; ...
        "oce.plotting.summary.saveExperimentAngleDispersionSummary"; ...
        "oce.plotting.summary.plotPhaseSpeedVsFrequencyBy" + retiredMeridianToken; ...
        "oce.plotting.summary.savePhaseSpeedVsFrequencyBy" + retiredMeridianToken];
    for index = 1:numel(retiredSummaryPackage)
        if ~isempty(which(char(retiredSummaryPackage(index)), '-all'))
            error('OCE:RegressionPlotting:RetiredSummaryApi', ...
                'Retired summary plotting API still resolves: %s.', ...
                retiredSummaryPackage(index));
        end
    end

    oldSummaryNamespace = "oce.plotting." + summaryNames;
    for index = 1:numel(oldSummaryNamespace)
        if ~isempty(which(char(oldSummaryNamespace(index)), '-all'))
            error('OCE:RegressionPlotting:RetiredSummaryNamespace', ...
                'Ungrouped summary plotting API still resolves: %s.', ...
                oldSummaryNamespace(index));
        end
    end

    engine = fileread(fullfile(context.repoRoot, 'src', '+oce', '+pipeline', ...
        'runSingleAcquisition.m'));
    outputRouter = fileread(fullfile(context.repoRoot, 'src', '+oce', '+pipeline', ...
        'private', 'generateRequestedOutputs.m'));
    removed = {'save_bmode_preview', 'save_border_preview', 'save_filter_previews', ...
        'save_dispersion_window_previews', 'save_speed_dispersion_preview', ...
        'safe_normalize', 'close_generated_figures'};
    for index = 1:numel(removed)
        if contains(engine, ['function ' removed{index}]) || ...
                contains(outputRouter, ['function ' removed{index}])
            error('OCE:RegressionPlotting:LocalDuplicate', ...
                'Local plotting helper remains active: %s.', removed{index});
        end
    end
    if ~contains(engine, 'generateRequestedOutputs') || ...
            ~contains(outputRouter, 'oce.plotting.saveReconstructionPreview') || ...
            ~contains(outputRouter, 'oce.plotting.saveDispersionWindowContext') || ...
            ~contains(outputRouter, 'oce.plotting.saveDispersionKfPreview') || ...
            ~contains(outputRouter, 'oce.plotting.saveSpeedDispersionPreview') || ...
            ~contains(outputRouter, 'oce.plotting.savePolarPhaseResults') || ...
            ~contains(outputRouter, 'oce.video.createFilteredMotionVideo')
        error('OCE:RegressionPlotting:Caller', ...
            'Maintained output routing does not use canonical output owners.');
    end

    savePairs = {
        'saveReconstructionPreview.m', 'oce.plotting.plotReconstructionPreview';
        'saveFilterPreviews.m', 'oce.plotting.plotFilterPreviews';
        'saveCompleteSpaceTime.m', 'oce.plotting.plotCompleteSpaceTime';
        'saveDispersionWindowContext.m', ...
            'oce.plotting.plotDispersionWindowContext';
        'saveDispersionKfPreview.m', ...
            'oce.plotting.plotDispersionKfPreview';
        'saveSpeedDispersionPreview.m', ...
            'oce.plotting.plotSpeedDispersionPreview';
        'savePolarPhaseResults.m', 'oce.plotting.plotPolarPhaseResults'};
    for index = 1:size(savePairs, 1)
        saveSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
            '+plotting', savePairs{index, 1}));
        if ~contains(saveSource, savePairs{index, 2})
            error('OCE:RegressionPlotting:RendererReuse', ...
                '%s does not reuse %s.', savePairs{index, 1}, savePairs{index, 2});
        end
    end

    summarySavePairs = {
        'savePhaseSpeedPolarSummary.m', ...
            'oce.plotting.summary.plotPhaseSpeedPolarSummary';
        'saveThicknessPolarSummary.m', ...
            'oce.plotting.summary.plotThicknessPolarSummary';
        'saveRepetitionAveragedDispersionSummary.m', ...
            'oce.plotting.summary.plotRepetitionAveragedDispersionSummary';
        'saveAngleAveragedDispersionSummary.m', ...
            'oce.plotting.summary.plotAngleAveragedDispersionSummary';
        'savePhaseSpeedVsFrequencyByAngle.m', ...
            'oce.plotting.summary.plotPhaseSpeedVsFrequencyByAngle';
        'savePhaseSpeedVsFrequencyAngleAveraged.m', ...
            'oce.plotting.summary.plotPhaseSpeedVsFrequencyAngleAveraged';
        'savePhaseSpeedVsFrequencyByScanAxis.m', ...
            'oce.plotting.summary.plotPhaseSpeedVsFrequencyByScanAxis'};
    for index = 1:size(summarySavePairs, 1)
        saveSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
            '+plotting', '+summary', summarySavePairs{index, 1}));
        if ~contains(saveSource, summarySavePairs{index, 2})
            error('OCE:RegressionPlotting:SummaryRendererReuse', ...
                '%s does not reuse %s.', ...
                summarySavePairs{index, 1}, summarySavePairs{index, 2});
        end
    end

    phaseSaveNames = ["saveFilterPreviews.m"; ...
        "saveCompleteSpaceTime.m"; "saveDispersionWindowContext.m"];
    for index = 1:numel(phaseSaveNames)
        saveSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
            '+plotting', phaseSaveNames(index)));
        if ~contains(saveSource, 'varargin{:}')
            error('OCE:RegressionPlotting:CLimForwarding', ...
                '%s must forward the renderer CLim policy.', phaseSaveNames(index));
        end
    end

    motionResolver = 'oce.plotting.resolveMotionOverlayCLim';
    animationSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', 'showDepthMotionAnimation.m'));
    videoSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+video', 'createFilteredMotionVideo.m'));
    if ~contains(animationSource, motionResolver) || ...
            ~contains(videoSource, motionResolver)
        error('OCE:RegressionPlotting:MotionCLimOwnership', ...
            'Motion preview and persisted video must share one CLim owner.');
    end
    requiredVideoRendering = [ ...
        "'MedianWindow', [5 3]"; ...
        "oce.plotting.postprocessMotionOverlayFrame"; ...
        "writer.Quality = 95"; ...
        "layoutTitle.String"; ...
        "ax.Toolbar.Visible = 'off'"];
    if any(~contains(videoSource, requiredVideoRendering))
        error('OCE:RegressionPlotting:VideoRendering', ...
            'Filtered video must preserve the maintained visual denoising/layout contract.');
    end

    contextSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', 'plotDispersionWindowContext.m'));
    if ~contains(contextSource, 'oce.plotting.plotBmodeSpaceTime') || ...
            contains(contextSource, 'imagesc(') || contains(contextSource, 'clim(')
        error('OCE:RegressionPlotting:SpaceTimeRendererReuse', ...
            'Dispersion-window context must reuse the shared space-time renderer.');
    end

    polarPlotSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', 'plotPolarPhaseResults.m'));
    if contains(polarPlotSource, 'saveas(') || ...
            contains(polarPlotSource, 'exportgraphics(')
        error('OCE:RegressionPlotting:PolarRendererPersistence', ...
            'plotPolarPhaseResults must remain display-only.');
    end

    filterSaveSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', 'saveFilterPreviews.m'));
    if ~contains(filterSaveSource, '''BmodeMode'', "all"') || ...
            ~contains(videoSource, '''BmodeMode'', "all"') || ...
            ~contains(videoSource, 'data.selection.row_count') || ...
            ~contains(videoSource, 'OCE:Video:FilteringRequired')
        error('OCE:RegressionPlotting:CompleteBmodeOutput', ...
            'Saved space-time and filtered video must render complete B-mode mosaics.');
    end

    resultsCaller = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'runSubexperimentSummary.m'));
    if count(resultsCaller, 'oce.plotting.summary.') ~= 6
        error('OCE:RegressionPlotting:Caller', ...
            'Results summary must use six grouped canonical summary plots.');
    end

    experimentSummaryCaller = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'runExperimentSummary.m'));
    requiredExperimentSummaryOwners = [ ...
        "oce.plotting.summary.savePhaseSpeedVsFrequencyByScanAxis"; ...
        "oce.plotting.summary.savePhaseSpeedPolarSummary"];
    for index = 1:numel(requiredExperimentSummaryOwners)
        if ~contains(experimentSummaryCaller, requiredExperimentSummaryOwners(index))
            error('OCE:RegressionPlotting:ExperimentSummaryCaller', ...
                'Experiment summary must use canonical owner: %s.', ...
                requiredExperimentSummaryOwners(index));
        end
    end
end
