function test_pipeline_domain_resolution(context)
%TEST_PIPELINE_DOMAIN_RESOLUTION Verify canonical pipeline ownership.

    names = ["prepareAcquisitionRun"; "runSingleAcquisition"; ...
        "runBatchProcessing"; "runSubexperimentSummary"; ...
        "runExperimentSummary"; ...
        "processPreparedAcquisition"; "resolveOutputDirectory"];
    for index = 1:numel(names)
        qualified = "oce.pipeline." + names(index);
        locations = which(char(qualified), '-all');
        if ischar(locations), locations = {locations}; end
        expected = fullfile(context.repoRoot, 'src', '+oce', '+pipeline', ...
            names(index) + '.m');
        if numel(locations) ~= 1 || ~strcmpi(locations{1}, expected)
            error('OCE:RegressionPipeline:Resolution', ...
                'Expected one definition for %s; actual=%s.', ...
                qualified, strjoin(string(locations), ', '));
        end
    end
    packageFiles = dir(fullfile(context.repoRoot, 'src', '+oce', '+pipeline', '*.m'));
    forbidden = '\<(cd|assignin|eval|evalin|addpath)\s*\(|\<global\>';
    for index = 1:numel(packageFiles)
        source = fileread(fullfile(packageFiles(index).folder, packageFiles(index).name));
        if ~isempty(regexp(source, forbidden, 'once'))
            error('OCE:RegressionPipeline:ForbiddenApi', ...
                'Forbidden API in %s.', packageFiles(index).name);
        end
        if contains(source, "exist('") && contains(source, "'file'")
            error('OCE:RegressionPipeline:PathFallback', ...
                'Path-dependent implementation fallback in %s.', packageFiles(index).name);
        end
    end

    assert_prepared_contract_ownership(context.repoRoot);

    retired = ["run_full_processing_single", "run_batch_processing", ...
        "run_results_summary", "PP_MBmode_Phantom_test_v2", ...
        "run_single_acquisition", "oce.pipeline.runResultsSummary", ...
        "oce.pipeline.runExperimentMeridianSummary"];
    for index = 1:numel(retired)
        if ~isempty(which(char(retired(index)), '-all'))
            error('OCE:RegressionPipeline:RetiredAdapter', ...
                'Retired pipeline adapter still resolves: %s.', retired(index));
        end
    end
end

function assert_prepared_contract_ownership(repoRoot)
    calculation = fileread(fullfile(repoRoot, 'src', '+oce', '+pipeline', ...
        'processPreparedAcquisition.m'));
    entrypoint = fileread(fullfile(repoRoot, 'src', '+oce', '+pipeline', ...
        'runSingleAcquisition.m'));
    outputResolver = fileread(fullfile(repoRoot, 'src', '+oce', '+pipeline', ...
        'resolveOutputDirectory.m'));

    duplicatedSchemaTokens = ["requiredConfig ="; "expectedRunFields ="; ...
        "validate_parallel_contract"; "isfile(processingInputs.fullfile)"];
    if any(contains(calculation, duplicatedSchemaTokens))
        error('OCE:RegressionPipeline:PreparedContractOwnership', ...
            ['processPreparedAcquisition must consume prepared inputs and ' ...
             'resolved options without duplicating their owner schemas.']);
    end
    if ~contains(entrypoint, "'ValidateFiles', false")
        error('OCE:RegressionPipeline:InventoryValidationOwnership', ...
            ['Single acquisition execution must not repeat whole-subexperiment ' ...
             'inventory validation for every batch item.']);
    end
    if ~contains(outputResolver, 'processingInputs.acquisition_row.filename') || ...
            ~contains(outputResolver, 'fileparts') || ...
            contains(outputResolver, 'acquisition_row.run_id') || ...
            contains(outputResolver, 'makeValidName')
        error('OCE:RegressionPipeline:OutputDirectoryOwnership', ...
            ['Per-acquisition output directories must use the acquisition ' ...
             'filename without its extension.']);
    end

    acquisitionRow = table("R999", "sample-acquisition.bin", ...
        'VariableNames', {'run_id', 'filename'});
    processingInputs = struct( ...
        'acquisition_row', acquisitionRow, ...
        'resultsDir', fullfile(repoRoot, 'ResultsTestRoot'));
    actualOutput = string(oce.pipeline.resolveOutputDirectory(processingInputs));
    expectedOutput = string(fullfile( ...
        repoRoot, 'ResultsTestRoot', 'sample-acquisition'));
    if actualOutput ~= expectedOutput
        error('OCE:RegressionPipeline:OutputDirectoryContract', ...
            'Filename-based output directory resolved incorrectly.');
    end
end
