function test_canonical_helper_ownership_contract(context)
%TEST_CANONICAL_HELPER_OWNERSHIP_CONTRACT Verify canonical helper ownership.

    expectedCanonical = [ ...
        "oce.borders.findSurface", "src/+oce/+borders/findSurface.m"; ...
        "oce.motion.estimateLoupasPhaseIncrement", ...
            "src/+oce/+motion/estimateLoupasPhaseIncrement.m"];
    for index = 1:size(expectedCanonical, 1)
        resolved = string(which(expectedCanonical(index, 1), '-all'));
        assert(isscalar(resolved) && endsWith(normalize_path(resolved), ...
            expectedCanonical(index, 2)), ...
            'Canonical helper resolution is not unique: %s.', ...
            expectedCanonical(index, 1));
    end

    assert(isempty(which('FindSurface', '-all')), ...
        'Flat FindSurface still resolves.');
    assert(isempty(which('Loupas2D_Fast', '-all')), ...
        'Flat Loupas2D_Fast still resolves.');
    assert(~isfile(fullfile(context.repoRoot, 'Codes', 'FindSurface.m')), ...
        'Codes/FindSurface.m still exists.');
    assert(~isfile(fullfile(context.repoRoot, 'Codes', 'Loupas2D_Fast.m')), ...
        'Codes/Loupas2D_Fast.m still exists.');

    inheritedRoot = fullfile(context.repoRoot, 'inherited');
    assert(isfolder(fullfile(inheritedRoot, 'Codes')), ...
        'Preserved inherited/Codes reference tree is missing.');
    assert(isfolder(fullfile(inheritedRoot, 'Processing')), ...
        'Preserved inherited/Processing reference tree is missing.');
    pathEntries = normalize_path(string(strsplit(path, pathsep)));
    assert(~any(startsWith(pathEntries, normalize_path(inheritedRoot))), ...
        'The inherited reference tree must remain off the MATLAB path.');

    borderCaller = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+borders', '+methods', 'findPhantomBorders.m'));
    assert(count(borderCaller, 'oce.borders.findSurface(') == 2, ...
        'Phantom border caller does not use the canonical surface detector.');
    motionCaller = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+motion', 'computeDepthResolvedPhase.m'));
    borderMotionCaller = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+motion', 'computeSurfacePhase.m'));
    assert(count(motionCaller, ...
        'oce.motion.estimateLoupasPhaseIncrement(') == 1, ...
        'Depth-resolved phase canonical Loupas ownership changed.');
    assert(count(borderMotionCaller, ...
        'oce.motion.estimateLoupasPhaseIncrement(') == 1, ...
        'Surface phase canonical Loupas ownership changed.');

    scan_roots_for_flat_calls(context.repoRoot);
    assert_forbidden_apis(fullfile(context.repoRoot, 'src', '+oce', ...
        '+borders', 'findSurface.m'));
    assert_forbidden_apis(fullfile(context.repoRoot, 'src', '+oce', ...
        '+motion', 'estimateLoupasPhaseIncrement.m'));
end

function scan_roots_for_flat_calls(repoRoot)
    roots = [fullfile(repoRoot, 'src'); fullfile(repoRoot, 'workflows')];
    forbidden = ["FindSurface("; "Loupas2D_Fast("];
    for rootIndex = 1:numel(roots)
        files = dir(fullfile(roots(rootIndex), '**', '*.m'));
        for fileIndex = 1:numel(files)
            source = string(fileread(fullfile(files(fileIndex).folder, ...
                files(fileIndex).name)));
            for tokenIndex = 1:numel(forbidden)
                assert(~contains(source, forbidden(tokenIndex)), ...
                    'Flat helper call remains in %s: %s.', ...
                    files(fileIndex).name, forbidden(tokenIndex));
            end
        end
    end
end

function assert_forbidden_apis(filename)
    source = string(fileread(filename));
    forbidden = ["cd("; "assignin("; "eval("; "evalin("; ...
        "global "; "addpath("; "genpath("];
    for index = 1:numel(forbidden)
        assert(~contains(source, forbidden(index)), ...
            'Forbidden API %s found in %s.', forbidden(index), filename);
    end
end

function value = normalize_path(value)
    value = replace(string(value), "\", "/");
end
