function test_dispersion_analysis_resolution(context)
%TEST_DISPERSION_ANALYSIS_RESOLUTION Verify canonical analysis ownership.

    canonical = {
        'oce.dispersion.computePhaseGradientSpeed', ...
            'src/+oce/+dispersion/computePhaseGradientSpeed.m';
        'oce.config.resolveDispersionAnalysisOptions', ...
            'src/+oce/+config/resolveDispersionAnalysisOptions.m';
        'oce.dispersion.computeDirectionalPhaseSpeed', ...
            'src/+oce/+dispersion/computeDirectionalPhaseSpeed.m';
        'oce.dispersion.computeDispersionSpectrum', ...
            'src/+oce/+dispersion/computeDispersionSpectrum.m';
        'oce.dispersion.analyzeWindows', ...
            'src/+oce/+dispersion/analyzeWindows.m';
        'oce.dispersion.orderBidirectionalAngles', ...
            'src/+oce/+dispersion/orderBidirectionalAngles.m';
        'oce.results.computeScalarStatistics', ...
            'src/+oce/+results/computeScalarStatistics.m';
        'oce.results.buildScientificResult', ...
            'src/+oce/+results/buildScientificResult.m';
        'oce.results.validateScientificResult', ...
            'src/+oce/+results/validateScientificResult.m';
        'oce.io.saveScientificResult', ...
            'src/+oce/+io/saveScientificResult.m';
        'oce.io.loadScientificResult', ...
            'src/+oce/+io/loadScientificResult.m'};
    assert_unique_locations(canonical, context.repoRoot);
    assert_absent(["oce.dispersion.buildAnalysisParameters", ...
        "oce.dispersion.legacy.computeWindowedPhaseSpeed", ...
        "oce.dispersion.legacy.computeDispersionSpectrum", ...
        "DisperssionSpeedFullWin", "IDXSelection", "DispersionK"]);

    fixture = create_dispersion_analysis_fixture();
    options = fixture.DispersionAnalysisOptions;
    first = oce.dispersion.analyzeWindows( ...
        fixture.window_result, fixture.DistBorder, options);
    second = oce.dispersion.analyzeWindows( ...
        fixture.window_result, fixture.DistBorder, options);
    if ~isequaln(first, second)
        error('OCE:DispersionAnalysisTest:Determinism', ...
            'Repeated analysis of identical inputs changed the result.');
    end

    withoutThickness = oce.dispersion.analyzeWindows( ...
        fixture.window_result, nan(size(fixture.DistBorder)), options);
    baselineSpeed = reshape(arrayfun(@(item) ...
        item.target_selection.selected_phase_speed_m_per_s, ...
        first.directions), [], 1);
    noThicknessSpeed = reshape(arrayfun(@(item) ...
        item.target_selection.selected_phase_speed_m_per_s, ...
        withoutThickness.directions), [], 1);
    noThicknessMean = reshape( ...
        [withoutThickness.directions.mean_thickness_mm], [], 1);
    if ~isequaln(baselineSpeed, noThicknessSpeed) || ...
            ~all(isnan(noThicknessMean))
        error('OCE:DispersionAnalysisTest:OptionalThickness', ...
            ['Unavailable thickness must remain NaN without changing the ' ...
             'directional phase-speed result.']);
    end

    calculationCaller = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'processPreparedAcquisition.m'));
    requiredCalls = ["oce.config.resolveDispersionAnalysisOptions", ...
        "oce.dispersion.analyzeWindows", ...
        "oce.results.buildScientificResult"];
    for index = 1:numel(requiredCalls)
        if count(calculationCaller, requiredCalls(index)) ~= 1
            error('OCE:DispersionAnalysisTest:Caller', ...
                'Pipeline must call %s exactly once.', requiredCalls(index));
        end
    end
    entrypoint = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+pipeline', 'runSingleAcquisition.m'));
    if count(entrypoint, "oce.io.saveScientificResult") ~= 1 || ...
            contains(calculationCaller, "oce.io.saveScientificResult")
        error('OCE:DispersionAnalysisTest:Caller', ...
            'Only the single-run entrypoint may persist scientific results.');
    end
    forbidden = ["buildAnalysisParameters", "ParamsDisp", ...
        "oce.dispersion.legacy"];
    for index = 1:numel(forbidden)
        if contains(calculationCaller, forbidden(index))
            error('OCE:DispersionAnalysisTest:RetiredRuntime', ...
                'Pipeline contains retired runtime text: %s.', ...
                forbidden(index));
        end
    end
end

function assert_absent(names)
    for index = 1:numel(names)
        if ~isempty(which(char(names(index)), '-all'))
            error('OCE:DispersionAnalysisTest:RetiredResolution', ...
                'Retired function still resolves: %s.', names(index));
        end
    end
end

function assert_unique_locations(expected, repoRoot)
    for index = 1:size(expected, 1)
        locations = string(which(expected{index, 1}, '-all'));
        locations = locations(strlength(locations) > 0);
        expectedPath = fullfile(repoRoot, expected{index, 2});
        if numel(locations) ~= 1 || ...
                ~strcmpi(normalize_path(locations), ...
                    normalize_path(expectedPath))
            error('OCE:DispersionAnalysisTest:Resolution', ...
                'Unexpected resolution for %s.', expected{index, 1});
        end
    end
end

function value = normalize_path(value)
    value = replace(string(value), ["/", "\"], filesep);
end
