function test_synthetic_golden_harness_contract(context)
%TEST_SYNTHETIC_GOLDEN_HARNESS_CONTRACT Protect self-contained golden ownership.

    runnerPath = fullfile(context.repoRoot, 'tests', 'runners', ...
        'run_regression_tests.m');
    snapshotPath = fullfile(context.repoRoot, 'tests', 'helpers', ...
        'create_synthetic_scientific_golden_snapshot.m');
    runner = fileread(runnerPath);
    snapshot = fileread(snapshotPath);

    requiredRunner = [ ...
        "addParameter(p, 'UpdateBaseline', false"; ...
        "synthetic_scientific_golden_manifest(repoRoot)"; ...
        "create_synthetic_scientific_golden_snapshot()"; ...
        "save(context.goldenManifest.goldenFile, 'baseline', '-v7')"; ...
        "assert_baseline_is_safe(baseline)"];
    assert_contains_all(runner, requiredRunner, ...
        'OCE:SyntheticGoldenHarness:MissingContract');

    forbiddenExternal = [ ...
        "DataRoot"; "RunScientific"; "OCE_TEST_DATA_ROOT"; ...
        "resolve_r004_dataset"; "execute_r004_regression_case"; ...
        "r004_regression_manifest"; "r004_lightweight_baseline.mat"];
    assert_contains_none(runner, forbiddenExternal, ...
        'OCE:SyntheticGoldenHarness:ExternalDependency');

    requiredSnapshot = [ ...
        "create_synthetic_scientific_golden_fixture()"; ...
        "oce.borders.detectAndMask"; ...
        "oce.dispersion.analyzeWindows"; ...
        "oce.results.buildScientificResult"];
    assert_contains_all(snapshot, requiredSnapshot, ...
        'OCE:SyntheticGoldenHarness:ScientificChain');

    retiredPaths = [ ...
        fullfile(context.repoRoot, 'tests', 'fixtures', 'r004_regression_manifest.m'); ...
        fullfile(context.repoRoot, 'tests', 'helpers', 'resolve_r004_dataset.m'); ...
        fullfile(context.repoRoot, 'tests', 'helpers', 'execute_r004_regression_case.m'); ...
        fullfile(context.repoRoot, 'tests', 'fixtures', 'r004_lightweight_baseline.mat')];
    if any(arrayfun(@isfile, retiredPaths))
        error('OCE:SyntheticGoldenHarness:RetiredR004Artifact', ...
            'Retired R004 regression artifacts still exist.');
    end
end

function assert_contains_all(source, values, identifier)
    missing = values(~arrayfun(@(value) contains(source, value), values));
    if ~isempty(missing)
        error(identifier, 'Required contract text is missing: %s.', ...
            strjoin(missing, ', '));
    end
end

function assert_contains_none(source, values, identifier)
    found = values(arrayfun(@(value) contains(source, value), values));
    if ~isempty(found)
        error(identifier, 'Forbidden contract text is present: %s.', ...
            strjoin(found, ', '));
    end
end
