function [fitresult, gof] = LinealFit(Xfit, Yfit)
%CREATEFIT(XFIT,YFIT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Xfit
%      Y Output: Yfit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Feb-2020 21:05:11


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Xfit, Yfit );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Yfit vs. Xfit', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Xfit', 'Interpreter', 'none' );
ylabel( 'Yfit', 'Interpreter', 'none' );
grid on


