function [fitresult, gof] = Poly2DFitting(xfit, yfit, zfit)
%realiza un ajuste polinomico

%CREATEFIT(XFIT,YFIT,ZFIT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xfit
%      Y Input : yfit
%      Z Output: zfit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Feb-2020 18:22:08


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xfit, yfit, zfit );

% Set up fittype and options.
ft = fittype( 'poly11' );%define el tipo de ajuste como un polinomio de primer grado
opts = fitoptions( 'Method', 'LinearLeastSquares' );%especifica que el ajuste se realiza utilizando el método de mínimos cuadrados lineales
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );
%fitresult es el objeto de ajuste que contiene la información del modelo ajustado
%gof es una estructura que contiene estadísticas sobre la calidad del ajuste, como el coeficiente R

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'zfit vs. xfit, yfit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'xfit', 'Interpreter', 'none' );
% ylabel( 'yfit', 'Interpreter', 'none' );
% zlabel( 'zfit', 'Interpreter', 'none' );
% grid on
% view( 5.3, -13.5 );


