function test_interactive_acquisition_helpers(context) %#ok<INUSD>
%TEST_INTERACTIVE_ACQUISITION_HELPERS Validate crop interaction boundaries.

    fixture = createInteractiveAcquisitionFixture('double');
    depthRectangle = [1.2 -2.2 2.1 6.1];
    interaction = preview_interaction(depthRectangle);
    depth = oce.acquisition.selectDepthCropFromPreview( ...
        fixture.measurement, fixture.OCT_system, fixture.geometry, ...
        struct('selection', "interactive", ...
            'bmode_intensity_limits_db', [10 80]), interaction);

    assert(depth.selection == "interactive");
    assert(depth.start_index_inclusive == 1);
    assert(depth.end_index_inclusive == 4);
    assert(size(depth.cropped_preview_db, 1) == ...
        depth.end_index_inclusive - depth.start_index_inclusive + 1);
    assert(numel(depth.bmode_intensity_limits_db) == 2);
    assert(all(isfinite(depth.bmode_intensity_limits_db)));
    assert(depth.bmode_intensity_limits_db(1) < ...
        depth.bmode_intensity_limits_db(2));
    assert(isequal(depth.bmode_intensity_limits_db, [10 80]));

    points = [2.2 2.1 1; 3.4 1.8 1];
    timeRectangle = [-20.4 -5 60.2 10];
    time = oce.acquisition.selectTimeCropFromPhasePreview( ...
        fixture.measurement, fixture.OCT_system, fixture.geometry, ...
        depth, depth.bmode_intensity_limits_db, ...
        struct('selection', "interactive"), 2, ...
        time_interaction(points, timeRectangle));
    assert(time.selection == "interactive");
    assert(time.start_index_inclusive == 1);
    assert(time.end_index_inclusive == 40);

    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        oce.acquisition.selectDepthCropFromPreview( ...
            fixture.measurement, fixture.OCT_system, fixture.geometry, ...
            struct('selection', "interactive", ...
                'bmode_intensity_limits_db', [10 80]), ...
            preview_interaction([1.2 -20 2.1 3])));
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        oce.acquisition.selectTimeCropFromPhasePreview( ...
            fixture.measurement, fixture.OCT_system, fixture.geometry, ...
            depth, depth.bmode_intensity_limits_db, ...
            struct('selection', "interactive"), 2, ...
            time_interaction(points, [-20 -5 5 10])));

    manualDepth = oce.acquisition.selectDepthCropFromPreview( ...
        fixture.measurement, fixture.OCT_system, fixture.geometry, ...
        struct('selection', "manual_indices", ...
            'start_index_inclusive', 2, ...
            'end_index_inclusive', 6, ...
            'bmode_intensity_limits_db', [10 80], ...
            'depth_limit', fixture.geometry.available_depth_sample_count), ...
        forbidden_interaction());
    assert(manualDepth.selection == "manual_indices");
    assert(isequal(size(manualDepth.cropped_preview_db), [5 4]));

    manualTime = oce.acquisition.selectTimeCropFromPhasePreview( ...
        fixture.measurement, fixture.OCT_system, fixture.geometry, ...
        manualDepth, [10 80], ...
        struct('selection', "manual_indices", ...
            'start_index_inclusive', 3, ...
            'end_index_inclusive', 90), 2, forbidden_interaction());
    assert(manualTime.selection == "manual_indices");
    assert(manualTime.start_index_inclusive == 3);
    assert(manualTime.end_index_inclusive == 90);

    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        invalid_depth(fixture, 0, 2));
    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        invalid_depth(fixture, 2, fixture.geometry.available_depth_sample_count + 1));
    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        invalid_depth(fixture, 5, 2));
    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        invalid_depth(fixture, 1.5, 2));
    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        invalid_depth(fixture, NaN, 2));
    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        invalid_depth(fixture, 1, Inf));
    assert_identifier('OCE:Acquisition:InvalidDepthCrop', @() ...
        invalid_depth(fixture, [1 2], 3));

    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        invalid_time(fixture, manualDepth, 0, 2));
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        invalid_time(fixture, manualDepth, 2, ...
            fixture.geometry.temporal_repetition_count + 1));
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        invalid_time(fixture, manualDepth, 8, 2));
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        invalid_time(fixture, manualDepth, 1.5, 2));
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        invalid_time(fixture, manualDepth, NaN, 2));
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        invalid_time(fixture, manualDepth, 1, Inf));
    assert_identifier('OCE:Acquisition:InvalidTimeCrop', @() ...
        invalid_time(fixture, manualDepth, [1 2], 3));
    assert_identifier('OCE:Acquisition:InvalidDisplayLimits', @() ...
        invalid_display(fixture));
end

function invalid_depth(fixture, startIndex, endIndex)
    oce.acquisition.selectDepthCropFromPreview( ...
        fixture.measurement, fixture.OCT_system, fixture.geometry, ...
        struct('selection', "manual_indices", ...
            'start_index_inclusive', startIndex, ...
            'end_index_inclusive', endIndex, ...
            'bmode_intensity_limits_db', [10 80], ...
            'depth_limit', fixture.geometry.available_depth_sample_count), ...
        forbidden_interaction());
end

function invalid_time(fixture, depth, startIndex, endIndex)
    oce.acquisition.selectTimeCropFromPhasePreview( ...
        fixture.measurement, fixture.OCT_system, fixture.geometry, ...
        depth, [10 80], struct('selection', "manual_indices", ...
            'start_index_inclusive', startIndex, ...
            'end_index_inclusive', endIndex), 2, ...
        forbidden_interaction());
end

function invalid_display(fixture)
    oce.acquisition.selectDepthCropFromPreview( ...
        fixture.measurement, fixture.OCT_system, fixture.geometry, ...
        struct('selection', "manual_indices", ...
            'start_index_inclusive', 2, ...
            'end_index_inclusive', 6, ...
            'bmode_intensity_limits_db', [80 10], ...
            'depth_limit', fixture.geometry.available_depth_sample_count), ...
        forbidden_interaction());
end

function interaction = preview_interaction(rectangle)
    interaction = struct();
    interaction.createFigure = @() figure('Visible', 'off');
    interaction.selectRectangle = @(axesHandle, initialPosition) ...
        return_rectangle(rectangle, axesHandle, initialPosition);
end

function interaction = time_interaction(points, rectangle)
    interaction = struct();
    interaction.createFigure = @() figure('Visible', 'off');
    interaction.selectPoint = make_point_selector(points);
    interaction.selectRectangle = @(axesHandle, initialPosition) ...
        return_rectangle(rectangle, axesHandle, initialPosition);
end

function interaction = forbidden_interaction()
    interaction = struct( ...
        'createFigure', @() forbidden(), ...
        'selectRectangle', @(varargin) forbidden(varargin{:}), ...
        'selectPoint', @() forbidden());
end

function varargout = forbidden(varargin)
    varargout = cell(1, nargout); %#ok<NASGU>
    error('OCE:Test:UnexpectedInteraction', ...
        'Manual selection invoked an interactive callback.');
end

function selector = make_point_selector(points)
    currentIndex = 0;
    selector = @next_point;
    function [x, y, button] = next_point
        currentIndex = currentIndex + 1;
        selection = points(currentIndex, :);
        x = selection(1);
        y = selection(2);
        button = selection(3);
    end
end

function selected = return_rectangle(rectangle, axesHandle, initialPosition) %#ok<INUSD>
    selected = rectangle;
end

function assert_identifier(identifier, callback)
    try
        callback();
    catch ME
        assert(strcmp(ME.identifier, identifier), ...
            'Expected %s; actual %s.', identifier, ME.identifier);
        return;
    end
    error('OCE:Test:MissingError', ...
        'Expected error was not raised: %s.', identifier);
end
