function fig = plotPhasePreview(phaseResult, reconstructionResult, geometry, varargin)
%PLOTPHASEPREVIEW Render preliminary representative space-time phase maps.
% Shows only preview B-modes nearest 0 and 90 degrees. Plotting choices are
% visualization-only and never alter phase results.

    if ~isstruct(phaseResult) || ~isfield(phaseResult, 'surface') || ...
            ~isfield(phaseResult.surface, 'values') || ...
            ~isfield(phaseResult.surface, 'units')
        error('OCE:Plotting:InvalidPhaseResult', ...
            'phaseResult.surface must contain values and units.');
    end
    timeCount = size(phaseResult.surface.values, 2);
    startIndex = double(reconstructionResult.crop.time.start_index_inclusive);
    dt = double(reconstructionResult.geometry.time_sample_interval_s);
    timeOffsetS = (startIndex - 0.5) * dt;
    if isfield(phaseResult.surface, 'quantity') && ...
            string(phaseResult.surface.quantity) == "wrapped_phase"
        timeOffsetS = (startIndex - 1) * dt;
    end
    timeAxisMs = (reconstructionResult.axes.time.values(1:timeCount) + ...
        timeOffsetS) * 1e3;
    timeSampleIndices = startIndex + (0:timeCount - 1);
    fig = oce.plotting.plotBmodeSpaceTime( ...
        phaseResult.surface.values, timeAxisMs, phaseResult.surface.units, ...
        geometry, "Preliminary space-time", ...
        'BmodeMode', "representative", ...
        'TimeSampleIndices', timeSampleIndices, varargin{:});
end
