function test_filtering_domain_contract(~)
%TEST_FILTERING_DOMAIN_CONTRACT Validate explicit filtering behavior.

    fixture = create_filtering_fixture();
    resolved = oce.config.resolveFilterOptions(fixture.config_for_run, ...
        fixture.surfaceEven, fixture.OCT_system);
    assert_resolved_contract(resolved);

    design = oce.filtering.designTemporalFilter( ...
        fixture.surfaceEven, fixture.standardOCE, resolved);
    assert_design_contract(design, resolved, fixture);
    assert_design_variants(fixture, resolved);
    expectedResolved = resolved;
    expectedResolved.diagnostic.line_index_used = ...
        design.diagnostic.line_index_used;

    filtered = oce.filtering.applyTemporalFilter( ...
        fixture.depthResultEven, fixture.surfaceResultEven, design, ...
        resolved.invalid_row_policy);
    postprocessed = oce.filtering.postprocessSurfacePhase( ...
        filtered.surface, resolved.surface_postprocessing);
    assert_application_contract(filtered, postprocessed, fixture);

    phaseResult = struct( ...
        'depth_resolved', fixture.depthResultEven, ...
        'surface', fixture.surfaceResultEven, ...
        'options', struct());
    [assembled, assembledOptions] = oce.filtering.filterPhaseResults( ...
        phaseResult, fixture.config_for_run, fixture.OCT_system, ...
        fixture.standardOCE);
    expectedFields = ["enabled"; "method"; "applied"; "depth"; ...
        "surface"; "depth_temporal_mean"; "surface_postprocessed"; ...
        "invalid_rows"; "design"; "time_axis_s"; ...
        "frequency_axis_hz"];
    if ~isequaln(assembledOptions, expectedResolved) || ...
            ~isequal(string(fieldnames(assembled)), expectedFields) || ...
            ~isequaln(assembled.depth, filtered.depth) || ...
            ~isequaln(assembled.surface, filtered.surface) || ...
            ~isequaln(assembled.surface_postprocessed, postprocessed)
        error('OCE:FilteringTest:SharedBoundary', ...
            'Shared filtering boundary changed the maintained result.');
    end

    [surfaceOnly, surfaceOnlyOptions] = oce.filtering.filterSurfacePhase( ...
        fixture.surfaceResultEven, fixture.config_for_run, ...
        fixture.OCT_system, fixture.standardOCE);
    expectedSurfaceFields = ["enabled"; "method"; "applied"; "surface"; ...
        "surface_postprocessed"; "invalid_rows"; "design"; ...
        "time_axis_s"; "frequency_axis_hz"];
    if ~isequaln(surfaceOnlyOptions, expectedResolved) || ...
            ~isequal(string(fieldnames(surfaceOnly)), expectedSurfaceFields) || ...
            ~isequaln(surfaceOnly.surface, filtered.surface) || ...
            ~isequaln(surfaceOnly.surface_postprocessed, postprocessed) || ...
            ~isequaln(surfaceOnly.invalid_rows, filtered.invalid_rows) || ...
            ~isequaln(surfaceOnly.design, design)
        error('OCE:FilteringTest:SurfaceBoundary', ...
            'Surface-only filtering changed the maintained filtering result.');
    end

    assert_disabled_passthrough(fixture, resolved);
    assert_invalid_rows(fixture, design, resolved);
    assert_postprocessing_controls(filtered.surface, resolved);
    assert_validation_errors(fixture, resolved);
end

function assert_resolved_contract(options)
    expected = ["enabled"; "method"; "sampling_frequency_hz"; ...
        "sample_interval_s"; "nyquist_frequency_hz"; "frequency"; ...
        "order"; "diagnostic"; "surface_postprocessing"; ...
        "invalid_row_policy"];
    if ~isequal(string(fieldnames(options)), expected) || ...
            ~options.enabled || options.method ~= "fir_bandpass" || ...
            options.sampling_frequency_hz ~= 20000 || ...
            options.sample_interval_s ~= 1 / 20000 || ...
            options.frequency.center_hz ~= 1000 || ...
            options.frequency.bandwidth_hz ~= 400 || ...
            ~isequal(options.frequency.requested_passband_hz, [800 1200]) || ...
            options.frequency.passband_was_clamped || ...
            options.order ~= 20 || options.diagnostic.fft_length ~= 256 || ...
            ~isempty(options.diagnostic.line_index) || ...
            ~isempty(options.diagnostic.line_index_used) || ...
            options.invalid_row_policy ~= ...
                "zero_surface_and_matching_depth"
        error('OCE:FilteringTest:ResolvedContract', ...
            'Resolved FilterOptions does not match the maintained contract.');
    end
end

function assert_design_contract(design, resolved, fixture)
    expectedFrequency = (0:floor(resolved.diagnostic.fft_length / 2)) * ...
        resolved.sampling_frequency_hz / resolved.diagnostic.fft_length;
    expectedTime = 0:resolved.sample_interval_s: ...
        (size(fixture.surfaceEven, 2) - 1) * resolved.sample_interval_s;
    expectedLineIndex = round(fixture.standardOCE.samples_per_bmode / 2);
    if ~design.applied || design.method ~= "fir_bandpass" || ...
            numel(design.coefficients) ~= resolved.order + 1 || ...
            design.delay_samples ~= resolved.order / 2 || ...
            design.delay_seconds ~= ...
                design.delay_samples * resolved.sample_interval_s || ...
            ~isequal(design.time_axis_s, expectedTime) || ...
            ~isequal(design.frequency_axis_hz, expectedFrequency) || ...
            design.diagnostic.line_index_used ~= expectedLineIndex || ...
            ~isequal(design.diagnostic.input_line, ...
                fixture.surfaceEven(expectedLineIndex, :)) || ...
            numel(design.diagnostic.input_spectrum) ~= numel(expectedFrequency) || ...
            ~isequal(size(design.diagnostic.input_line), ...
                [1 size(fixture.surfaceEven, 2)])
        error('OCE:FilteringTest:DesignContract', ...
            ['FIR design metadata, axes, or first-B-mode diagnostic ' ...
             'selection are inconsistent.']);
    end
end

function assert_design_variants(fixture, resolved)
    oddDesign = oce.filtering.designTemporalFilter( ...
        fixture.surfaceOdd, fixture.oddOCE, resolved);
    shortDesign = oce.filtering.designTemporalFilter( ...
        fixture.surfaceShort, fixture.shortOCE, resolved);
    if numel(oddDesign.time_axis_s) ~= size(fixture.surfaceOdd, 2) || ...
            numel(shortDesign.time_axis_s) ~= size(fixture.surfaceShort, 2)
        error('OCE:FilteringTest:TimeAxis', ...
            'Filter time axes must follow the input sample count.');
    end

    oddOrder = resolved;
    oddOrder.order = 21;
    oddOrderDesign = oce.filtering.designTemporalFilter( ...
        fixture.surfaceEven, fixture.standardOCE, oddOrder);
    if numel(oddOrderDesign.coefficients) ~= 22 || ...
            oddOrderDesign.delay_samples ~= 11
        error('OCE:FilteringTest:OddOrder', ...
            'Odd FIR order did not produce order+1 coefficients and expected delay.');
    end
end

function assert_application_contract(filtered, postprocessed, fixture)
    if ~filtered.depth.applied || ~filtered.surface.applied || ...
            filtered.depth.quantity ~= "phase_increment" || ...
            filtered.depth.units ~= "rad" || ...
            filtered.depth.layout ~= "lateral_depth_time" || ...
            filtered.surface.layout ~= "lateral_time" || ...
            filtered.invalid_rows.count ~= 0 || ...
            ~isequal(size(filtered.depth.values), size(fixture.depthEven)) || ...
            ~isequal(size(filtered.surface.values), size(fixture.surfaceEven)) || ...
            ~postprocessed.temporal_mean_removed || ...
            ~postprocessed.median_applied || ...
            ~isequal(postprocessed.median_window_samples, [3 3]) || ...
            ~isequal(size(postprocessed.values), size(fixture.surfaceEven))
        error('OCE:FilteringTest:ApplicationContract', ...
            'Filtering application metadata or dimensions are incomplete.');
    end
end

function assert_disabled_passthrough(fixture, resolved)
    disabled = resolved;
    disabled.enabled = false;
    design = oce.filtering.designTemporalFilter( ...
        fixture.surfaceEven, fixture.standardOCE, disabled);
    if design.applied || ~isempty(design.coefficients) || ...
            design.delay_samples ~= 0 || design.delay_seconds ~= 0
        error('OCE:FilteringTest:DisabledDesign', ...
            'Disabled filtering must not design FIR coefficients.');
    end
    filtered = oce.filtering.applyTemporalFilter( ...
        fixture.depthResultEven, fixture.surfaceResultEven, design, ...
        disabled.invalid_row_policy);
    if filtered.depth.applied || filtered.surface.applied || ...
            ~isequal(filtered.depth.values, fixture.depthEven) || ...
            ~isequal(filtered.surface.values, fixture.surfaceEven) || ...
            ~strcmp(class(filtered.depth.values), class(fixture.depthEven))
        error('OCE:FilteringTest:Passthrough', ...
            'Disabled filtering did not preserve exact valid phase values.');
    end
    postprocessed = oce.filtering.postprocessSurfacePhase( ...
        filtered.surface, disabled.surface_postprocessing);
    if ~isequal(size(postprocessed.values), size(fixture.surfaceEven))
        error('OCE:FilteringTest:PassthroughDownstream', ...
            'Disabled filtering did not produce a downstream surface map.');
    end
end

function assert_invalid_rows(fixture, design, resolved)
    surfaceNaN = fixture.surfaceResultEven;
    surfaceNaN.values = fixture.surfaceNaN;
    filtered = oce.filtering.applyTemporalFilter( ...
        fixture.depthResultEven, surfaceNaN, design, ...
        resolved.invalid_row_policy);
    expectedMask = false(size(fixture.surfaceEven, 1), 1);
    expectedMask(2) = true;
    if ~isequal(filtered.invalid_rows.mask, expectedMask) || ...
            filtered.invalid_rows.count ~= 1 || ...
            any(filtered.surface.values(2, :) ~= 0) || ...
            any(filtered.depth.values(2, :, :) ~= 0, 'all')
        error('OCE:FilteringTest:InvalidRowMask', ...
            'Invalid surface rows must be zeroed with matching depth provenance.');
    end

    depthNaN = fixture.depthResultEven;
    depthNaN.values = fixture.depthNaN;
    assert_error('OCE:Filtering:InvalidVolumetricMotion', @() ...
        oce.filtering.applyTemporalFilter(depthNaN, ...
            fixture.surfaceResultEven, design, resolved.invalid_row_policy));
end

function assert_postprocessing_controls(surface, resolved)
    noMean = resolved.surface_postprocessing;
    noMean.remove_temporal_mean = false;
    noMean.median.enabled = false;
    direct = oce.filtering.postprocessSurfacePhase(surface, noMean);
    if ~isequal(direct.values, surface.values) || ...
            direct.temporal_mean_removed || direct.median_applied
        error('OCE:FilteringTest:PostprocessingPassthrough', ...
            'Disabled surface postprocessing must preserve exact values.');
    end

    meanOnly = noMean;
    meanOnly.remove_temporal_mean = true;
    demeaned = oce.filtering.postprocessSurfacePhase(surface, meanOnly);
    expected = surface.values - mean(surface.values, 2);
    if ~isequal(demeaned.values, expected)
        error('OCE:FilteringTest:MeanRemoval', ...
            'Temporal mean removal changed its established formula.');
    end

    medianOnly = noMean;
    medianOnly.median.enabled = true;
    actual = oce.filtering.postprocessSurfacePhase(surface, medianOnly);
    expected = medfilt2(surface.values, [3 3], 'Symmetric');
    if ~isequal(actual.values, expected)
        error('OCE:FilteringTest:Median', ...
            'Surface median filtering changed its established formula.');
    end
end

function assert_validation_errors(fixture, resolved)
    bad = fixture.config_for_run;
    bad.FilterOptions = rmfield(bad.FilterOptions, 'enabled');
    assert_error('OCE:Filtering:MissingOption', @() ...
        oce.config.resolveFilterOptions(bad, fixture.surfaceEven, ...
            fixture.OCT_system));

    bad = fixture.config_for_run;
    bad.FilterOptions.method = "iir";
    assert_error('OCE:Filtering:InvalidMethod', @() ...
        oce.config.resolveFilterOptions(bad, fixture.surfaceEven, ...
            fixture.OCT_system));

    bad = resolved;
    bad.frequency.effective_passband_hz = [1200 800];
    assert_error('OCE:Filtering:InvalidResolvedOptions', @() ...
        oce.filtering.designTemporalFilter(42, fixture.standardOCE, bad));
end

function assert_error(identifier, action)
    actual = "";
    try
        action();
    catch ME
        actual = string(ME.identifier);
    end
    if actual ~= string(identifier)
        error('OCE:FilteringTest:ErrorIdentifier', ...
            'Expected identifier=%s; actual=%s.', identifier, actual);
    end
end
