function filtered = applySurfaceTemporalFilter(surfacePhase, design, invalidRowPolicy)
%APPLYSURFACETEMPORALFILTER Apply the maintained FIR to surface phase only.

    validate_inputs(surfacePhase, design, invalidRowPolicy);
    surfaceValues = surfacePhase.values;
    outputSurface = surfaceValues;
    invalidMask = false(size(surfaceValues, 1), 1);

    for lateralIndex = 1:size(surfaceValues, 1)
        surfaceSignal = squeeze(surfaceValues(lateralIndex, :));
        if any(isnan(surfaceSignal), 'all')
            invalidMask(lateralIndex) = true;
            outputSurface(lateralIndex, :) = zeros( ...
                1, size(surfaceSignal, 2), 'like', outputSurface);
        elseif design.applied
            outputSurface(lateralIndex, :) = filter( ...
                design.coefficients, 1, surfaceSignal);
        end
    end

    filtered = struct( ...
        'surface', phase_output(outputSurface, surfacePhase, design.applied), ...
        'invalid_rows', struct( ...
            'mask', invalidMask, ...
            'count', sum(invalidMask), ...
            'policy', string(invalidRowPolicy)));
end

function output = phase_output(values, source, applied)
    output = struct( ...
        'values', values, ...
        'quantity', string(source.quantity), ...
        'units', string(source.units), ...
        'layout', string(source.layout), ...
        'applied', logical(applied));
end

function validate_inputs(surfacePhase, design, invalidRowPolicy)
    requiredPhase = {'values', 'quantity', 'units', 'layout'};
    if ~isstruct(surfacePhase) || any(~isfield(surfacePhase, requiredPhase)) || ...
            ~isnumeric(surfacePhase.values) || ~ismatrix(surfacePhase.values)
        error('OCE:Filtering:InvalidPhaseInput', ...
            'Surface phase must contain numeric lateral-by-time values.');
    end
    if ~isstruct(design) || ~isfield(design, 'applied') || ...
            ~isfield(design, 'coefficients') || ...
            (design.applied && isempty(design.coefficients)) || ...
            (~design.applied && ~isempty(design.coefficients))
        error('OCE:Filtering:InvalidDesign', ...
            'Filtering design has inconsistent applied/coefficient values.');
    end
    if string(invalidRowPolicy) ~= "zero_surface_and_matching_depth"
        error('OCE:Filtering:UnsupportedInvalidRowPolicy', ...
            'Unsupported invalid-row policy "%s".', string(invalidRowPolicy));
    end
end
