function design = designTemporalFilter(surfacePhaseValues, geometry, resolvedFilter)
%DESIGNTEMPORALFILTER Build temporal axes, diagnostics, and FIR design.

    validate_inputs(surfacePhaseValues, geometry, resolvedFilter);
    sampleIntervalS = resolvedFilter.sample_interval_s;
    timeSampleCount = size(surfacePhaseValues, 2);
    expectedTimeSampleCount = geometry.time_sample_count - 1;
    if timeSampleCount ~= expectedTimeSampleCount
        error('OCE:Filtering:TimeLengthMismatch', ...
            ['Surface-phase length (%d) does not match the cropped ' ...
             'acquisition geometry time_sample_count - 1 (%d).'], ...
            timeSampleCount, expectedTimeSampleCount);
    end

    timeAxisS = 0:sampleIntervalS: ...
        (timeSampleCount - 1) * sampleIntervalS;
    lineIndex = resolve_diagnostic_line_index( ...
        surfacePhaseValues, geometry, resolvedFilter.diagnostic);
    inputLine = squeeze(surfacePhaseValues(lineIndex, :));
    fftLength = resolvedFilter.diagnostic.fft_length;
    fullSpectrum = fft(inputLine, fftLength);
    oneSidedIndices = 1:(floor(fftLength / 2) + 1);
    inputSpectrum = fullSpectrum(oneSidedIndices);
    frequencyAxisHz = (0:floor(fftLength / 2)) * ...
        resolvedFilter.sampling_frequency_hz / fftLength;

    coefficients = [];
    delaySamples = 0;
    if resolvedFilter.enabled
        normalizedPassband = ...
            resolvedFilter.frequency.effective_passband_hz * ...
            2 * resolvedFilter.sample_interval_s;
        coefficients = fir1(resolvedFilter.order, normalizedPassband);
        delaySamples = round(mean(grpdelay(coefficients)));
    end

    diagnostic = struct( ...
        'line_index_used', lineIndex, ...
        'input_line', inputLine, ...
        'input_spectrum', inputSpectrum);
    design = struct( ...
        'applied', resolvedFilter.enabled, ...
        'method', resolvedFilter.method, ...
        'coefficients', coefficients, ...
        'delay_samples', delaySamples, ...
        'delay_seconds', delaySamples * sampleIntervalS, ...
        'requested_passband_hz', ...
            resolvedFilter.frequency.requested_passband_hz, ...
        'effective_passband_hz', ...
            resolvedFilter.frequency.effective_passband_hz, ...
        'frequency_axis_hz', frequencyAxisHz, ...
        'time_axis_s', timeAxisS, ...
        'diagnostic', diagnostic);
end

function lineIndex = resolve_diagnostic_line_index( ...
        surfacePhaseValues, geometry, diagnostic)
    if ~isempty(diagnostic.line_index_used)
        lineIndex = diagnostic.line_index_used;
        return;
    end

    if ~isfield(geometry, 'samples_per_bmode') || ...
            ~isnumeric(geometry.samples_per_bmode) || ...
            ~isscalar(geometry.samples_per_bmode) || ...
            ~isfinite(geometry.samples_per_bmode) || ...
            geometry.samples_per_bmode <= 0 || ...
            geometry.samples_per_bmode ~= round(geometry.samples_per_bmode)
        error('OCE:Filtering:InvalidResolvedOptions', ...
            ['Canonical geometry samples_per_bmode is required for ' ...
             'automatic filter diagnostic line selection.']);
    end
    samplesPerBmode = double(geometry.samples_per_bmode);
    if samplesPerBmode > size(surfacePhaseValues, 1)
        error('OCE:Filtering:InvalidResolvedOptions', ...
            ['geometry.samples_per_bmode exceeds the available surface-phase ' ...
             'lateral samples.']);
    end
    lineIndex = round(samplesPerBmode / 2);
end

function validate_inputs(surfacePhaseValues, geometry, resolvedFilter)
    if ~isnumeric(surfacePhaseValues) || ~ismatrix(surfacePhaseValues) || ...
            isempty(surfacePhaseValues) || size(surfacePhaseValues, 2) < 2
        error('OCE:Filtering:InvalidResolvedOptions', ...
            'Surface phase must be a nonempty numeric lateral-by-time matrix.');
    end
    if ~isstruct(geometry) || ...
            ~isfield(geometry, 'time_sample_count') || ...
            ~isscalar(geometry.time_sample_count) || ...
            ~isfinite(geometry.time_sample_count)
        error('OCE:Filtering:InvalidResolvedOptions', ...
            'Canonical geometry time_sample_count is required.');
    end
    required = {'enabled', 'method', 'sampling_frequency_hz', ...
        'sample_interval_s', 'nyquist_frequency_hz', 'frequency', ...
        'order', 'diagnostic'};
    if ~isstruct(resolvedFilter) || ...
            any(~isfield(resolvedFilter, required))
        error('OCE:Filtering:InvalidResolvedOptions', ...
            'Filtering design requires resolved FilterOptions.');
    end
    if resolvedFilter.method ~= "fir_bandpass"
        error('OCE:Filtering:InvalidMethod', ...
            'Filtering design supports only "fir_bandpass".');
    end
end
