from __future__ import annotations

import time
from threading import Event
from typing import Sequence

import numpy as np

from ..config import HardwareConfig, OCE_TRIGGER_DUTY_CYCLE, optimized_scan_period_ticks
from ..scan import ScanSegment
from .base import BackendError


class NIDaqGalvoController:
    """Finite, hardware-timed AO + PFI12/PFI13 task group.

    Counter tasks wait on AO StartTrigger.  Starting AO last is the single
    software action that releases the synchronized segment.
    """

    def __init__(self, config: HardwareConfig):
        try:
            import nidaqmx
            from nidaqmx.constants import AcquisitionType, Edge, Level, TaskMode
            from nidaqmx.stream_writers import AnalogMultiChannelWriter
        except ImportError as exc:
            raise BackendError(
                "Falta el paquete oficial nidaqmx. Ejecute: python -m pip install nidaqmx"
            ) from exc
        self.nidaqmx = nidaqmx
        self.AcquisitionType = AcquisitionType
        self.Edge = Edge
        self.Level = Level
        self.TaskMode = TaskMode
        self.AnalogMultiChannelWriter = AnalogMultiChannelWriter
        self.config = config
        self._tasks: list[object] = []
        self._continuous_tasks: list[object] = []
        self._last_volts = np.asarray(config.park_volts, dtype=np.float64)
        self._ever_started = False

    def start_mb_chunk(self, segments: Sequence[ScanSegment]) -> int:
        """Generate finite MB/BM sweeps with one AO task and counter trains.

        Returns the number of AO samples per segment, including any unacquired
        hold needed for camera rearm or a delayed OCE pulse.  Every segment has
        the same length; its PFI12/PFI13 pulse is generated by hardware, not by
        the Python buffer-reading loop.
        """
        if self._tasks or self._continuous_tasks:
            raise BackendError("Existe una tarea DAQ activa.")
        if not segments:
            raise BackendError("El lote de escaneo no puede estar vacío.")
        first = segments[0]
        if any(
            segment.active_start != first.active_start
            or segment.active_count != first.active_count
            or segment.bframes_delay_us != first.bframes_delay_us
            for segment in segments
        ):
            raise BackendError("El lote requiere captura y desfase uniformes.")
        trigger_indices = [i for i, segment in enumerate(segments) if segment.oce_trigger_count]
        if any(segment.oce_trigger_count not in (0, 1) for segment in segments):
            raise BackendError("El lote requiere a lo sumo un pulso OCE por sweep.")
        if len(trigger_indices) == len(segments):
            oce_stride = 1
        elif (len(segments) % 2 == 0 and
              trigger_indices == list(range(0, len(segments), 2))):
            oce_stride = 2
        elif self.config.oce_enabled:
            raise BackendError("PFI13 requiere disparos uniformes, o solo en los sweeps X de crosshair.")
        else:
            oce_stride = 1
        cfg = self.config
        rate = cfg.effective_line_rate_hz
        camera_delay_s = first.active_start / rate + cfg.camera_phase_offset_us * 1e-6
        oce_delay_s = camera_delay_s + first.bframes_delay_us * 1e-6
        if camera_delay_s < 0 or (cfg.oce_enabled and oce_delay_s < 0):
            raise BackendError("El trigger del lote MB no puede preceder al inicio AO.")
        # NI-IMAQ ignored frame triggers when the next pulse coincided exactly
        # with the end of a frame.  The shared calculation is also recorded in
        # the .bin header for reproducibility.
        ticks = optimized_scan_period_ticks(
            cfg,
            active_start=first.active_start,
            active_count=first.active_count,
            nominal_ticks=max(segment.ticks for segment in segments),
            bframes_delay_us=first.bframes_delay_us,
            oce_stride=oce_stride,
        )
        if ticks * len(segments) > 2_000_000:
            raise BackendError("El lote MB supera 2 millones de muestras AO; reduzca su tamaño.")
        parts = []
        for segment in segments:
            part = np.asarray(segment.xy_volts, dtype=np.float64)
            extra = ticks - segment.ticks
            if extra:
                part = np.concatenate((part, np.repeat(part[-1:], extra, axis=0)), axis=0)
            parts.append(part)
        waveform = np.concatenate(parts, axis=0)
        ao = self.nidaqmx.Task("octoce_mb_chunk_ao")
        camera = self.nidaqmx.Task("octoce_mb_chunk_camera")
        oce = self.nidaqmx.Task("octoce_mb_chunk_oce") if cfg.oce_enabled else None
        self._tasks = [task for task in (camera, oce, ao) if task is not None]
        try:
            ao.ao_channels.add_ao_voltage_chan(
                f"{cfg.daq_device}/ao0:1", min_val=cfg.ao_min_v, max_val=cfg.ao_max_v
            )
            ao.timing.cfg_samp_clk_timing(
                rate=rate,
                sample_mode=self.AcquisitionType.FINITE,
                samps_per_chan=waveform.shape[0],
            )
            writer = self.AnalogMultiChannelWriter(ao.out_stream, auto_start=False)
            written = int(
                writer.write_many_sample(np.ascontiguousarray(waveform.T), timeout=10.0)
            )
            if written != waveform.shape[0]:
                raise BackendError(
                    f"DAQmx aceptó {written} de {waveform.shape[0]} muestras AO del lote MB."
                )
            period_s = ticks / rate
            camera_width_s = cfg.camera_trigger_width_us * 1e-6
            for task, counter, terminal, initial_s, width_s, pulse_period_s, pulse_count in (
                (camera, cfg.camera_counter, cfg.camera_trigger_terminal, camera_delay_s, camera_width_s,
                 period_s, len(segments)),
                (oce, cfg.oce_counter, cfg.oce_trigger_terminal, oce_delay_s,
                 period_s * oce_stride * OCE_TRIGGER_DUTY_CYCLE,
                 period_s * oce_stride, len(trigger_indices)),
            ):
                if task is None:
                    continue
                if not 0 <= initial_s <= period_s - width_s:
                    raise BackendError("El trigger del lote excede el sweep AO.")
                channel = task.co_channels.add_co_pulse_chan_time(
                    f"{cfg.daq_device}/{counter}",
                    idle_state=self.Level.LOW,
                    initial_delay=initial_s,
                    low_time=pulse_period_s - width_s,
                    high_time=width_s,
                )
                channel.co_pulse_term = terminal
                task.timing.cfg_implicit_timing(
                    sample_mode=self.AcquisitionType.FINITE,
                    samps_per_chan=pulse_count,
                )
                task.triggers.start_trigger.cfg_dig_edge_start_trig(
                    cfg.camera_start_trigger_source, trigger_edge=self.Edge.RISING
                )
            for task in (camera, oce, ao):
                if task is not None:
                    task.control(self.TaskMode.TASK_COMMIT)
            actual_rate = float(ao.timing.samp_clk_rate)
            if abs(actual_rate - rate) / rate > 1e-6:
                raise BackendError(
                    f"DAQmx coercionó la frecuencia de {rate:.6f} a {actual_rate:.6f} Hz."
                )
            camera.start()
            if oce is not None:
                oce.start()
            ao.start()
            self._ever_started = True
            self._last_volts = waveform[-1].copy()
            return ticks
        except Exception:
            self.abort_segment()
            raise

    def start_continuous_alignment(
        self, *, alines_per_block: int, block_rate_hz: float | None = None
    ) -> None:
        """Hold both galvos at the centre and clock both triggers without rearming.

        The two counters share the AO start trigger.  The short AO task is kept
        open throughout acquisition so its final 0 V sample remains asserted.
        """
        if self._tasks or self._continuous_tasks:
            raise BackendError("Existe una tarea DAQ activa.")
        if alines_per_block < 1 or not self.config.oce_enabled:
            raise BackendError("Alineación continua requiere A-lines y PFI13/OCE habilitado.")
        cfg = self.config
        line_rate_hz = cfg.effective_line_rate_hz
        period_s = 1.0 / block_rate_hz if block_rate_hz is not None else alines_per_block / line_rate_hz
        if period_s <= alines_per_block / line_rate_hz:
            raise BackendError(
                "La cámara necesita un intervalo libre entre bloques MB; "
                "aumente la frecuencia de A-lines o reduzca la frecuencia de PFI12/PFI13."
            )
        camera_width_s = cfg.camera_trigger_width_us * 1e-6
        oce_width_s = period_s * OCE_TRIGGER_DUTY_CYCLE
        camera_phase_s = cfg.camera_phase_offset_us * 1e-6
        oce_phase_s = camera_phase_s
        if not (0 <= camera_phase_s < period_s - camera_width_s):
            raise BackendError("El desfase PFI12 no cabe en el período MB continuo.")
        if not (0 <= oce_phase_s < period_s - oce_width_s):
            raise BackendError("El desfase PFI13 no cabe en el período MB continuo.")
        ao = self.nidaqmx.Task("octoce_alignment_ao_hold")
        camera = self.nidaqmx.Task("octoce_alignment_camera_50hz")
        oce = self.nidaqmx.Task("octoce_alignment_oce_50hz")
        self._continuous_tasks = [camera, oce, ao]
        try:
            ao.ao_channels.add_ao_voltage_chan(
                f"{cfg.daq_device}/ao0:1", min_val=cfg.ao_min_v, max_val=cfg.ao_max_v
            )
            ao.timing.cfg_samp_clk_timing(
                rate=line_rate_hz,
                sample_mode=self.AcquisitionType.FINITE,
                samps_per_chan=2,
            )
            writer = self.AnalogMultiChannelWriter(ao.out_stream, auto_start=False)
            written = int(writer.write_many_sample(np.zeros((2, 2), dtype=np.float64), timeout=5.0))
            if written != 2:
                raise BackendError(f"DAQmx aceptó {written} de 2 muestras AO de alineación.")

            # One whole block of settle time precedes the first frame trigger;
            # after that, counter timing alone defines every 20 ms boundary.
            for task, counter, terminal, width_s, phase_s in (
                (camera, cfg.camera_counter, cfg.camera_trigger_terminal, camera_width_s, camera_phase_s),
                (oce, cfg.oce_counter, cfg.oce_trigger_terminal, oce_width_s, oce_phase_s),
            ):
                channel = task.co_channels.add_co_pulse_chan_time(
                    f"{cfg.daq_device}/{counter}",
                    idle_state=self.Level.LOW,
                    initial_delay=period_s + phase_s,
                    low_time=period_s - width_s,
                    high_time=width_s,
                )
                channel.co_pulse_term = terminal
                task.timing.cfg_implicit_timing(sample_mode=self.AcquisitionType.CONTINUOUS)
                task.triggers.start_trigger.cfg_dig_edge_start_trig(
                    cfg.camera_start_trigger_source, trigger_edge=self.Edge.RISING
                )
            for task in (camera, oce, ao):
                task.control(self.TaskMode.TASK_COMMIT)
            actual_rate = float(ao.timing.samp_clk_rate)
            if abs(actual_rate - line_rate_hz) / line_rate_hz > 1e-6:
                raise BackendError(
                    f"DAQmx coercionó la frecuencia de {line_rate_hz:.6f} a {actual_rate:.6f} Hz."
                )
            camera.start()
            oce.start()
            ao.start()
            self._ever_started = True
            self._last_volts = np.zeros(2, dtype=np.float64)
        except Exception:
            self.abort_segment()
            raise

    def start_segment(self, segment: ScanSegment) -> None:
        if self._tasks or self._continuous_tasks:
            raise BackendError("Existe un segmento DAQ activo.")
        cfg = self.config
        line_rate_hz = cfg.effective_line_rate_hz
        waveform = np.asarray(segment.xy_volts, dtype=np.float64)
        if waveform.shape[0] < 2:
            waveform = np.vstack((waveform, waveform[-1]))
        ao = self.nidaqmx.Task("octoce_ao")
        camera = self.nidaqmx.Task("octoce_camera_trigger")
        oce = (
            self.nidaqmx.Task("octoce_oce_trigger")
            if cfg.oce_enabled and segment.oce_trigger_count > 0
            else None
        )
        self._tasks = [task for task in (camera, oce, ao) if task is not None]
        try:
            ao.ao_channels.add_ao_voltage_chan(
                f"{cfg.daq_device}/ao0:1",
                min_val=cfg.ao_min_v,
                max_val=cfg.ao_max_v,
            )
            ao.timing.cfg_samp_clk_timing(
                rate=line_rate_hz,
                sample_mode=self.AcquisitionType.FINITE,
                samps_per_chan=waveform.shape[0],
            )
            writer = self.AnalogMultiChannelWriter(ao.out_stream, auto_start=False)
            written = int(
                writer.write_many_sample(np.ascontiguousarray(waveform.T), timeout=10.0)
            )
            if written != waveform.shape[0]:
                raise BackendError(
                    f"DAQmx aceptó {written} de {waveform.shape[0]} muestras AO por canal."
                )

            period = 1.0 / line_rate_hz
            high_time = cfg.camera_trigger_width_us * 1e-6
            low_time = period - high_time
            first_camera_delay = max(
                0.0,
                segment.active_start / line_rate_hz + cfg.camera_phase_offset_us * 1e-6,
            )
            cam_chan = camera.co_channels.add_co_pulse_chan_time(
                f"{cfg.daq_device}/{cfg.camera_counter}",
                idle_state=self.Level.LOW,
                initial_delay=first_camera_delay,
                low_time=low_time,
                high_time=high_time,
            )
            cam_chan.co_pulse_term = cfg.camera_trigger_terminal
            camera.timing.cfg_implicit_timing(
                sample_mode=self.AcquisitionType.FINITE,
                samps_per_chan=1,
            )
            camera.triggers.start_trigger.cfg_dig_edge_start_trig(
                cfg.camera_start_trigger_source,
                trigger_edge=self.Edge.RISING,
            )

            if oce is not None:
                oce_delay = max(
                    0.0,
                    segment.active_start / line_rate_hz
                    + cfg.camera_phase_offset_us * 1e-6
                    + segment.bframes_delay_us * 1e-6,
                )
                high = cfg.oce_pulse_width_us * 1e-6
                low = high * (1.0 / OCE_TRIGGER_DUTY_CYCLE - 1.0)
                oce_chan = oce.co_channels.add_co_pulse_chan_time(
                    f"{cfg.daq_device}/{cfg.oce_counter}",
                    idle_state=self.Level.LOW,
                    initial_delay=oce_delay,
                    low_time=low,
                    high_time=high,
                )
                oce_chan.co_pulse_term = cfg.oce_trigger_terminal
                oce.timing.cfg_implicit_timing(
                    sample_mode=self.AcquisitionType.FINITE,
                    samps_per_chan=segment.oce_trigger_count,
                )
                oce.triggers.start_trigger.cfg_dig_edge_start_trig(
                    cfg.camera_start_trigger_source,
                    trigger_edge=self.Edge.RISING,
                )

            for task in (camera, oce, ao):
                if task is not None:
                    task.control(self.TaskMode.TASK_COMMIT)
            actual_rate = float(ao.timing.samp_clk_rate)
            relative_error = abs(actual_rate - line_rate_hz) / line_rate_hz
            if relative_error > 1e-6:
                raise BackendError(
                    f"DAQmx coercionó la frecuencia de {line_rate_hz:.6f} a {actual_rate:.6f} Hz."
                )
            camera.start()
            if oce is not None:
                oce.start()
            ao.start()
            self._ever_started = True
            self._last_volts = waveform[-1].copy()
        except Exception:
            self.abort_segment()
            raise

    def wait_segment(self, stop_event: Event, timeout_s: float) -> None:
        if not self._tasks:
            raise BackendError("No existe un segmento DAQ activo.")
        deadline = time.monotonic() + timeout_s
        try:
            while True:
                if stop_event.is_set():
                    raise BackendError("Adquisición detenida por el usuario.")
                # AO can finish before a delayed OCE pulse. Closing ctr1 here
                # would cut PFI13 short (or suppress it altogether).
                if all(task.is_task_done() for task in self._tasks):
                    break
                if time.monotonic() >= deadline:
                    raise BackendError("Timeout esperando las tareas DAQ finitas (AO/PFI12/PFI13).")
                stop_event.wait(0.002)
        finally:
            self.abort_segment()

    def abort_segment(self) -> None:
        tasks = self._tasks + self._continuous_tasks
        self._tasks = []
        self._continuous_tasks = []
        for task in reversed(tasks):
            try:
                task.stop()
            except Exception:
                pass
        for task in reversed(tasks):
            try:
                task.close()
            except Exception:
                pass

    def park(self) -> None:
        self.abort_segment()
        # Opening the NI backend performs camera preflight before enabling AO.
        # If that preflight fails, closing the backend must not energize the
        # galvos merely to write their nominal park value.
        if not self._ever_started:
            return
        cfg = self.config
        line_rate_hz = cfg.effective_line_rate_hz
        target = np.asarray(cfg.park_volts, dtype=np.float64)
        count = max(2, int(cfg.park_ramp_points))
        waveform = np.linspace(self._last_volts, target, count, dtype=np.float64)
        task = self.nidaqmx.Task("octoce_safe_park")
        try:
            task.ao_channels.add_ao_voltage_chan(
                f"{cfg.daq_device}/ao0:1",
                min_val=cfg.ao_min_v,
                max_val=cfg.ao_max_v,
            )
            task.timing.cfg_samp_clk_timing(
                rate=line_rate_hz,
                sample_mode=self.AcquisitionType.FINITE,
                samps_per_chan=count,
            )
            writer = self.AnalogMultiChannelWriter(task.out_stream, auto_start=False)
            written = int(
                writer.write_many_sample(np.ascontiguousarray(waveform.T), timeout=5.0)
            )
            if written != count:
                raise BackendError(
                    f"DAQmx aceptó {written} de {count} muestras de parqueo por canal."
                )
            task.start()
            task.wait_until_done(timeout=max(2.0, count / line_rate_hz + 1.0))
            self._last_volts = target
        finally:
            try:
                task.stop()
            except Exception:
                pass
            task.close()
