function resolution = fractionOfBmode(options, samplesPerBmode)
%FRACTIONOFBMODE Resolve spatial interval count from a B-mode fraction.

    intervalCount = round(options.interval_fraction * samplesPerBmode);
    resolution = struct( ...
        'method', "fraction_of_bmode", ...
        'interval_count', intervalCount, ...
        'sample_count', intervalCount + 1, ...
        'requested_fraction', options.interval_fraction);
end
