function test_manual_preview_helpers(context)
%TEST_MANUAL_PREVIEW_HELPERS Validate display-only preview helper contracts.

    geometry = struct('bmode_count', 4, ...
        'samples_per_bmode', 10, 'bmode_scan_width_mm', 5);
    selection = oce.plotting.resolveBmodeLayout( ...
        geometry, 40, "representative");
    if ~isequal(selection.indices, [1 3]) || ...
            ~isequal(selection.angles_deg, [0 90]) || ...
            ~isequal(selection.global_lateral_ranges, [1 10; 21 30]) || ...
            numel(selection.local_lateral_axis_mm) ~= 10
        error('OCE:PreviewTest:RepresentativeBmodes', ...
            'Representative preview B-mode selection changed unexpectedly.');
    end
    for bmodeCount = [4 8 16 32]
        completeGeometry = geometry;
        completeGeometry.bmode_count = bmodeCount;
        completeGeometry.samples_per_bmode = 4;
        completeSelection = oce.plotting.resolveBmodeLayout( ...
            completeGeometry, 4 * bmodeCount, "all");
        if ~isequal(completeSelection.indices, 1:bmodeCount) || ...
                completeSelection.row_count ~= bmodeCount / 4 || ...
                completeSelection.column_count ~= 4
            error('OCE:PreviewTest:CompleteBmodeLayout', ...
                'Complete B-mode layouts must use four columns and grow downward.');
        end
    end

    assert_motion_visualization_masks();

    values = zeros(100, 10);
    values(:) = linspace(-0.02, 0.02, numel(values));
    values(1) = 5;
    robust = oce.plotting.resolvePhasePreviewCLim(values, "robust", []);
    if robust(1) >= 0 || robust(2) <= 0 || ...
            abs(robust(1) + robust(2)) > 10 * eps(max(abs(robust))) || ...
            robust(2) >= 5
        error('OCE:PreviewTest:RobustCLim', ...
            'Robust phase preview limits must be symmetric and outlier-resistant.');
    end
    localizedOutlier = values;
    localizedOutlier(1:8, :) = 8;
    localizedRobust = oce.plotting.resolvePhasePreviewCLim( ...
        localizedOutlier, "robust", []);
    if localizedRobust(2) >= 1 || localizedRobust(2) <= 0
        error('OCE:PreviewTest:LocalizedRobustCLim', ...
            ['Robust phase limits must resist a localized high-amplitude ' ...
             'lateral region.']);
    end

    videoValues = 10 + repmat(reshape( ...
        [-0.10 -0.06 -0.02 0.02 0.06 0.10], 1, 1, []), 4, 5, 1);
    panels = struct('phase_values', videoValues, ...
        'visualization_mask', true(4, 5));
    motionRobust = oce.plotting.resolveMotionOverlayCLim( ...
        panels, "robust", [], 'MedianWindow', [5 3]);
    motionAuto = oce.plotting.resolveMotionOverlayCLim( ...
        panels, "auto", [], 'MedianWindow', [5 3]);
    motionManual = oce.plotting.resolveMotionOverlayCLim( ...
        struct('phase_values', videoValues), "manual", 0.5, ...
        'MedianWindow', [5 3]);
    uncenteredRobust = oce.plotting.resolvePhasePreviewCLim( ...
        videoValues, "robust", []);
    if motionRobust(2) >= 0.2 || motionRobust(2) <= 0 || ...
            uncenteredRobust(2) <= 5 || ...
            motionAuto(1) >= -0.09 || motionAuto(2) <= 0.09 || ...
            ~isequal(motionManual, [-0.5 0.5])
        error('OCE:PreviewTest:MotionOverlayCLim', ...
            ['Motion overlay limits must follow the temporally centered ' ...
             'displayed signal and preserve manual limits.']);
    end

    visibleMask = true(4, 5);
    visibleMask(:, 1:2) = false;
    referencePanel = struct('phase_values', videoValues, ...
        'visualization_mask', visibleMask);
    outlierValues = videoValues;
    outlierTrace = reshape(1000 * [-1 -0.6 -0.2 0.2 0.6 1], 1, 1, []);
    outlierValues(:, 1:2, :) = repmat(outlierTrace, 4, 2, 1);
    outlierPanel = struct('phase_values', outlierValues, ...
        'visualization_mask', visibleMask);
    referenceRobust = oce.plotting.resolveMotionOverlayCLim( ...
        referencePanel, "robust", []);
    outlierRobust = oce.plotting.resolveMotionOverlayCLim( ...
        outlierPanel, "robust", []);
    referenceAuto = oce.plotting.resolveMotionOverlayCLim( ...
        referencePanel, "auto", []);
    outlierAuto = oce.plotting.resolveMotionOverlayCLim( ...
        outlierPanel, "auto", []);
    if ~isequal(referenceRobust, outlierRobust) || ...
            ~isequal(referenceAuto, outlierAuto)
        error('OCE:PreviewTest:MotionOverlayMaskedCLim', ...
            'Out-of-ROI phase must not influence robust or auto motion CLim.');
    end

    impulseFrame = zeros(7, 7);
    impulseFrame(4, 4) = 5;
    medianFrame = oce.plotting.postprocessMotionOverlayFrame( ...
        impulseFrame, [3 3]);
    if medianFrame(4, 4) ~= 0 || any(medianFrame(:) ~= 0)
        error('OCE:PreviewTest:MotionMedian', ...
            'Visualization-only median filtering must suppress isolated impulses.');
    end

    manual = oce.plotting.resolvePhasePreviewCLim(values, "manual", 0.05);
    if ~isequal(manual, [-0.05 0.05]) || ...
            ~isempty(oce.plotting.resolvePhasePreviewCLim(values, "auto", []))
        error('OCE:PreviewTest:CLimModes', ...
            'Phase preview CLim mode contract changed unexpectedly.');
    end

    background = reshape(linspace(50, 100, 20), 4, 5);
    phase = zeros(4, 5);
    phase(2, 2) = 0.05;
    mask = true(4, 5);
    mask(1, 1) = false;
    rgb = oce.plotting.composeMotionOverlay( ...
        background, phase, mask, [50 100], [-0.05 0.05], 0.5);
    grayscale = oce.plotting.composeMotionOverlay( ...
        background, phase, false(4, 5), [50 100], [-0.05 0.05], 0.5);
    outsideMask = repmat(~mask, 1, 1, 3);
    if ~isequal(size(rgb), [4 5 3]) || any(~isfinite(rgb), 'all') || ...
            any(rgb(outsideMask) ~= grayscale(outsideMask))
        error('OCE:PreviewTest:MotionOverlay', ...
            ['Motion overlay must return finite RGB and preserve grayscale ' ...
             'structure outside the visualization mask.']);
    end

    oldVisibility = get(groot, 'defaultFigureVisible');
    cleanup = onCleanup(@() restore_figures(oldVisibility));
    set(groot, 'defaultFigureVisible', 'off');

    kfMagnitude = [1 2 3; 4 5 6; 7 8 9];
    kfDirection = struct( ...
        'direction', "right", ...
        'spectrum', struct( ...
            'magnitude', kfMagnitude, ...
            'frequency_axis_hz', [1000 2000 3000], ...
            'wavenumber_axis_per_m', [10 20 30]), ...
        'ridge', struct('wavenumber_per_m', [10 20 30]), ...
        'target_selection', struct( ...
            'requested_frequency_hz', 2000, ...
            'selected_bin_index', 2, ...
            'selected_frequency_hz', 2000, ...
            'selected_wavenumber_per_m', 20));
    kfAnalysis = struct('directions', [kfDirection kfDirection]);
    [kfFigure, kfPreview] = oce.plotting.plotDispersionKfPreview(kfAnalysis, 1);
    if ~isequal(kfPreview.profile_lines(1).YData(:), kfMagnitude(:, 2)) || ...
            kfPreview.profile_frequency_hz(1) ~= 2000 || ...
            kfPreview.profile_peak_lines(1).Value ~= 20
        error('OCE:PreviewTest:SelectedFrequencyKProfile', ...
            'The k profile must reuse M(k) at the selected frequency bin.');
    end
    close(kfFigure);

    mapValues = reshape(linspace(-0.1, 0.1, 400), 40, 10);
    [fig, preview] = oce.plotting.plotBmodeSpaceTime( ...
        mapValues, 0:9, "rad", geometry, "Filtered space-time", ...
        'DelaySamples', 2);
    if preview.delay_samples ~= 2 || ...
            ~isequal(preview.source_time_indices, 3:10) || ...
            ~isequal(preview.display_time_indices, 1:8) || ...
            string(preview.primary_axes(1).XLabel.String) ~= "Lateral sample" || ...
            string(preview.primary_axes(1).YLabel.String) ~= "Time sample" || ...
            strlength(string(preview.primary_axes(2).YLabel.String)) ~= 0 || ...
            string(preview.physical_unit_labels(1).String) ~= "mm" || ...
            string(preview.secondary_axes(2).YLabel.String) ~= "ms" || ...
            ~isequal(preview.panel_titles, ["0.0 deg"; "90.0 deg"]) || ...
            string(preview.colorbar.Label.String) ~= "rad"
        error('OCE:PreviewTest:SpaceTimeContract', ...
            'Space-time axes, units, or visual delay compensation changed.');
    end
    close(fig);

    [selectedFigure, selectedPreview] = oce.plotting.plotBmodeSpaceTime( ...
        mapValues, 0:9, "rad", geometry, "Window context", ...
        'BmodeIndices', 2, 'DelaySamples', 2);
    if selectedPreview.selection.mode ~= "selected" || ...
            ~isequal(selectedPreview.selection.indices, 2) || ...
            numel(selectedPreview.primary_axes) ~= 1 || ...
            selectedPreview.panel_titles ~= "45.0 deg"
        error('OCE:PreviewTest:SelectedSpaceTime', ...
            'Explicit B-mode rendering must reuse the shared space-time owner.');
    end
    close(selectedFigure);

    interactionSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+interaction', 'selectTemporalFilterPassband.m'));
    requiredInteraction = ["drawline"; "InteractionsAllowed"; ...
        "SelectionType"; "'open'"; "uiresume"];
    if any(~contains(interactionSource, requiredInteraction))
        error('OCE:PreviewTest:PassbandInteraction', ...
            'Manual passband selection must use movable lines and double-click acceptance.');
    end

    videoSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+video', 'createFilteredMotionVideo.m'));
    animationSource = fileread(fullfile(context.repoRoot, 'src', '+oce', ...
        '+plotting', 'showDepthMotionAnimation.m'));
    if ~contains(videoSource, 'panel.visualization_mask') || ...
            contains(videoSource, 'panel.intensity_mask') || ...
            ~contains(animationSource, 'panel.visualization_mask') || ...
            contains(animationSource, 'panel.intensity_mask')
        error('OCE:PreviewTest:MotionMaskRouting', ...
            'Motion overlay consumers must route the final visualization mask.');
    end
    requiredVideoLayout = ["verticalExaggeration = 2"; ...
        "panelHeight = max(110"; ...
        "daspect(ax, [1 1 / verticalExaggeration 1])"; ...
        "yticklabels(ax, {})"; ...
        "'TileSpacing', 'compact', 'Padding', 'compact'"; ...
        "box(ax, 'on')"];
    if any(~contains(videoSource, requiredVideoLayout))
        error('OCE:PreviewTest:FilteredMotionLayout', ...
            ['Filtered motion video must retain independent compact panels, ' ...
             'two-times vertical exaggeration, and local axis separation.']);
    end
    clear cleanup
end

function assert_motion_visualization_masks()
    geometry = struct('bmode_count', 2, ...
        'samples_per_bmode', 3, 'bmode_scan_width_mm', 3);
    depthProduct = struct('values', zeros(6, 18, 3), 'units', "rad");
    reconstruction = struct();
    reconstruction.axes.depth.values = (0:19)';
    reconstruction.log_amplitude.values = zeros(20, 6);
    intensityMask = true(20, 6);
    intensityMask(6, 1) = false;
    borderResult = struct( ...
        'surface_mode', "anterior_posterior", ...
        'indices', struct( ...
            'anterior', [8 10 NaN 12 7 8], ...
            'posterior', [13 16 18 14 10 NaN]), ...
        'intensityMask', intensityMask);
    depthOptions = struct('estimator', "loupas", ...
        'loupas', struct('axial_window_samples', 3));
    timeAxisS = [0 1 2] * 1e-3;
    alignedRows = (2:19)';

    data = oce.plotting.prepareMotionVisualization( ...
        depthProduct, reconstruction, borderResult, geometry, ...
        timeAxisS, depthOptions, 'BmodeMode', "all");
    expectedGeometry1 = false(18, 3);
    expectedGeometry1(:, 1) = alignedRows >= 3 & alignedRows <= 18;
    expectedGeometry1(:, 2) = alignedRows >= 5 & alignedRows <= 21;
    expectedGeometry2 = false(18, 3);
    expectedGeometry2(:, 1) = alignedRows >= 7 & alignedRows <= 19;
    expectedGeometry2(:, 2) = alignedRows >= 2 & alignedRows <= 15;
    expectedIntensity1 = intensityMask(2:19, 1:3);
    if ~isequal(data.panels(1).geometry_mask, expectedGeometry1) || ...
            ~isequal(data.panels(2).geometry_mask, expectedGeometry2) || ...
            ~isequal(data.panels(1).intensity_mask, expectedIntensity1) || ...
            ~isequal(data.panels(1).visualization_mask, ...
                expectedGeometry1 & expectedIntensity1) || ...
            ~isequal(data.panels(2).visualization_mask, ...
                expectedGeometry2 & intensityMask(2:19, 4:6))
        error('OCE:PreviewTest:MotionGeometryMask', ...
            ['Motion visualization ROI must include five pixels outside both ' ...
             'surfaces, intersect intensity, and preserve B-mode independence.']);
    end

    borderResult.surface_mode = "anterior_only";
    anteriorOnly = oce.plotting.prepareMotionVisualization( ...
        depthProduct, reconstruction, borderResult, geometry, ...
        timeAxisS, depthOptions, 'BmodeMode', "all");
    expectedAnteriorOnly1 = false(18, 3);
    expectedAnteriorOnly1(:, 1) = alignedRows >= 3;
    expectedAnteriorOnly1(:, 2) = alignedRows >= 5;
    expectedAnteriorOnly2 = false(18, 3);
    expectedAnteriorOnly2(:, 1) = alignedRows >= 7;
    expectedAnteriorOnly2(:, 2) = alignedRows >= 2;
    expectedAnteriorOnly2(:, 3) = alignedRows >= 3;
    if ~isequal(anteriorOnly.panels(1).geometry_mask, expectedAnteriorOnly1) || ...
            ~isequal(anteriorOnly.panels(2).geometry_mask, expectedAnteriorOnly2) || ...
            any(anteriorOnly.panels(1).geometry_mask(:, 3)) || ...
            ~all(anteriorOnly.panels(2).geometry_mask(alignedRows >= 3, 3))
        error('OCE:PreviewTest:AnteriorOnlyMotionGeometryMask', ...
            ['Anterior-only ROI must start five pixels above the anterior ' ...
             'surface, reach the aligned depth bottom, and ignore posterior NaN.']);
    end
end

function restore_figures(oldVisibility)
    close all force;
    set(groot, 'defaultFigureVisible', oldVisibility);
end
