function fixture = createInteractiveAcquisitionFixture(dataClass)
%CREATEINTERACTIVEACQUISITIONFIXTURE Deterministic interactive-helper input.

% This fixture is permanent synthetic contract data. It is not scientific
% validation and contains no experimental signal.

    if nargin < 1
        dataClass = 'double';
    end

    specLength = 16;
    repetitions = 100;
    lateralPositions = 4;
    [spectralIndex, repetitionIndex, lateralIndex] = ndgrid( ...
        0:(specLength - 1), 0:(repetitions - 1), 0:(lateralPositions - 1));
    rawdata = 1200 + ...
        180 * sin(2 * pi * spectralIndex / specLength + ...
            0.071 * repetitionIndex + 0.19 * lateralIndex) + ...
        35 * cos(4 * pi * spectralIndex / specLength - ...
            0.037 * repetitionIndex);
    rawdata = cast(rawdata, dataClass);

    fixture.measurement = struct('rawdata', rawdata);
    fixture.OCT_system = oce.config.resolveOCTSystemOptions( ...
        oce.config.getOCTSystemOptions("swept_source_1300"));
    fixture.geometry = struct( ...
        'spectral_sample_count', specLength, ...
        'lateral_sample_count', lateralPositions, ...
        'temporal_repetition_count', repetitions, ...
        'available_depth_sample_count', specLength / 2);
end
