function fixture = create_synthetic_scientific_golden_fixture()
%CREATE_SYNTHETIC_SCIENTIFIC_GOLDEN_FIXTURE Build controlled golden inputs.
%
% The fixture contains no external data, random values, timestamps, or local
% paths. It combines a synthetic OCT-amplitude volume with known interfaces and
% deterministic traveling-wave windows with known phase speed.

    scanAxisCount = 2;
    samplesPerDirection = 65;
    samplesPerBmode = 2 * samplesPerDirection + 1;
    timeSampleCount = 129;

    frequencyBinHz = 100;
    wavenumberBinPerM = 50;
    timeFftCount = 129;
    spatialFftCount = 65;
    dt = 1 / (timeFftCount * frequencyBinHz);
    dxM = 1 / (spatialFftCount * wavenumberBinPerM);

    componentFrequencyHz = (400:200:1600)';
    expectedPhaseSpeedMPerS = 2;
    componentWavenumberPerM = ...
        componentFrequencyHz / expectedPhaseSpeedMPerS;
    componentAmplitude = [0.55; 0.70; 0.85; 1.00; 0.85; 0.70; 0.55];
    targetFrequencyHz = 1000;

    timeAxisS = (0:(timeSampleCount - 1)) * dt;
    localDirectionAxisM = (0:(samplesPerDirection - 1)) * dxM;
    [timeGrid, spaceGrid] = ndgrid(timeAxisS, localDirectionAxisM);

    bmodes = repmat(struct('index', [], ...
        'global_lateral_range', [], 'center', [], ...
        'left', [], 'right', []), 1, scanAxisCount);
    totalLateralCount = scanAxisCount * samplesPerBmode;

    for scanAxisIndex = 1:scanAxisCount
        phaseOffset = (scanAxisIndex - 1) * pi / 5;
        signal = zeros(size(timeGrid));
        for componentIndex = 1:numel(componentFrequencyHz)
            signal = signal + componentAmplitude(componentIndex) * sin( ...
                2*pi*(componentFrequencyHz(componentIndex) * timeGrid - ...
                componentWavenumberPerM(componentIndex) * spaceGrid) + ...
                phaseOffset);
        end

        firstGlobal = (scanAxisIndex - 1) * samplesPerBmode + 1;
        globalRange = firstGlobal:(firstGlobal + samplesPerBmode - 1);
        leftLocal = 1:samplesPerDirection;
        centerLocal = samplesPerDirection + 1;
        rightLocal = (samplesPerDirection + 2):samplesPerBmode;
        leftGlobal = globalRange(leftLocal);
        rightGlobal = globalRange(rightLocal);
        bmodeAxisMm = ((1:samplesPerBmode) - centerLocal) * dxM * 1e3;

        bmodes(scanAxisIndex).index = scanAxisIndex;
        bmodes(scanAxisIndex).global_lateral_range = ...
            [globalRange(1) globalRange(end)];
        bmodes(scanAxisIndex).center = struct( ...
            'method', "manual_local_index", ...
            'local_lateral_index', centerLocal, ...
            'global_lateral_index', globalRange(centerLocal), ...
            'x_coordinate_mm', bmodeAxisMm(centerLocal));
        bmodes(scanAxisIndex).left = make_window( ...
            "left", true, leftLocal, leftGlobal, bmodeAxisMm(leftLocal), ...
            timeAxisS, flipud(signal'));
        bmodes(scanAxisIndex).right = make_window( ...
            "right", false, rightLocal, rightGlobal, bmodeAxisMm(rightLocal), ...
            timeAxisS, signal');
    end

    windowResult = struct( ...
        'source', struct( ...
            'quantity', "phase_increment", ...
            'units', "rad", ...
            'layout', "lateral_time", ...
            'filter_enabled', true, ...
            'filter_applied', true, ...
            'signal_size', [totalLateralCount timeSampleCount]), ...
        'frequency', struct('center_hz', targetFrequencyHz), ...
        'sample_interval_s', dt, ...
        'resolved_options', struct(), ...
        'bmodes', bmodes);

    editableOptions = struct( ...
        'phase_gradient', struct('enabled', false), ...
        'method', "windowed_fft_ridge", ...
        'spectrum', struct( ...
            'fft', struct( ...
                'time_bin_count', timeFftCount, ...
                'spatial_bin_count', spatialFftCount), ...
            'crop', struct( ...
                'maximum_frequency_hz', 2000, ...
                'maximum_wavenumber_per_m', 1200), ...
            'window', struct( ...
                'time', struct('enabled', false, ...
                    'method', "hann_symmetric"), ...
                'space', struct('enabled', false, ...
                    'method', "hann_symmetric"))), ...
        'ridge', struct( ...
            'maximum_wavenumber_jump_per_m', 150, ...
            'minimum_relative_magnitude', 0.01, ...
            'interpolation', struct( ...
                'method', "linear", 'extrapolate', true)), ...
        'phase_speed', struct('smoothing', struct( ...
            'method', "lowess", 'span_fraction', 0.1)), ...
        'target_frequency', struct( ...
            'source', "resolved_filter_center"));
    filterOptions = struct('frequency', struct( ...
        'center_hz', targetFrequencyHz));
    resolvedOptions = oce.config.resolveDispersionAnalysisOptions( ...
        editableOptions, filterOptions);

    processingInputs = struct( ...
        'experimentRoot', "synthetic_experiment", ...
        'subExperiment', "SyntheticGolden", ...
        'run_id', "SYN001", ...
        'filename', fullfile('fixtures', 'synthetic_scientific.bin'), ...
        'resultsDir', fullfile('results', 'synthetic_scientific'), ...
        'acquisition_row', table( ...
            "synthetic_experiment", "SYN001", "phantom", ...
            "angular_bmodes", ...
            'VariableNames', {'experiment_id', 'run_id', ...
            'sample_type', 'scan_geometry'}));
    configForRun = struct( ...
        'profile', "synthetic_scientific_golden", ...
        'AcquisitionOptions', struct( ...
            'acquisition_mode', "mb_mode", ...
            'scan_geometry', "angular_bmodes"), ...
        'DispersionWindowOptions', struct( ...
            'spatial', struct('method', "manual_interval_count")), ...
        'DispersionAnalysisOptions', resolvedOptions);

    [acquisitionState, borderOptions, borderTruth] = ...
        create_border_detection_input(samplesPerBmode, scanAxisCount);

    fixture = struct();
    fixture.contract = struct( ...
        'name', "synthetic_border_and_traveling_wave", ...
        'version', 4, ...
        'scan_axis_count', scanAxisCount, ...
        'component_frequency_hz', componentFrequencyHz, ...
        'component_wavenumber_per_m', componentWavenumberPerM, ...
        'expected_phase_speed_m_per_s', expectedPhaseSpeedMPerS, ...
        'target_frequency_hz', targetFrequencyHz, ...
        'time_sample_interval_s', dt, ...
        'spatial_sample_interval_m', dxM, ...
        'border_truth', borderTruth);
    fixture.processing_inputs = processingInputs;
    fixture.config_for_run = configForRun;
    fixture.window_result = windowResult;
    fixture.DispersionAnalysisOptions = resolvedOptions;
    fixture.acquisition_state = acquisitionState;
    fixture.BorderOptions = borderOptions;
end

function [state, options, truth] = create_border_detection_input( ...
        samplesPerBmode, bmodeCount)
    depthCount = 500;
    lateralCount = samplesPerBmode * bmodeCount;
    axialPixelResolutionUm = 7.1;
    refractiveIndex = 1.4;
    storageAxis = 1:lateralCount;
    localAxisMm = linspace(0, 6, samplesPerBmode);
    amplitude = ones(depthCount, lateralCount);
    anteriorPeak = zeros(1, lateralCount);
    posteriorPeak = zeros(1, lateralCount);

    [rowGrid, colGrid] = ndgrid(1:depthCount, 1:lateralCount);
    amplitude = amplitude + 0.01 * ...
        (sin(rowGrid / 19) + cos(colGrid / 11));

    for bmodeIndex = 1:bmodeCount
        local = 1:samplesPerBmode;
        globalRange = (bmodeIndex - 1) * samplesPerBmode + local;
        anterior = 120 + 18 * (bmodeIndex - 1) + ...
            round(3 * sin(2*pi*local / samplesPerBmode));
        posterior = 230 + 23 * (bmodeIndex - 1) + ...
            round(4 * cos(2*pi*local / samplesPerBmode));
        anteriorPeak(globalRange) = anterior;
        posteriorPeak(globalRange) = posterior;
        for localIndex = local
            column = globalRange(localIndex);
            top = anterior(localIndex);
            bottom = posterior(localIndex);
            amplitude(top:bottom, column) = ...
                amplitude(top:bottom, column) + 5;
            amplitude(top-2:top+2, column) = ...
                amplitude(top-2:top+2, column) + 95;
            amplitude(bottom-2:bottom+2, column) = ...
                amplitude(bottom-2:bottom+2, column) + 75;
        end
    end

    geometry = struct( ...
        'lateral_sample_count', lateralCount, ...
        'samples_per_bmode', samplesPerBmode, ...
        'bmode_count', bmodeCount, ...
        'bmode_scan_width_mm', 6, ...
        'bmode_lateral_axis_mm', localAxisMm, ...
        'depth_sample_count', depthCount, ...
        'depth_sample_interval_mm', axialPixelResolutionUm / refractiveIndex * 1e-3);
    sampleOptics = struct('refractive_index', struct( ...
        'value', refractiveIndex, 'source', "synthetic_fixture"));
    depthAxisMm = (0:depthCount-1)' * ...
        axialPixelResolutionUm / refractiveIndex * 1e-3;
    reconstruction = struct( ...
        'axes', struct( ...
            'lateral', struct('values', storageAxis), ...
            'depth', struct('values', depthAxisMm)), ...
        'amplitude', struct('values', amplitude), ...
        'log_amplitude', struct('values', 20 * log10(amplitude)));
    state = struct( ...
        'sample', struct('optics', sampleOptics), ...
        'geometry', geometry, ...
        'reconstruction', reconstruction);

    base = oce.config.getDefaultProcessingConfig("phantom").BorderOptions;
    base.selection = "manual";
    base.method = "phantom";
    base.mask_threshold = 20;
    base.lateral_edge_exclusion.enabled = false;
    % These offsets define this controlled fixture, independently of editable
    % production defaults (which have their own configuration contract).
    base.methods.phantom.top_search_offset = 0;
    base.methods.phantom.top_index_offset = 2;
    base.methods.phantom.bottom_index_offset = 0;
    crop = struct('depth', struct('sample_count', depthCount));
    options = oce.config.resolveBorderOptions(base, table(), crop);

    % The 1-based profile offset and explicit anterior/posterior offsets 2/0
    % place both targets approximately one sample before the synthetic peaks.
    % Keep this analytical reference independent of the detector output.
    expectedAnterior = anteriorPeak - 1;
    expectedPosterior = posteriorPeak - 1;
    expectedThicknessMm = (expectedPosterior - expectedAnterior) * ...
        axialPixelResolutionUm / refractiveIndex * 1e-3;
    truth = struct( ...
        'anterior_peak_index', anteriorPeak, ...
        'posterior_peak_index', posteriorPeak, ...
        'expected_anterior_index', expectedAnterior, ...
        'expected_posterior_index', expectedPosterior, ...
        'expected_thickness_mm', expectedThicknessMm(:), ...
        'index_tolerance_px', 6, ...
        'thickness_tolerance_mm', ...
            8 * axialPixelResolutionUm / refractiveIndex * 1e-3);
end

function window = make_window(direction, reverseSpatially, localIndices, ...
        globalIndices, xAxisMm, timeAxisS, values)
    window = struct( ...
        'direction', direction, ...
        'spatial_reversal_required', reverseSpatially, ...
        'local_lateral_indices', localIndices, ...
        'global_lateral_indices', globalIndices, ...
        'time_indices', 1:numel(timeAxisS), ...
        'x_axis_mm', xAxisMm, ...
        'time_axis_s', timeAxisS, ...
        'values', values, ...
        'spatial_interval_count', numel(localIndices) - 1, ...
        'spatial_sample_count', numel(localIndices), ...
        'temporal_interval_count', numel(timeAxisS) - 1, ...
        'temporal_sample_count', numel(timeAxisS));
end
