function baseline = create_synthetic_scientific_golden_snapshot()
%CREATE_SYNTHETIC_SCIENTIFIC_GOLDEN_SNAPSHOT Build compact canonical baseline.

    fixture = create_synthetic_scientific_golden_fixture();
    borders = oce.borders.detectAndMask( ...
        fixture.acquisition_state, fixture.BorderOptions);
    analysis = oce.dispersion.analyzeWindows( ...
        fixture.window_result, borders.thickness, ...
        fixture.DispersionAnalysisOptions);
    scientificResult = oce.results.buildScientificResult( ...
        fixture.processing_inputs, fixture.config_for_run, ...
        fixture.window_result, analysis);

    baseline = struct();
    baseline.schema = struct( ...
        'name', "oce_synthetic_scientific_golden", ...
        'version', 3);
    baseline.fixture = fixture.contract;
    baseline.border_result = compact_border_result(borders);
    baseline.scientific_result = scientificResult;
end

function snapshot = compact_border_result(result)
    snapshot = rmfield(result, {'surface_mode', 'intensityMask'});
    mask = result.intensityMask;
    snapshot.intensity_mask = struct( ...
        'size', size(mask), ...
        'true_count', nnz(mask), ...
        'column_true_count', sum(mask, 1));
end
