function resolution = cycleCount(options, frequencyHz, sampleIntervalS, ...
        ~, availableIntervalCount)
%CYCLECOUNT Resolve temporal intervals from excitation cycles.

    requestedDurationS = options.cycle_count / frequencyHz;
    requestedIntervalCount = round(requestedDurationS / sampleIntervalS);
    intervalCount = min(requestedIntervalCount, availableIntervalCount);
    if intervalCount < requestedIntervalCount
        warning('OCE:DispersionWindows:CycleCountTruncated', ...
            ['cycle_count requests %d temporal intervals at %.6g Hz, but only ' ...
             '%d are available after temporal alignment. Using all valid intervals.'], ...
            requestedIntervalCount, frequencyHz, availableIntervalCount);
    end
    resolution = struct( ...
        'method', "cycle_count", ...
        'interval_count', intervalCount, ...
        'sample_count', intervalCount + 1, ...
        'requested_duration_s', requestedDurationS, ...
        'effective_duration_s', intervalCount * sampleIntervalS, ...
        'requested_cycle_count', options.cycle_count, ...
        'represented_cycle_count', intervalCount * sampleIntervalS * frequencyHz);
end
