function resolution = manualIntervalCount(options, ~, sampleIntervalS, varargin)
%MANUALINTERVALCOUNT Resolve an explicit temporal interval count.

    intervalCount = options.manual_interval_count;
    resolution = make_resolution("manual_interval_count", intervalCount, ...
        sampleIntervalS, [], []);
end

function result = make_resolution(method, intervalCount, sampleIntervalS, ...
        requestedDurationS, requestedCycles)
    result = struct('method', method, 'interval_count', intervalCount, ...
        'sample_count', intervalCount + 1, ...
        'requested_duration_s', requestedDurationS, ...
        'effective_duration_s', intervalCount * sampleIntervalS, ...
        'requested_cycle_count', requestedCycles, ...
        'represented_cycle_count', []);
end
